objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>An individual rooftop.</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <formula>TEXT(Contract__r.Contract_Type__c)</formula>
        <inlineHelpText>Formula field that reads the picklist value from the Contract Type field on Contracts for use in views and reporting</inlineHelpText>
        <label>Contract Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LOB_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned WriteOff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Needs Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Needs Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Pre Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - SVOC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Temp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transitioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Triage</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Legacy_Active_Date__c</fullName>
        <label>Legacy Active Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Sold__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Sold</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>physical location of the asset</inlineHelpText>
        <label>Subscriber Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billed Assets (Subscriber Account)</relationshipLabel>
        <relationshipName>Billed_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>Add a new line item to a billing contract</description>
        <label>ADD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>Line of Business - Use this to determine Contract Type (1 per LOB)</description>
        <inlineHelpText>LOB</inlineHelpText>
        <label>Contract Type</label>
        <picklist>
            <picklistValues>
                <fullName>AutoProcess</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak OEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Know Me Overages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non RMB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto Trader Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VinSolutions</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>use to add a new contract (order) to the AutoTrader Billing System</description>
        <label>ADD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <businessProcess>vAuto</businessProcess>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Base_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Set to have product show on a POA related list &quot;Base Asset&quot;</inlineHelpText>
        <label>Base Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Suite__c</fullName>
        <description>Allows this product to be managed by Performance Management in POAs.</description>
        <inlineHelpText>Allows this product to be managed by Performance Management in POAs.</inlineHelpText>
        <label>Product Suite</label>
        <picklist>
            <picklistValues>
                <fullName>Auction Genius</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Feeds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deposit - Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deposit - Provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Genius Labs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ILM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KBB PAR New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KBB PAR Used</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promo - Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promo - Genius Labs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promo - Provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Setup - Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Setup - Genius Labs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Setup - Provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stockwave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TIM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Website</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <label>vAuto</label>
    </recordTypes>
</CustomObject>

classes/vAutoSubscriberProductInfo_Test.cls
@isTest(SeeAllData=true)
private class vAutoSubscriberProductInfo_Test {
	
	@isTest static void test_method_one() {
		// Setup test data
		Integer DATA_SET_SIZE = 6;

		Account testAcct = TestData.setupAccount();
		testAcct.RecordType = [SELECT Id, Name FROM RecordType WHERE SobjectType='Account' AND Name = 'Dealer' LIMIT 1];
		insert testAcct;

		Contact testContact = TestData.setupContact();
		insert testContact;

		Opportunity testOpp = TestData.setupOpportunity(testAcct, testContact);
		insert testOpp;

		RecordType rt = [SELECT Id, Name FROM RecordType WHERE SobjectType='Contract' AND Name = 'ADD' LIMIT 1];
		Contract testContract = TestData.setupContract(testAcct, rt);
		testContract.Contract_Type__c = 'vAuto';
		insert testContract;

		List<Product2> productList = new List<Product2>();

		Product2 testProduct = TestData.getProduct();
		testProduct.Product_Suite__c = 'Auction Genius';
		testProduct.Base_Product__c = true;
		productList.add(testProduct);

		Product2 testProduct1 = TestData.getProduct();
		testProduct1.Product_Suite__c = 'Provision';
		testProduct1.Base_Product__c = true;
		productList.add(testProduct1);

		Product2 testProduct2 = TestData.getProduct();
		testProduct2.Product_Suite__c = 'Conquest';
		testProduct2.Base_Product__c = true;
		productList.add(testProduct2);

		Product2 testProduct3 = TestData.getProduct();
		testProduct3.Product_Suite__c = 'KBB PAR Used';
		testProduct3.Base_Product__c = true;
		productList.add(testProduct3);

		Product2 testProduct4 = TestData.getProduct();
		testProduct4.Product_Suite__c = 'KBB PAR New';
		testProduct4.Base_Product__c = true;
		productList.add(testProduct4);

		Product2 testProduct5 = TestData.getProduct();
		testProduct5.Product_Suite__c = 'Test';
		testProduct5.Base_Product__c = true;
		productList.add(testProduct5);

		insert productList;

        List<Billing_Item__c> biList = new List<Billing_Item__c>();
		RecordType rt2 = [SELECT Id, Name FROM RecordType WHERE SobjectType='Billing_Item__c' AND Name = 'ADD' LIMIT 1];
		for(Integer i = 0; i < DATA_SET_SIZE; i++) {
			biList.add(
				new Billing_Item__c(
					Contract__c = testContract.Id,
        			Product_Sold__c = productList[i].Id,
					Subscriber_Account__c = testAcct.Id,
					LOB_Status__c = 'Good',
					Legacy_Active_Date__c = System.today(),
					RecordType = rt2
				)
			);
		}
		insert biList;

		Test.startTest();

		Test.setCurrentPageReference(new PageReference('/'));
		ApexPages.currentPage().getParameters().put('id', testAcct.Id);
		ApexPages.StandardController controller = new ApexPages.StandardController(testAcct);
		vAutoSubscriberProductInfo ctrl = new vAutoSubscriberProductInfo(controller);
		system.assert(ctrl.numOfRows == 6);
		system.assert(ctrl.SAWrapList.size() == 5);



		Test.stopTest();
	}
}