objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <inlineHelpText>Select Franchise or Independent.</inlineHelpText>
        <label>Dealer Type</label>
        <picklist>
            <picklistValues>
                <fullName>Franchise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Other</fullName>
        <active>false</active>
        <description>Partners, Consultants,</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DashboardTaskStatus__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Primary_Subject__c</fullName>
        <label>Primary Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Subject__c</fullName>
        <label>Secondary Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Status__c</fullName>
        <label>Task Status</label>
        <type>TextArea</type>
    </fields>
    <label>DashboardTaskStatus</label>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Stage__c</fullName>
        <inlineHelpText>Updated by the system upon milestone completion</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>1-Initiating</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>2-Planning and Design</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>3-Executing</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>4-Review</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>5-Finalizing</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Launched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-ILM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GO LIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Intro Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Strategy Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Dealer Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <description>Used for reporting.</description>
        <formula>TEXT(Account__r.Dealer_Type__c)</formula>
        <label>Dealer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <formula>IF(!ISPICKVAL(Approval_Stage__c, &quot;Go Live&quot;) &amp;&amp; Project_Due_Date__c &gt;today() , &quot;Working&quot;,
IF(!ISPICKVAL(Approval_Stage__c, &quot;Go Live&quot;) &amp;&amp; Project_Due_Date__c &lt;Today() , &quot;Past Due&quot;, 
IF(ISPICKVAL(Approval_Stage__c, &quot;Go Live&quot;)&amp;&amp; Project_Due_Date__c &lt;  Project_Complete_Date__c , &quot;Goal Missed&quot;, 
IF(ISPICKVAL(Approval_Stage__c, &quot;Go Live&quot;) &amp;&amp; Project_Due_Date__c &gt;=  Project_Complete_Date__c , &quot;Goal Completed&quot;, 
&quot;Log Change Request&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>this field looks at the Project Due Date and formulates a status</inlineHelpText>
        <label>Project Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FOD_Helper.cls
public class FOD_Helper {
    
    /***** NEW LOGIC START *******/
    
    public static String excludeOppCondition() {
        //String excludeOpp = ' and ((NOT Opportunity__r.Name like \'%HQ Tree%\') and (NOT Opportunity__r.Name like \'%Price Change%\')) ';
        String excludeOpp = ' and (NOT(Name like \'%HQ Tree%\' or Name like \'%Price Change%\' or Name like \'%AUX Account Setup%\' or Name like \'%Remove%\' or Name like \'%Auto Trader Canada%\')) ';
        return excludeOpp;
    }
    
    public static Map<String, Integer> projectCount(String pName, String pStage) {
        Map<String, Integer> map_pStatusCount = new Map<String, Integer>();
        
        List<DashboardTaskStatus__c> dbSettingList = queryDashboardSettings(pName, pStage);
        
        Map<String, String> tStatus_pStatus_Map = returnTaskStatus(dbSettingList);
        Set<String> statusSet = new Set<String>();
        statusSet.addAll(tStatus_pStatus_Map.keySet());
        
        String subjectCondition = returnSubjectCondition(dbSettingList[0].Primary_Subject__c);
        
        String query = 'select id, name, (select WhatId, subject, Status from Tasks where ' + subjectCondition + ' and Status in :statusSet) from SFDC_520_Quote__c where Name like \'%' + pName + '%\' and Approval_Stage__c = :pStage';
        System.debug('-tStatus_pStatus_Map--' + tStatus_pStatus_Map);
        for(SFDC_520_Quote__c proj :Database.query(query)) {
            Set<String> tStatusSet = new Set<String>();
                
            for(Task tsk :proj.Tasks) {
                
                if(tStatus_pStatus_Map != null && tStatus_pStatus_Map.containsKey(tsk.Status)) {
                    String pStatus = tStatus_pStatus_Map.get(tsk.Status);
                    Integer count = 0;
                    if(map_pStatusCount != null && map_pStatusCount.containsKey(pStatus)) {
                        count = map_pStatusCount.get(pStatus);
                    }
                    if(!tStatusSet.contains(tsk.Status)) count++;
                    map_pStatusCount.put(pStatus, count);
                    tStatusSet.add(tsk.Status);
                }
            }
        }
        return map_pStatusCount;
    }
    
    public static List<SFDC_520_Quote__c> returnProjectTask(String pName, String pStage, String pStatus) {
        Map<String, Integer> map_pStatusCount = new Map<String, Integer>();
        
        List<DashboardTaskStatus__c> dbSettingList = queryDashboardSettings(pName, pStage, pStatus);
        
        Map<String, String> tStatus_pStatus_Map = returnTaskStatus(dbSettingList);
        Set<String> statusSet = new Set<String>();
        statusSet.addAll(tStatus_pStatus_Map.keySet());
        
        String subjectCondition1 = returnSubjectCondition(dbSettingList[0].Primary_Subject__c);
        
        String query1 = 'select id, name, (select WhatId, subject, Status, Owner.Name, Date_Time_Completed__c from Tasks where ' + subjectCondition1 + ' and Status in :statusSet) from SFDC_520_Quote__c where Name like \'%' + pName + '%\' and Approval_Stage__c = :pStage';
        Set<Id> projIds = new Set<Id>();
        for(SFDC_520_Quote__c proj :Database.query(query1)) {
            if(proj.Tasks != null && proj.Tasks.size() > 0)
                projIds.add(proj.id);
        }
        
        String secSub = dbSettingList[0].Secondary_Subject__c == null ? '' : dbSettingList[0].Secondary_Subject__c;
        
        String subjectCondition = returnSubjectStatusCondition(dbSettingList[0].Primary_Subject__c, secSub, statusSet);
        
        String query = 'select id, name, Approval_Stage__c, Account__r.Name, Start_Date__c, (select WhatId, Subject, Status, Activity_Age__c, CreatedDate, Owner.Name, Date_Time_Completed__c from Tasks where ' + subjectCondition + ' ) from SFDC_520_Quote__c where id in :projIds';
        
        return Database.query(query);
    }
    
    public static Map<String, Integer> projectCountForNewUser(String pName) {
        Map<String, Integer> map_pStatusCount = new Map<String, Integer>();
        
        List<DashboardTaskStatus__c> dbSettingList = queryDashboardSettings(pName);
        
        Map<String, String> tStatus_pStatus_Map = returnTaskStatus(dbSettingList);
        Set<String> statusSet = new Set<String>();
        statusSet.addAll(tStatus_pStatus_Map.keySet());
        System.debug('statusSet==' + statusSet);
        String subjectCondition = returnSubjectCondition(dbSettingList[0].Primary_Subject__c);
        
        String query = 'select WhatId, subject, Status from Task where ' + subjectCondition + ' and Status in :statusSet';
        System.debug('query==' + query);
        
        Set<String> tStatusSet = new Set<String>();
            
        for(Task tsk :Database.query(query)) {
            if(tStatus_pStatus_Map != null && tStatus_pStatus_Map.containsKey(tsk.Status)) {
                String pStatus = tStatus_pStatus_Map.get(tsk.Status);
                Integer count = 0;
                if(map_pStatusCount != null && map_pStatusCount.containsKey(pStatus)) {
                    count = map_pStatusCount.get(pStatus);
                }
                count++;
                map_pStatusCount.put(pStatus, count);
                tStatusSet.add(tsk.Status);
            }
        }
        System.debug('map_pStatusCount===' + map_pStatusCount);
        return map_pStatusCount;
    }
    
    public static Map<String, Integer> projectCountForNewUserCompleted(String pName) {
        Map<String, Integer> map_monthCount = new Map<String, Integer>();
        List<DashboardTaskStatus__c> dbSettingList = queryDashboardSettings(pName);
        
        String subjectCondition = returnSubjectCondition(dbSettingList[0].Primary_Subject__c);
        
        String query = 'select WhatId, subject, Status, Date_Time_Completed__c from Task where ' + subjectCondition + ' and Status = \'Completed\'';
        System.debug('query==' + query);
        
        Date todayDate = System.today();
        Integer thisMonth = todayDate.month();
        
        Integer compByMonth = 0;
        Integer compByYear = 0;
           
        for(Task tsk :Database.query(query)) {
            if(tsk.Date_Time_Completed__c.month() == thisMonth) {
                compByMonth++;
            }
            compByYear++;
        }
        map_monthCount.put('Month', compByMonth);
        map_monthCount.put('Year', compByYear);
        return map_monthCount;
    }
    
    public static Map<String, Integer> projectCountForCompleted(String pName) {
        Map<String, Integer> map_monthCount = new Map<String, Integer>();
        
        List<DashboardTaskStatus__c> dbSettingList = [select Project__c, Stage__c, Project_Status__c, Task_Status__c,
                Primary_Subject__c from DashboardTaskStatus__c where Project__c = :pName and Project_Status__c = 'Completed'];
        
        
        String subjectCondition = returnSubjectCondition(dbSettingList[0].Primary_Subject__c);
        
        String query = 'select id, name, (select WhatId, subject, Status, Date_Time_Completed__c from Tasks where ' + subjectCondition + ' and Status = \'Completed\' and Date_Time_Completed__c = THIS_QUARTER) from SFDC_520_Quote__c where Name like \'%' + pName + '%\'';
        Date todayDate = System.today();
        Integer thisMonth = todayDate.month();
        
        Integer compByMonth = 0;
        Integer compByYear = 0;
        
        for(SFDC_520_Quote__c proj :Database.query(query)) {
            Set<String> tStatusSet = new Set<String>();
            
            for(Task tsk :proj.Tasks) {
                if(tsk.Date_Time_Completed__c.month() == thisMonth) {
                    compByMonth++;
                }
                compByYear++;
                break;
            }
        }
        map_monthCount.put('Month', compByMonth);
        map_monthCount.put('Year', compByYear);
        return map_monthCount;
    }
    
    public static List<SFDC_520_Quote__c> returnProjectTaskCompleted(String pName, String duration) {
        Map<String, Integer> map_pStatusCount = new Map<String, Integer>();
        
        List<DashboardTaskStatus__c> dbSettingList = [select Project__c, Stage__c, Project_Status__c, Task_Status__c,
                Primary_Subject__c, Secondary_Subject__c from DashboardTaskStatus__c where Project__c = :pName and Project_Status__c = 'Completed'];
        
        
        String subjectCondition1 = returnSubjectCondition(dbSettingList[0].Primary_Subject__c);
        
        String query1 = 'select id, name, (select WhatId, subject, Status, Owner.Name, Date_Time_Completed__c from Tasks where ' + subjectCondition1 + ' and Status = \'Completed\') from SFDC_520_Quote__c where Name like \'%' + pName + '%\'';
        Set<Id> projIds = new Set<Id>();
        for(SFDC_520_Quote__c proj :Database.query(query1)) {
            if(proj.Tasks != null && proj.Tasks.size() > 0)
                projIds.add(proj.id);
        }
        System.debug('projIds==' + projIds);
        String secSub = dbSettingList[0].Secondary_Subject__c == null ? '' : dbSettingList[0].Secondary_Subject__c;
        
        Set<String> statusSet = new Set<String>();
        statusSet.add('Completed');
        String subjectCondition = returnSubjectStatusCondition(dbSettingList[0].Primary_Subject__c, secSub, statusSet);
        
        String durationCondition = '';
        if(duration == 'month') {
             durationCondition = ' Date_Time_Completed__c = THIS_MONTH and ';
        }
        if(duration == 'year') {
             durationCondition = ' Date_Time_Completed__c = THIS_QUARTER and ';
        }
        
        String query = 'select id, name, Approval_Stage__c, Account__c, Account__r.Name, Start_Date__c, (select WhatId, Subject, Status, Activity_Age__c, CreatedDate, Owner.Name, Date_Time_Completed__c from Tasks where ' +  durationCondition + subjectCondition  + ' ) from SFDC_520_Quote__c where id in :projIds';
        System.debug('query===' + query);
        return Database.query(query);
    }
    
    public static Map<Id, List<Task>> returnProjectTaskSecondary(String pName, String duration) {
        Map<String, Integer> map_pStatusCount = new Map<String, Integer>();
        
        List<DashboardTaskStatus__c> dbSettingList = [select Project__c, Stage__c, Project_Status__c, Task_Status__c,
                Primary_Subject__c, Secondary_Subject__c from DashboardTaskStatus__c where Project__c = :pName and Project_Status__c = 'Completed'];
        
        
        String subjectCondition1 = returnSubjectCondition(dbSettingList[0].Primary_Subject__c);
        
        String query1 = 'select id, name, (select WhatId, subject, Status, Owner.Name, Date_Time_Completed__c from Tasks where ' + subjectCondition1 + ' and Status = \'Completed\') from SFDC_520_Quote__c where Name like \'%' + pName + '%\'';
        Set<Id> projIds = new Set<Id>();
        for(SFDC_520_Quote__c proj :Database.query(query1)) {
            if(proj.Tasks != null && proj.Tasks.size() > 0)
                projIds.add(proj.id);
        }
        
        String secSub = dbSettingList[0].Secondary_Subject__c == null ? '' : dbSettingList[0].Secondary_Subject__c;
        
        String subjectCondition = '';
        List<String> secSubList = secSub.split(',');
        Integer count = 0;
        for(String str :secSubList) {
            str = str.trim();
            if(str != '')
            count++;
            if(count == 1) subjectCondition = ' ( ';
            if(count == secSubList.size())
                subjectCondition += ' Subject like \'%' + str + '%\' ) and';
            else
                subjectCondition += ' Subject like \'%' + str + '%\' or ';
        }
        
        Map<Id, List<Task>> mapProjectTaskMap = new Map<Id, List<Task>>();
        
        
        String query2 = 'select id, name, Approval_Stage__c, Account__c, Account__r.Name, Start_Date__c, (select WhatId, Subject, Status, Activity_Age__c, CreatedDate, Owner.Name, Date_Time_Completed__c from Tasks where ' +  subjectCondition  + ' Status != \'Completed\') from SFDC_520_Quote__c where id in :projIds';
        
        for(SFDC_520_Quote__c proj :Database.query(query2)) {
            if(proj.Tasks != null && proj.Tasks.size() > 0) {
                System.debug('proj.id==== ' + proj.id);
                System.debug('proj.name==== ' + proj.name);
                mapProjectTaskMap.put(proj.id, proj.Tasks);
            }
        }
        
        String query3 = 'select id, name, Approval_Stage__c, Account__r.Name, Start_Date__c, (select WhatId, Subject, Status, Activity_Age__c, CreatedDate, Owner.Name, Date_Time_Completed__c from Tasks where ' +  subjectCondition  + ' Status = \'Completed\') from SFDC_520_Quote__c where id in :projIds';
        
        List<SFDC_520_Quote__c> projList2 = new List<SFDC_520_Quote__c>();
        
        projList2 = Database.query(query3);
        
        for(SFDC_520_Quote__c proj :projList2) {
            if(proj.Tasks != null && proj.Tasks.size() > 0) {
                List<Task> tskList = new List<Task>();
                if(mapProjectTaskMap.containsKey(proj.id)) {
                    tskList.addAll(mapProjectTaskMap.get(proj.id));
                }
                tskList.addAll(proj.Tasks);
                mapProjectTaskMap.put(proj.id, tskList);
            }
        }
        
        return mapProjectTaskMap;
    }
    
    public static List<SFDC_520_Quote__c> returnProjectTaskCompletedDT(String pName, String duration, String dealerType) {
        String dealerTypeCondition = ' and Account__r.Dealer_Type__c = :dealerType ';
        if(dealerType == 'Other')
            dealerTypeCondition = 'and Account__r.Dealer_Type__c = null';
        
        Map<String, Integer> map_pStatusCount = new Map<String, Integer>();
        
        List<DashboardTaskStatus__c> dbSettingList = [select Project__c, Stage__c, Project_Status__c, Task_Status__c,
                Primary_Subject__c, Secondary_Subject__c from DashboardTaskStatus__c where Project__c = :pName and Project_Status__c = 'Completed'];
        
        
        String subjectCondition1 = returnSubjectCondition(dbSettingList[0].Primary_Subject__c);
        
        String query1 = 'select id, name, (select WhatId, subject, Status, Owner.Name, Date_Time_Completed__c from Tasks where ' + subjectCondition1 + ' and Status = \'Completed\') from SFDC_520_Quote__c where Name like \'%' + pName + '%\' ' + dealerTypeCondition;
        Set<Id> projIds = new Set<Id>();
        for(SFDC_520_Quote__c proj :Database.query(query1)) {
            if(proj.Tasks != null && proj.Tasks.size() > 0)
                projIds.add(proj.id);
        }
        System.debug('projIds==' + projIds);
        String secSub = dbSettingList[0].Secondary_Subject__c == null ? '' : dbSettingList[0].Secondary_Subject__c;
        
        Set<String> statusSet = new Set<String>();
        statusSet.add('Completed');
        String subjectCondition = returnSubjectStatusCondition(dbSettingList[0].Primary_Subject__c, secSub, statusSet);
        
        String durationCondition = '';
        if(duration == 'month') {
             durationCondition = ' Date_Time_Completed__c = THIS_MONTH and ';
        }
        if(duration == 'year') {
             durationCondition = ' Date_Time_Completed__c = THIS_QUARTER and ';
        }
        
        String query = 'select id, name, Approval_Stage__c, Account__c, Account__r.Name, Start_Date__c, (select WhatId, Subject, Status, Activity_Age__c, CreatedDate, Owner.Name, Date_Time_Completed__c from Tasks where ' +  durationCondition + subjectCondition  + ' ) from SFDC_520_Quote__c where id in :projIds';
        System.debug('query===' + query);
        return Database.query(query);
    }
    
    public static Map<Id, List<Task>> returnProjectTaskSecondaryDT(String pName, String duration, String dealerType) {
        String dealerTypeCondition = ' and Account__r.Dealer_Type__c = :dealerType ';
        if(dealerType == 'Other')
            dealerTypeCondition = 'and Account__r.Dealer_Type__c = null';
        
        Map<String, Integer> map_pStatusCount = new Map<String, Integer>();
        
        List<DashboardTaskStatus__c> dbSettingList = [select Project__c, Stage__c, Project_Status__c, Task_Status__c,
                Primary_Subject__c, Secondary_Subject__c from DashboardTaskStatus__c where Project__c = :pName and Project_Status__c = 'Completed'];
        
        
        String subjectCondition1 = returnSubjectCondition(dbSettingList[0].Primary_Subject__c);
        
        String durationCondition = '';
        if(duration == 'month') {
             durationCondition = ' Date_Time_Completed__c = THIS_MONTH and ';
        }
        if(duration == 'year') {
             durationCondition = ' Date_Time_Completed__c = THIS_QUARTER and ';
        }
        
        String query1 = 'select id, name, (select WhatId, subject, Status, Owner.Name, Date_Time_Completed__c from Tasks where ' + subjectCondition1 + ' and Status = \'Completed\') from SFDC_520_Quote__c where Name like \'%' + pName + '%\' ' + dealerTypeCondition;
        Set<Id> projIds = new Set<Id>();
        for(SFDC_520_Quote__c proj :Database.query(query1)) {
            if(proj.Tasks != null && proj.Tasks.size() > 0)
                projIds.add(proj.id);
        }
        
        String secSub = dbSettingList[0].Secondary_Subject__c == null ? '' : dbSettingList[0].Secondary_Subject__c;
        
        String subjectCondition = '';
        List<String> secSubList = secSub.split(',');
        Integer count = 0;
        for(String str :secSubList) {
            str = str.trim();
            if(str != '')
            count++;
            if(count == 1) subjectCondition = ' ( ';
            if(count == secSubList.size())
                subjectCondition += ' Subject like \'%' + str + '%\' ) and';
            else
                subjectCondition += ' Subject like \'%' + str + '%\' or ';
        }
        
        Map<Id, List<Task>> mapProjectTaskMap = new Map<Id, List<Task>>();
        
        
        String query2 = 'select id, name, Approval_Stage__c, Account__c, Account__r.Name, Start_Date__c, (select WhatId, Subject, Status, Activity_Age__c, CreatedDate, Owner.Name, Date_Time_Completed__c from Tasks where ' + subjectCondition  + ' Status != \'Completed\') from SFDC_520_Quote__c where id in :projIds';
        
        for(SFDC_520_Quote__c proj :Database.query(query2)) {
            if(proj.Tasks != null && proj.Tasks.size() > 0) {
                System.debug('proj.id==== ' + proj.id);
                System.debug('proj.name==== ' + proj.name);
                mapProjectTaskMap.put(proj.id, proj.Tasks);
            }
        }
        
        String query3 = 'select id, name, Approval_Stage__c, Account__r.Name, Start_Date__c, (select WhatId, Subject, Status, Activity_Age__c, CreatedDate, Owner.Name, Date_Time_Completed__c from Tasks where ' + subjectCondition  + ' Status = \'Completed\') from SFDC_520_Quote__c where id in :projIds';
        
        List<SFDC_520_Quote__c> projList2 = new List<SFDC_520_Quote__c>();
        
        projList2 = Database.query(query3);
        
        for(SFDC_520_Quote__c proj :projList2) {
            if(proj.Tasks != null && proj.Tasks.size() > 0) {
                List<Task> tskList = new List<Task>();
                if(mapProjectTaskMap.containsKey(proj.id)) {
                    tskList.addAll(mapProjectTaskMap.get(proj.id));
                }
                tskList.addAll(proj.Tasks);
                mapProjectTaskMap.put(proj.id, tskList);
            }
        }
        
        return mapProjectTaskMap;
    }
    
    public static String returnSubjectStatusCondition(String priSubject, String secSubject, Set<String> statusSet) {
        String subCond = '';
        subCond += ' ((Subject like \'%' + priSubject + '%\' and Status in : statusSet) ';
        
        for(String str :secSubject.split(',')) {
            str = str.trim();
            if(str != '')
            subCond += ' or Subject like \'%' + str + '%\'';
        }
        subCond += ')';
        return subCond;
    }
    
    public static String returnSubjectCondition(String taskSubject) {
        String subQry = '';
        taskSubject = taskSubject.trim();
        subQry += 'Subject like \'%' + taskSubject + '%\'';
        return subQry;
    }
    
    public static Map<String, String> returnTaskStatus(List<DashboardTaskStatus__c> dbSettingList) {
        Map<String, String> tStatus_pStatus_Map = new Map<String, String>();
        
        for(DashboardTaskStatus__c ts : dbSettingList) {
            for(String st :ts.Task_Status__c.split(',')) {
                st = st.trim();
                if(st != 'Completed')
                    tStatus_pStatus_Map.put(st, ts.Project_Status__c);
            }
        }
        return tStatus_pStatus_Map;
    }
    
    public static List<DashboardTaskStatus__c> queryDashboardSettings(String pName) {
        List<DashboardTaskStatus__c> dbSettingList = [select Project__c, Stage__c, Project_Status__c, Task_Status__c,
                Primary_Subject__c from DashboardTaskStatus__c where Project__c = :pName];
        return dbSettingList;
    }
    
    
    public static List<DashboardTaskStatus__c> queryDashboardSettings(String pName, String pStage) {
        List<DashboardTaskStatus__c> dbSettingList = [select Project__c, Stage__c, Project_Status__c, Task_Status__c,
                Primary_Subject__c from DashboardTaskStatus__c where Project__c = :pName and Stage__c = :pStage
                and Project_Status__c != 'Completed'];
        return dbSettingList;
    }
    
    public static List<DashboardTaskStatus__c> queryDashboardSettings(String pName, String pStage, String pStatus) {
        System.debug('pName==' + pName);
        System.debug('pStage==' + pStage);
        System.debug('pStatus==' + pStatus);
        List<DashboardTaskStatus__c> dbSettingList = [select Project__c, Stage__c, Project_Status__c, Task_Status__c,
                Primary_Subject__c, Secondary_Subject__c from DashboardTaskStatus__c 
                where Project__c = :pName and Stage__c = :pStage
                and Project_Status__c = :pStatus];
        return dbSettingList;
    }
    
    /***** NEW LOGIC END *******/
    
}