objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <formula>VinPro2__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vin PM Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory State</label>
        <referenceTo>Territory_State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account has associated completed Training records.</description>
        <inlineHelpText>This account has completed some form of training.</inlineHelpText>
        <label>Training Completed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <label>Implementation Manager</label>
        <picklist>
            <picklistValues>
                <fullName>Matt Bench</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travis Douglas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jennifer Merrick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kandy Richert</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Product_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Piece_Issue__c</fullName>
        <inlineHelpText>Auto-populated from Products sold when Opportunity marked PAID</inlineHelpText>
        <label>Piece Issue</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trainer_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Pieces1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trainer_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Pieces2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trainer_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Pieces3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Completed__c</fullName>
        <label>Training Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Training_Coordinated__c</fullName>
        <label>Training Coordinated</label>
        <type>Date</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <description>Vin_Performance_Manager__r.User_Full_Name__c</description>
        <formula>Vin_Performance_Manager__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Vin_Performance_Manager__r.User_Full_Name__c</inlineHelpText>
        <label>Vin PM (formula)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Confirmed_Training_End__c</fullName>
        <label>Training End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Confirmed_Training_Start__c</fullName>
        <label>Training Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DDM_Finalization_Complete__c</fullName>
        <label>Acct Mgr Finalization Complete</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Graphics_Obtained__c</fullName>
        <label>Date Graphics Obtained</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Packet_Ret_d__c</fullName>
        <inlineHelpText>the date the packet was returned by the Dealer - updates the stage from Introduction to Implementation</inlineHelpText>
        <label>Date Packet Ret&apos;d</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;&amp;Opportunity__r.Implementation_Contact__r.Id,  Opportunity__r.Implementation_Contact__r.FirstName&amp;&quot; &quot;&amp; Opportunity__r.Implementation_Contact__r.LastName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Implementation Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_Training_End__c</fullName>
        <label>Proposed Training End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Training_Start__c</fullName>
        <label>Proposed Training Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_number_of_users__c</fullName>
        <inlineHelpText>Enter the # Admins, # Managers, # Salespeople-Breakdown of users for the current install-input by the Implementation Manager-upon input Project Piece for manuals triggered</inlineHelpText>
        <label>Total number of users</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trainer_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trainer_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trainer_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Virtual Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trainer_Expenses_Submitted__c</fullName>
        <label>Trainer Expenses Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Trainer/Trainer 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Completed__c</fullName>
        <label>Training Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Training_Coordinated__c</fullName>
        <inlineHelpText>Training Dates Confirmed &amp; Training Preparations Completed by Trainer</inlineHelpText>
        <label>Training Coordinated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Training_Dates_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Training Dates Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Training_Expenses_Paid_by_Dealer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Training Expenses Paid by Dealer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Training_Included__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Training Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Training_is_GO__c</fullName>
        <inlineHelpText>Training Docs are ready, Implementation is ready, Travel is approved and financed (but not yet purchased)</inlineHelpText>
        <label>Training is GO</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Travel_Approved_Financed__c</fullName>
        <label>Travel Approved (Financed)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Travel_Approved_Trainer__c</fullName>
        <label>Travel Approved (Trainer)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Travel_Proposed__c</fullName>
        <label>Travel Proposed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Travel_Purchased__c</fullName>
        <label>Travel Purchased</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Territory_State__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DDM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProjectOwnerChange_Test.cls
@isTest
public class ProjectOwnerChange_Test {
	public static testMethod void TestTask()
	{
		/*Territory_State__c TS = new Territory_State__c();
		TS.Name = 'XX';
		TS.Account_Manager__c = userinfo.getUserId();
		TS.DDM__c = userinfo.getUserId();
		TS.Regional__c = userinfo.getUserId();
		TS.Implementation_Manager__c = userinfo.getUserId();
        TS.Implementation_Specialist__c = userinfo.getUserId();		
		insert TS;*/
		
		Account A = new Account();
		A.BillingState = 'KS';
		A.Name = 'test';
		A.BillingCity = 'test';
        A.BillingCountry = 'USA';
        A.BillingPostalCode = '66212';
        A.BillingState = 'KS';
        A.BillingStreet = '1234';
        A.ShippingCity = 'test';
        A.ShippingCountry = 'USA';
        A.ShippingPostalCode = '66212';
        A.ShippingState = 'KS';
        A.ShippingStreet = '1234';
		
		insert A; 
		
		Opportunity O = new Opportunity();
		O.AccountId = A.id;
		O.Type = 'SEO';
		O.Name = A.name;
		O.Type = 'New Business';
		O.CloseDate = system.today();
		O.StageName = 'Prospect';
		insert O;
		
		SFDC_520_Quote__c pr = new SFDC_520_Quote__c();
		pr.Account__c = A.id;
		pr.Opportunity__c = O.id;
		pr.Name = O.Name;
		pr.OwnerId = userinfo.getUserId();
		pr.Training_Included__c = true;		
						
		insert pr;
					
		Project_Piece__c pc = new Project_Piece__c();
		pc.Project__c = pr.Id;
		pc.Piece_Issue__c = 'test';
		pc.ownerId = userinfo.getUserId();
		//insert pc; 
		/*
		Task ppTask = new Task();
		ppTask.OwnerId = pc.OwnerId;
		ppTask.WhatId = pc.Id;
		ppTask.Subject = 'test';
		ppTask.Status = 'In Progress';
		ppTask.Type = 'Task';
		insert ppTask;
		*/
		/*
		Project_Piece__c pc2 = new Project_Piece__c();
		pc2.Project__c = pr.Id;
		pc2.Piece_Issue__c = 'test2';
		pc2.ownerId = userinfo.getUserId();
		
		insert pc2;
		*/
		
		pr.Date_Packet_Ret_d__c = system.today();
		pr.Date_Graphics_Obtained__c = system.today();
		update pr;	
		
		pr.OwnerId = '00570000001KeZm';
		update pr;
		//pr.OwnerId = userinfo.getUserId();
		//update pr;
		//pr.Regional__c = null;
		//pr.DDM__c = null;
		
	
		pr.Proposed_Training_Start__c = system.today();
		pr.Proposed_Training_End__c = system.today();		
		update pr;
		pr.Trainer__c = userinfo.getUserId();
		pr.Trainer_2__c = userinfo.getUserId();
		pr.Trainer_3__c = userinfo.getUserId();
		pr.Trainer_4__c = userinfo.getUserId();
		update pr;
		//===============================
	
		

		
		//pr.Confirmed_Training_Start__c=system.today();
		//update pr;
		
		//pr.Confirmed_Training_End__c=null;
		pr.Training_Expenses_Paid_by_Dealer__c = TRUE;
		pr.Training_Dates_Confirmed__c = TRUE;
		update pr;
		//pr.Confirmed_Training_End__c = system.today();
		//=================================
		pr.Travel_Proposed__c = system.today();
		//update pr; 
		pr.Training_Coordinated__c = system.today();
		//update pr;
		//==================================
		
		
		
			
		
	}
	public static testmethod void part2()
	{
		User adminUser = [select Id, ProfileId, IsActive from User where ProfileId =: '00e70000001FaWM' AND IsActive =: true limit 1];
		
		system.runAs(adminUser)
		{
			/*Territory_State__c TS = new Territory_State__c();
			TS.Name = 'XX';
			TS.Account_Manager__c = userinfo.getUserId();
			TS.DDM__c = userinfo.getUserId();
			TS.Regional__c = userinfo.getUserId();
			TS.Implementation_Manager__c = userinfo.getUserId();
	        TS.Implementation_Specialist__c = userinfo.getUserId();		
			insert TS;*/
			
			Account A = new Account();
			A.BillingState = 'KS';
			A.Name = 'test';
			A.BillingCity = 'test';
	        A.BillingCountry = 'USA';
	        A.BillingPostalCode = '66212'; 
	        A.BillingState = 'KS';
	        A.BillingStreet = '1234';
	       	A.ShippingCity = 'test';
	        A.ShippingCountry = 'USA';
	        A.ShippingPostalCode = '66212'; 
	        A.ShippingState = 'KS';
	        A.ShippingStreet = '1234';
			
			insert A; 
			
			Opportunity O = new Opportunity();
			O.AccountId = A.id;
			O.Type = 'SEO';
			O.Name = A.name;
			O.Type = 'New Business';
			O.CloseDate = system.today();
			O.StageName = 'Prospect';
			insert O;
			
			SFDC_520_Quote__c pr = new SFDC_520_Quote__c();
			pr.Account__c = A.id;
			pr.Opportunity__c = O.id;
			pr.Name = O.Name;
			pr.OwnerId = userinfo.getUserId();
			pr.Training_Included__c = true;									
			insert pr;		
			
			pr.Total_number_of_users__c='test';
			update pr;
			
			pr.Travel_Approved_Trainer__c= system.today();
			update pr;
			//===================================
			pr.Travel_Approved_Financed__c=system.today();
			update pr;
			//===================================
			//pr.Training_is_GO__c = system.today();
			//update pr;
			//=====================================
			pr.Travel_Purchased__c=system.today();
			update pr;
			//=====================================
			//pr.Training_Completed__c = system.today();
			//update pr;
			//=======================================
			pr.Trainer_Expenses_Submitted__c = system.today();
			update pr;
			//=====================================
			pr.DDM_Finalization_Complete__c = system.today();
			update pr; 
		
			pr.Total_number_of_users__c = 'test';
			update pr;
		}
	}
}