objects/Account.object
<CustomObject>
    <fields>
        <fullName>DMS_System__c</fullName>
        <inlineHelpText>for active dealers - updated by the sync program from admin&gt;&gt;selected dealer&gt;&gt;dms integration setup</inlineHelpText>
        <label>DMS System</label>
        <picklist>
            <picklistValues>
                <fullName>ACS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADP3PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autobase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Mate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoSoft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Tracker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Biz MSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CarThink</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citrix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Click</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DealerTrack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deal Pack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FEI Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frazer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Genisys</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grapevine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infiniti.net</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovative Dealer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jarvis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lightyear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money Maker</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Inactive_Product_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to override the disabling of marking an opportunity Closed Won that has inactive products on it.</description>
        <inlineHelpText>Managers Override to mark opportunity Closed Won with inactive products in the product list.</inlineHelpText>
        <label>Inactive Product Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PAID__c</fullName>
        <inlineHelpText>Account paid</inlineHelpText>
        <label>PAID</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Paid_Date__c</fullName>
        <description>The date the opportunity was paid to us by the dealer</description>
        <inlineHelpText>Set by the Vin Opportunity Approval Process being fully approved</inlineHelpText>
        <label>Paid Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phased_Project__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>updated by a trigger when a product has the solution product checkbox checked</inlineHelpText>
        <label>Phased Project</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Active_Product__c</fullName>
        <formula>IF(PricebookEntry.Product2.IsActive = TRUE, &quot;TRUE&quot;, &quot;FALSE&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active Product</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/OpportunityPopupController.cls
public with sharing class OpportunityPopupController {
        
    //setup public getters/setters
    public Id Id {get;set;}
    public Opportunity thisOpp {get;set;}
    public Account thisAccount {get;set;}
    public String oppStatus {get;set;}
    public boolean showPopupDataIntegration {get;set;}
    public boolean showPopupInactiveProducts {get;set;}
    public boolean showAgain {get;set;}
    public LIST<OpportunityLineItem> theseOLIs {get;set;}
	        
        
    public OpportunityPopupController(ApexPages.Standardcontroller controller) {
                
    	Opportunity tempOpp = (Opportunity)controller.getRecord();
        
        if(tempOpp != null) { 
    		
    		Id = tempOpp.Id;
        }
        
        init();
    }

    public void init() {  
    	           
    	if(Id == null) { 
			setId();
    	}
    	
        setThisOpp();
        setThisAccount();
        setTheseOLIs();         
        setOppStatus();
        setShowPopupDataIntegration();
        setShowPopupInactiveProducts();
    }
    
    public pageReference updateOppToNoShow() {
            
    	thisOpp.Phased_Project__c = true;
        update thisOpp;
        
        PageReference thisPage = new PageReference('/' + id);           
        return thisPage;
    }
        
    public void setTheseOLIs() {
        
        theseOLIs = [SELECT Id, PricebookEntry.Name, OpportunityId, Active_Product__c 
                     FROM OpportunityLineItem 
                     WHERE OpportunityId = :Id];
    }
    
    public void setId() {
        
        Id = Apexpages.currentPage().getParameters().get('id');
    }
    
    public Id getId() {
        
        return Id;
    }       
    
    public void setThisOpp() {
            
        thisOpp = [SELECT Id, StageName, AccountId, Inactive_Product_Override__c, PAID__c, Paid_Date__c, IsWon
        		   FROM Opportunity 
        		   WHERE Id = :Id 
        		   limit 1]; 
    }
    
    public Opportunity getThisOpp() {                
        
        return thisOpp;
    }   
        
    public void setThisAccount() {
        
        thisAccount = [SELECT Id, DMS_System__c 
    				   FROM Account 
    				   WHERE Id = :thisOpp.AccountId limit 1];
    }
    
    public Account getThisAccount() {
        
        return thisAccount;
    }
    
    public void setOppStatus() {
        
        oppStatus = thisOpp.StageName;
    }
    
    public String getOppStatus() {
        return oppStatus;
    }
    
    public void setShowPopupDataIntegration() {
    	
    	boolean overrideShow = false;
    	            
        if(thisOpp.StageName != 'Closed or Won') {
        	
        	for(OpportunityLineItem thisOLI : theseOLIs) {
                    
            	system.debug('OLI ' + thisOLI.PricebookEntry.Name);
            	
                if(thisOLI.PricebookEntry.Name.contains('ILM') || thisOLI.PricebookEntry.Name.contains('CRM') || 
                   thisOLI.PricebookEntry.Name.contains('Inventory Module') || thisOLI.PricebookEntry.Name.contains('Inventory Light')) {
                   	                               
                	showPopupDataIntegration = true;                               
                }
                        
            	if(thisOLI.PricebookEntry.Name.contains('Data Integration')) {
            		
                	overrideShow = true;
                }                               
             }                       
        }
    	
    	if(overrideShow == true) { 
			
			showPopupDataIntegration = false;
    	}
    }
        
    public boolean getShowPopupDateIntegration() {
    	
    	return showPopupDataIntegration;
    }
        
    public void setShowPopupInactiveProducts() {
    	        	
		if((thisOpp.IsWon == false && thisOpp.Inactive_Product_Override__c != true) || 
		   (thisOpp.PAID__c != 'Yes' && thisOpp.IsWon == true && thisOpp.Inactive_Product_Override__c != true) ||
		   (thisOpp.PAID__c == 'Yes' && thisOpp.IsWon == true && (system.today().addDays(-7) < thisOpp.Paid_Date__c) && thisOpp.Inactive_Product_Override__c != true)) {
			
			for(OpportunityLineItem thisOLI: theseOLIs) {
				
				system.debug('OLI ' + thisOLI.Active_Product__c);
				
    			if(thisOLI.Active_Product__c == 'FALSE') {
    				
					showPopupInactiveProducts = true;
    			}
    		}
    	}
    }
        
    public boolean getShowPopupInactiveProducts() {
    	
    	return showPopupInactiveProducts;
    }
        

        
}