objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <formula>VinPro2__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vin PM Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory State</label>
        <referenceTo>Territory_State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the primary contact associated with the Opportunity</inlineHelpText>
        <label>Deal Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Deal Contact)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>look up the contact under the Salesforce account that Implementation will contact regarding the setup of the products purchased</inlineHelpText>
        <label>Implementation Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Implementation Contact)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <label>Implementation Manager</label>
        <picklist>
            <picklistValues>
                <fullName>Matt Bench</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travis Douglas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jennifer Merrick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kandy Richert</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the user that initiated the opportunity: fishing pole, PM, etc</inlineHelpText>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>We_Owe__c</fullName>
        <inlineHelpText>Notes added to this field will automatically populate to the project when the sale is approved</inlineHelpText>
        <label>Implementation Notes</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ActualDescription__c</fullName>
        <label>ActualDescription</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Territory_State__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DDM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityProductClass.cls
@isTest
public with sharing class OpportunityProductClass 
{
	/*
	public static testmethod void TestOpptyLineItems()
	{
		Territory_State__c TS = new Territory_State__c();
  		TS.Name = 'XX';
		TS.Account_Manager__c = userinfo.getUserId();
		TS.DDM__c = userinfo.getUserId();
		TS.Regional__c = userinfo.getUserId();
		TS.Implementation_Manager__c = userinfo.getUserId();
        TS.Implementation_Specialist__c = userinfo.getUserId();
		insert TS;
  		
  		Account A = new Account();
		A.ShippingCity='test';
		A.ShippingStreet='test';
		A.ShippingState='XX';
		A.ShippingPostalCode='test';
		A.BillingState = 'XX';
		A.AccountNumber = '1';
		A.BillingCity = 'test';
        A.BillingCountry = 'USA';
        A.BillingPostalCode = '66212';
        A.BillingState = 'TS';
        A.BillingStreet = '1234';
		
		A.name = 'TestAccount';
						
		insert A;
		
		A.Type = 'Prospect';
		
		update A;
		
		string AcctId = A.Id;
		
		Contact Ctc = new Contact();
		Ctc.AccountId = A.Id;
		Ctc.FirstName = 'test';
		Ctc.LastName = 'test';
				
		insert Ctc;
		Opportunity O  = new Opportunity();
		O.AccountId = AcctId; //set the required fields
		O.Name = 'test';
		O.Deal_Contact__c = Ctc.id;
		O.CloseDate = System.today();
		O.StageName = 'Prospect';
		O.Type = 'New Business';
		O.Salesperson__c = userinfo.getUserId();
		O.Implementation_Contact__c = Ctc.id;
		O.We_Owe__c = 'N/A'; 
		
		insert O; //save it to SFDC (it will rollback after your test
		
		/*
		Product2 PT2 = new Product2();
		PT2.Description = 'test';
		PT2.Name = 'test';
		PT2.Family = 'setup';
		PT2.IsActive = true;		
		Insert PT2;
		
		Pricebook2 PB2 = new Pricebook2();
		PB2.Name = 'test';
		PB2.IsActive = true;
		PB2.Description = 'test';			
		insert PB2;		
		 *//*
		PricebookEntry PBE = [select id, Product2Id, Pricebook2Id, IsActive, UnitPrice, UseStandardPrice from PricebookEntry where IsActive = true limit 1];
				
		OpportunityLineItem OLI = new OpportunityLineItem();
		OLI.PricebookEntryId = PBE.Id;
		OLI.Quantity = 1;		
		OLI.ActualDescription__c = 'website';
		OLI.OpportunityId = O.id;		
		OLI.TotalPrice = 10.00;
		insert OLI;
	}
	*/
}