objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <formula>VinPro2__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vin PM Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flag_for_Heat__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>used to Flag an account as a Heat account</inlineHelpText>
        <label>Flag for Heat</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Heat_Notes__c</fullName>
        <inlineHelpText>when an account is flagged for heat - heat notes must be entered to go into heat email</inlineHelpText>
        <label>Heat Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Implementation_Date__c</fullName>
        <inlineHelpText>last time the customer had a product implemented (CRM, ILM, DIY, Website) - equals the Confirmed Training Start Date</inlineHelpText>
        <label>Implementation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Special_Account_Status__c</fullName>
        <label>Special Account Status</label>
        <picklist>
            <controllingField>Flag_for_Heat__c</controllingField>
            <picklistValues>
                <fullName>DAB Heat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAB Member</fullName>
                <color>#990000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Heat Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revenue Opportunity</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Revenue Opp Heat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Territory_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory State</label>
        <referenceTo>Territory_State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Force_High__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Forces a Case to have the highest severity value in TFS. (via formula)</description>
        <inlineHelpText>Forces a Case to have the highest severity value in TFS.</inlineHelpText>
        <label>Force Highest Severity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Been_Flagged_Manager__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This Case has been flagged by a Queue Lead sometime in the past. Formerly set to Manager.</description>
        <inlineHelpText>This Case has been flagged by a Queue Lead sometime in the past.</inlineHelpText>
        <label>Has Been Flagged by Queue Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Been_Flagged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Denotes that this Case has been flagged by a worker sometime in the past.</description>
        <inlineHelpText>Denotes that this Case has been flagged by a worker sometime in the past.</inlineHelpText>
        <label>Has Been Flagged by Worker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Super_Priority__c</fullName>
        <inlineHelpText>4 - lowest priority, 1 - highest priority. Formerly known as Wrangler Priority.</inlineHelpText>
        <label>Super Priority</label>
        <picklist>
            <picklistValues>
                <fullName>4 - Cold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Cool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Warm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 - Hot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Special_Account_Status__c</fullName>
        <formula>TEXT( Account.Special_Account_Status__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Special Account Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DDM__c</fullName>
        <formula>IF(State = &quot;NY&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;PA&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;NC&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;IL&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;IN&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;GA&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;WI&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;OH&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;WA&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;OR&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;TN&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;IA&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;SC&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;AR&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;LA&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;MA&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;ID&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;VT&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;NE&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;NV&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;ME&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;NH&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;DE&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;TX&quot;, &quot;Alex Moore&quot;,
IF(State = &quot;RI&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;WV&quot;, &quot;Donna Stearns&quot;,
IF(State = &quot;CA&quot;, &quot;Donna Stearns&quot;, &quot;Alex Moore&quot;)
))))))))))))))))))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DDM</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Territory_State__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DDM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Website_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Website Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States9</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WeightedRanking_TEST.cls
@isTest
private class WeightedRanking_TEST {

    static testMethod void WeightedRanking_TestMethod() {
        // TO DO: implement unit test
     		
     		
     		/*Territory_State__c TS = new Territory_State__c();
	  		TS.Name = 'XX';
			TS.Account_Manager__c = userinfo.getUserId();
			TS.DDM__c = userinfo.getUserId();
			TS.Regional__c = userinfo.getUserId();
			TS.Implementation_Manager__c = userinfo.getUserId();
	        TS.Implementation_Specialist__c = userinfo.getUserId();	
	        TS.Website_Manager__c = userInfo.getUserId();	
			insert TS;*/
     		
     		Account a = new Account();
        	a.ShippingCity = 'test';
        	a.shippingStreet = 'test';
        	a.ShippingState = 'KS';
        	a.ShippingPostalCode = '12345';
        	a.BillingState = 'KS';
        	a.AccountNumber = '1';
        	a.BillingCity = 'test';
        	a.BillingCountry = 'USA';
        	a.BillingPostalCode = '12345';
        	a.BillingState = 'KS';
        	a.BillingStreet = '1234';
        	a.Flag_for_Heat__c = true;
        	a.Implementation_Date__c = system.today() - 30;
        	a.Special_Account_Status__c = 'DAB Heat';
        	a.Heat_Notes__c = 'Test notes here';
        	a.name = 'Test Account';
        	a.Type = 'Prospect';
        	//a.Territory_State__c = TS.Id;
        	//a.Special_Account_Status__c = 'DAB Hest';
        	
        	insert a;
        	string aid = a.Id;
        	
        	Contact ct = new Contact();
        	ct.AccountId = a.Id;
        	ct.FirstName = 'test';
        	ct.LastName = 'test';
        	ct.Phone = '9999999999';
        	
        	insert ct;
        	
        	Case c = new Case();
        
        	c.AccountId = a.Id;
        	c.ContactId = ct.Id;
        	c.Origin = 'Phone';
        	c.Reason = 'Lead Issue'; 
        	c.Status = 'new';
        	c.Priority = '3 - Cold (Fix in the future)';
        	c.Has_Been_Flagged_Manager__c = true;
        	c.Has_Been_Flagged__c = true;
        	c.Super_Priority__c = '1 - Hot';
        	c.Force_High__c = true;
        	
        	
        	insert c;
        	
        	Case c2 = new Case();
        
        	c2.AccountId = a.Id;
        	c2.ContactId = ct.Id;
        	c2.Origin = 'Phone';
        	c2.Reason = 'Lead Issue';
        	c2.Status = 'new';
        	c2.Priority = '3 - Cold (Fix in the future)';
        	c2.Has_Been_Flagged_Manager__c = true;
        	c2.Has_Been_Flagged__c = true;
        	c2.parentId = c.Id;
        	c2.Super_Priority__c = '1 - Hot';
        	c2.Force_High__c = true;
        	insert c2;
        	
        	WeightedRanking wr = new WeightedRanking();
        	wr.CalculateParentRanking(new Set<Id>{c.Id});
        	wr.CalculateChildRanking(new Set<Id>{c2.Id});
        	
    }
  
}