objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <formula>VinPro2__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vin PM Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory State</label>
        <referenceTo>Territory_State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VS_Dealer_ID__c</fullName>
        <inlineHelpText>CAN BE DELETED when this is no longer referenced. This is an admin used in test code and batch jobs</inlineHelpText>
        <label>VS Dealer ID DONOTUSE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the primary contact associated with the Opportunity</inlineHelpText>
        <label>Deal Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Deal Contact)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>look up the contact under the Salesforce account that Implementation will contact regarding the setup of the products purchased</inlineHelpText>
        <label>Implementation Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Implementation Contact)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <label>Implementation Manager</label>
        <picklist>
            <picklistValues>
                <fullName>Matt Bench</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travis Douglas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jennifer Merrick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kandy Richert</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Inactive_Product_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to override the disabling of marking an opportunity Closed Won that has inactive products on it.</description>
        <inlineHelpText>Managers Override to mark opportunity Closed Won with inactive products in the product list.</inlineHelpText>
        <label>Inactive Product Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when an invoice is generated so that we can make sure nothing gets paid without an invoice being created.</description>
        <label>Invoice Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Multi_Installments_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Multi-Installments Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Installments__c</fullName>
        <label>Number of Installments</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Override_Related_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>check to override the whole product of the related product error</inlineHelpText>
        <label>Override Related Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Territory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>We_Owe__c</fullName>
        <inlineHelpText>Notes added to this field will automatically populate to the project when the sale is approved</inlineHelpText>
        <label>Implementation Notes</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ActualDescription__c</fullName>
        <label>ActualDescription</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Override_Related_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>check box to override the related product error</inlineHelpText>
        <label>Override Related Product</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Related_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product relation required to Close Won an opportunity</inlineHelpText>
        <label>Related Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Related Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Territory_State__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DDM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityClass_test.cls
@isTest(SeeAllData=True)
private class OpportunityClass_test {

    static testMethod void myUnitTest() {
        
        Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
        	emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
        	localesidkey = 'en_US', profileid = pro.Id, UserRoleId = '00E70000001GBsB',
        	timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com');
        	
        insert u_testMethodUser;
        
        System.runas(u_testMethodUser) {
        
        
        }
    }
    
    public static TestMethod void testInvoiceInformation()
    {
        /*Territory_State__c TS = new Territory_State__c();
        TS.DDM__c = userinfo.getUserId();
        TS.Account_Manager__c = userinfo.getUserId();
        TS.Territory_Manager__c = userinfo.getUserId();
        TS.Implementation_Manager__c = userinfo.getUserId();
        TS.Implementation_Specialist__c = userinfo.getUserId();
        TS.Regional__c = userinfo.getUserId();
        
        TS.Name = 'TS';
        insert TS;*/
        
        Account A = new Account();
        A.BillingState = 'TS';
        A.BillingCity = 'Test City';
        A.BillingStreet = '123 Test'; 
        A.BillingPostalCode = '12345'; 
        A.BillingCountry = 'USA';
        A.ShippingStreet = '123 Test';
        A.ShippingState = 'KS';
        A.ShippingPostalCode = '12345';
        A.ShippingCountry = 'USA';
        A.ShippingCity = 'Test City';
        A.Name = 'test';
        A.VS_Dealer_ID__c = 1234;
        A.AccountNumber = '1234';
        try{
        insert A;
        } catch(Exception e){
        
        }
        Contact C = new Contact();
        C.FirstName = 'Testfirst';
        C.LastName = 'Testlast';
        C.Account = A;
        try{
        insert C;
        } catch(DmlException e) {
        	
        	
        	
        }
        Opportunity O = new Opportunity();
        O.AccountId = A.Id;
        O.Name = 'test';
        O.CloseDate = system.today();
        O.Deal_Contact__c = C.Id;
        O.StageName = 'Prospect';
        O.Implementation_Contact__c = C.id;
        //O.We_Owe__c = 'test we owe';
        O.Number_of_Installments__c = '1';
        O.Amount = 1000;
        
        insert O;
        
        Product2 product = [select Id, Related_Product__c, isActive from Product2 where isActive = true AND (Related_Product__c = null OR Related_Product__c = '') limit 1];            
        

        PricebookEntry PBE = [select id, Product2Id, Pricebook2Id, IsActive, UnitPrice, UseStandardPrice from PricebookEntry where IsActive = true AND Product2Id =: product.Id limit 1];
        
        
                
    
                
        OpportunityLineItem OLI = new OpportunityLineItem();
        OLI.PricebookEntryId = PBE.Id;
        OLI.Quantity = 1;       
        OLI.ActualDescription__c = 'website';
        OLI.OpportunityId = O.id;       
        OLI.TotalPrice = 1000.00;       
        insert OLI;
        
        Test.startTest();
        OLI.Override_Related_Product__c = true;
        update OLI;
        
        O.StageName = 'Closed or Won';
        O.Inactive_Product_Override__c = true;
       
		try {       
        update O;
		} Catch(Exception e) {
			
		}
        //OpportunityClass.GenerateInstallments(O);
        //OpportunityClass.UpdateInvoiceInformation(O);
        
        O.Multi_Installments_Approved__c = true;
        O.Number_of_Installments__c = '2';
        O.Invoice_Generated__c = false;
        
        try{
        update O;}
        catch(Exception e){
        	
        	
        }
        
        O.StageName = 'Prospect';
        try{
        update O;
        } catch(Exception e) {
        	
        	
        }
        
        O.StageName = 'Closed or Won';
        try {
        update O; 
        }catch(DmlException e) {
        	
        }
        
        //OpportunityClass.UpdateInstallments(O);                 
        //OpportunityClass.UpdateInvoiceInformation(O);
        test.stopTest();
    }
}