objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status can only be updated from a first time Closed Won Paid Opportunity and by accounting when a customer cancel services</inlineHelpText>
        <label>Vin Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OOB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>vAuto_POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>vAuto POA</description>
        <inlineHelpText>updated by a trigger</inlineHelpText>
        <label>vAuto POA</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>POA__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>vAuto</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>POA_Type__c</fullName>
        <description>This field controls which type of POA this Opportunity gets assigned to.</description>
        <inlineHelpText>Controls the type of POA this Opportunity gets Assigned to</inlineHelpText>
        <label>POA Type</label>
        <picklist>
            <picklistValues>
                <fullName>Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Genius Labs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red Wagon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOT DEFINED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <businessProcess>vAuto</businessProcess>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Opp_Product_Suite__c</fullName>
        <formula>TEXT(Opportunity.Opportunity_Names__c)</formula>
        <inlineHelpText>formula field that reads the opportunity product suite</inlineHelpText>
        <label>Opp Product Suite</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will hold the POA for this product.</description>
        <label>POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <formula>PricebookEntry.Product2.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductId</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/POA__c.object
<CustomObject>
    <description>used to handle Plan of Action items for an Account- gives the ability to group support or implementation issues together</description>
    <fields>
        <fullName>Account_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>POA_AD_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <description>This holds the Account OwnerId; Creating this to compare when creating Accont Team Members;</description>
        <formula>Dealer__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Account Owner</inlineHelpText>
        <label>Account Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Acquisition_Pro__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Acquisition Pro</label>
        <referenceTo>User</referenceTo>
        <relationshipName>POAs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup the dealer that the plan of action is needed for</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan of Action(s)</relationshipLabel>
        <relationshipName>POA_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POA_Type__c</fullName>
        <formula>CASE(RecordTypeId, 
   &quot;01270000000Q8PX&quot;, &quot;New Account F/U&quot;, 
   &quot;01270000000Q8Fw&quot;, &quot;Support&quot;,
   &quot;01270000000Q8G1&quot;, &quot;Cancellation&quot;,
   &quot;01270000000Q8G6&quot;, &quot;AutoTrader&quot;,
   &quot;01270000000Q8QL&quot;, &quot;CRM Followup&quot;,
   &quot;01270000000Q8QG&quot;, &quot;Implementation&quot;,
   &quot;01270000000Q8SH&quot;, &quot;VinSocial&quot;,
   &quot;01270000000Q9Pi&quot;,&quot;New Website Followup&quot;,
   &quot;01270000000Q9a7&quot;,&quot;New Website Followup&quot;,
   &quot;01270000000QARz&quot;,&quot;Account Mgmt POA&quot;,
   &quot;01270000000QB6U&quot;,&quot;Haystak SEM&quot;,
   &quot;01270000000QB5g&quot;,&quot;Haystak SEO&quot;,
   &quot;012Q000000095t4&quot;, &quot;vAuto Provision&quot;,
   &quot;NOT DEFINED, EDIT FIELD&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>looks up the record type id and converts it to text</inlineHelpText>
        <label>POA Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending PM Assignment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Intro Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Needs Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 1 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 2 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 3 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 4 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 5 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 6 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation - LOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failure to Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>POA</label>
    <nameField>
        <label>Plan of Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POAs</pluralLabel>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProductId__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This feild will control which project will be created</description>
        <label>Project Definition</label>
        <referenceTo>Project_Definition__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <label>vAuto</label>
    </recordTypes>
</CustomObject>

objects/Project_Definition__c.object
<CustomObject>
    <description>This object will hold the attributes of the project.</description>
    <fields>
        <fullName>Default_POA_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default POA Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Definitions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POA_Type__c</fullName>
        <inlineHelpText>Sets the record type of the POA that is generated. If this is blank, no POA will be generated.</inlineHelpText>
        <label>POA Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Haystak ADVD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Account Mgmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Behavioral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Website</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Definition</label>
    <nameField>
        <label>Project Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>vAuto_Layout</fullName>
        <active>true</active>
        <label>vAuto Layout</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vAuto_Acquisition_Assignment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to assign Acquisition Pro field on vAuot POAs for Stoackwave</description>
    <fields>
        <fullName>UserID__c</fullName>
        <description>The actual ID of the user assigned to the Name field</description>
        <label>UserID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>vAuto Acquisition Assignment</label>
</CustomObject>

classes/vAutoPOAHandler.cls
public class vAutoPOAHandler extends POAHandler{   
 
     public override void afterInsert(POA__c poa){
    	system.debug('setting vAuto POA on account after POA is inserted');
        setvAutoPOA(poa);
    }
    
    public override void afterUpdate(POA__c newpoa,POA__c oldpoa){
       
        if(newpoa.Dealer__c !=null && newpoa.Dealer__r.vAuto_POA__c == null){
             setvAutoPOA(newpoa);
        }
        
        if(newpoa.OwnerId != oldpoa.OwnerId){
             ResetPerformanceManagerAccountTeam(newpoa,oldpoa);
        }
        if(newpoa.Account_Director__c != oldpoa.Account_Director__c){
             ResetAccountDirectorAccountTeam(newpoa,oldpoa);
             //CreateTask('* Reassigned Account Director Call',0,newpoa.ownerId, newpoa.Id,'You have been assigned to an existing customer. Please make an intro call and introduce yourself.');
        }
       
    }
   

    public override  Map<String, POA__c>  UpsertPOA(OpportunityLineItem oppLine, Map<String, POA__c> existingPOAs){
        POA__c poa;             
        //Product2 product = [Select Id, Project_Definition__c,Name from Product2 where Id =: oppLine.ProductId__c];
        //if(product.Project_Definition__c == null){
        if(oppLine.PricebookEntry.Product2.Project_Definition__c == null){
             //throw new CoxAutomotiveException('No Project Definition Specified for Product: '+product.Name);
             System.debug('No POA Required for product: No Project Definition Specified for Product: '+oppLine.PricebookEntry.Product2.Name);
             
            return existingPOAs;          
        }
        
        Project_Definition__c productDefinition = StaticData.getInstance().ProjectDefinitions().get(oppLine.PricebookEntry.Product2.Project_Definition__c);
        
        if(productDefinition == null){
             throw new CoxAutomotiveException('Project Definition is not valid for Product: '+oppLine.PricebookEntry.Product2.Name);          
        }
        
        //check if there is a POA existing 
        String posRecordTypeName = productDefinition.POA_Type__c;
        if(posRecordTypeName == null || posRecordTypeName.trim()==''){
            System.debug('No POA Required for product: '+oppLine.PricebookEntry.Product2.Name);
            return existingPOAs;
        }

        RecordType poaRecordType = StaticData.getInstance().POARecTypesMapByName.get(posRecordTypeName);

        if(poaRecordType == null){
            throw new CoxAutomotiveException('Could not find POA recordType :'+posRecordTypeName +' for product: '+oppLine.PricebookEntry.Product2.Name);
        }
        
        System.debug('poaRecordType.Name:' + poaRecordType.Name);
       
        //Check if the POA is already retrived  
        //If not find/create one and add to it
        if(!existingPOAs.containsKey(poaRecordType.Name)){          
            /*Ramana Mosali: Changes related to CR-00011898; Updated to look for non-churned POA and use it and incase if none found then look for Churned POA since it could be a returning customer and 
            reset the status on that POA to Open and use that instead of creating a new POA.
            */

            //get all non-churned vAUto POA for the account and use the most recently modified POA
            List<POA__c> existingPOA = [Select Id, Acquisition_Pro__c from POA__c where Dealer__c =: oppLine.Opportunity.AccountId and  RecordTypeId =: poaRecordType.Id and status__c !=: 'Churned' order by LastModifiedDate desc];
            
            if(existingPOA != null && existingPOA.size() > 0){
                // Updating Acquisition Pro field as per Story W-000915

                poa = existingPOA[0];
                System.debug('Assigning Existing POA: '+poa.Id);
            }
            else {
                //If there are no non-churned vAUto POA for the account
                //check if there are any churned POA since he could be a returning customer
                //get any churned vAuto POA's ordered by the most recently modified
                List<POA__c> existingChurnedPOA = [Select Id, Acquisition_Pro__c from POA__c where Dealer__c =: oppLine.Opportunity.AccountId and  RecordTypeId =: poaRecordType.Id and status__c =: 'Churned' order by LastModifiedDate desc];
                if(existingChurnedPOA != null && existingChurnedPOA.size() > 0){
                    poa = existingChurnedPOA[0];
                    System.debug('Found a Churned POA:'+poa.Id+' updating it to Open status');
                    poa.Status__c = 'Open';
                    update poa;
                    System.debug('Updated a Churned POA:'+poa.Id+' to Open status');
                    System.debug('Assigning Existing POA: '+poa.Id);
                }
                else{
                    //poa = CreatePOA(oppLine.Opportunity.AccountId,poaName,poaRecordType);
                    poa = new POA__c();    
                    String poaName =  StaticData.getInstance().getBUIdentifierByOppRecType(oppLine.Opportunity.RecordTypeId)+'-';
                
                    if(oppLine.Opportunity.Account.Name.length() > 61){        
                        poaName  += oppLine.Opportunity.Account.Name.substring(0,58) + '...';
                    }
                    else {        
                        poaName  += oppLine.Opportunity.Account.Name; 
                    }

                    //Ramana:: Catch to make sure not to cross max 80 char limit.
                    //if the name still exceeds 80 max length
                    if(poaName.length() >= 80){
                        //get only the first 80 char.
                        poaName = poaName.substring(0,79);  
                    } 

                    if(productDefinition.Default_POA_Owner__c != null){     
                        poa.OwnerId = productDefinition.Default_POA_Owner__c;
                    }
                    poa.Dealer__c =  oppLine.Opportunity.AccountId;
                    poa.RecordTypeId = poaRecordType.Id;
                    poa.Name =  poaName;
                    insert poa;    

                    System.debug('Created New POA of RecordType: '+poaRecordType.Name);
                    System.debug('Created New POA: '+poa.Id);            
                }
            } 
            // Updating Acquisition Pro field as per Story W-000915
            if(oppLine.Opp_Product_Suite__c.contains('Stockwave') && (oppLine.Opportunity.Type == 'Sale' || oppLine.Opportunity.Type == 'Reactivate')){
                // vAuto_Acquisition_Assignment__c is a custom setting
                vAuto_Acquisition_Assignment__c instance = vAuto_Acquisition_Assignment__c.getInstance('Acquisition Pro');
                poa.Acquisition_Pro__c = instance.UserID__c;
                update poa;
            }
            existingPOAs.put(poaRecordType.Name,poa);
        }
        
        return existingPOAs;
    }

    private void CreateTask(String subject, Integer dueInDays, Id ownerId, Id whatId
    ,String description){
	Task task = new Task();
	task.Subject =  subject;
	task.ActivityDate = System.today().addDays(dueInDays);
	task.OwnerId = ownerId;
	task.WhatId = whatId;
	task.Description =description;
	task.Priority ='Normal';
	task.Type='Task';
 	task.RecordTypeId = StaticData.getInstance().TaskRecordTypeMapByDevName.get('vAuto_Layout').Id;
	
	insert task;
}
     private void ResetAccountDirectorAccountTeam(POA__c newpoa,POA__c oldpoa){
     	System.debug('BEGIN Assigning VAT Account Director');
     	DeleteAccountTeam(oldpoa.Dealer__c,oldpoa.Account_Director__c,'VAT Account Director');
		InsertAccountTeam(newpoa.Dealer__c,newpoa.Account_Owner__c, newpoa.Account_Director__c,'VAT Account Director');
		System.debug('END Assigning VAT Account Director');
     } 
     private void ResetPerformanceManagerAccountTeam(POA__c newpoa,POA__c oldpoa){
     	System.debug('BEGIN Assigning VAT Performance Manager');
     	DeleteAccountTeam(oldpoa.Dealer__c,oldpoa.ownerId,'VAT Performance Manager');
		InsertAccountTeam(newpoa.Dealer__c,newpoa.Account_Owner__c,newpoa.ownerId,'VAT Performance Manager');
		System.debug('END Assigning VAT Performance Manager');
     }
	 private void DeleteAccountTeam(Id accountId, Id userId, String roleName){
	 	if(userId == null) {return;}
	   	List<AccountTeamMember> teamMembers = [Select Id from AccountTeamMember
	   	where UserId =: userId
	   	and AccountId =: accountId
	   	and TeamMemberRole =: roleName];
	   	if(teamMembers.size()> 0){ 
	   		System.debug('deleting existing VAT Performance Manager');
	   		delete teamMembers;
	   	}
	 }


     private void InsertAccountTeam(Id accountId,Id accountOwnerId, Id userId , String roleName){

        //check if the user being assigned is not Account owner already
        if(accountOwnerId == userId){
            //user is already a owner of the account no need to create AccountTeam member
            //If attemped to create; will error out with
            // INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY, insufficient access rights on cross-reference id
            // Since as a owner user already has more access than and creating this AccountTeam member will create conflict
            System.debug('User is already a owner on the account; cannot create AccountTeam with role:'+roleName);
            return;
        }

        if(userId != null && accountId != null && roleName != null) {
            AccountTeamMember accTeam = new AccountTeamMember(
                UserId = userId,
                AccountId = accountId,
                TeamMemberRole = roleName
            );
 
            AccountShare accShare = new AccountShare(
                AccountId = accountId,
                UserOrGroupId = userId,
                AccountAccessLevel = 'Edit',
                OpportunityAccessLevel = 'Read',
                CaseAccessLevel = 'Read',
                ContactAccessLevel = 'Read'
            ); 

            AccountTMHelper atmh = new AccountTMHelper(accTeam, accShare);
            List<AccountShare> acctShare = [SELECT Id,AccountId,UserOrGroupId, AccountAccessLevel, ContactAccessLevel, OpportunityAccessLevel, CaseAccessLevel FROM AccountShare WHERE AccountId=: accountId and UserOrGroupId = :userId LIMIT 1];

            if(acctShare != null && acctShare.size() > 0) {
                atmh = atmh.mergeTM(new AccountTMHelper(acctShare[0]));
            }
			System.debug('Inserting existing VAT Performance Manager');
			System.debug('accTeam.UserId: '+accTeam.UserId);
			System.debug('accTeam.AccountId: '+accTeam.AccountId);
			System.debug('accTeam.TeamMemberRole: '+accTeam.TeamMemberRole);
            insert atmh.tm;
            insert atmh.acctShare;
        }   
     }

    private void setvAutoPOA(POA__c poa){
        system.debug('Checking vAuto POA on account: '+poa.Dealer__c);
        
            //set the vAuto POA lookup on account
            //

   /*Ramana Mosali: Changes related to CR-00011898; updating to assign not the passed POA but most recently modified non-churned POA*/
   /* List<POA__c> existingPOA = [Select Id from POA__c where Dealer__c =:poa.Dealer__c and  RecordTypeId =: poa.RecordTypeId and status__c !=: 'Churned' and Id !=: poa.Id];
    if(existingPOA == null || existingPOA.size() == 0){
            
            system.debug('Setting vAuto POA on account: '+poa.Dealer__c);
            //if this is the only one set the field
            Account acct = new Account(Id = poa.Dealer__c);
            acct.vAuto_POA__c = poa.Id;
            update acct;            
        }
        else{
            // throw an error since there can not be more than one vAuto POA on a account
             throw new CoxAutomotiveException('There are '+existingPOA.size()+' existing vAuto POA on account, cannot create more than one');
        }
    */
   
   //get all non churned vAuto POA's for this account
    List<POA__c> existingPOA = [Select Id from POA__c where Dealer__c =:poa.Dealer__c and  RecordTypeId =: poa.RecordTypeId and status__c !=: 'Churned' order by LastModifiedDate desc];
        
        if( existingPOA != null && existingPOA.size() >0){
        	
        	system.debug('Setting vAuto POA on account: '+poa.Dealer__c);
            //if this is the only one set the field
            Account acct = new Account(Id = poa.Dealer__c);
            acct.vAuto_POA__c = existingPOA[0].Id;
            update acct;            
        }
        else {

        //If there are no non-churned vAUto POA for the account
        //check if there are any churned POA since he could be a returning customer
        //get any churned vAuto POA's ordered by the most recently modified
        List<POA__c> existingChurnedPOA = [Select Id from POA__c where Dealer__c =:poa.Dealer__c and  RecordTypeId =: poa.RecordTypeId and status__c = 'Churned' order by LastModifiedDate desc];
        if(existingChurnedPOA != null && existingChurnedPOA.size() > 0){
        system.debug('Setting vAuto POA on account: '+poa.Dealer__c);
            //if this is the only one set the field
            Account acct = new Account(Id = poa.Dealer__c);
            acct.vAuto_POA__c = existingChurnedPOA[0].Id;
            update acct;     
        }       
        else{
            //There is nothing to assign; this should not happen 
            throw new CoxAutomotiveException('There is no '+poa.RecordType.Id+' type POA found to assign for Account: '+poa.Dealer__c);
        }        
        }
      }
    
}