objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status can only be updated from a first time Closed Won Paid Opportunity and by accounting when a customer cancel services</inlineHelpText>
        <label>Vin Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OOB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>POA_Type__c</fullName>
        <description>This field controls which type of POA this Opportunity gets assigned to.</description>
        <inlineHelpText>Controls the type of POA this Opportunity gets Assigned to</inlineHelpText>
        <label>POA Type</label>
        <picklist>
            <picklistValues>
                <fullName>Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Genius Labs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red Wagon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOT DEFINED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will hold the POA for this product.</description>
        <label>POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <formula>PricebookEntry.Product2.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductId</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/POA__c.object
<CustomObject>
    <description>used to handle Plan of Action items for an Account- gives the ability to group support or implementation issues together</description>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup the dealer that the plan of action is needed for</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan of Action(s)</relationshipLabel>
        <relationshipName>POA_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POA_Type__c</fullName>
        <formula>CASE(RecordTypeId, 
   &quot;01270000000Q8PX&quot;, &quot;New Account F/U&quot;, 
   &quot;01270000000Q8Fw&quot;, &quot;Support&quot;,
   &quot;01270000000Q8G1&quot;, &quot;Cancellation&quot;,
   &quot;01270000000Q8G6&quot;, &quot;AutoTrader&quot;,
   &quot;01270000000Q8QL&quot;, &quot;CRM Followup&quot;,
   &quot;01270000000Q8QG&quot;, &quot;Implementation&quot;,
   &quot;01270000000Q8SH&quot;, &quot;VinSocial&quot;,
   &quot;01270000000Q9Pi&quot;,&quot;New Website Followup&quot;,
   &quot;01270000000Q9a7&quot;,&quot;New Website Followup&quot;,
   &quot;01270000000QARz&quot;,&quot;Account Mgmt POA&quot;,
   &quot;01270000000QB6U&quot;,&quot;Haystak SEM&quot;,
   &quot;01270000000QB5g&quot;,&quot;Haystak SEO&quot;,
   &quot;012Q000000095t4&quot;, &quot;vAuto Provision&quot;,
   &quot;NOT DEFINED, EDIT FIELD&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>looks up the record type id and converts it to text</inlineHelpText>
        <label>POA Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending PM Assignment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Intro Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Needs Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 1 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 2 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 3 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 4 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 5 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 6 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation - LOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failure to Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VinPro_Manager__c</fullName>
        <formula>Owner:User.Manager.User_Full_Name__c</formula>
        <inlineHelpText>formula field that reads the Performance Manager&apos;s assigned Manager from the Account</inlineHelpText>
        <label>Manager/Director</label>
        <type>Text</type>
    </fields>
    <label>POA</label>
    <nameField>
        <label>Plan of Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POAs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProductId__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This feild will control which project will be created</description>
        <label>Project Definition</label>
        <referenceTo>Project_Definition__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Project_Definition__c.object
<CustomObject>
    <description>This object will hold the attributes of the project.</description>
    <fields>
        <fullName>Default_POA_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default POA Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Definitions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POA_Type__c</fullName>
        <inlineHelpText>Sets the record type of the POA that is generated. If this is blank, no POA will be generated.</inlineHelpText>
        <label>POA Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Haystak ADVD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Account Mgmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Behavioral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Website</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Definition</label>
    <nameField>
        <label>Project Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/VinPOAHandler.cls
public class VinPOAHandler  extends POAHandler{ 
  
   /*  public override void beforeInsert(POA__c poa){
    	system.debug('setting Vin Performance Manager POA on inserted');
        setVinPerformanceManager(poa);
    }
    
    public override void beforeUpdate(POA__c newpoa,POA__c oldpoa){
    	system.debug('setting Vin Performance Manager POA on update');
    	if(newpoa.Dealer__c !=null && newpoa.Dealer__c != oldpoa.Dealer__c){
        setVinPerformanceManager(newpoa);
    	}
    }

    private void setVinPerformanceManager(POA__c poa){
	 	if(poa.Dealer__c == null) {return;}

	   	List<AccountTeamMember> teamMembers = [Select Id from AccountTeamMember
	   	where AccountId =: poa.Dealer__c
	   	and TeamMemberRole =: 'Vin Performance Manager'];
	   	if(teamMembers.size()> 0){ 
	   		System.debug('Setting the Vin Performance Manager on POA');
	   		poa.VinPro_Manager__c = teamMembers[0].userId;
	   	}
	 }*/ 
  public override  Map<String, POA__c>  UpsertPOA(OpportunityLineItem oppLine, Map<String, POA__c> existingPOAs){
	POA__c poa;         	

	    //Product2 product = [Select Id, Project_Definition__c,Name from Product2 where Id =: oppLine.ProductId__c];
	    //if(product.Project_Definition__c == null){
	    if(oppLine.PricebookEntry.Product2.Project_Definition__c == null){
	         //throw new CoxAutomotiveException('No Project Definition Specified for Product: '+product.Name);
	         System.debug('No POA Required for product: No Project Definition Specified for Product: '+oppLine.PricebookEntry.Product2.Name);
	         
	    	return existingPOAs;	      
	    }
	    
	    Project_Definition__c productDefinition = StaticData.getInstance().ProjectDefinitions().get(oppLine.PricebookEntry.Product2.Project_Definition__c);
	    if(productDefinition == null){
	         throw new CoxAutomotiveException('Project Definition is not valid for Product: '+oppLine.PricebookEntry.Product2.Name);	      
	    }
	    
	    //check if there is a POA existing
	    
	    String posRecordTypeName = productDefinition.POA_Type__c;
	    if(posRecordTypeName == null || posRecordTypeName.trim()==''){
	    	
	    	System.debug('No POA Required for product: '+oppLine.PricebookEntry.Product2.Name);
	    	return existingPOAs;
	    }
	    RecordType poaRecordType = StaticData.getInstance().POARecTypesMapByName.get(posRecordTypeName);
	    if(poaRecordType == null){
	    throw new CoxAutomotiveException('Could not find POA recordType :'+posRecordTypeName +' for product: '+oppLine.PricebookEntry.Product2.Name);
	    }
	    
	    System.debug('poaRecordType.Name:' + poaRecordType.Name);
	   
	    //Check if the POA is already retrived	
	    //If not find/create one and add to it
	    if(!existingPOAs.containsKey(poaRecordType.Name)){	    	
	    
	    List<POA__c> existingPOA = [Select Id from POA__c where Dealer__c =: oppLine.Opportunity.AccountId and  RecordTypeId =: poaRecordType.Id and status__c !=: 'Churned'];
	    
	    if(existingPOA != null && existingPOA.size() > 0){
	    poa = existingPOA[0];
	   
	    System.debug('Assigning Existing POA: '+poa.Id);
	    }
	    else {
	    poa = new POA__c();
 
	    String poaName =  productDefinition.POA_Type__c+'-';
	
			if(oppLine.Opportunity.Account.Name.length() >= 61){        
	    	poaName  += oppLine.Opportunity.Account.Name.substring(0,60) + '...'+'-';
		}
		else {        
	     poaName  += oppLine.Opportunity.Account.Name+'-'; 
		}

	poaName  += system.today().format();


	// check name length
	//If length exceeds 80; try to take the excceded char count from account Name
    if(poaName.length() >= 80){
      try{
      Integer exceededCharCount =  poaName.length() - 80;
      if(oppLine.Opportunity.Account.Name.length() > 41){
          poaName = productDefinition.POA_Type__c+'-'+oppLine.Opportunity.Account.Name.substring(0,41-exceededCharCount);
        }
        else{
           poaName = productDefinition.POA_Type__c+'-'+oppLine.Opportunity.Account.Name.substring(0,oppLine.Opportunity.Account.Name.length() - exceededCharCount);
        }
        poaName  += system.today().format();
      } 
      Catch(Exception ex){
        //Being cautious
        //For some reason there is a error while trying to get the right split;
        //it is not end of the world; let's continue by truncating from the end;
        //Users can still have an option to change the name; instead of erroring out on 
        //creation all together;
      }
    }

    //Ramana:: Catch to make sure not to cross max 80 char limit.
    //if the name still exceeds 80 max length
    if(poaName.length() >= 80){
      //get only the first 80 char.
      poaName = poaName.substring(0,79);
      
    } 

	    if(productDefinition.Default_POA_Owner__c != null){	    
	    poa.OwnerId = productDefinition.Default_POA_Owner__c;
		}
	    poa.Dealer__c =  oppLine.Opportunity.AccountId;
	    poa.RecordTypeId = poaRecordType.Id;
	    poa.Name =  poaName;
	    insert poa;	   
	    System.debug('Created New POA of RecordType: '+poaRecordType.Name);
	    System.debug('Created New POA: '+poa.Id);
	    }
	    
	    existingPOAs.put(poaRecordType.Name,poa);
	    }
	    
	    
	    return existingPOAs;
	}
    
}