objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <inlineHelpText>Select Franchise or Independent.</inlineHelpText>
        <label>Dealer Type</label>
        <picklist>
            <picklistValues>
                <fullName>Franchise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Other</fullName>
        <active>false</active>
        <description>Partners, Consultants,</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DashboardTaskStatus__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Primary_Subject__c</fullName>
        <label>Primary Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Subject__c</fullName>
        <label>Secondary Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Status__c</fullName>
        <label>Task Status</label>
        <type>TextArea</type>
    </fields>
    <label>DashboardTaskStatus</label>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Stage__c</fullName>
        <inlineHelpText>Updated by the system upon milestone completion</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>1-Initiating</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>2-Planning and Design</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>3-Executing</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>4-Review</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>5-Finalizing</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Launched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-ILM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GO LIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Intro Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Strategy Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Dealer Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Setup Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training 1</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <description>Used for reporting.</description>
        <formula>TEXT(Account__r.Dealer_Type__c)</formula>
        <label>Dealer Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <formula>IF(!ISPICKVAL(Approval_Stage__c, &quot;Go Live&quot;) &amp;&amp; Project_Due_Date__c &gt;today() , &quot;Working&quot;,
IF(!ISPICKVAL(Approval_Stage__c, &quot;Go Live&quot;) &amp;&amp; Project_Due_Date__c &lt;Today() , &quot;Past Due&quot;, 
IF(ISPICKVAL(Approval_Stage__c, &quot;Go Live&quot;)&amp;&amp; Project_Due_Date__c &lt;  Project_Complete_Date__c , &quot;Goal Missed&quot;, 
IF(ISPICKVAL(Approval_Stage__c, &quot;Go Live&quot;) &amp;&amp; Project_Due_Date__c &gt;=  Project_Complete_Date__c , &quot;Goal Completed&quot;, 
&quot;Log Change Request&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>this field looks at the Project Due Date and formulates a status</inlineHelpText>
        <label>Project Status</label>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Stickers</fullName>
        <active>true</active>
        <description>View for Sticker Orders</description>
        <label>Stickers</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestFOD.cls
@isTest
public class TestFOD {
    
    static testmethod void testSalesPipelineCtrl() {
        Test.startTest();
        Account acc = new Account(Name = 'Account Setup', Dealer_Type__c = 'Independent');
        insert acc;
        Opportunity opp = new Opportunity(Name = 'Account Setup', CloseDate = System.today().addMonths(1), StageName = 'Prospecting', AccountId = acc.id);
        insert opp;
        opp.CloseDate = System.today();
        update opp;
        System.debug('opp==' + [select Name from Opportunity where id = :opp.id].Name);
        Account acc1 = new Account(Name = 'Conquest', Dealer_Type__c = 'Independent');
        insert acc1;
        Opportunity opp1 = new Opportunity(Name = 'Conquest', CloseDate = System.today().addMonths(1), StageName = 'Prospecting', AccountId = acc1.id);
        insert opp1;
        opp1.CloseDate = System.today();
        update opp1;
        System.debug('opp1==' + [select Name from Opportunity where id = :opp1.id].Name);
        FOD_SalesPipelineCtrl ctrl = new FOD_SalesPipelineCtrl();
        FOD_SalesPipelineCtrl.getChartInput('Conquest:Open', 'project', 'Next Month');
        FOD_SalesPipelineCtrl.getChartInput('Conquest:Open', 'acc', 'This Month');
        FOD_SalesPipelineCtrl.getChartInput('Provision:Open', 'project', 'Next Month');
        FOD_SalesPipelineCtrl.getChartInput('Provision:Open', 'acc', 'This Month');
        
        ApexPages.currentPage().getParameters().put('sp', 'Provision:Open');
        FOD_AccountListCtrl ctrl2 = new FOD_AccountListCtrl();
        ctrl2.backToDashboard();
        Test.stopTest();
        
    }
    
    static testmethod void testProvisionCtrl() {
        Test.startTest();
        customSettingData();
        SFDC_520_Quote__c proj = new SFDC_520_Quote__c(Name = 'Account Setup 1', Approval_Stage__c = 'Integration');
        insert proj;
        proj.Name = 'Account Setup 1';
        update proj;
        List<Task> tskList = new List<Task>();
        Task tsk1 = new Task(Subject = 'Integration A', Status = 'Not Started', WhatId = proj.id);
        tskList.add(tsk1);
        Task tsk2 = new Task(Subject = 'Training 1', Status = 'Not Started', WhatId = proj.id);
        tskList.add(tsk2);
        Task tsk3 = new Task(Subject = 'Integration A', Status = 'Back to Sales', WhatId = proj.id);
        tskList.add(tsk3);
        Task tsk4 = new Task(Subject = 'Training 1', Status = 'Back to Sales', WhatId = proj.id);
        tskList.add(tsk4);
        Task tsk5 = new Task(Subject = 'Integration A', Status = 'Deferred', WhatId = proj.id);
        tskList.add(tsk5);
        Task tsk6 = new Task(Subject = 'Training 1', Status = 'Deferred', WhatId = proj.id);
        tskList.add(tsk6);
        Task tsk7 = new Task(Subject = 'Integration A', Status = 'Escalated', WhatId = proj.id);
        tskList.add(tsk7);
        Task tsk8 = new Task(Subject = 'Training 1', Status = 'Escalated', WhatId = proj.id);
        tskList.add(tsk8);
        Task tsk9 = new Task(Subject = 'Training 1', Status = 'Completed', WhatId = proj.id);
        tskList.add(tsk9);
        insert tskList;
        FOD_ProvisionCtrl ctrl = new FOD_ProvisionCtrl();
        FOD_ProvisionCtrl.getChartData('0-15', 'acc', 'month');
        
        ApexPages.currentPage().getParameters().put('pname', 'Account Setup');
        ApexPages.currentPage().getParameters().put('stage', 'Integration');
        ApexPages.currentPage().getParameters().put('onholdtype', 'Active');
        FOD_ProjectListCtrl ctrl2 = new FOD_ProjectListCtrl();
        
        ApexPages.currentPage().getParameters().put('completedtype', 'month');
        ctrl2 = new FOD_ProjectListCtrl();
        Test.stopTest();
    }
    
    static testmethod void testConquestCtrl() {
        Test.startTest();
        customSettingData();
        SFDC_520_Quote__c proj = new SFDC_520_Quote__c(Name = 'Conquest 1', Approval_Stage__c = 'Integration');
        insert proj;
        proj.Name = 'Conquest 1';
        update proj;
        List<Task> tskList = new List<Task>();
        Task tsk1 = new Task(Subject = 'Integration C', Status = 'Not Started', WhatId = proj.id);
        tskList.add(tsk1);
        Task tsk2 = new Task(Subject = 'Training 1', Status = 'Not Started', WhatId = proj.id);
        tskList.add(tsk2);
        Task tsk3 = new Task(Subject = 'Integration C', Status = 'Back to Sales', WhatId = proj.id);
        tskList.add(tsk3);
        Task tsk4 = new Task(Subject = 'Training 1', Status = 'Back to Sales', WhatId = proj.id);
        tskList.add(tsk4);
        Task tsk5 = new Task(Subject = 'Integration C', Status = 'Deferred', WhatId = proj.id);
        tskList.add(tsk5);
        Task tsk6 = new Task(Subject = 'Training 1', Status = 'Deferred', WhatId = proj.id);
        tskList.add(tsk6);
        Task tsk7 = new Task(Subject = 'Integration C', Status = 'Escalated', WhatId = proj.id);
        tskList.add(tsk7);
        Task tsk8 = new Task(Subject = 'Training 1', Status = 'Escalated', WhatId = proj.id);
        tskList.add(tsk8);
        Task tsk9 = new Task(Subject = 'Training 1', Status = 'Completed', WhatId = proj.id);
        tskList.add(tsk9);
        Task tsk10 = new Task(Subject = 'Setup', Status = 'Not Started', WhatId = proj.id);
        tskList.add(tsk10);
        Task tsk11 = new Task(Subject = 'Setup', Status = 'Back to Sales', WhatId = proj.id);
        tskList.add(tsk11);
        Task tsk12 = new Task(Subject = 'Setup', Status = 'Deferred', WhatId = proj.id);
        tskList.add(tsk12);
        Task tsk13 = new Task(Subject = 'Setup', Status = 'Escalated', WhatId = proj.id);
        tskList.add(tsk13);
        insert tskList;
        FOD_ConquestCtrl ctrl = new FOD_ConquestCtrl();
        FOD_ConquestCtrl.getChartData('0-21', 'acc', 'month');
        ApexPages.currentPage().getParameters().put('pname', 'Conquest');
        ApexPages.currentPage().getParameters().put('stage', 'Integration');
        ApexPages.currentPage().getParameters().put('onholdtype', 'Active');
        FOD_ProjectListCtrl ctrl2 = new FOD_ProjectListCtrl();
        ctrl2.sortByMttrSt();
        ctrl2.sortByAccountName();
        ctrl2.sortByProjStg();
        ctrl2.sortByStartDate();
        ctrl2.sortByIntStatus();
        ctrl2.sortByIntAge();
        ctrl2.sortByTrnStatus();
        ctrl2.sortByTrnAge();
        ctrl2.sortBySetStatus();
        ctrl2.sortBySetAge();
        ctrl2.sortByAssigned();
        ctrl2.sortByCompletionDate();
        ctrl2.sortByIntCompletionDate();
        ctrl2.sortBySetCompletionDate();
        ctrl2.reverse();
        ctrl2.backToDashboard();
        
        FOD_ProjectListCtrl.ProjectWrap pw = new FOD_ProjectListCtrl.ProjectWrap();
        pw.compareTo(ctrl2.projWrapList[0]);
        pw.sortString('Test', 'Testing');
        pw.sortInteger(10, 20);
        Test.stopTest();
    }
    
    static testmethod void testUpsellCtrl() {
        Test.startTest();
        customSettingData();
        SFDC_520_Quote__c proj = new SFDC_520_Quote__c(Name = 'Module-Upsell 1', Approval_Stage__c = 'Integration');
        insert proj;
        proj.Name = 'Module-Upsell 1';
        update proj;
        List<Task> tskList = new List<Task>();
        Task tsk1 = new Task(Subject = 'Training 1', Status = 'Not Started', WhatId = proj.id);
        tskList.add(tsk1);
        Task tsk2 = new Task(Subject = 'Training 1', Status = 'Back to Sales', WhatId = proj.id);
        tskList.add(tsk2);
        Task tsk3 = new Task(Subject = 'Training 1', Status = 'Deferred', WhatId = proj.id);
        tskList.add(tsk3);
        Task tsk4 = new Task(Subject = 'Training 1', Status = 'Escalated', WhatId = proj.id);
        tskList.add(tsk4);
        Task tsk5 = new Task(Subject = 'Training 1', Status = 'Completed', WhatId = proj.id);
        tskList.add(tsk5);
        insert tskList;
        FOD_UpsellCtrl ctrl = new FOD_UpsellCtrl();
        ctrl.queryUpsellProjects();
        
        ApexPages.currentPage().getParameters().put('pname', 'Module-Upsell');
        ApexPages.currentPage().getParameters().put('stage', 'Training 1');
        ApexPages.currentPage().getParameters().put('onholdtype', 'Active');
        FOD_ProjectListCtrl ctrl2 = new FOD_ProjectListCtrl();
        Test.stopTest();
    }
    
    static testmethod void testListingCtrl() {
        Test.startTest();
        customSettingData();
        SFDC_520_Quote__c proj = new SFDC_520_Quote__c(Name = 'Listings/Photos/Syndication-Upsell 1', Approval_Stage__c = 'Integration');
        insert proj;
        proj.Name = 'Listings/Photos/Syndication-Upsell 1';
        update proj;
        List<Task> tskList = new List<Task>();
        Task tsk1 = new Task(Subject = 'Integration L', Status = 'Not Started', WhatId = proj.id);
        tskList.add(tsk1);
        Task tsk2 = new Task(Subject = 'Integration L', Status = 'Back to Sales', WhatId = proj.id);
        tskList.add(tsk2);
        Task tsk3 = new Task(Subject = 'Integration L', Status = 'Deferred', WhatId = proj.id);
        tskList.add(tsk3);
        Task tsk4 = new Task(Subject = 'Integration L', Status = 'Escalated', WhatId = proj.id);
        tskList.add(tsk4);
        Task tsk5 = new Task(Subject = 'Integration L', Status = 'Completed', WhatId = proj.id);
        tskList.add(tsk5);
        insert tskList;
        FOD_UpsellCtrl ctrl = new FOD_UpsellCtrl();
        ctrl.queryListingProjects();
        
        ApexPages.currentPage().getParameters().put('pname', 'Listings/Photos/Syndication-Upsell');
        ApexPages.currentPage().getParameters().put('stage', 'Integration');
        ApexPages.currentPage().getParameters().put('onholdtype', 'Active');
        FOD_ProjectListCtrl ctrl2 = new FOD_ProjectListCtrl();
        Test.stopTest();
    }
    
    static testmethod void testWindowCtrl() {
        Test.startTest();
        customSettingData();
        SFDC_520_Quote__c proj = new SFDC_520_Quote__c(Name = 'Window Stickers-Upsell 1', Approval_Stage__c = 'Integration');
        insert proj;
        proj.Name = 'Window Stickers-Upsell 1';
        update proj;
        List<Task> tskList = new List<Task>();
        Task tsk1 = new Task(Subject = 'Integration W', Status = 'Not Started', WhatId = proj.id);
        tskList.add(tsk1);
        Task tsk2 = new Task(Subject = 'Integration W', Status = 'Back to Sales', WhatId = proj.id);
        tskList.add(tsk2);
        Task tsk3 = new Task(Subject = 'Integration W', Status = 'Deferred', WhatId = proj.id);
        tskList.add(tsk3);
        Task tsk4 = new Task(Subject = 'Integration W', Status = 'Escalated', WhatId = proj.id);
        tskList.add(tsk4);
        Task tsk5 = new Task(Subject = 'Integration W', Status = 'Completed', WhatId = proj.id);
        tskList.add(tsk5);
        insert tskList;
        FOD_UpsellCtrl ctrl = new FOD_UpsellCtrl();
        ctrl.queryListingProjects();
        
        ApexPages.currentPage().getParameters().put('pname', 'Window Stickers-Upsell');
        ApexPages.currentPage().getParameters().put('stage', 'Integration');
        ApexPages.currentPage().getParameters().put('onholdtype', 'Active');
        FOD_ProjectListCtrl ctrl2 = new FOD_ProjectListCtrl();
        Test.stopTest();
    }
    
    static testmethod void testNewUserCtrl() {
        Test.startTest();
        customSettingData();
        SFDC_520_Quote__c proj = new SFDC_520_Quote__c(Name = 'Window Stickers-Upsell 1', Approval_Stage__c = 'Integration');
        insert proj;
        proj.Name = 'Window Stickers-Upsell 1';
        update proj;
        List<Task> tskList = new List<Task>();
        Task tsk1 = new Task(Subject = 'New User Session', Status = 'Not Started', WhatId = proj.id, ActivityDate = System.today());
        tskList.add(tsk1);
        Task tsk2 = new Task(Subject = 'New User Session', Status = 'Back to Sales', WhatId = proj.id, ActivityDate = System.today());
        tskList.add(tsk2);
        Task tsk3 = new Task(Subject = 'New User Session', Status = 'Deferred', WhatId = proj.id, ActivityDate = System.today());
        tskList.add(tsk3);
        Task tsk4 = new Task(Subject = 'New User Session', Status = 'Escalated', WhatId = proj.id, ActivityDate = System.today());
        tskList.add(tsk4);
        Task tsk5 = new Task(Subject = 'New User Session', Status = 'Completed', WhatId = proj.id, ActivityDate = System.today());
        tskList.add(tsk5);
        insert tskList;
        FOD_UpsellCtrl ctrl = new FOD_UpsellCtrl();
        ctrl.queryNewUserProjects();
        ctrl.back();
        
        ApexPages.currentPage().getParameters().put('status', 'Deferred');
        FOD_TaskListCtrl ctrl2 = new FOD_TaskListCtrl();
        ApexPages.currentPage().getParameters().put('status', 'Completed');
        ctrl2 = new FOD_TaskListCtrl();
        ctrl2.sortByAccName();
        ctrl2.sortBySubject();
        ctrl2.sortByActDate();
        ctrl2.sortByAssigned();
        ctrl2.sortByStatus();
        ctrl2.reverse();
        
        FOD_TaskListCtrl.TaskWrap pw = new FOD_TaskListCtrl.TaskWrap();
        pw.compareTo(ctrl2.taskList[0]);
        pw.sortString('Test', 'Testing');
        pw.sortDate(System.today(), System.today());
        Test.stopTest();
    }
    
    static testmethod void testCompletedProjCtrl() {
        Test.startTest();
            customSettingData();
            ApexPages.currentPage().getParameters().put('pname', 'Window Stickers-Upsell');
            FOD_CompletedProjectsCtrl ctrl = new FOD_CompletedProjectsCtrl();
            
            
            ApexPages.currentPage().getParameters().put('pname', 'Module-Upsell');
            ctrl = new FOD_CompletedProjectsCtrl();
            
            
            Account acc = new Account(Name = 'Test');
            insert acc;
            SFDC_520_Quote__c proj = new SFDC_520_Quote__c(Name = 'Conquest 1', Approval_Stage__c = 'Integration', Account__c = acc.id);
            insert proj;
            proj.Name = 'Conquest 1';
            update proj;
            List<Task> tskList = new List<Task>();
            Task tsk1 = new Task(Subject = 'Training 1', Status = 'Completed', WhatId = proj.id, Date_Time_Completed__c = System.today());
            tskList.add(tsk1);
            Task tsk2 = new Task(Subject = 'Integration L', Status = 'Completed', WhatId = proj.id, Date_Time_Completed__c = System.today());
            tskList.add(tsk2);
            Task tsk3 = new Task(Subject = 'Conquest Franchise Setup', Status = 'Completed', WhatId = proj.id, Date_Time_Completed__c = System.today());
            tskList.add(tsk3);
            insert tskList;
            
            ApexPages.currentPage().getParameters().put('pname', 'Account Setup');
            ApexPages.currentPage().getParameters().put('sd', 'month');
            ApexPages.currentPage().getParameters().put('sv', 'Other');
            ApexPages.currentPage().getParameters().put('sm', '0-15');
            ctrl = new FOD_CompletedProjectsCtrl();
            ctrl.doSearch('Account Setup');
            ApexPages.currentPage().getParameters().put('pname', 'Conquest');
            ApexPages.currentPage().getParameters().put('sd', 'month');
            ApexPages.currentPage().getParameters().put('sv', 'Other');
            ApexPages.currentPage().getParameters().put('sm', '0-21');
            ctrl = new FOD_CompletedProjectsCtrl();
            
            
            ctrl.sortByMttrSt();
            ctrl.sortByAccountName();
            ctrl.sortByProjStg();
            ctrl.sortByStartDate();
            ctrl.sortByIntStatus();
            ctrl.sortByIntAge();
            ctrl.sortByTrnStatus();
            ctrl.sortByTrnAge();
            ctrl.sortBySetStatus();
            ctrl.sortBySetAge();
            ctrl.sortByAssigned();
            ctrl.sortByCompletionDate();
            ctrl.sortByIntCompletionDate();
            ctrl.sortBySetCompletionDate();
            ctrl.reverse();
            ctrl.backToDashboard();
            
            FOD_CompletedProjectsCtrl.ProjectWrap pw = new FOD_CompletedProjectsCtrl.ProjectWrap();
            pw.compareTo(ctrl.projWrapList[0]);
            pw.sortString('Test', 'Testing');
            pw.sortInteger(10, 20);
            
            proj.Name = 'Listings/Photos/Syndication-Upsell';
            update proj;
            ApexPages.currentPage().getParameters().put('pname', 'Listings/Photos/Syndication-Upsell');
            ctrl = new FOD_CompletedProjectsCtrl();
            
        Test.stopTest();
    }
    
    public static void customSettingData() {
        List<DashboardTaskStatus__c> dbList = new List<DashboardTaskStatus__c>();
        dbList.add(new DashboardTaskStatus__c(Name = 'Provision1', Project__c = 'Account Setup', Stage__c = 'Integration', Project_Status__c = 'Active', Task_Status__c = 'Not Started', Primary_Subject__c = 'Integration A', Secondary_Subject__c = 'Training 1'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Provision2', Project__c = 'Account Setup', Stage__c = 'Integration', Project_Status__c = 'Back to Sales', Task_Status__c = 'Back to Sales', Primary_Subject__c = 'Integration A', Secondary_Subject__c = 'Training 1'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Provision3', Project__c = 'Account Setup', Stage__c = 'Integration', Project_Status__c = 'Deferred', Task_Status__c = 'Deferred', Primary_Subject__c = 'Integration A', Secondary_Subject__c = 'Training 1'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Provision4', Project__c = 'Account Setup', Stage__c = 'Integration', Project_Status__c = 'Escalated', Task_Status__c = 'Escalated', Primary_Subject__c = 'Integration A', Secondary_Subject__c = 'Training 1'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Provision5', Project__c = 'Account Setup', Stage__c = 'Training 1', Project_Status__c = 'Active', Task_Status__c = 'Not Started', Primary_Subject__c = 'Training 1', Secondary_Subject__c = 'Integration A'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Provision6', Project__c = 'Account Setup', Stage__c = 'Training 1', Project_Status__c = 'Back to Sales', Task_Status__c = 'Back to Sales', Primary_Subject__c = 'Training 1', Secondary_Subject__c = 'Integration A'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Provision7', Project__c = 'Account Setup', Stage__c = 'Training 1', Project_Status__c = 'Deferred', Task_Status__c = 'Deferred', Primary_Subject__c = 'Training 1', Secondary_Subject__c = 'Integration A'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Provision8', Project__c = 'Account Setup', Stage__c = 'Training 1', Project_Status__c = 'Escalated', Task_Status__c = 'Escalated', Primary_Subject__c = 'Training 1', Secondary_Subject__c = 'Integration A'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Provision9', Project__c = 'Account Setup', Stage__c = '', Project_Status__c = 'Completed', Task_Status__c = 'Completed', Primary_Subject__c = 'Training 1', Secondary_Subject__c = 'Integration A'));
        
        dbList.add(new DashboardTaskStatus__c(Name = 'Conquest1', Project__c = 'Conquest', Stage__c = 'Integration', Project_Status__c = 'Active', Task_Status__c = 'Not Started', Primary_Subject__c = 'Integration C', Secondary_Subject__c = 'Training 1, Setup'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Conquest2', Project__c = 'Conquest', Stage__c = 'Integration', Project_Status__c = 'Back to Sales', Task_Status__c = 'Back to Sales', Primary_Subject__c = 'Integration C', Secondary_Subject__c = 'Training 1, Setup'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Conquest3', Project__c = 'Conquest', Stage__c = 'Integration', Project_Status__c = 'Deferred', Task_Status__c = 'Deferred', Primary_Subject__c = 'Integration C', Secondary_Subject__c = 'Training 1, Setup'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Conquest4', Project__c = 'Conquest', Stage__c = 'Integration', Project_Status__c = 'Escalated', Task_Status__c = 'Escalated', Primary_Subject__c = 'Integration C', Secondary_Subject__c = 'Training 1, Setup'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Conquest5', Project__c = 'Conquest', Stage__c = 'Training 1', Project_Status__c = 'Active', Task_Status__c = 'Not Started', Primary_Subject__c = 'Training 1', Secondary_Subject__c = 'Integration C, Setup'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Conquest6', Project__c = 'Conquest', Stage__c = 'Training 1', Project_Status__c = 'Back to Sales', Task_Status__c = 'Back to Sales', Primary_Subject__c = 'Training 1', Secondary_Subject__c = 'Integration C, Setup'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Conquest7', Project__c = 'Conquest', Stage__c = 'Training 1', Project_Status__c = 'Deferred', Task_Status__c = 'Deferred', Primary_Subject__c = 'Training 1', Secondary_Subject__c = 'Integration C, Setup'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Conquest8', Project__c = 'Conquest', Stage__c = 'Training 1', Project_Status__c = 'Escalated', Task_Status__c = 'Escalated', Primary_Subject__c = 'Training 1', Secondary_Subject__c = 'Integration C, Setup'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Conquest9', Project__c = 'Conquest', Stage__c = 'Setup Pricing', Project_Status__c = 'Active', Task_Status__c = 'Not Started', Primary_Subject__c = 'Setup', Secondary_Subject__c = 'Integration C, Training 1'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Conquest10', Project__c = 'Conquest', Stage__c = 'Setup Pricing', Project_Status__c = 'Back to Sales', Task_Status__c = 'Back to Sales', Primary_Subject__c = 'Setup', Secondary_Subject__c = 'Integration C, Training 1'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Conquest11', Project__c = 'Conquest', Stage__c = 'Setup Pricing', Project_Status__c = 'Deferred', Task_Status__c = 'Deferred', Primary_Subject__c = 'Setup', Secondary_Subject__c = 'Integration C, Training 1'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Conquest12', Project__c = 'Conquest', Stage__c = 'Setup Pricing', Project_Status__c = 'Escalated', Task_Status__c = 'Escalated', Primary_Subject__c = 'Setup', Secondary_Subject__c = 'Integration C, Training 1'));
        dbList.add(new DashboardTaskStatus__c(Name = 'Conquest13', Project__c = 'Conquest', Stage__c = '', Project_Status__c = 'Completed', Task_Status__c = 'Completed', Primary_Subject__c = 'Training 1', Secondary_Subject__c = 'Integration C, Setup'));
        
        dbList.add(new DashboardTaskStatus__c(Name = 'Module-Upsell1', Project__c = 'Module-Upsell', Stage__c = 'Training 1', Project_Status__c = 'Active', Task_Status__c = 'Not Started', Primary_Subject__c = 'Training 1', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'Module-Upsell2', Project__c = 'Module-Upsell', Stage__c = 'Training 1', Project_Status__c = 'Back to Sales', Task_Status__c = 'Back to Sales', Primary_Subject__c = 'Training 1', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'Module-Upsell3', Project__c = 'Module-Upsell', Stage__c = 'Training 1', Project_Status__c = 'Deferred', Task_Status__c = 'Deferred', Primary_Subject__c = 'Training 1', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'Module-Upsell4', Project__c = 'Module-Upsell', Stage__c = 'Training 1', Project_Status__c = 'Escalated', Task_Status__c = 'Escalated', Primary_Subject__c = 'Training 1', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'Module-Upsell5', Project__c = 'Module-Upsell', Stage__c = '', Project_Status__c = 'Completed', Task_Status__c = 'Completed', Primary_Subject__c = 'Training 1', Secondary_Subject__c = ''));
        
        dbList.add(new DashboardTaskStatus__c(Name = 'Listings/Photos/Syndication-Upsell1', Project__c = 'Listings/Photos/Syndication-Upsell', Stage__c = 'Integration', Project_Status__c = 'Active', Task_Status__c = 'Not Started', Primary_Subject__c = 'Integration L', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'Listings/Photos/Syndication-Upsell2', Project__c = 'Listings/Photos/Syndication-Upsell', Stage__c = 'Integration', Project_Status__c = 'Deferred', Task_Status__c = 'Deferred', Primary_Subject__c = 'Integration L', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'Listings/Photos/Syndication-Upsell3', Project__c = 'Listings/Photos/Syndication-Upsell', Stage__c = 'Integration', Project_Status__c = 'Escalated', Task_Status__c = 'Escalated', Primary_Subject__c = 'Integration L', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'Listings/Photos/Syndication-Upsell4', Project__c = 'Listings/Photos/Syndication-Upsell', Stage__c = '', Project_Status__c = 'Completed', Task_Status__c = 'Completed', Primary_Subject__c = 'Integration L'));
        
        dbList.add(new DashboardTaskStatus__c(Name = 'Window Stickers-Upsell1', Project__c = 'Window Stickers-Upsell', Stage__c = 'Integration', Project_Status__c = 'Active', Task_Status__c = 'Not Started', Primary_Subject__c = 'Integration W', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'Window Stickers-Upsell2', Project__c = 'Window Stickers-Upsell', Stage__c = 'Integration', Project_Status__c = 'Deferred', Task_Status__c = 'Deferred', Primary_Subject__c = 'Integration W', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'Window Stickers-Upsell3', Project__c = 'Window Stickers-Upsell', Stage__c = 'Integration', Project_Status__c = 'Escalated', Task_Status__c = 'Escalated', Primary_Subject__c = 'Integration W', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'Window Stickers-Upsell4', Project__c = 'Window Stickers-Upsell', Stage__c = '', Project_Status__c = 'Completed', Task_Status__c = 'Completed', Primary_Subject__c = 'Integration W', Secondary_Subject__c = ''));
        
        dbList.add(new DashboardTaskStatus__c(Name = 'New User1', Project__c = 'New User', Stage__c = '', Project_Status__c = 'Active', Task_Status__c = 'Not Started', Primary_Subject__c = 'New User Session', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'New User2', Project__c = 'New User', Stage__c = '', Project_Status__c = 'Deferred', Task_Status__c = 'Deferred', Primary_Subject__c = 'New User Session', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'New User3', Project__c = 'New User', Stage__c = '', Project_Status__c = 'Escalated', Task_Status__c = 'Escalated', Primary_Subject__c = 'New User Session', Secondary_Subject__c = ''));
        
        insert dbList;
    }
}