objects/Account.object
<CustomObject>
    <fields>
        <fullName>ValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ValidationRules</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ValidationRules</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the primary contact associated with the Opportunity</inlineHelpText>
        <label>Deal Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Deal Contact)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Names__c</fullName>
        <inlineHelpText>what is the core product being sold</inlineHelpText>
        <label>Product Suite</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Account Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Inventory with MPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Bundle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Genius - Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Genius - With Provision Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoVisor - Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoVisor - With Provision Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUX Account Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR New Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR Used Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR Used w/ vAuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest Stand-Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Plus Desking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Plus MPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Premier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Pro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Marketing Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment Coop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak CLLC SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak CLLC SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak DM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the user that initiated the opportunity: fishing pole, PM, etc</inlineHelpText>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TryCatchTest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TryCatchTest</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to bypass Validation Rules in unit tests.</description>
        <inlineHelpText>Used to bypass Validation Rules in unit tests.</inlineHelpText>
        <label>ValidationRules</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ExpPaidByDealer__c</fullName>
        <formula>IF( PricebookEntry.Product2.ExpPaidByDealer__c , &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ExpPaidByDealer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsTraining__c</fullName>
        <formula>IF( PricebookEntry.Product2.isTraining__c , &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsTraining</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Discount_Percentage__c</fullName>
        <label>Package Discount Percentage</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ProdProj_Default_Owner__c</fullName>
        <formula>PricebookEntry.Product2.ProdProj_Default_Owner__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProdProj Default Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Department__c</fullName>
        <description>Selects the proper Department page layout for created issues</description>
        <formula>CASE(PricebookEntry.Product2.Production_Department__c, 
&quot;Creative&quot;,&quot;012700000005e2z&quot;,
&quot;DDM&quot;,&quot;012700000005e3J&quot;,
&quot;Implementation&quot;,&quot;012700000005e34&quot;,
&quot;Integration&quot;,&quot;012700000005e3O&quot;,
&quot;Shipping&quot;,&quot;012700000005e3E&quot;,
&quot;Support&quot;,&quot;012700000005e3T&quot;,
&quot;Training&quot;,&quot;012700000005e39&quot;,
&quot;Training - Sales&quot;,&quot;012700000005ebs&quot;,
&quot;Training - Purchasing&quot;,&quot;012700000005ebn&quot;,
&quot;Implementation Hardware&quot;, &quot;012700000005eOt&quot;,
&quot;Implementation Click to Chat&quot;, &quot;012700000005eOy&quot;,
&quot;Support - Custom Form Design&quot;, &quot;012700000005ejj&quot;,
&quot;Implementation - VinVideos&quot;, &quot;01270000000Q3VI&quot;,
&quot;700 Credit&quot;,&quot;01270000000Q3eo&quot;,
&quot;AIS Rebates&quot;,&quot;01270000000Q3hd&quot;,
&quot;Craigslist Manual&quot;,&quot;01270000000Q3rn&quot;,
&quot;Desking Module&quot;,&quot;01270000000Q3rh&quot;,
&quot;Inventory Gallery&quot;,&quot;01270000000Q3rm&quot;,
&quot;Inventory Module&quot;,&quot;01270000000Q3rv&quot;,
&quot;KnowMe&quot;,&quot;01270000000Q3rg&quot;,
&quot;Market Pricing Tool&quot;,&quot;01270000000Q3rw&quot;,
&quot;Training (WebEx/Internet)&quot;,&quot;01270000000Q3rl&quot;,
&quot;012700000005e2u&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Production Department</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_Exception__c</fullName>
        <formula>IF( PricebookEntry.Product2.Quantity_Exception__c , &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity Exception</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to bypass validation rules in unit tests.</description>
        <label>ValidationRules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>requiresWelcomePacket__c</fullName>
        <formula>IF( PricebookEntry.Product2.requiresWelcomePacket__c , &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>requiresWelcomePacket</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ExpPaidByDealer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ExpPaidByDealer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPackageParent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this product is considered to be a parent product for a package (i.e. Bronze 2 is a parent product)</description>
        <inlineHelpText>If checked, this product is considered to be a parent product for a package (i.e. Bronze 2 is a parent product)</inlineHelpText>
        <label>IsPackageParent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Package_Discount_Percentage__c</fullName>
        <label>Package Discount Percentage</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ProdProj_Default_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Default Owner of the Product Projects that will be generated for this product. A Project Piece will only be generated for this Product if this field is filled in.</description>
        <inlineHelpText>The Default Owner of the Product Projects that will be generated for this product. A Project Piece will only be generated for this Product if this field is filled in.</inlineHelpText>
        <label>ProdProj Default Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Production_Department__c</fullName>
        <label>Production Department</label>
        <picklist>
            <picklistValues>
                <fullName>700 Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AIS Rebates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Manual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Creative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desking Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation - VinVideos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Gallery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KnowMe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Pricing Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Search &amp; Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support - Custom Form Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training (WebEx/Internet)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training - Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training - Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Websites</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Production_Issue__c</fullName>
        <label>Production Issue</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quantity Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ValidationRules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isTraining__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isTraining</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>requiresWelcomePacket__c</fullName>
        <defaultValue>false</defaultValue>
        <label>requiresWelcomePacket</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ValidationRules</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Opp_PriceAdjustment_TEST.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seeAllData=true)
private class Opp_PriceAdjustment_TEST {

    static testMethod void testSelectLists() {
        
        /*Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
          emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
          localesidkey = 'en_US', profileid = pro.Id, UserRoleId = '00E70000001GBsB',
          timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com');
          
        insert u_testMethodUser;
        
        System.runas(u_testMethodUser) {*/
            
	        Account a = new Account();
	        a.Name = 'TestPriceAdjustment';
	        a.ShippingCity = 'Belton';
	        a.ShippingStreet = '7900 E 159th St';
	        a.ShippingState = 'MO';
	        a.AccountNumber = '565656565656';
	        a.BillingState = 'MO';
	        a.BillingCity = 'Belton';
	        a.BillingCountry = 'USA';
	        a.BillingPostalCode = '64012';
	        a.BillingStreet = '7900 E 159th St';
	        	        a.ShippingState = 'MO';
	        a.ShippingCity = 'Belton';
	        a.ShippingCountry = 'USA';
	        a.ShippingPostalCode = '64012';
	        a.ShippingStreet = '7900 E 159th St';
	        
	        insert a;
	        
	        Contact ct = new Contact();
	        ct.AccountId = a.Id;
	        ct.FirstName = 'Dean';
	        ct.LastName = 'Martin';
	        ct.Phone = '9999999999';
	        
	        insert ct;
	        
	        Opportunity opp = new Opportunity();
	        opp.AccountId = a.Id;
	        opp.Name = 'Test Price Adjustment';
	        opp.Deal_Contact__c = ct.Id;
	        opp.CloseDate = system.today();
	        opp.StageName = 'Prospect';
	        opp.Type = 'New Business';
	        opp.Salesperson__c = userinfo.getUserId();
	        opp.RecordTypeId = '01270000000Q7t7';
	        opp.TryCatchTest__c = true;
	        
	        insert opp;
	        
	        string prodName = 'CRM';
	        
	        Product2 p = new Product2();
	        p.Name = 'CRM';
	        p.Quantity_Exception__c = true;
	        p.IsTraining__c = true;
	        p.ExpPaidByDealer__c = true;
	        p.ProdProj_Default_Owner__c = userinfo.getUserId();
	        p.Description = 'website';
	        p.IsPackageParent__c = true;
	        p.Production_Department__c = 'creative';
	        p.Production_Issue__c = 'website';
	        p.requiresWelcomePacket__c = false;
	        p.Family = 'Reoccuring';
	        p.Package_Discount_Percentage__c = .55;
	        
	        insert p;
	        
	        Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE Name='Standard Price Book' limit 1];
	        
	        PricebookEntry pbe = new PricebookEntry();
	        pbe.UnitPrice = 10000.00;
	        pbe.Pricebook2Id = pb.Id;
	        pbe.Product2Id = p.Id;
	        pbe.IsActive = true;
	        
	        insert pbe;
	        
	        OpportunityLineItem oli = new OpportunityLineItem();
	        oli.PricebookEntryId = pbe.Id;
	        oli.OpportunityId = opp.Id;
	        oli.Quantity = 1;
	        oli.ValidationRules__c = true;
	        oli.TotalPrice = 10000.00;
	        
	        //insert oli;
	        
	        opp.Opportunity_Names__c = 'Hardware';
	        opp.StageName = 'Negotiation/Review';
	        opp.Implementation_Contact__c = ct.Id;
	        opp.Deal_Contact__c = ct.Id;
	        //opp.We_Owe__c = 'N/A';
	        opp.Amount = 10000.00;
	        
	        //update opp;
	        
	        
	        ApexPages.Standardcontroller sc = new ApexPages.StandardController(opp);
	        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
	        Opp_PriceAdjustment opa = new Opp_PriceAdjustment(sc);
	        
	        test.startTest();
	        opa.getIncDec();
	        opa.getPerFlat();
	        opa.typeChange();
	        
	        opa.typeOfAdjustment = 'Decrease';
	        opa.typeOfRate = 'Percentage';
	        opa.rateType();
	        
	        opa.typeOfAdjustment = 'Decrease';
	        opa.typeOfRate = 'Flat';
	        opa.rateType();
	        
	        opa.typeOfAdjustment = 'Increase';
	        opa.typeOfRate = 'Percentage';
	        opa.rateType();
	        
	        opa.typeOfAdjustment = 'Increase';
	        opa.typeOfRate = 'Flat';
	        opa.rateType();
	        
	        opa.returnToOpp();
	        
	        test.stopTest();
       // }
    }
    
    static testMethod void testCalculations() {
        
        /*Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
          emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
          localesidkey = 'en_US', profileid = pro.Id, UserRoleId = '00E70000001GBsB',
          timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com');
          
        insert u_testMethodUser;
        
        System.runas(u_testMethodUser) {*/
            
	        Account a = new Account();
	        a.Name = 'TestPriceAdjustment';
	        a.ShippingCity = 'Belton';
	        a.ShippingStreet = '7900 E 159th St';
	        a.ShippingState = 'MO';
	        a.AccountNumber = '565656565656';
	        a.BillingState = 'MO';
	        a.BillingCity = 'Belton';
	        a.BillingCountry = 'USA';
	        a.BillingPostalCode = '64012';
	        a.BillingStreet = '7900 E 159th St';
	        	        a.ShippingState = 'MO';
	        a.ShippingCity = 'Belton';
	        a.ShippingCountry = 'USA';
	        a.ShippingPostalCode = '64012';
	        a.ShippingStreet = '7900 E 159th St';
	        
	        insert a;
	        
	        Contact ct = new Contact();
	        ct.AccountId = a.Id;
	        ct.FirstName = 'Dean';
	        ct.LastName = 'Martin';
	        ct.Phone = '9999999999';
	        
	        insert ct;
	        
	        Opportunity opp = new Opportunity();
	        opp.AccountId = a.Id;
	        opp.Name = 'Test Price Adjustment';
	        opp.Deal_Contact__c = ct.Id;
	        opp.CloseDate = system.today();
	        opp.StageName = 'Prospect';
	        opp.Type = 'New Business';
	        opp.Salesperson__c = userinfo.getUserId();
	        opp.RecordTypeId = '01270000000Q7t7';
	        opp.TryCatchTest__c = true;
	        
	        insert opp;
	        
	        string prodName = 'CRM';
	        
	        Product2 p = new Product2();
	      	p.Name = 'Platimum 1 Package';
	        p.Quantity_Exception__c = false;
	        p.IsTraining__c = false;
	        p.ExpPaidByDealer__c = true;
	        p.ProdProj_Default_Owner__c = userinfo.getUserId();
	        p.Description = 'Email Banner';
	        p.IsPackageParent__c = false;
	        p.Production_Department__c = 'creative';
	        p.Production_Issue__c = 'email Banner';
	        p.requiresWelcomePacket__c = false;
	        p.Family = 'Reoccuring';
	        p.Package_Discount_Percentage__c = .55;
	        
	        insert p;
	        
	        Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE Name='Standard Price Book' limit 1];
	        
	        PricebookEntry pbe = new PricebookEntry();
	        pbe.UnitPrice = 10000.00;
	        pbe.Pricebook2Id = pb.Id;
	        pbe.Product2Id = p.Id;
	        pbe.IsActive = true;
	        
	        insert pbe;
	        
	        OpportunityLineItem oli = new OpportunityLineItem();
	        oli.PricebookEntryId = pbe.Id;
	        oli.OpportunityId = opp.Id;
	        oli.Quantity = 1;
	        oli.ValidationRules__c = true;
	        oli.TotalPrice = 10000.00;
	        //oli.Setup_Fee__c = true;
	        
	        insert oli;
	        
	        OpportunityLineItem oli1 = new OpportunityLineItem();
	        oli1.PricebookEntryId = pbe.Id;
	        //oli.PricebookEntryId = '01s70000000MZ4f';
	        oli1.OpportunityId = opp.Id;
	        oli1.Quantity = 1;
	        oli1.TotalPrice = 1000;
	        oli1.ValidationRules__c = true;
	        oli1.Setup_Fee__c = true;
	        
	        insert oli1;
	        
	        opp.Opportunity_Names__c = 'Hardware';
	        opp.StageName = 'Negotiation/Review';
	        opp.Implementation_Contact__c = ct.Id;
	        opp.Deal_Contact__c = ct.Id;
	        //opp.We_Owe__c = 'N/A';
	        opp.Amount = 10000.00;
	        
	        update opp;
        
	        ApexPages.Standardcontroller sc = new ApexPages.StandardController(opp);
	        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
	        Opp_PriceAdjustment opa = new Opp_PriceAdjustment(sc);
	        
	        test.startTest();
	        
	        opa.mrrPercent = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.trainPercent = 10.00;
	        opa.calculateDecPer();
	        
	        opa.mrrPercent = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.trainPercent = 10.00;
	        opa.calculateIncPer();
	        
	        opa.mrrFlat = 100.00;
	        opa.oneTimeFlat = 100.00;
	        opa.setUpFlat = 100.00;
	        opa.trainFlat = 100.00;
	        opa.calculateDecFlat();
	        
	        opa.mrrFlat = 100.00;
	        opa.oneTimeFlat = 100.00;
	        opa.setUpFlat = 100.00;
	        opa.trainFlat = 100;
	        opa.calculateIncFlat();
	        
	        opa.totalPercentageIncrease();
	        opa.mrrph2 = 1;
	        
	        opa.totalPercentageDiscount();
	        opa.mrrph2 = opa.oppInfo.Monthly_Recurring_Fees__c;
	        opa.suph2 = opa.oppInfo.Setup_Fees__c;
	        opa.totalPercentageDiscount();
	        opa.totalFlatDiscount();
	        opa.totalFlatIncrease();
	        opa.realTimeTotalFlatIncrease();
	        
	        opa.totalPercentageDiscount();
	        opa.mrrph2 = opa.oppInfo.Monthly_Recurring_Fees__c + 100;
	        opa.suph2 = opa.oppInfo.Setup_Fees__c + 100;
	        opa.otph2 = opa.oppInfo.One_Time_Fees2__c + 100;
	        opa.trph2 = opa.oppInfo.Total_Training__c + 100;
	        opa.totalPercentageDiscount();
	        opa.totalFlatDiscount();
	        opa.totalFlatIncrease();
	        opa.realTimeTotalFlatIncrease();
	        opa.realTimeTotalFlatDiscount();
	        opa.totalPercentageIncrease();
	        opa.realTimeTotalPercentageIncrease();
	        
	        opa.mrrph2 = 1;
	        opa.realTimeTotalDiscountPercentage();
	        opa.totalPercentageDiscount();
	        
	        test.stopTest();
        //}
    }
    
    static testMethod void testSubmits() {
        
       /* Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
          emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
          localesidkey = 'en_US', profileid = pro.Id, UserRoleId = '00E70000001GBsB',
          timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com');
          
        insert u_testMethodUser;
        
        System.runas(u_testMethodUser) {*/
            
	        Account a = new Account();
	        a.Name = 'TestPriceAdjustment';
	        a.ShippingCity = 'Belton';
	        a.ShippingStreet = '7900 E 159th St';
	        a.ShippingState = 'MO';
	        a.AccountNumber = '565656565656';
	        a.BillingState = 'MO';
	        a.BillingCity = 'Belton';
	        a.BillingCountry = 'USA';
	        a.BillingPostalCode = '64012';
	        a.BillingStreet = '7900 E 159th St';
	        	        a.ShippingState = 'MO';
	        a.ShippingCity = 'Belton';
	        a.ShippingCountry = 'USA';
	        a.ShippingPostalCode = '64012';
	        a.ShippingStreet = '7900 E 159th St';
	        
	        insert a;
	        
	        Contact ct = new Contact();
	        ct.AccountId = a.Id;
	        ct.FirstName = 'Dean';
	        ct.LastName = 'Martin';
	        ct.Phone = '9999999999';
	        
	        insert ct;
	        
	        Opportunity opp = new Opportunity();
	        opp.AccountId = a.Id;
	        opp.Name = 'Test Price Adjustment';
	        opp.Deal_Contact__c = ct.Id;
	        opp.CloseDate = system.today();
	        opp.StageName = 'Prospect';
	        opp.Type = 'New Business';
	        opp.Salesperson__c = userinfo.getUserId();
	        opp.RecordTypeId = '01270000000Q7t7';
	        opp.TryCatchTest__c = true;
	        
	        insert opp;
	        
	        string prodName = 'CRM';
	        
	        Product2 p = new Product2();
	        p.Name = 'Platimum 1 Package';
	        p.Quantity_Exception__c = true;
	        p.IsTraining__c = true;
	        p.ExpPaidByDealer__c = true;
	        p.ProdProj_Default_Owner__c = userinfo.getUserId();
	        p.Description = 'Email Banner';
	        p.IsPackageParent__c = false;
	        p.Production_Department__c = 'creative';
	        p.Production_Issue__c = 'email Banner';
	        p.requiresWelcomePacket__c = false;
	        p.Family = 'Reoccuring';
	        p.Package_Discount_Percentage__c = .55;
	        
	        insert p;
	        
	        Product2 pp = new Product2();
	        pp.Name = 'Bronze 1 Package';
	        pp.Quantity_Exception__c = true;
	        pp.IsTraining__c = false;
	        //pp.ProductIsParent = 'T';
	        pp.ExpPaidByDealer__c = true;
	        pp.ProdProj_Default_Owner__c = userinfo.getUserId();
	        pp.Description = 'Bronze Package';
	        pp.IsPackageParent__c = true;
	        pp.Production_Department__c = 'package';
	        pp.Production_Issue__c = 'package';
	        pp.requiresWelcomePacket__c = false;
	        pp.Family = 'Monthly Reoccuring';
	        pp.Package_Discount_Percentage__c = .79;
	        
	        insert pp;
	        
	        Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE Name='Standard Price Book' limit 1];
	        
	        PricebookEntry pbe = new PricebookEntry();
	        pbe.UnitPrice = 10000.00;
	        pbe.Pricebook2Id = pb.Id;
	        pbe.Product2Id = p.Id;
	        pbe.IsActive = true;
	        
	        insert pbe;
	        
	        PricebookEntry pbe1 = new PricebookEntry();
	        pbe1.UnitPrice = 5999.99;
	        pbe1.Pricebook2Id = pb.Id;
	        pbe1.Product2Id = pp.Id;
	        pbe1.IsActive = true;
	        
	        insert pbe1;
	        
	        OpportunityLineItem oli = new OpportunityLineItem();
	        oli.PricebookEntryId = pbe.Id;
	        //oli.PricebookEntryId = '01s70000000MZ4f';
	        oli.OpportunityId = opp.Id;
	        oli.Quantity = 1;
	        oli.ValidationRules__c = true;
	        oli.TotalPrice = 10000.00;
	        
	        //oli.Setup_Fee__c = true;
	        
	        insert oli;
	        
	        OpportunityLineItem oli1 = new OpportunityLineItem();
	        oli1.PricebookEntryId = pbe.Id;
	        oli1.OpportunityId = opp.Id;
	        oli1.Quantity = 1;
	        oli1.TotalPrice = 1000;
	        oli1.ValidationRules__c = true;
	        oli1.Setup_Fee__c = true;
	        
	        insert oli1;
	        
	        opp.Opportunity_Names__c = 'Hardware';
	        opp.StageName = 'Negotiation/Review';
	        opp.Implementation_Contact__c = ct.Id;
	        opp.Deal_Contact__c = ct.Id;
	        //opp.We_Owe__c = 'N/A';
	        opp.Amount = 10000.00;
	        
	        //update opp;
        
	        ApexPages.Standardcontroller sc = new ApexPages.StandardController(opp);
	        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
	        Opp_PriceAdjustment opa = new Opp_PriceAdjustment(sc);
	        
	        test.startTest();
	        
	        opa.mrrPercent = 10.00;
	        opa.mrrPercentPH = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.oneTimePercentPh = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.setUpPercentPH = 10.00;
	        opa.trainPercent = 10.00;
	        opa.trainPercentPH = 10.00;
	        opa.mrrDPCPH = 1;
	        opa.mrrph2 = 1;
	        opa.returnToOppSubDecPer();
	        
	         opa.mrrPercent = 10.00;
	        opa.mrrPercentPH = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.oneTimePercentPh = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.setUpPercentPH = 10.00;
	        opa.trainPercent = 10.00;
	        opa.trainPercentPH = 10.00;
	        opa.mrrDPCPH = 0;
	        opa.mrrph2 = 1;
	        
	        opa.mrrPercent = 10.00;
	        opa.mrrPercentPH = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.oneTimePercentPh = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.setUpPercentPH = 10.00;
	        opa.trainPercent = 10.00;
	        opa.trainPercentPH = 10.00;
	        opa.mrrDPCPH = 1;
	        //opa.otDPCPH = 1;
	        //opa.otph = 1;
	        opa.suDPCPH = 1;
	        opa.suph = 1;
	        opa.suph2 = 10000;
	        //opa.trDPCPH = 1;
	        
	        opa.mrrph2 = 10000;
	        opa.returnToOppSubDecPer();
	        
	      opa.mrrPercent = 10.00;
	        opa.mrrPercentPH = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.oneTimePercentPh = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.setUpPercentPH = 10.00;
	        opa.trainPercent = 10.00;
	        opa.trainPercentPH = 10.00;
	        opa.mrrDPCPH = 1;
	        //opa.otDPCPH = 1;
	        //opa.otph = 1;
	        opa.suDPCPH = 1;
	        opa.suph = 1;
	        opa.suph2 = opa.oppInfo.Setup_Fees__c;
	        //opa.trDPCPH = 1;
	        
	        opa.mrrph2 = 10000;
	        opa.returnToOppSubDecPer();
	        
	        opa.mrrPercent = 10.00;
	        opa.mrrPercentPH = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.oneTimePercentPh = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.setUpPercentPH = 10.00;
	        opa.trainPercent = 10.00;
	        opa.trainPercentPH = 10.00;
	        opa.returnToOppSubIncPer();
	        
	        opa.mrrph2 = 10000;
	        opa.returnToOppSubDecPer();
	        
	        opa.mrrDPCPH = 1;
	        opa.mrrph2 = 1;
	        opa.suph2 = 1;
	        opa.mrrPercent = 10.00;
	        opa.mrrPercentPH = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.oneTimePercentPh = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.setUpPercentPH = 10.00;
	        opa.trainPercent = 10.00;
	        opa.trainPercentPH = 10.00;
	        opa.returnToOppSubIncPer();
	        
	        opa.mrrDPCPH = 0;
	        opa.suDPCPH = 0;
	        opa.mrrph2 = 1;
	        opa.mrrPercent = 10.00;
	        opa.mrrPercentPH = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.oneTimePercentPh = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.setUpPercentPH = 10.00;
	        opa.trainPercent = 10.00;
	        opa.trainPercentPH = 10.00;
	        opa.returnToOppSubIncPer();
	        
	        opa.mrrFlat = 100;
	        opa.oneTimeFlat = opa.oppInfo.One_Time_Fees2__c;
	        opa.setUpFlat = 100;
	        opa.trainFlat = opa.oppInfo.Total_Training__c;
	        //opa.returnToOppSubDecFlat();
	        
	        opa.mrrFlat = 100;
	        opa.mrrDPCPH = 1;
	        opa.suDPCPH = 1;
	        opa.oneTimeFlat = opa.oppInfo.One_Time_Fees2__c;
	        opa.setUpFlat = 100;
	        opa.trainFlat = opa.oppInfo.Total_Training__c;
	        //opa.returnToOppSubDecFlat();
	        
	        opa.mrrFlat = 100;
	        opa.mrrph2 = 10000;
	        opa.suph2 = opa.oppInfo.Setup_Fees__c;
	        opa.mrrDPCPH = 1;
	        opa.suDPCPH = 1;
	        opa.oneTimeFlat = opa.oppInfo.One_Time_Fees2__c;
	        opa.setUpFlat = 100;
	        opa.trainFlat = opa.oppInfo.Total_Training__c;
	        //opa.returnToOppSubDecFlat();
	        
	        /*opa.mrrFlat = 100;
	        opa.oneTimeFlat = opa.oppInfo.One_Time_Fees2__c;
	        opa.setUpFlat = 100;
	        opa.trainFlat = opa.oppInfo.Total_Training__c;
	        opa.returnToOppSubIncFlat();
	        
	        /*opa.mrrFlat = 100;
	        opa.mrrDPCPH = 1;
	        opa.suDPCPH = 1;
	        opa.oneTimeFlat = opa.oppInfo.One_Time_Fees2__c;
	        opa.setUpFlat = 100;
	        opa.trainFlat = opa.oppInfo.Total_Training__c;
	        opa.returnToOppSubIncFlat();
	        
	        opa.mrrFlat = 100;
	        opa.mrrph2 = 10000;
	        opa.suph2 = opa.oppInfo.Setup_Fees__c;
	        opa.mrrDPCPH = 1;
	        opa.suDPCPH = 1;
	        opa.oneTimeFlat = opa.oppInfo.One_Time_Fees2__c;
	        opa.setUpFlat = 100;
	        opa.trainFlat = opa.oppInfo.Total_Training__c;
	        opa.returnToOppSubIncFlat();*/

	        //opa.totalPercentageDiscount();
	        
	        test.stopTest();
	        
        //}
    }
    
    static testMethod void testSubmitsInc() {
        
        User u_testMethodUser = TestData.setupUser();
        
        System.runas(u_testMethodUser) {
            
	        Account a = new Account();
	        a.Name = 'TestPriceAdjustment';
	        a.ShippingCity = 'Belton';
	        a.ShippingStreet = '7900 E 159th St';
	        a.ShippingState = 'MO';
	        a.AccountNumber = '565656565656';
	        a.BillingState = 'MO';
	        a.BillingCity = 'Belton';
	        a.BillingCountry = 'USA';
	        a.BillingPostalCode = '64012';
	        a.BillingStreet = '7900 E 159th St';
	        	        a.ShippingState = 'MO';
	        a.ShippingCity = 'Belton';
	        a.ShippingCountry = 'USA';
	        a.ShippingPostalCode = '64012';
	        a.ShippingStreet = '7900 E 159th St';
	        
	        insert a;
	        
	        Contact ct = new Contact();
	        ct.AccountId = a.Id;
	        ct.FirstName = 'Dean';
	        ct.LastName = 'Martin';
	        ct.Phone = '9999999999';
	        
	        insert ct;
	        
	        Opportunity opp = new Opportunity();
	        opp.AccountId = a.Id;
	        opp.Name = 'Test Price Adjustment';
	        opp.Deal_Contact__c = ct.Id;
	        opp.CloseDate = system.today();
	        opp.StageName = 'Prospect';
	        opp.Type = 'New Business';
	        opp.Salesperson__c = userinfo.getUserId();
	        opp.RecordTypeId = '01270000000Q7t7';
	        opp.TryCatchTest__c = true;

	        
	        insert opp;
	        
	        string prodName = 'CRM';
	        
	        Product2 p = new Product2();
	        p.Name = 'Platimum 1 Package';
	        p.Quantity_Exception__c = true;
	        p.IsTraining__c = true;
	        p.ExpPaidByDealer__c = true;
	        p.ProdProj_Default_Owner__c = userinfo.getUserId();
	        p.Description = 'Email Banner';
	        p.IsPackageParent__c = false;
	        p.Production_Department__c = 'creative';
	        p.Production_Issue__c = 'email Banner';
	        p.requiresWelcomePacket__c = false;
	        p.Family = 'Reoccuring';
	        p.Package_Discount_Percentage__c = .55;
	        
	        insert p;
	        
	        Product2 pp = new Product2();
	        pp.Name = 'Bronze 1 Package';
	        pp.Quantity_Exception__c = true;
	        pp.IsTraining__c = false;
	        //pp.ProductIsParent = 'T';
	        pp.ExpPaidByDealer__c = true;
	        pp.ProdProj_Default_Owner__c = userinfo.getUserId();
	        pp.Description = 'Bronze Package';
	        pp.IsPackageParent__c = true;
	        pp.Production_Department__c = 'package';
	        pp.Production_Issue__c = 'package';
	        pp.requiresWelcomePacket__c = false;
	        pp.Family = 'Monthly Reoccuring';
	        pp.Package_Discount_Percentage__c = .79;
	        
	        insert pp;
	        
	        Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE Name='Standard Price Book' limit 1];
	        
	        PricebookEntry pbe = new PricebookEntry();
	        pbe.UnitPrice = 10000.00;
	        pbe.Pricebook2Id = pb.Id;
	        pbe.Product2Id = p.Id;
	        pbe.IsActive = true;

	        
	        insert pbe;
	        
	        PricebookEntry pbe1 = new PricebookEntry();
	        pbe1.UnitPrice = 5999.99;
	        pbe1.Pricebook2Id = pb.Id;
	        pbe1.Product2Id = pp.Id;
	        pbe1.IsActive = true;
	        
	        insert pbe1;
	        
	        OpportunityLineItem oli = new OpportunityLineItem();
	        oli.PricebookEntryId = pbe.Id;
	        //oli.PricebookEntryId = '01s70000000MZ4f';
	        oli.OpportunityId = opp.Id;
	        oli.Quantity = 1;
	        oli.ValidationRules__c = true;
	        oli.TotalPrice = 10000.00;

	        
	        //oli.Setup_Fee__c = true;
	        
	        insert oli;
	        
	        OpportunityLineItem oli1 = new OpportunityLineItem();
	        oli1.PricebookEntryId = pbe.Id;
	        oli1.OpportunityId = opp.Id;
	        oli1.Quantity = 1;
	        oli1.ValidationRules__c = true;
	        oli1.TotalPrice = 1000;
	        oli1.Setup_Fee__c = true;
	        //oli1.Product_Family_Workflow__c = 'Setup fee';
	        
	        Database.SaveResult SR1 = Database.insert(oli1);
	        
	        opp.Opportunity_Names__c = 'Hardware';
	        opp.StageName = 'Negotiation/Review';
	        opp.Implementation_Contact__c = ct.Id;
	        opp.Deal_Contact__c = ct.Id;
	        //opp.We_Owe__c = 'N/A';
	        opp.Amount = 10000.00;


	        
	        //update opp;
        	system.debug('=========================================>>>>>>> opp.Id = ' + opp.Id);
	        ApexPages.Standardcontroller sc = new ApexPages.StandardController(opp);
	        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
	        Opp_PriceAdjustment opa = new Opp_PriceAdjustment(sc);
	        
	        test.startTest();
	        
	        opa.otph2 = 112233;
	        opa.totalsDisablePriceChange();
	        
	        /*opa.mrrPercent = 10.00;
	        opa.mrrPercentPH = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.oneTimePercentPh = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.setUpPercentPH = 10.00;
	        opa.trainPercent = 10.00;
	        opa.trainPercentPH = 10.00;
	        opa.mrrDPCPH = 1;
	        opa.mrrph2 = 1;
	        opa.returnToOppSubDecPer();
	        
	        opa.mrrPercent = 10.00;
	        opa.mrrPercentPH = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.oneTimePercentPh = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.setUpPercentPH = 10.00;
	        opa.trainPercent = 10.00;
	        opa.trainPercentPH = 10.00;
	        opa.mrrDPCPH = 1;
	        //opa.otDPCPH = 1;
	        //opa.otph = 1;
	        opa.suDPCPH = 1;
	        opa.suph = 1;
	        opa.suph2 = 10000;
	        //opa.trDPCPH = 1;
	        
	        opa.mrrph2 = 10000;
	        opa.returnToOppSubDecPer();
	        
	     	opa.mrrPercent = 10.00;
	        opa.mrrPercentPH = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.oneTimePercentPh = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.setUpPercentPH = 10.00;
	        opa.trainPercent = 10.00;
	        opa.trainPercentPH = 10.00;
	        opa.mrrDPCPH = 1;
	        //opa.otDPCPH = 1;
	        //opa.otph = 1;
	        opa.suDPCPH = 1;
	        opa.suph = 1;
	        opa.suph2 = opa.oppInfo.Setup_Fees__c;
	        //opa.trDPCPH = 1;
	        
	        opa.mrrph2 = 10000;
	        opa.returnToOppSubDecPer();
	        
	        opa.mrrPercent = 10.00;
	        opa.mrrPercentPH = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.oneTimePercentPh = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.setUpPercentPH = 10.00;
	        opa.trainPercent = 10.00;
	        opa.trainPercentPH = 10.00;
	        opa.returnToOppSubIncPer();
	        
	        opa.mrrph2 = 10000;
	        opa.returnToOppSubDecPer();
	        
	        opa.mrrDPCPH = 1;
	        opa.mrrph2 = 1;
	        opa.suph2 = 1;
	        opa.mrrPercent = 10.00;
	        opa.mrrPercentPH = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.oneTimePercentPh = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.setUpPercentPH = 10.00;
	        opa.trainPercent = 10.00;
	        opa.trainPercentPH = 10.00;
	        opa.returnToOppSubIncPer();
	        
	        opa.mrrDPCPH = 0;
	        opa.suDPCPH = 0;
	        opa.mrrph2 = 1;
	        opa.mrrPercent = 10.00;
	        opa.mrrPercentPH = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.oneTimePercentPh = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.setUpPercentPH = 10.00;
	        opa.trainPercent = 10.00;
	        opa.trainPercentPH = 10.00;
	        opa.returnToOppSubIncPer();
	        
	        opa.mrrFlat = 100;
	        opa.oneTimeFlat = opa.oppInfo.One_Time_Fees2__c;
	        opa.setUpFlat = 100;
	        opa.trainFlat = opa.oppInfo.Total_Training__c;
	        opa.returnToOppSubDecFlat();
	        
	        opa.mrrFlat = 100;
	        opa.mrrDPCPH = 1;
	        opa.suDPCPH = 1;
	        opa.oneTimeFlat = opa.oppInfo.One_Time_Fees2__c;
	        opa.setUpFlat = 100;
	        opa.trainFlat = opa.oppInfo.Total_Training__c;
	        opa.returnToOppSubDecFlat();
	        
	        opa.mrrFlat = 100;
	        opa.mrrph2 = 10000;
	        opa.suph2 = opa.oppInfo.Setup_Fees__c;
	        opa.mrrDPCPH = 1;
	        opa.suDPCPH = 1;
	        opa.oneTimeFlat = opa.oppInfo.One_Time_Fees2__c;
	        opa.setUpFlat = 100;
	        opa.trainFlat = opa.oppInfo.Total_Training__c;
	        opa.returnToOppSubDecFlat();*/

	        opa.mrrFlat = 100;
	        opa.mrrDPCPH = 1;
	        opa.suDPCPH = 1;
	        opa.oneTimeFlat = opa.oppInfo.One_Time_Fees2__c;
	        //opa.setUpFlat = 100;
	        opa.trainFlat = opa.oppInfo.Total_Training__c;
	        opa.returnToOppSubIncFlat();
	        
	        opa.mrrFlat = 100;
	        opa.mrrph2 = 10000;
	        opa.suph2 = opa.oppInfo.Setup_Fees__c;
	        opa.mrrDPCPH = 1;
	        opa.suDPCPH = 1;
	        opa.oneTimeFlat = opa.oppInfo.One_Time_Fees2__c;
	        //opa.setUpFlat = 100;
	        opa.trainFlat = opa.oppInfo.Total_Training__c;
	        opa.returnToOppSubIncFlat();
			
			//opa.totalPercentageDiscount();
			opa.resetDecPer();
			opa.resetDecFlat();
			opa.resetIncPer();
			opa.resetIncFlat();
			
	        
	        test.stopTest();
	        
        }
    }
    
    static testMethod void testCalculationsMore() {
        /*
        Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
          emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
          localesidkey = 'en_US', profileid = pro.Id, UserRoleId = '00E70000001GBsB',
          timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com');
          
        insert u_testMethodUser;
        
        System.runas(u_testMethodUser) {*/
            
	        Account a = new Account();
	        a.Name = 'TestPriceAdjustment';
	        a.ShippingCity = 'Belton';
	        a.ShippingStreet = '7900 E 159th St';
	        a.ShippingState = 'MO';
	        a.AccountNumber = '565656565656';
	        a.BillingState = 'MO';
	        a.BillingCity = 'Belton';
	        a.BillingCountry = 'USA';
	        a.BillingPostalCode = '64012';
	        a.BillingStreet = '7900 E 159th St';
	        	        a.ShippingState = 'MO';
	        a.ShippingCity = 'Belton';
	        a.ShippingCountry = 'USA';
	        a.ShippingPostalCode = '64012';
	        a.ShippingStreet = '7900 E 159th St';
	        
	        insert a;
	        
	        Contact ct = new Contact();
	        ct.AccountId = a.Id;
	        ct.FirstName = 'Dean';
	        ct.LastName = 'Martin';
	        ct.Phone = '9999999999';
	        
	        insert ct;
	        
	        Opportunity opp = new Opportunity();
	        opp.AccountId = a.Id;
	        opp.Name = 'Test Price Adjustment';
	        opp.Deal_Contact__c = ct.Id;
	        opp.CloseDate = system.today();
	        opp.StageName = 'Prospect';
	        opp.Type = 'New Business';
	        opp.Salesperson__c = userinfo.getUserId();
	        opp.RecordTypeId = '01270000000Q7t7';
	        opp.TryCatchTest__c = true;
	        
	        insert opp;
	        
	        string prodName = 'CRM';
	        
	        Product2 p = new Product2();
	      	p.Name = 'Platinum 1 Package';
	        p.Quantity_Exception__c = false;
	        p.IsTraining__c = false;
	        p.ExpPaidByDealer__c = true;
	        p.ProdProj_Default_Owner__c = userinfo.getUserId();
	        p.Description = 'Email Banner';
	        p.IsPackageParent__c = false;
	        p.Production_Department__c = 'creative';
	        p.Production_Issue__c = 'email Banner';
	        p.requiresWelcomePacket__c = false;
	        p.Family = 'Reoccuring';
	        p.Package_Discount_Percentage__c = .55;
	        
	        insert p;
	        
	        Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE Name='Standard Price Book' limit 1];
	        
	        PricebookEntry pbe = new PricebookEntry();
	        pbe.UnitPrice = 10000.00;
	        pbe.Pricebook2Id = pb.Id;
	        pbe.Product2Id = p.Id;
	        pbe.IsActive = true;
	        
	        insert pbe;
	        
	        OpportunityLineItem oli = new OpportunityLineItem();
	        oli.PricebookEntryId = pbe.Id;
	        oli.OpportunityId = opp.Id;
	        oli.Quantity = 1;
	        oli.ValidationRules__c = true;
	        oli.TotalPrice = 10000.00;
	        //oli.Setup_Fee__c = true;
	        
	        insert oli;
	        
	        OpportunityLineItem oli1 = new OpportunityLineItem();
	        oli1.PricebookEntryId = pbe.Id;
	        //oli.PricebookEntryId = '01s70000000MZ4f';
	        oli1.OpportunityId = opp.Id;
	        oli1.Quantity = 1;
	        oli1.ValidationRules__c = true;
	        oli1.TotalPrice = 1000;
	        oli1.Setup_Fee__c = true;
	        
	        insert oli1;
	        
	        opp.Opportunity_Names__c = 'Hardware';
	        opp.StageName = 'Negotiation/Review';
	        opp.Implementation_Contact__c = ct.Id;
	        opp.Deal_Contact__c = ct.Id;
	        //opp.We_Owe__c = 'N/A';
	        opp.Amount = 10000.00;
	        
	        update opp;
        
	        ApexPages.Standardcontroller sc = new ApexPages.StandardController(opp);
	        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
	        Opp_PriceAdjustment opa = new Opp_PriceAdjustment(sc);
	        
	        test.startTest();
	        
	        opa.mrrph2 = 1;
	        opa.suph2 = 1;
	        opa.totalFlatDiscount();
	        opa.mrrFlat = 100;
	        opa.setUpFlat = 100;
	        opa.realTimeTotalFlatDiscount();
	        opa.totalPercentageDiscount();
	        
	        
	        test.stopTest();
        //}
    }
    
     static testMethod void moreTests() {
        
        /*Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
          emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
          localesidkey = 'en_US', profileid = pro.Id, UserRoleId = '00E70000001GBsB',
          timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com');
          
        insert u_testMethodUser;
        
        System.runas(u_testMethodUser) {*/
            
	        Account a = new Account();
	        a.Name = 'TestPriceAdjustment';
	        a.ShippingCity = 'Belton';
	        a.ShippingStreet = '7900 E 159th St';
	        a.ShippingState = 'MO';
	        a.AccountNumber = '565656565656';
	        a.BillingState = 'MO';
	        a.BillingCity = 'Belton';
	        a.BillingCountry = 'USA';
	        a.BillingPostalCode = '64012';
	        a.BillingStreet = '7900 E 159th St';
	        	        a.ShippingState = 'MO';
	        a.ShippingCity = 'Belton';
	        a.ShippingCountry = 'USA';
	        a.ShippingPostalCode = '64012';
	        a.ShippingStreet = '7900 E 159th St';
	        
	        insert a;
	        
	        Contact ct = new Contact();
	        ct.AccountId = a.Id;
	        ct.FirstName = 'Dean';
	        ct.LastName = 'Martin';
	        ct.Phone = '9999999999';
	        
	        insert ct;
	        
	        Opportunity opp = new Opportunity();
	        opp.AccountId = a.Id;
	        opp.Name = 'Test Price Adjustment';
	        opp.Deal_Contact__c = ct.Id;
	        opp.CloseDate = system.today();
	        opp.StageName = 'Prospect';
	        opp.Type = 'New Business';
	        opp.Salesperson__c = userinfo.getUserId();
	        opp.RecordTypeId = '01270000000Q7t7';
	        opp.TryCatchTest__c = true;
	        
	        insert opp;
	        
	        string prodName = 'CRM';
	        
	        Product2 p = new Product2();
	      	p.Name = 'Platimum 1 Package';
	        p.Quantity_Exception__c = false;
	        p.IsTraining__c = false;
	        p.ExpPaidByDealer__c = true;
	        p.ProdProj_Default_Owner__c = userinfo.getUserId();
	        p.Description = 'Email Banner';
	        p.IsPackageParent__c = false;
	        p.Production_Department__c = 'creative';
	        p.Production_Issue__c = 'email Banner';
	        p.requiresWelcomePacket__c = false;
	        p.Family = 'Reoccuring';
	        p.Package_Discount_Percentage__c = .55;
	        
	        insert p;
	        
	        Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE Name='Standard Price Book' limit 1];
	        
	        PricebookEntry pbe = new PricebookEntry();
	        pbe.UnitPrice = 10000.00;
	        pbe.Pricebook2Id = pb.Id;
	        pbe.Product2Id = p.Id;
	        pbe.IsActive = true;
	        
	        insert pbe;
	        
	        OpportunityLineItem oli = new OpportunityLineItem();
	        oli.PricebookEntryId = pbe.Id;
	        oli.OpportunityId = opp.Id;
	        oli.Quantity = 1;
	        oli.ValidationRules__c = true;
	        oli.TotalPrice = 10000.00;
	        //oli.Setup_Fee__c = true;
	        
	        insert oli;
	        
	        OpportunityLineItem oli1 = new OpportunityLineItem();
	        oli1.PricebookEntryId = pbe.Id;
	        //oli.PricebookEntryId = '01s70000000MZ4f';
	        oli1.OpportunityId = opp.Id;
	        oli1.Quantity = 1;
	        oli1.TotalPrice = 1000;
	        oli1.ValidationRules__c = true;
	        oli1.Setup_Fee__c = true;
	        
	        insert oli1;
	        
	        opp.Opportunity_Names__c = 'Hardware';
	        opp.StageName = 'Negotiation/Review';
	        opp.Implementation_Contact__c = ct.Id;
	        opp.Deal_Contact__c = ct.Id;
	        //opp.We_Owe__c = 'N/A';
	        opp.Amount = 10000.00;
	        
	        update opp;
        
	        ApexPages.Standardcontroller sc = new ApexPages.StandardController(opp);
	        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
	        Opp_PriceAdjustment opa = new Opp_PriceAdjustment(sc);
	        
	        test.startTest();
	        
	        opa.mrrph2 = 1;
	        opa.suph2 = 1;
	        opa.totalFlatDiscount();
	        opa.mrrFlat = 100;
	        opa.setUpFlat = 100;
	        opa.realTimeTotalFlatDiscount();
	        opa.totalPercentageDiscount();
	        
	        
	        opa.mrrPercent = 10.00;
	        opa.mrrPercentPH = 10.00;
	        opa.oneTimePercent = 10.00;
	        opa.oneTimePercentPh = 10.00;
	        opa.setUpPercent = 10.00;
	        opa.setUpPercentPH = 10.00;
	        opa.trainPercent = 10.00;
	        opa.trainPercentPH = 10.00;
	        opa.mrrDPCPH = 1;
	        opa.mrrph2 = 1;
	        opa.otDPCPH = 1;
	        opa.trDPCPH = 1;
	        opa.trph2 = opa.oppInfo.Total_Training__c;
	        opa.otph = 1;
	        opa.otph2 = opa.oppInfo.One_Time_Fees2__c;
	        opa.submitDecPer();
	        test.stopTest();
	        
       // }
        
     }

    static testMethod void testSubmitsInc2() {
        
        User u_testMethodUser = TestData.setupUser();
        
        System.runas(u_testMethodUser) {
            
	        Account a = new Account();
	        a.Name = 'TestPriceAdjustment';
	        a.ShippingCity = 'Belton';
	        a.ShippingStreet = '7900 E 159th St';
	        a.ShippingState = 'MO';
	        a.AccountNumber = '565656565656';
	        a.BillingState = 'MO';
	        a.BillingCity = 'Belton';
	        a.BillingCountry = 'USA';
	        a.BillingPostalCode = '64012';
	        a.BillingStreet = '7900 E 159th St';
	        	        a.ShippingState = 'MO';
	        a.ShippingCity = 'Belton';
	        a.ShippingCountry = 'USA';
	        a.ShippingPostalCode = '64012';
	        a.ShippingStreet = '7900 E 159th St';
	        
	        insert a;
	        
	        Contact ct = new Contact();
	        ct.AccountId = a.Id;
	        ct.FirstName = 'Dean';
	        ct.LastName = 'Martin';
	        ct.Phone = '9999999999';
	        
	        insert ct;
	        
	        Opportunity opp = new Opportunity();
	        opp.AccountId = a.Id;
	        opp.Name = 'Test Price Adjustment';
	        opp.Deal_Contact__c = ct.Id;
	        opp.CloseDate = system.today();
	        opp.StageName = 'Prospect';
	        opp.Type = 'New Business';
	        opp.Salesperson__c = userinfo.getUserId();
	        opp.RecordTypeId = '01270000000Q7t7';
	        opp.TryCatchTest__c = true;

	        
	        insert opp;
	        
	        string prodName = 'CRM';
	        
	        Product2 p = new Product2();
	        p.Name = 'Platimum 1 Package';
	        p.Quantity_Exception__c = true;
	        p.IsTraining__c = true;
	        p.ExpPaidByDealer__c = true;
	        p.ProdProj_Default_Owner__c = userinfo.getUserId();
	        p.Description = 'Email Banner';
	        p.IsPackageParent__c = false;
	        p.Production_Department__c = 'creative';
	        p.Production_Issue__c = 'email Banner';
	        p.requiresWelcomePacket__c = false;
	        p.Family = 'Setup fee';
	        p.Package_Discount_Percentage__c = .55;
	        
	        insert p;

	        Product2 p2 = TestData.getProduct();
	        p2.Family = 'Monthly Reoccuring';
	        /*
	        Product2 pp = new Product2();
	        pp.Name = 'CRM with Website Limited Users Package';
	        pp.Quantity_Exception__c = true;
	        //pp.ProductIsParent = 'T';
	        pp.ExpPaidByDealer__c = true;
	        pp.ProdProj_Default_Owner__c = userinfo.getUserId();
	        pp.Description = 'Bronze Package';
	        pp.IsPackageParent__c = true;
	        pp.Production_Department__c = 'package';
	        pp.Production_Issue__c = 'package';
	        pp.requiresWelcomePacket__c = false;
	        pp.Family = 'Monthly Reoccuring';
	        pp.Package_Discount_Percentage__c = .79;
	        */
	        insert p2;

	        Product2 p3 = TestData.getProduct();
	        p3.Family = 'One Time';
	        p3.IsTraining__c = true;
	        insert p3;
	        
	        Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE Name='Standard Price Book' limit 1];
	        
	        PricebookEntry pbe = new PricebookEntry();
	        pbe.UnitPrice = 10000.00;
	        pbe.Pricebook2Id = pb.Id;
	        pbe.Product2Id = p.Id;
	        pbe.IsActive = true;

	        
	        insert pbe;
	        
	        PricebookEntry pbe2 = new PricebookEntry();
	        pbe2.UnitPrice = 5999.99;
	        pbe2.Pricebook2Id = pb.Id;
	        pbe2.Product2Id = p2.Id;
	        pbe2.IsActive = true;
	        
	        insert pbe2;

	        PricebookEntry pbe3 = new PricebookEntry();
	        pbe3.UnitPrice = 5999.99;
	        pbe3.Pricebook2Id = pb.Id;
	        pbe3.Product2Id = p3.Id;
	        pbe3.IsActive = true;
	        insert pbe3;
	        
	        OpportunityLineItem oli = new OpportunityLineItem();
	        oli.PricebookEntryId = pbe2.Id;
	        //oli.PricebookEntryId = '01s70000000MZ4f';
	        oli.OpportunityId = opp.Id;
	        oli.Quantity = 1;
	        oli.ValidationRules__c = true;
	        oli.TotalPrice = 1000.00;

	        
	        //oli.Setup_Fee__c = true;
	        
	        insert oli;
	        
	        OpportunityLineItem oli1 = new OpportunityLineItem();
	        oli1.PricebookEntryId = pbe.Id;
	        oli1.OpportunityId = opp.Id;
	        oli1.Quantity = 1;
	        oli1.ValidationRules__c = true;
	        oli1.TotalPrice = 1000;
	        oli1.Setup_Fee__c = true;
	        
	        Database.SaveResult SR1 = Database.insert(oli1);

	        OpportunityLineItem oli3 = new OpportunityLineItem();
	        oli3.PricebookEntryId = pbe3.Id;
	        //oli.PricebookEntryId = '01s70000000MZ4f';
	        oli3.OpportunityId = opp.Id;
	        oli3.Quantity = 3;
	        oli3.ValidationRules__c = true;
	        oli3.TotalPrice = 10000.00;
	        insert oli3;
	        
	        opp.Opportunity_Names__c = 'Hardware';
	        opp.StageName = 'Negotiation/Review';
	        opp.Implementation_Contact__c = ct.Id;
	        opp.Deal_Contact__c = ct.Id;
	        //opp.We_Owe__c = 'N/A';
	        opp.Amount = 10000.00;


	        
	        //update opp;
        	system.debug('=========================================>>>>>>> opp.Id = ' + opp.Id);
	        ApexPages.Standardcontroller sc = new ApexPages.StandardController(opp);
	        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
	        Opp_PriceAdjustment opa = new Opp_PriceAdjustment(sc);
	        
	        test.startTest();
	        
	        opa.otph2 = 112233;
	        opa.totalsDisablePriceChange();
	        opa.mrrFlat = 100;
	        opa.oneTimeFlat = opa.oppInfo.One_Time_Fees2__c;
	        opa.setUpFlat = 100;
	        opa.trainFlat = opa.oppInfo.Total_Training__c;
	        opa.returnToOppSubIncFlat();

	        opa.mrrFlat = 100.00;
	        opa.oneTimeFlat = 0;
	        opa.setUpFlat = 100.00;
	        opa.trainFlat = 100.00;
	        opa.calculateDecFlat();

	        opa.returnToOppSubDecFlat();
			
	        
	        test.stopTest();
	        
        }
    }

}