objects/Account.object
<CustomObject>
    <fields>
        <fullName>ATC_Account_ID__c</fullName>
        <inlineHelpText>for Leads submitted into the AutoTrader Lead Campaign</inlineHelpText>
        <label>ATC Account ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>An individual rooftop.</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Dynamic_Email__c.object
<CustomObject>
    <fields>
        <fullName>Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template</label>
        <referenceTo>Template__c</referenceTo>
        <relationshipLabel>Dynamic Emails</relationshipLabel>
        <relationshipName>Dynamic_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Urgency__c</fullName>
        <label>Urgency</label>
        <picklist>
            <picklistValues>
                <fullName>Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dynamic Email</label>
    <nameField>
        <label>Dynamic Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dynamic Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Template__c.object
<CustomObject>
    <fields>
        <fullName>API_Name__c</fullName>
        <label>API Name</label>
        <picklist>
            <picklistValues>
                <fullName>POA__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC_520_Quote__c</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Text__c</fullName>
        <label>Standard Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Urgency__c</fullName>
        <label>Urgency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Template</label>
    <nameField>
        <displayFormat>Temp-{0000000000}</displayFormat>
        <label>Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Template_Merge_Field__c.object
<CustomObject>
    <fields>
        <fullName>API_Name__c</fullName>
        <label>API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Column_Header__c</fullName>
        <label>Column Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plural_Name__c</fullName>
        <label>Plural Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Template</label>
        <referenceTo>Template__c</referenceTo>
        <relationshipLabel>Template Merge Fields</relationshipLabel>
        <relationshipName>Template_Merge_Fiels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Template Merge Field</label>
    <nameField>
        <displayFormat>TMF-{0000000000}</displayFormat>
        <label>Template Merge Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Template Merge Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/test_dynamicEmail.cls
@isTest//(SeeAllData = true)
private class test_dynamicEmail {

    static testMethod void myUnitTest() {
    	Map <String,Schema.RecordTypeInfo> accountRecordTypes = Account.sObjectType.getDescribe().getRecordTypeInfosByName();
    	ID dealerRecID = accountRecordTypes.get('Dealer').getRecordTypeId();
       	Account a = new Account(Name = 'Test', RecordTypeID = dealerRecID, BillingPostalCode = '66210', BillingStreet = 'Number 1 Happy Street', BillingCity='Overland Park', BillingState = 'KS', BillingCountry='US'
        , ShippingPostalCode = '66210', ShippingStreet = 'Number 1 Happy Street', ShippingCity='Overland Park', ShippingState = 'KS', ShippingCountry='US'
          );
       	insert a;
       	
       	Map <String,Schema.RecordTypeInfo> oppRecordTypes = Opportunity.sObjectType.getDescribe().getRecordTypeInfosByName();
    	ID genSalesRecID = oppRecordTypes.get('Vin').getRecordTypeId();
       	Opportunity opp = new Opportunity(Name='Test', StageName='Prospect', CloseDate = date.today(), AccountID = a.ID, RecordTypeID = genSalesRecID);
       	insert opp;
       	
       	Template__c temp = new Template__c();
       	temp.API_Name__c = 'Account';
       	temp.Name__c = 'Test Template';
       	temp.Standard_Text__c = 'Lorem Ipsum';
       	insert temp;
       	
       	Template_Merge_Field__c tmf = new Template_Merge_Field__c();
       	tmf.API_Name__c = 'ATC_Account_ID__c';
       	tmf.Name__c = 'ATC Account ID';
       	tmf.Template__c = temp.ID;
       	insert tmf;
       	
       	Template_Merge_Field__c tmfTable = new Template_Merge_Field__c();
       	tmfTable.API_Name__c = 'StageName';
       	tmfTable.Name__c = 'oppStage';
       	tmfTable.Plural_Name__c = 'Opportunities';
       	tmfTable.Column_Header__c  = 'Stage Name';
       	tmfTable.template__c = temp.iD;
       	insert tmfTable;
       	
       	Dynamic_Email__c de = new Dynamic_Email__c();
       	de.Template__c = temp.ID;
       	de.Urgency__c = 'Critical';
       	insert de;
       	
       	EmailTemplate et = [SELECT ID, Name FROM EmailTemplate WHERE Name = 'Dynamic Email Template'];
       	Test.startTest();
       	test.setCurrentPage(new pageReference('/apex/emailSetup?relatedToID='+a.ID));
    	ctrl_EmailSetup controller = new ctrl_EmailSetup();
    	list<SelectOption> tempOps = controller.getTemplateOptions();
    	//controller.mainTemplate = temp;
    	controller.mainTemplate = temp;
    	controller.tempNum = 0;
    	controller.findTemplate();
    	controller.UrgencyImage = 'Critical';
    	controller.findUrgencyImage();
    	controller.UrgencyImage = 'Normal';
    	controller.findUrgencyImage();
    	controller.UrgencyImage = 'Low';
    	controller.findUrgencyImage();
		string s = controller.getStandardText();
    	controller.findUserInfo();

    	PageReference pr = controller.runHandler();
    	
    	test.setCurrentPage(new pageReference('/_ui/core/email/author/EmailAuthor?p3_lkid='+de.ID+'&template_id='+eT.ID+'&sobj_id='+a.ID));
    	ctrl_DynamicEmail controller2 = new ctrl_DynamicEmail();
    	//controller2.getDynamicEmail();
    	controller2.getThisID();
    	controller2.getEmail();
    	controller2.getFirstName();
    	controller2.getLastName();
    	controller2.getObjID();
    	controller2.getPhone();
    	controller2.getStandardText();
    	controller2.getTitle();
    	controller2.getDynamicEmail();
    	controller2.getExt();
    	controller2.getObjID();
    	list<dynamicEmailHandler.tableDisplay> emailTables = controller2.getTables();
    	
    	test.setCurrentPage(new pageReference('/apex/addTemplateMergeField'));
   		ApexPages.StandardController sc = new ApexPages.StandardController(temp);
    	ctrl_addTemplateMergeField controller3 = new ctrl_addTemplateMergeField(sc);
    	controller3.findFieldListStandard();
    	controller3.getTemplateTypes();
    	controller3.runRefresh();
    	controller3.findMergeFieldType();
    	pageReference pr2 = controller3.saveTMF();
    	
    	ctrl_EmailTables controller4 = new ctrl_EmailTables();
    	controller4.RID = a.ID;
    	controller4.tempID = temp.ID;
    	list<dynamicEmailHandler.tableDisplay> emailTables2 = controller4.getTables();
    	
    	ctrl_BannerComponent controller5 = new ctrl_BannerComponent();
    	controller5.getBanner();
    	
    	dynamicEmailHandler handler = new dynamicEmailHandler();
    	list<string> colHeaders = dynamicEmailHandler.findColumnHeaders(temp);
    	list<string> headerValues = dynamicEmailHandler.findHeaderValues(temp);
    	
    	Test.stopTest();
    }
}