objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <formula>VinPro2__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vin PM Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flag_for_Heat__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>used to Flag an account as a Heat account</inlineHelpText>
        <label>Flag for Heat</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Heat_Notes__c</fullName>
        <inlineHelpText>when an account is flagged for heat - heat notes must be entered to go into heat email</inlineHelpText>
        <label>Heat Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Special_Account_Status__c</fullName>
        <label>Special Account Status</label>
        <picklist>
            <controllingField>Flag_for_Heat__c</controllingField>
            <picklistValues>
                <fullName>DAB Heat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAB Member</fullName>
                <color>#990000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Heat Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revenue Opportunity</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Revenue Opp Heat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Territory_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory State</label>
        <referenceTo>Territory_State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Special_Account_Status__c</fullName>
        <formula>TEXT( Account.Special_Account_Status__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Special Account Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Territory_State__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DDM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Website_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Website Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States9</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/job_updateCaseRankings_test.cls
@isTest(SeeAllData=True)
private class job_updateCaseRankings_test {

    static testMethod void myUnitTest() {
        
        /*Territory_State__c TS = new Territory_State__c();
  		TS.Name = 'XX';
		TS.Account_Manager__c = userinfo.getUserId();
		TS.DDM__c = userinfo.getUserId();
		TS.Regional__c = userinfo.getUserId();
		TS.Implementation_Manager__c = userinfo.getUserId();
        TS.Implementation_Specialist__c = userinfo.getUserId();	
        TS.Website_Manager__c = userInfo.getUserId();	
		insert TS;*/
        
        
        Account a = new Account();
    	a.ShippingCity = 'test';
    	a.shippingStreet = 'test';
    	a.ShippingState = 'xx';
    	a.ShippingPostalCode = '12345';
    	a.BillingState = 'KS';
    	a.AccountNumber = '1';
    	a.BillingCity = 'test';
    	a.BillingCountry = 'USA';
    	a.BillingPostalCode = '12345';
    	a.BillingState = 'KS';
    	a.BillingStreet = '1234';
    	a.Flag_for_Heat__c = true;
    	a.Special_Account_Status__c = 'DAB Heat';
    	a.Heat_Notes__c = 'Test notes here';
    	a.name = 'Test Account';
    	a.Type = 'Prospect';
    	insert a;
    	string aid = a.Id;
    	
    	Contact ct = new Contact();
    	ct.AccountId = a.Id;
    	ct.FirstName = 'test';
    	ct.LastName = 'test';
        ct.Phone = '9999999999';
    	
    	insert ct;
    	
    	Case c = new Case();
    
    	c.AccountId = a.Id;
    	c.ContactId = ct.Id;
    	c.Origin = 'Phone';
    	c.Reason = 'Billing';
    	c.Status = 'new';
    	c.Priority = '3 - Cold (Fix in the future)';
    	c.ParentId = null;
    	
    	insert c;
    	
    	Case c2 = new Case();
    
    	c2.AccountId = a.Id;
    	c2.ContactId = ct.Id;
    	c2.Origin = 'Phone';
    	c2.Reason = 'Billing';
    	c2.Status = 'new';
    	c2.Priority = '3 - Cold (Fix in the future)';
    	c2.parentId = c.Id;
    	insert c2;
    	
    	test.startTest();
    	database.executebatch(new job_updateCaseRankings());
    	test.stopTest();
    }
}