objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <formula>VinPro2__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vin PM Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory State</label>
        <referenceTo>Territory_State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <label>Implementation Manager</label>
        <picklist>
            <picklistValues>
                <fullName>Matt Bench</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travis Douglas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jennifer Merrick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kandy Richert</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Territory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Piece_Issue__c</fullName>
        <inlineHelpText>Auto-populated from Products sold when Opportunity marked PAID</inlineHelpText>
        <label>Piece Issue</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Runner__c.object
<CustomObject>
    <description>used to move Project Pieces departmentally</description>
    <fields>
        <fullName>Designer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assign To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>Website, Design, Creative, Integration, Marketing, SEO, SEM, SMM</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Runners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <inlineHelpText>Time to set even date/time for the Designer</inlineHelpText>
        <label>Event Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <label>Event End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project_Piece__c</fullName>
        <label>Project Piece</label>
        <referenceTo>Project_Piece__c</referenceTo>
        <relationshipLabel>Project Runners</relationshipLabel>
        <relationshipName>Project_Runners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Runner_Action__c</fullName>
        <label>Runner Action</label>
        <picklist>
            <picklistValues>
                <fullName>Go Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Pull</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pull Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Start</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Runner_Type__c</fullName>
        <label>Runner Type</label>
        <picklist>
            <picklistValues>
                <fullName>All Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PBX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Runner</label>
    <nameField>
        <displayFormat>PR-{0000000000}</displayFormat>
        <label>Project Runner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Runners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <description>Vin_Performance_Manager__r.User_Full_Name__c</description>
        <formula>Vin_Performance_Manager__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Vin_Performance_Manager__r.User_Full_Name__c</inlineHelpText>
        <label>Vin PM (formula)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;&amp;Opportunity__r.Implementation_Contact__r.Id,  Opportunity__r.Implementation_Contact__r.FirstName&amp;&quot; &quot;&amp; Opportunity__r.Implementation_Contact__r.LastName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Implementation Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Territory_State__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DDM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdatePieceStage_test.cls
@isTest(SeeAllData=true)
private class UpdatePieceStage_test {

    static testMethod void myUnitTest() {
        /*Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];        
        UserRole role = [SELECT Id From UserRole WHERE Name = 'Director of Sales'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
            emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
            localesidkey = 'en_US', profileid = pro.Id, 
            timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com',
            UserRoleId = role.Id);
                        
        insert u_testMethodUser;
        
                
        System.runas(u_testMethodUser) {*/
            
            //Set your controller
            UpdatePieceStage controller = new UpdatePieceStage();            
            
            /*Territory_State__c TS = new Territory_State__c();
            TS.DDM__c = userinfo.getUserId();
            TS.Account_Manager__c = userinfo.getUserId();
            TS.Territory_Manager__c = userinfo.getUserId();
            TS.Implementation_Manager__c = userinfo.getUserId();
            TS.Implementation_Specialist__c = userinfo.getUserId();
            TS.Regional__c = userinfo.getUserId();
            
            
            TS.Name = 'TS';
            insert TS;*/
            
            Account A = new Account();
            A.BillingState = 'KS';
            A.Name = 'test';
            A.BillingCity = 'test';
            A.BillingCountry = 'USA';
            A.BillingPostalCode = '66212';
            A.BillingState = 'KS';
            A.BillingStreet = '1234';
                            A.ShippingCity = 'test';
        A.ShippingCountry = 'USA';
        A.ShippingPostalCode = '66212';
        A.ShippingState = 'KS';
        A.ShippingStreet = '1234';
            insert A;
            
            Opportunity O = new Opportunity();
            O.AccountId = A.Id;
            O.Name = 'test';
            O.CloseDate = system.today();
            O.StageName = 'Prospect';
            insert O;
            
            Product2 product = new Product2(
            name = 'test');     
            insert product;
            
            SFDC_520_Quote__c P = new SFDC_520_Quote__c();
            P.Opportunity__c = O.id;
            User thisUser = [select id, Email from User where Id=:userinfo.getuserId()];        
            insert P;
            
            Project_Piece__c PP = new Project_Piece__c();
            PP.Project__c = P.Id;
            PP.Piece_Issue__c = 'test';
            PP.RecordTypeId = '01270000000Q4V0';
            PP.Name = 'PP-Website - landing page-';
            insert PP;
            
            LIST<Project_Runner__c> testPRs = new LIST<Project_Runner__c>();
            
            Project_Runner__c PR = new Project_Runner__c();
            PR.Project_Piece__c = PP.Id;
            PR.Designer__c = Userinfo.getUserId();
            PR.Event_Date_Time__c = system.now();
            PR.Event_End_Date_Time__c = system.now();
            PR.Runner_Action__c = 'Request';
            PR.Runner_Type__c = 'Comp';
            insert PR;
            
            test.startTest();
            // original PR action/type is Request/Comp, need to change action to Start, Submit, Approve
            
            PR.Runner_Action__c = 'Start';
            update PR;    
            UpdatePieceStage.updatePieceStage(PR);           
            PR.Runner_Action__c = 'Submit';
            update PR;    
            UpdatePieceStage.updatePieceStage(PR);           
            PR.Runner_Action__c = 'Approve';
            update PR;    
            UpdatePieceStage.updatePieceStage(PR);           

            test.stopTest();
            
        //}
    }
    static testMethod void myUnitTest2() {
        
        /*Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        UserRole role = [SELECT Id From UserRole WHERE Name = 'Director of Sales'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
            emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
            localesidkey = 'en_US', profileid = pro.Id, 
            timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com',
            UserRoleId = role.Id);
                        
        insert u_testMethodUser;
        
                
        System.runas(u_testMethodUser) {*/
            
            //Set your controller
            UpdatePieceStage controller = new UpdatePieceStage();            
            
            /*Territory_State__c TS = new Territory_State__c();
            TS.DDM__c = userinfo.getUserId();
            TS.Account_Manager__c = userinfo.getUserId();
            TS.Territory_Manager__c = userinfo.getUserId();
            TS.Implementation_Manager__c = userinfo.getUserId();
            TS.Implementation_Specialist__c = userinfo.getUserId();
            TS.Regional__c = userinfo.getUserId();
            
            
            TS.Name = 'TS';
            insert TS;*/
            
            Account A = new Account();
            A.BillingState = 'KS';
            A.Name = 'test';
            A.BillingCity = 'test';
            A.BillingCountry = 'USA';
            A.BillingPostalCode = '66212';
            A.BillingState = 'KS';
            A.BillingStreet = '1234';
                            A.ShippingCity = 'test';
        A.ShippingCountry = 'USA';
        A.ShippingPostalCode = '66212';
        A.ShippingState = 'KS';
        A.ShippingStreet = '1234';
            insert A;
            
            Opportunity O = new Opportunity();
            O.AccountId = A.Id;
            O.Name = 'test';
            O.CloseDate = system.today();
            O.StageName = 'Prospect';
            insert O;
            
            Product2 product = new Product2(
            name = 'test');     
            insert product;
            
            SFDC_520_Quote__c P = new SFDC_520_Quote__c();
            P.Opportunity__c = O.id;
            User thisUser = [select id, Email from User where Id=:userinfo.getuserId()];        
            insert P;
            
            Project_Piece__c PP = new Project_Piece__c();
            PP.Project__c = P.Id;
            PP.Piece_Issue__c = 'test';
            PP.RecordTypeId = '01270000000Q4V0';
            PP.Name = 'PP-Website - landing page-';
            insert PP;
            
            LIST<Project_Runner__c> testPRs = new LIST<Project_Runner__c>();
            
            Project_Runner__c PR = new Project_Runner__c();
            PR.Project_Piece__c = PP.Id;
            PR.Designer__c = Userinfo.getUserId();
            PR.Event_Date_Time__c = system.now();
            PR.Event_End_Date_Time__c = system.now();
            PR.Runner_Action__c = 'Request';
            PR.Runner_Type__c = 'Correction';
            insert PR;
            
            test.startTest();
            // original PR action/type is Request/Correction, need to change action to Start, Submit, Approve
            
            PR.Runner_Action__c = 'Start';
            update PR;    
            UpdatePieceStage.updatePieceStage(PR);           
            PR.Runner_Action__c = 'Submit';
            update PR;    
            UpdatePieceStage.updatePieceStage(PR);           
            PR.Runner_Action__c = 'Approve';
            update PR;    
            UpdatePieceStage.updatePieceStage(PR);           
            
            test.stopTest();
            
        //}
    }
    static testMethod void myUnitTest3() {
        
       /* Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        UserRole role = [SELECT Id From UserRole WHERE Name = 'Director of Sales'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
            emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
            localesidkey = 'en_US', profileid = pro.Id, 
            timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com',
            UserRoleId = role.Id);
                        
        insert u_testMethodUser;
        
                
        System.runas(u_testMethodUser) {*/
            
            //Set your controller
            UpdatePieceStage controller = new UpdatePieceStage();            
            
            /*Territory_State__c TS = new Territory_State__c();
            TS.DDM__c = userinfo.getUserId();
            TS.Account_Manager__c = userinfo.getUserId();
            TS.Territory_Manager__c = userinfo.getUserId();
            TS.Implementation_Manager__c = userinfo.getUserId();
            TS.Implementation_Specialist__c = userinfo.getUserId();
            TS.Regional__c = userinfo.getUserId();
            
            
            TS.Name = 'TS';
            insert TS;*/
            
            Account A = new Account();
            A.BillingState = 'KS';
            A.Name = 'test';
            A.BillingCity = 'test';
            A.BillingCountry = 'USA';
            A.BillingPostalCode = '66212';
            A.BillingState = 'KS';
            A.BillingStreet = '1234';
                            A.ShippingCity = 'test';
        A.ShippingCountry = 'USA';
        A.ShippingPostalCode = '66212';
        A.ShippingState = 'KS';
        A.ShippingStreet = '1234';
            insert A;
            
            Opportunity O = new Opportunity();
            O.AccountId = A.Id;
            O.Name = 'test';
            O.CloseDate = system.today();
            O.StageName = 'Prospect';
            insert O;
            
            Product2 product = new Product2(
            name = 'test');     
            insert product;
            
            SFDC_520_Quote__c P = new SFDC_520_Quote__c();
            P.Opportunity__c = O.id;
            User thisUser = [select id, Email from User where Id=:userinfo.getuserId()];        
            insert P;
            
            Project_Piece__c PP = new Project_Piece__c();
            PP.Project__c = P.Id;
            PP.Piece_Issue__c = 'test';
            PP.RecordTypeId = '01270000000Q4V0';
            PP.Name = 'PP-Website - landing page-';
            insert PP;
            
            LIST<Project_Runner__c> testPRs = new LIST<Project_Runner__c>();
            
            Project_Runner__c PR = new Project_Runner__c();
            PR.Project_Piece__c = PP.Id;
            PR.Designer__c = Userinfo.getUserId();
            PR.Event_Date_Time__c = system.now();
            PR.Event_End_Date_Time__c = system.now();
            PR.Runner_Action__c = 'Request';
            PR.Runner_Type__c = 'Revision';
            insert PR;
            
            test.startTest();
            // original PR action/type is Request/Correction, need to change action to Start, Submit, Approve
            
            PR.Runner_Action__c = 'Start';
            update PR;    
            UpdatePieceStage.updatePieceStage(PR);           
            PR.Runner_Action__c = 'Submit';
            update PR;    
            UpdatePieceStage.updatePieceStage(PR);           
            PR.Runner_Action__c = 'Approve';
            update PR;    
            UpdatePieceStage.updatePieceStage(PR);           
            test.stopTest();
            
        //}
    }    
    static testMethod void myUnitTest4() {
        
        /*Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        UserRole role = [SELECT Id From UserRole WHERE Name = 'Director of Sales'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
            emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
            localesidkey = 'en_US', profileid = pro.Id, 
            timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com',
            UserRoleId = role.Id);
                        
        insert u_testMethodUser;
        
                
        System.runas(u_testMethodUser) {*/
            
            //Set your controller
            UpdatePieceStage controller = new UpdatePieceStage();            
            
            /*Territory_State__c TS = new Territory_State__c();
            TS.DDM__c = userinfo.getUserId();
            TS.Account_Manager__c = userinfo.getUserId();
            TS.Territory_Manager__c = userinfo.getUserId();
            TS.Implementation_Manager__c = userinfo.getUserId();
            TS.Implementation_Specialist__c = userinfo.getUserId();
            TS.Regional__c = userinfo.getUserId();
            
            
            TS.Name = 'TS';
            insert TS;*/
            
            Account A = new Account();
            A.BillingState = 'KS';
            A.Name = 'test';
            A.BillingCity = 'test';
            A.BillingCountry = 'USA';
            A.BillingPostalCode = '66212';
            A.BillingState = 'KS';
            A.BillingStreet = '1234';
                            A.ShippingCity = 'test';
        A.ShippingCountry = 'USA';
        A.ShippingPostalCode = '66212';
        A.ShippingState = 'KS';
        A.ShippingStreet = '1234';
            insert A;
            
            Opportunity O = new Opportunity();
            O.AccountId = A.Id;
            O.Name = 'test';
            O.CloseDate = system.today();
            O.StageName = 'Prospect';
            insert O;
            
            Product2 product = new Product2(
            name = 'test');     
            insert product;
            
            SFDC_520_Quote__c P = new SFDC_520_Quote__c();
            P.Opportunity__c = O.id;
            User thisUser = [select id, Email from User where Id=:userinfo.getuserId()];         
            insert P;
            
            Project_Piece__c PP = new Project_Piece__c();
            PP.Project__c = P.Id;
            PP.Piece_Issue__c = 'test';
            PP.RecordTypeId = '01270000000Q4V0';
            PP.Name = 'PP-Website - landing page-';
            insert PP;
            
            LIST<Project_Runner__c> testPRs = new LIST<Project_Runner__c>();
            
            Project_Runner__c PR = new Project_Runner__c();
            PR.Project_Piece__c = PP.Id;
            PR.Designer__c = Userinfo.getUserId();
            PR.Event_Date_Time__c = system.now();
            PR.Event_End_Date_Time__c = system.now();
            PR.Runner_Action__c = 'Request';
            PR.Runner_Type__c = 'Site';
            insert PR;
            
            test.startTest();
            // original PR action/type is Request/Correction, need to change action to Start, Submit, Approve
            
            PR.Runner_Action__c = 'Start';
            update PR;    
            UpdatePieceStage.updatePieceStage(PR);           
            PR.Runner_Action__c = 'Submit';
            update PR;    
            UpdatePieceStage.updatePieceStage(PR);           
            PR.Runner_Action__c = 'Approve';
            update PR;    
            UpdatePieceStage.updatePieceStage(PR);           
            test.stopTest();
            
        }
    //}        
}