objects/Account.object
<CustomObject>
    <fields>
        <fullName>Territory_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory State</label>
        <referenceTo>Territory_State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Installment__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Installments</relationshipLabel>
        <relationshipName>Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Installment</label>
    <nameField>
        <label>Installment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <label>Implementation Manager</label>
        <picklist>
            <picklistValues>
                <fullName>Matt Bench</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travis Douglas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jennifer Merrick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kandy Richert</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ExpPaidByDealer__c</fullName>
        <formula>IF( PricebookEntry.Product2.ExpPaidByDealer__c , &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ExpPaidByDealer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsTraining__c</fullName>
        <formula>IF( PricebookEntry.Product2.isTraining__c , &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsTraining</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProdProj_Default_Owner__c</fullName>
        <formula>PricebookEntry.Product2.ProdProj_Default_Owner__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProdProj Default Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_Exception__c</fullName>
        <formula>IF( PricebookEntry.Product2.Quantity_Exception__c , &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity Exception</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>requiresWelcomePacket__c</fullName>
        <formula>IF( PricebookEntry.Product2.requiresWelcomePacket__c , &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>requiresWelcomePacket</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ExpPaidByDealer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ExpPaidByDealer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProdProj_Default_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Default Owner of the Product Projects that will be generated for this product. A Project Piece will only be generated for this Product if this field is filled in.</description>
        <inlineHelpText>The Default Owner of the Product Projects that will be generated for this product. A Project Piece will only be generated for this Product if this field is filled in.</inlineHelpText>
        <label>ProdProj Default Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quantity Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isTraining__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isTraining</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>requiresWelcomePacket__c</fullName>
        <defaultValue>false</defaultValue>
        <label>requiresWelcomePacket</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Product_Process__c.object
<CustomObject>
    <fields>
        <fullName>Milestone_1_Stage__c</fullName>
        <label>Milestone 1 Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer&apos;s Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Travel Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing/Shipping/Uploading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Milestone_1__c</fullName>
        <label>Milestone 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_2_Stage__c</fullName>
        <label>Milestone 2 Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer&apos;s Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Travel Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing/Shipping/Uploading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Milestone_2__c</fullName>
        <label>Milestone 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Processes</relationshipLabel>
        <relationshipName>Product_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Process</label>
    <nameField>
        <label>Product Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Milestone_1_Stage__c</fullName>
        <formula>TEXT( Product_Process__r.Milestone_1_Stage__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milestone 1 Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_1__c</fullName>
        <formula>Product_Process__r.Milestone_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milestone 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_2_Stage__c</fullName>
        <formula>TEXT( Product_Process__r.Milestone_2_Stage__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milestone 2 Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_2__c</fullName>
        <formula>Product_Process__r.Milestone_2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milestone 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>look up Product to assign the milestone and stages for the product process</inlineHelpText>
        <label>Product Process</label>
        <referenceTo>Product_Process__c</referenceTo>
        <relationshipLabel>Project Pieces</relationshipLabel>
        <relationshipName>Project_Pieces</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;&amp;Opportunity__r.Implementation_Contact__r.Id,  Opportunity__r.Implementation_Contact__r.FirstName&amp;&quot; &quot;&amp; Opportunity__r.Implementation_Contact__r.LastName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Implementation Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>CRM</fullName>
        <active>false</active>
        <label>CRM</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Territory_State__c.object
<CustomObject>
    <fields>
        <fullName>DDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DDM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States5</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProjectPieceReconciliation_test.cls
@isTest(SeeAllData=True)
private class ProjectPieceReconciliation_test {

    static testMethod void myUnitTest() {
        
        Profile pro = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
        	emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
        	localesidkey = 'en_US', profileid = pro.Id, 
        	timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com');
        	
        insert u_testMethodUser;
        
        System.runas(u_testMethodUser) {
        	
        	//Set your controller
        	//ProjectPieceReconciliation controller = new ProjectPieceReconciliation();
        	
        	test.startTest();
        	
        	//ProjectPieceReconciliation.reconcile();
        	
        	test.stopTest();
        }
    }
    
    public static testmethod void testRec()
  	{
  		
        for(integer i=0;i<2;i++)
        {
  			/*Territory_State__c TS = new Territory_State__c();
            TS.DDM__c = userinfo.getUserId();
            TS.Name = 'TS';
			TS.Implementation_Manager__c = userinfo.getUserId();
        	TS.Implementation_Specialist__c = userinfo.getUserId();            
            insert TS;*/
            
            Account A = new Account();
            A.BillingState = 'KS';
            A.Name = 'test';
            A.AccountNumber = '1234';
            A.ShippingStreet = '1234';
            A.ShippingState = 'TS';
            A.ShippingPostalCode = '66212';
            A.ShippingCountry = 'USA';
            A.ShippingCity = 'test';
            A.BillingCity = 'test';
            A.BillingCountry = 'USA';
            A.BillingPostalCode = '66212';
            A.BillingState = 'KS';
            A.BillingStreet = '1234';
            insert A;
            
            Contact C = new Contact();
            C.FirstName = 'test';
            C.LastName = 'testing';
            C.AccountId = A.Id;
            C.Phone = '9999999999';
            insert C;
            
            string opptyName = 'test';
            if(i==0) opptyName = 'CRM';
            if(i==1) opptyName = 'ILM';
            if(i==2) opptyName = 'Inventory Light';
            if(i==3) opptyName = 'DIY';         
            
            Opportunity O = new Opportunity();
            O.AccountId = A.Id;
            O.Name = opptyName;
            O.CloseDate = system.today();
            O.StageName = 'Prospect';
            insert O;
            
            SFDC_520_Quote__c Proj = new SFDC_520_Quote__c();
            Proj.Name = 'TEST PROJECT';
            Proj.Opportunity__c = O.Id;
            
            insert Proj;
            
            string prodName = 'test';
            if(i==0) prodName = 'CRM';
            if(i==1) prodName = 'ILM';
            if(i==2) prodName = 'Inventory Light';
            if(i==3) prodName = 'DIY';  
            
            Product2 product = new Product2(
            name = prodName);   
            product.Quantity_Exception__c = true;
            product.IsTraining__c = true;
            product.requiresWelcomePacket__c = true;
            product.ExpPaidByDealer__c = true;
            product.ProdProj_Default_Owner__c = userinfo.getUserId();                   
            insert product;
            
            Pricebook2 PB = [select id from Pricebook2 where name = 'Standard Price Book' limit 1];     
            
            PricebookEntry PBE = new PricebookEntry();
            PBE.UnitPrice = 100.00;
            PBE.Pricebook2Id = PB.Id;
            PBE.Product2Id = product.Id;
            PBE.IsActive = true;        
            insert PBE;
            
            Product_Process__c pProc = new Product_Process__c();
            pProc.Product__c = product.Id;
            pProc.Milestone_1__c = 'Test1';
            pProc.Milestone_1_Stage__c = 'Introduction';
            pProc.Milestone_2__c = 'Test3';
            pProc.Milestone_2_Stage__c = 'Printing/Shipping/Uploading';         
            insert pProc;   
            
            OpportunityLineItem OLI = new OpportunityLineItem();
            OLI.PricebookEntryId = PBE.Id;
            OLI.OpportunityId = O.Id;
            OLI.Quantity = 2;
            OLI.TotalPrice = 100.00;
            //insert OLI;
            
            O.Implementation_Contact__c = C.Id;
            O.Deal_Contact__c = C.Id;
            //O.We_Owe__c = 'test';
            //O.Number_of_Installments__c = '1';
            //update O;
            
            O.Inactive_Product_Override__c = true;
            O.StageName = 'Closed or Won';
            //update O;
            
            //if(i==1)
           // {
                //Installment__c Ins = new Installment__c(); //[select id, Paid__c from Installment__c where Opportunity__c =: O.Id order by Installment_Due_Date__c asc limit 1];//new Installment__c();
                //Ins.Opportunity__c = O.id;
                //Ins.OwnerId = '00570000001eX7eAAE';
                //insert Ins;
                
                //Ins.Paid__c = system.today();
                //update Ins;
            //}   
        
        
      
        
        PageReference testStart = Page.ProjectPieceReconciliation;
		Test.setCurrentPage(testStart);
		
		ApexPages.currentPage().getParameters().put('Id', O.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(O);
        
        ProjectPieceReconciliation PPR = new ProjectPieceReconciliation(controller);
       
       
       
       PPR.initList();
       PPR.getOLIs();
       PPR.getPPs();
       
       		//PPR.reconcile();
            
        }
       
  	}
  	
  	public static testmethod void testRec2()
  	{
  		
        for(integer i=2;i<4;i++)
        {
  			/*Territory_State__c TS = new Territory_State__c();
            TS.DDM__c = userinfo.getUserId();
            TS.Name = 'TS';
			TS.Implementation_Manager__c = userinfo.getUserId();
        	TS.Implementation_Specialist__c = userinfo.getUserId();            
            insert TS;*/
            
            Account A = new Account();
            A.BillingState = 'TS';
            A.Name = 'test';
            A.AccountNumber = '1234';
            A.ShippingStreet = '1234';
            A.ShippingState = 'KS';
            A.ShippingPostalCode = '66212';
            A.ShippingCountry = 'USA';
            A.ShippingCity = 'test';
            A.BillingCity = 'test';
            A.BillingCountry = 'USA';
            A.BillingPostalCode = '66212'; 
            A.BillingState = 'KS';
            A.BillingStreet = '1234';
            insert A;
            
            Contact C = new Contact();
            C.FirstName = 'test';
            C.LastName = 'testing';
            C.AccountId = A.Id;
            C.Phone = '9999999999';
            insert C;
            
            string opptyName = 'test';
            if(i==0) opptyName = 'CRM';
            if(i==1) opptyName = 'ILM';
            if(i==2) opptyName = 'Inventory Light';
            if(i==3) opptyName = 'DIY';         
            
            Opportunity O = new Opportunity();
            O.AccountId = A.Id;
            O.Name = opptyName;
            O.CloseDate = system.today();
            O.StageName = 'Prospect';
            insert O;
            
            SFDC_520_Quote__c Proj = new SFDC_520_Quote__c();
            Proj.Name = 'TEST PROJECT';
            Proj.Opportunity__c = O.Id;
            
            insert Proj;
            
            string prodName = 'test';
            if(i==0) prodName = 'CRM';
            if(i==1) prodName = 'ILM';
            if(i==2) prodName = 'Inventory Light';
            if(i==3) prodName = 'DIY';  
            
            Product2 product = new Product2(
            name = prodName);   
            product.Quantity_Exception__c = true;
            product.IsTraining__c = true;
            product.requiresWelcomePacket__c = true;
            product.ExpPaidByDealer__c = true;
            product.ProdProj_Default_Owner__c = userinfo.getUserId();                   
            insert product;
            
            Pricebook2 PB = [select id from Pricebook2 where name = 'Standard Price Book' limit 1];     
            
            PricebookEntry PBE = new PricebookEntry();
            PBE.UnitPrice = 100.00;
            PBE.Pricebook2Id = PB.Id;
            PBE.Product2Id = product.Id;
            PBE.IsActive = true;        
            insert PBE;
            
            Product_Process__c pProc = new Product_Process__c();
            pProc.Product__c = product.Id;
            pProc.Milestone_1__c = 'Test1';
            pProc.Milestone_1_Stage__c = 'Introduction';
            pProc.Milestone_2__c = 'Test3';
            pProc.Milestone_2_Stage__c = 'Printing/Shipping/Uploading';         
            insert pProc;   
            
            OpportunityLineItem OLI = new OpportunityLineItem();
            OLI.PricebookEntryId = PBE.Id;
            OLI.OpportunityId = O.Id;
            OLI.Quantity = 2;
            OLI.TotalPrice = 100.00;
            //insert OLI;
            
            O.Implementation_Contact__c = C.Id;
            O.Deal_Contact__c = C.Id;
           // O.We_Owe__c = 'test';
            //O.Number_of_Installments__c = '1';
            //update O;
            
            O.Inactive_Product_Override__c = true;
            O.StageName = 'Closed or Won';
            //update O;
            
            if(i==3)
            {
                //Installment__c Ins = new Installment__c(); //[select id, Paid__c from Installment__c where Opportunity__c =: O.Id order by Installment_Due_Date__c asc limit 1];//new Installment__c();
                //Ins.Opportunity__c = O.id;
                //Ins.OwnerId = '00570000001eX7eAAE';
                //insert Ins;
                
                //Ins.Paid__c = system.today();
                //update Ins;
	            SFDC_520_Quote__c deleteProject = [select Id, Opportunity__c from SFDC_520_Quote__c where Opportunity__c =: O.Id limit 1];
	            LIST<Project_Piece__c> deletePieces = [select Id, Project__c from Project_Piece__c where Project__c =: deleteProject.Id];
	            
	            delete deletePieces;
	            
            }
                    
	        PageReference testStart = Page.ProjectPieceReconciliation;
			Test.setCurrentPage(testStart);
			
			ApexPages.currentPage().getParameters().put('Id', O.Id);
	        
	        ApexPages.StandardController controller = new ApexPages.StandardController(O);
	        
	        ProjectPieceReconciliation PPR = new ProjectPieceReconciliation(controller);
       
       
       
	       /*PPR.initList();
	       PPR.getOLIs();
	       PPR.getPPs();*/
       
       
            
        }
       
  	}
}