objects/Account.object
<CustomObject>
    <fields>
        <fullName>SVOC_Id__c</fullName>
        <externalId>true</externalId>
        <label>SVOC Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status can only be updated from a first time Closed Won Paid Opportunity and by accounting when a customer cancel services</inlineHelpText>
        <label>Vin Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OOB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Cancelled_Trainings__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cancelled Trainings</relationshipLabel>
        <relationshipName>R00N80000002V4L8EAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Cancelled Trainings</relationshipLabel>
        <relationshipName>Cancelled_Trainings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Train_1_Sale__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Train 1 Sale</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N80000002V4L3EAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cancelled Trainings</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>CT Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancelled Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/POA__c.object
<CustomObject>
    <description>used to handle Plan of Action items for an Account- gives the ability to group support or implementation issues together</description>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup the dealer that the plan of action is needed for</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan of Action(s)</relationshipLabel>
        <relationshipName>POA_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending PM Assignment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Intro Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Needs Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 1 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 2 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 3 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 4 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 5 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 6 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation - LOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failure to Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>POA</label>
    <nameField>
        <label>Plan of Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POAs</pluralLabel>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Cancelled_Trainings_Test.cls
@isTest
private class Cancelled_Trainings_Test {
	
	@isTest static void test_UpdatingPOA() {
		// Implement test code
		Account a = TestData.setupAccount();
		insert a;
		 POA__c poa = TestData.setupPOA(a,'vAuto');
		 insert poa;

		RecordType poaRecordType = StaticData.getInstance().POARecTypesMapByName.get('vAuto');
    

		 User u =  TestData.setupUser('VinSystem Admin', 'Business Analyst');
		 Cancelled_Trainings__c ct = new Cancelled_Trainings__c();
		 ct.Account__c = a.Id;
		 ct.Trainer__c = u.Id;
		 ct.Train_1_Sale__c = false;
		 ct.Reason__c  = 'Testing';

		   List<POA__c> existingPOA = [Select Id from POA__c where Dealer__c =:ct.Account__c and  RecordTypeId =: poaRecordType.Id and status__c != 'Churned'];  
        system.assert(existingPOA != null,'No POA found');
        system.assert(existingPOA.size() > 0,'No POA found');

		 insert ct;
		  ct = [Select Id,POA__c from  Cancelled_Trainings__c where Id =:ct.Id];
		 system.assert(ct.POA__c == poa.Id,'POA is not assigned');
		
		 ct.Train_1_Sale__c = true;
		 update ct;
		 ct = [Select Id,POA__c from  Cancelled_Trainings__c where Id =:ct.Id];
		 system.assert(ct.POA__c == poa.Id,'POA is not assigned');


		 //update with another account with no POA
		Account a1 = TestData.setupAccount();
		a1.SVOC_Id__c  = 'TestData1';
		a1.AccountNumber  = '2';
		insert a1;
		 ct.Account__c = a1.Id;
		 update ct;
		 ct = [Select Id,POA__c from  Cancelled_Trainings__c where Id =:ct.Id];
		 system.assert(ct.POA__c == null,'POA is not removed');

	}

	
}