objects/Account.object
<CustomObject>
    <fields>
        <fullName>VIN_District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Accounts (VIN District)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>VIN_District__c</fullName>
        <formula>Account.VIN_District__r.Name</formula>
        <label>VIN District</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>CRM</fullName>
        <active>false</active>
        <label>CRM</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Welcome_Packet__c.object
<CustomObject>
    <fields>
        <fullName>Packet_Includes__c</fullName>
        <label>Packet Includes</label>
        <picklist>
            <picklistValues>
                <fullName>CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DIY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ILM</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Pick_Your_Packet__c</fullName>
        <label>Pick Your Packet</label>
        <picklist>
            <picklistValues>
                <fullName>ACCOUNT SET UP FORM (Page 1)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACCOUNT SET UP FORM (Page 2)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INVENTORY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THIRD PARTY EXPORTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PREDEFINED EXPORTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS PUSHING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ROUTE ONE / DEALERTRACK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MINIMUM SYSTEM REQUIRMENTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLD DATA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNSOLD (CRM) PROSPECT DATA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STANDARD FORMS REQUEST SHEET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CUSTOM FORMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add User List</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipLabel>Welcome Packets</relationshipLabel>
        <relationshipName>Welcome_Packets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Welcome Packet</label>
    <nameField>
        <label>Welcome Packet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Welcome Packets</pluralLabel>
    <recordTypes>
        <fullName>CRM</fullName>
        <active>true</active>
        <label>CRM</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Welcome_Packet_User__c.object
<CustomObject>
    <description>Used for storing the user list created by the dealer</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Welcome_Packet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Welcome Packet</label>
        <referenceTo>Welcome_Packet__c</referenceTo>
        <relationshipLabel>Welcome Packet Users</relationshipLabel>
        <relationshipName>WelcomePacketUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Welcome Packet User</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Welcome Packet Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WelcomePacketUser_test.cls
@isTest(SeeAllData=True)
private class WelcomePacketUser_test {

    static testMethod void myUnitTest() {
        
        Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
  		Account a = [select Id from Account where VIN_District__c != null limit 1];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
        	emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
        	localesidkey = 'en_US', profileid = pro.Id, 
        	timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com');
        	
        insert u_testMethodUser;
        
        System.runas(u_testMethodUser) {
        	
        	
        	Welcome_Packet__c W = new Welcome_Packet__c();
	        W.name = 'test';
	        W.Packet_Includes__c = 'CRM';        
	        W.OwnerId = userinfo.getuserid();
	        insert W;
	        
	        PageReference testStart = Page.Welcome_Packet_User;
			Test.setCurrentPage(testStart);
			
			ApexPages.currentPage().getParameters().put('ParentId', W.Id);
	        
	        
	        WelcomePacketUser WPW = new WelcomePacketUser();
	        
	        WPW.getUser();
	        WPW.saveUserListComplete();
	        
	        
	        Welcome_Packet_User__c newUser = new Welcome_Packet_User__c();
	        newUser.Name = 'test';
	        newUser.First_Name__c = 'testing';
	        
	        WPW.user.add(newUser);        
	        
	        WPW.addrow();        
	        WPW.addrow();
	        WPW.save();
	        WPW.goBack();
	        WPW.Skip();
	        
	        
	        W.Packet_Includes__c = 'ILM';
	        update W;
	        WPW.goBack();
	        
	        W.Packet_Includes__c = 'DIY';
	        update W;
	        WPW.goBack();
	        
	       	W.Packet_Includes__c=null;
	       	W.Pick_Your_Packet__c = 'CUSTOM FORMS';
	       	update W;
	       	WPW.goBack();
			
			W.Pick_Your_Packet__c = 'ILM CRM Inventory User Access';
			update W;
	       	WPW.goBack();
	       	
			W.Pick_Your_Packet__c = 'STANDARD FORMS REQUEST SHEET';
			update W;
	       	WPW.goBack();
	       	
			W.Pick_Your_Packet__c = 'UNSOLD (CRM) PROSPECT DATA';
			update W;
	       	WPW.goBack();
	       	
			W.Pick_Your_Packet__c = 'SOLD DATA';
			update W;
	       	WPW.goBack();
	       	
			W.Pick_Your_Packet__c = 'MINIMUM SYSTEM REQUIRMENTS';
			update W;
	       	WPW.goBack();
	       	
			W.Pick_Your_Packet__c = 'ROUTE ONE / DEALERTRACK';
			update W;
	       	WPW.goBack();
	       	
			W.Pick_Your_Packet__c = 'DMS PUSHING';
			update W;
	       	WPW.goBack();
	       	
			W.Pick_Your_Packet__c = 'PREDEFINED EXPORTS';
			update W;
	       	WPW.goBack();
	       	
			W.Pick_Your_Packet__c = 'THIRD PARTY EXPORTS';
			update W;
	       	WPW.goBack();
	       	
			W.Pick_Your_Packet__c = 'INVENTORY';
			update W;
	       	WPW.goBack();
	       	
			W.Pick_Your_Packet__c = 'ACCOUNT SET UP FORM (Page 2)';
			update W;
	       	WPW.goBack();
	       	
			W.Pick_Your_Packet__c = 'ACCOUNT SET UP FORM (Page 1)';
	        update W;
	       	WPW.goBack();
	       	
	       	W.Pick_Your_Packet__c = 'test';
	       	update W;
	       	WPW.goBack();  
	       	
	       	Opportunity O = new Opportunity();
	       	O.AccountId=a.id;
	       	O.Name = 'test';
	       	O.StageName = 'test';
	       	O.CloseDate = system.today();
	       	insert O;
	       
	       	SFDC_520_Quote__c project = new SFDC_520_Quote__c();
	       	project.Opportunity__c = O.Id;
			project.Name = 'test';
			insert project;
			
			W.Project__c = project.Id;
			update W;
			WPW.Skip();      
	        
	        W.Packet_Includes__c = null;
	        W.Pick_Your_Packet__c = null;
	        update W;
	        WPW.goBack();
	        
	        
	        
        	
        	
        	
        	test.startTest();
        	
        	
        	
        	test.stopTest();
        }
    }
}