objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <formula>VinPro2__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vin PM Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory State</label>
        <referenceTo>Territory_State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is updated by a trigger when the Case Runner assign is used to assign a user to an escalated Case</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Escalation_Type__c</fullName>
        <label>Escalation Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Third_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Third Party</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Third Party Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X1_What_is_happening__c</fullName>
        <inlineHelpText>Why do you believe there&apos;s a bug/defect?</inlineHelpText>
        <label>1) What is happening &amp; how to replicate?</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X2_What_did_you_expect_to_happen__c</fullName>
        <inlineHelpText>Indicate the proper functionality and NOT just the opposite of Question #1</inlineHelpText>
        <label>2) What is normally expected to happen?</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X3_When_did_it_start_happening__c</fullName>
        <label>3) When did it  start happening?</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X4_What_do_you_think_the_problem_is__c</fullName>
        <inlineHelpText>What type of problem do you think this is? and what data are you  basing this on? (EXAMPLE: &quot;This may be related to IE as it appears to only be an issue while using IE&quot;)</inlineHelpText>
        <label>4) What do you think the problem is?</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X5_What_have_you_tried_so_far__c</fullName>
        <inlineHelpText>Where have you looked and what have you tried in order to fix/workaround the issue and what did/didn&apos;t work?</inlineHelpText>
        <label>5) What have you tried so far?</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>VS Cases</businessProcess>
        <label>Support</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Runner__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Runners</relationshipLabel>
        <relationshipName>Case_Runners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Escalated_To__c</fullName>
        <label>Escalated To</label>
        <picklist>
            <picklistValues>
                <fullName>App Request Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Extract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhancement Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export Setup Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gatekeeper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Questions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Support Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - Creative Requests</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - Paid Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - Tech Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jira Request Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L1-Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Creative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-CRM Admin/Settings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Desking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Escalations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Exports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Forms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Phone System(PBX)</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Escalation_Type__c</fullName>
        <label>Escalation Type</label>
        <picklist>
            <controllingField>Escalated_To__c</controllingField>
            <picklistValues>
                <fullName>2014 Rebuild Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd Party Integrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad Copy Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad Disapprovals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADP3PA Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdWords Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analytic Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analytics Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Astera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavorial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broken UA Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Tracking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Tracking Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change/Update Existing Forms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chrysler PAP Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Requirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Prospects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current Campaign Modifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Import Problem / Customer Data Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Asset Updates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Creative Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Sites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Questions</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Runner_Action__c</fullName>
        <label>Runner Action</label>
        <picklist>
            <picklistValues>
                <fullName>Additional Information Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Dev Work to Do</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Post</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redirect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolve/Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved from Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitting Additional Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresolved</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Runner</label>
    <nameField>
        <displayFormat>CR-{YYYY}{MM}-{0}</displayFormat>
        <label>Case Runner Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Runners</pluralLabel>
    <recordTypes>
        <fullName>Assign</fullName>
        <active>true</active>
        <description>case runner used for assigning cases</description>
        <label>Assign</label>
    </recordTypes>
    <recordTypes>
        <fullName>Escalate</fullName>
        <active>true</active>
        <description>case runner used for escalating cases</description>
        <label>Escalate</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Territory_State__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DDM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateCaseStage_test.cls
@isTest(SeeAllData=True)
private class UpdateCaseStage_test {

    static testMethod void myUnitTest() {
        
        Profile pro = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
        	emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
        	localesidkey = 'en_US', profileid = pro.Id, 
        	timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com');
        	
        insert u_testMethodUser;
        
        System.runas(u_testMethodUser) {
        	
        	//Set your controller
        	UpdateCaseStage controller = new UpdateCaseStage();
        	
        	test.startTest();
        	
        	
        	
        	test.stopTest();
        }
    }
    
    
    public static testmethod void testUpdateCaseStage()
	{
		/*Territory_State__c TS = new Territory_State__c();
		TS.DDM__c = userinfo.getUserId();
		TS.Account_Manager__c = userinfo.getUserId();
		TS.Territory_Manager__c = userinfo.getUserId();
		TS.Implementation_Manager__c = userinfo.getUserId();
        TS.Implementation_Specialist__c = userinfo.getUserId();
		TS.Regional__c = userinfo.getUserId();
		
		TS.Name = 'TS';
		insert TS;*/
		
		Account A = new Account();
		A.BillingState = 'KS';
		A.Name = 'test';
		A.BillingCity = 'test';
        A.BillingCountry = 'USA';
        A.BillingPostalCode = '66212';
        A.BillingState = 'KS';
        A.BillingStreet = '1234';
        		A.ShippingCity = 'test';
        A.ShippingCountry = 'USA';
        A.ShippingPostalCode = '66212';
        A.ShippingState = 'KS';
        A.ShippingStreet = '1234';
		insert A;
		
		Contact newContact = new Contact();
		newContact.AccountId = A.Id;
		newContact.LastName = 'test';
		newContact.FirstName = 'firstname';
		newContact.Phone = '9999999999';
		insert newContact;
		
		Case C = new Case();
		
		C.AccountId = A.Id;
		C.Contact = newContact;
		C.Origin = 'Phone';
		C.Reason = 'Billing';
		C.X1_What_is_happening__c = 'TEST TEST TEST TEST TEST';
		C.X2_What_did_you_expect_to_happen__c = 'TEST TEST TEST TEST TEST';
		C.X3_When_did_it_start_happening__c = 'TEST TEST TEST TEST TEST';
		C.X4_What_do_you_think_the_problem_is__c = 'TEST TEST TEST TEST TEST';
		C.X5_What_have_you_tried_so_far__c = 'TEST TEST TEST TEST TEST';
		C.Third_Party__c = A.Id;
		insert C;
		
		Case_Runner__c CR = new Case_Runner__c();
		CR.Case__c = C.Id;
		CR.Escalated_To__c = 'Client Issues';
		CR.Escalation_Type__c = 'General Questions';
		Cr.Runner_Action__c = 'Comment';
		
		insert CR;
		
		CR.Escalated_To__c = 'DMS';
		update CR;
		//Cr.Escalated_To__c = 'Development';
		//update CR;
		//CR.Escalated_To__c = 'DDM';
		
		Case_Runner__c CR2 = new Case_Runner__c();
		CR2.Case__c = C.Id;
		CR.Runner_Action__c = 'Assign';
		CR.Assigned_To__c = userinfo.getUserId();
		insert CR2;		
		
		Case_Runner__c CR3 = new Case_Runner__c();
		CR3.Case__c = C.Id;
		CR3.Runner_Action__c = 'Resolved';
		CR3.Defect_Id__c = 'TEST';
		CR3.Feature_Request_Id__c = 'TEST';
		insert CR3;
		
		Case_Runner__c CR4 = new Case_Runner__c();
		CR4.Case__c = C.Id;
		CR4.Runner_Action__c = 'Unresolved';
		insert CR4;
		
		/*
		Case_Runner__c CR5 = new Case_Runner__c();
		CR5.Case__c = C.Id;
		CR5.Runner_Action__c = 'NMP';
		insert CR5;
		*/
		
		Case_Runner__c CR6 = new Case_Runner__c();
		CR6.Case__c = C.Id;
		CR6.Runner_Action__c = 'Escalate';
		CR6.Escalated_To__c = 'Exports';
		//insert CR6;
	}
	
	public static testmethod void testUpdateCaseStage2()
	{
		/*Territory_State__c TS = new Territory_State__c();
		TS.DDM__c = userinfo.getUserId();
		TS.Account_Manager__c = userinfo.getUserId();
		TS.Territory_Manager__c = userinfo.getUserId();
		TS.Implementation_Manager__c = userinfo.getUserId();
        TS.Implementation_Specialist__c = userinfo.getUserId();
		TS.Regional__c = userinfo.getUserId();
		
		TS.Name = 'TS';
		insert TS;*/
		
		Account A = new Account();
		A.BillingState = 'KS';
		A.Name = 'test';
		A.BillingCity = 'test';
        A.BillingCountry = 'USA';
        A.BillingPostalCode = '66212';
        A.BillingState = 'KS';
        A.BillingStreet = '1234';
                		A.ShippingCity = 'test';
        A.ShippingCountry = 'USA';
        A.ShippingPostalCode = '66212';
        A.ShippingState = 'KS';
        A.ShippingStreet = '1234';
		insert A;
		
		Contact newContact = new Contact();
		newContact.AccountId = A.Id;
		newContact.LastName = 'test';
		newContact.FirstName = 'firstname';
		newContact.Phone = '9999999999';
		insert newContact;
		
		Case C = new Case();
		
		C.AccountId = A.Id;
		C.Contact = newContact;
		C.Origin = 'Phone';
		C.Reason = 'Billing';
		C.X1_What_is_happening__c = 'TEST TEST TEST TEST TEST';
		C.X2_What_did_you_expect_to_happen__c = 'TEST TEST TEST TEST TEST';
		C.X3_When_did_it_start_happening__c = 'TEST TEST TEST TEST TEST';
		C.X4_What_do_you_think_the_problem_is__c = 'TEST TEST TEST TEST TEST';
		C.X5_What_have_you_tried_so_far__c = 'TEST TEST TEST TEST TEST';
		C.Third_Party__c = A.Id;
		insert C;
		
		Case_Runner__c CR = new Case_Runner__c();
		CR.Case__c = C.Id;
		CR.Escalated_To__c = 'Client Issues';
		CR.Escalation_Type__c = 'General Questions';
		Cr.Runner_Action__c = 'Issue Rejected';
		insert CR;
		
		CR.Escalated_To__c = 'DMS';
		update CR;
		//Cr.Escalated_To__c = 'Development';
		//update CR;
		CR.Escalated_To__c = 'DDM';
		
		
		//Procore - adding list to handle bulk dml 
		List<Case_Runner__c> insertCaseRunners = new List<Case_Runner__c>();
		
		Case_Runner__c CR7 = new Case_Runner__c();
		CR7.Case__c = C.Id;
		CR7.Runner_Action__c = 'Escalate';
		//CR7.Escalated_To__c = 'DDM';
		CR7.Escalated_To__c = 'Level 3 Support';
		//insert CR7;
		insertCaseRunners.add(CR7);
		
		Case_Runner__c CR8 = new Case_Runner__c();
		CR8.Case__c = C.Id;
		CR8.Runner_Action__c = 'Issue Rejected';
		CR8.Escalated_To__c = 'L2';
		//insert CR8;
		//insertCaseRunners.add(CR8);
		
		Case_Runner__c CR9 = new Case_Runner__c();
		CR9.Case__c = C.Id;
		CR9.Runner_Action__c = 'Additional Information Needed';
		//insert CR9;
		//insertCaseRunners.add(CR9);
		
		Case_Runner__c CR10 = new Case_Runner__c();
		CR10.Case__c = C.Id;
		CR10.Runner_Action__c = 'Submitting Additional Information';
		//insert CR10;
		//insertCaseRunners.add(CR10);
		
		Case_Runner__c CR11 = new Case_Runner__c();
		CR11.Case__c = C.Id;
		CR11.Runner_Action__c = 'Issue Rejected';
		//insert CR11;
		//insertCaseRunners.add(CR11);
		
		Case_Runner__c CR12 = new Case_Runner__c();
		CR12.Case__c = C.Id;
		CR12.Runner_Action__c = 'Resolved';
		CR12.RecordTypeId = '012700000005eL7';
		CR12.Case_Description__c = 'TEST';
		CR12.Defect_Id__c = 'TEST';
		CR12.Assigned_To__c = Userinfo.getUserId();
		//insert CR12;
		//insertCaseRunners.add(CR12);
		
		insert insertCaseRunners;
		
	}
	
}