objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <formula>VinPro2__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vin PM Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory State</label>
        <referenceTo>Territory_State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VS_Dealer_ID__c</fullName>
        <inlineHelpText>CAN BE DELETED when this is no longer referenced. This is an admin used in test code and batch jobs</inlineHelpText>
        <label>VS Dealer ID DONOTUSE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the primary contact associated with the Opportunity</inlineHelpText>
        <label>Deal Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Deal Contact)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>look up the contact under the Salesforce account that Implementation will contact regarding the setup of the products purchased</inlineHelpText>
        <label>Implementation Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Implementation Contact)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <label>Implementation Manager</label>
        <picklist>
            <picklistValues>
                <fullName>Matt Bench</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travis Douglas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jennifer Merrick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kandy Richert</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Installments__c</fullName>
        <label>Number of Installments</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Territory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>We_Owe__c</fullName>
        <inlineHelpText>Notes added to this field will automatically populate to the project when the sale is approved</inlineHelpText>
        <label>Implementation Notes</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ExpPaidByDealer__c</fullName>
        <formula>IF( PricebookEntry.Product2.ExpPaidByDealer__c , &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ExpPaidByDealer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsTraining__c</fullName>
        <formula>IF( PricebookEntry.Product2.isTraining__c , &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsTraining</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProdProj_Default_Owner__c</fullName>
        <formula>PricebookEntry.Product2.ProdProj_Default_Owner__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProdProj Default Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_Exception__c</fullName>
        <formula>IF( PricebookEntry.Product2.Quantity_Exception__c , &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity Exception</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>requiresWelcomePacket__c</fullName>
        <formula>IF( PricebookEntry.Product2.requiresWelcomePacket__c , &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>requiresWelcomePacket</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ExpPaidByDealer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ExpPaidByDealer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProdProj_Default_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Default Owner of the Product Projects that will be generated for this product. A Project Piece will only be generated for this Product if this field is filled in.</description>
        <inlineHelpText>The Default Owner of the Product Projects that will be generated for this product. A Project Piece will only be generated for this Product if this field is filled in.</inlineHelpText>
        <label>ProdProj Default Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quantity Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isTraining__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isTraining</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>requiresWelcomePacket__c</fullName>
        <defaultValue>false</defaultValue>
        <label>requiresWelcomePacket</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Product_Process__c.object
<CustomObject>
    <fields>
        <fullName>Milestone_1_Stage__c</fullName>
        <label>Milestone 1 Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer&apos;s Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Travel Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing/Shipping/Uploading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Milestone_1__c</fullName>
        <label>Milestone 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_2__c</fullName>
        <label>Milestone 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Processes</relationshipLabel>
        <relationshipName>Product_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Process</label>
    <nameField>
        <label>Product Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory_State__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DDM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityPopupController_TEST.cls
@isTest(SeeAllData=True)
private class OpportunityPopupController_TEST {

    static testMethod void OpportunityPopupController_TestMethod() {
        // TO DO: implement unit test
        
        
                /*Territory_State__c TS = new Territory_State__c();
                TS.DDM__c = userinfo.getUserId();
                TS.Account_Manager__c = userinfo.getUserId();
                TS.Territory_Manager__c = userinfo.getUserId();
                TS.Implementation_Manager__c = userinfo.getUserId();
       			TS.Implementation_Specialist__c = userinfo.getUserId();
                TS.Regional__c = userinfo.getUserId();
                
                TS.Name = 'TS';
                insert TS;*/
                
                Account A = new Account();
                A.BillingState = 'KS';
                A.BillingCity = 'Test City';
                A.BillingStreet = '123 Test'; 
                A.BillingPostalCode = '12345'; 
                A.BillingCountry = 'USA';
                A.ShippingStreet = '123 Test';
                A.ShippingState = 'KS';
                A.ShippingPostalCode = '12345';
                A.ShippingCountry = 'USA';
                A.ShippingCity = 'Test City';
                A.Name = 'test';
                A.VS_Dealer_ID__c = 1234;
                A.AccountNumber = '1234';
                insert A;
                
                Contact C = new Contact();
                C.FirstName = 'Testfirst';
                C.LastName = 'Testlast';
                C.Account = A;
                C.Phone = '9999999999';
                insert C;
                
                Opportunity O = new Opportunity();
                O.AccountId = A.Id;
                O.Name = 'test';
                O.CloseDate = system.today();
                O.Deal_Contact__c = C.Id;
                O.StageName = 'Prospect';
                O.Implementation_Contact__c = C.id;
                //O.We_Owe__c = 'test we owe';
                O.Number_of_Installments__c = '1';
                O.Amount = 1000;
                
                insert O;
                
                OpportunityLineItem OLI1 = new OpportunityLineItem(); 
                
                Product2 product = new Product2(
		        name = 'TEST');   
		        product.Quantity_Exception__c = true;
		        product.IsTraining__c = true;
		        product.requiresWelcomePacket__c = true;
		        product.ExpPaidByDealer__c = true;
		        product.ProdProj_Default_Owner__c = userinfo.getUserId();                   
		        insert product;
            
		        /*Pricebook2 PB = [select id from Pricebook2 where name = 'Standard Price Book'];     
		        
		        PricebookEntry PBE = new PricebookEntry();
		        PBE.UnitPrice = 100.00;
		        PBE.Pricebook2Id = PB.Id;
		        PBE.Product2Id = product.Id;
		        PBE.IsActive = true;        
		        insert PBE;*/
		        
		        Product_Process__c pProc = new Product_Process__c();
		        pProc.Product__c = product.Id;
		        pProc.Milestone_1__c = 'Test1';
		        pProc.Milestone_1_Stage__c = 'Introduction';
		        pProc.Milestone_2__c = 'Test3';
		        pProc.Milestone_2_Stage__c = 'Printing/Shipping/Uploading';         
		        insert pProc;   
		        
		        /*OpportunityLineItem OLI = new OpportunityLineItem();
		        OLI.PricebookEntryId = PBE.Id;
		        OLI.OpportunityId = O.Id;
		        OLI.Quantity = 2;
		        OLI.TotalPrice = 100.00;
		        insert OLI;*/
        
                PageReference pageRef = Page.OpportunityPopupPage;
                pageRef.getParameters().put('id', O.Id);
                ApexPages.currentPage().getParameters().put('id', O.Id);
                Test.setCurrentPage(pageRef);
                
                ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(O);
                OpportunityPopupController OPC = new OpportunityPopupController(controller);
                
                
                OPC.Id = O.Id;
                OPC.setThisOpp();
                OPC.updateOppToNoShow();
                OPC.setId();
                OPC.getId();
                OPC.getThisAccount();
                OPC.getOppStatus();
                OPC.setShowPopupDataIntegration();
                OPC.getShowPopupDateIntegration();
                OPC.getShowPopupInactiveProducts();
                OPC.getThisOpp();
                
                
                
                
    }
    
    public static testMethod void testOppPopupController() {
                
    	/*Territory_State__c TS = new Territory_State__c();
        TS.DDM__c = userinfo.getUserId();
        TS.Account_Manager__c = userinfo.getUserId();
        TS.Territory_Manager__c = userinfo.getUserId();
        TS.Implementation_Manager__c = userinfo.getUserId();
   		TS.Implementation_Specialist__c = userinfo.getUserId();
        TS.Regional__c = userinfo.getUserId();
            
        TS.Name = 'TS';
        insert TS;*/
            
		Account A = new Account();
        A.BillingState = 'KS';
        A.BillingCity = 'Test City';
        A.BillingStreet = '123 Test'; 
        A.BillingPostalCode = '12345'; 
        A.BillingCountry = 'USA';
        A.ShippingStreet = '123 Test';
        A.ShippingState = 'KS';
        A.ShippingPostalCode = '12345';
        A.ShippingCountry = 'USA';
        A.ShippingCity = 'Test City';
        A.Name = 'test';
        A.VS_Dealer_ID__c = 1234;
        A.AccountNumber = '1234';
        insert A;
            
        Contact C = new Contact();
        C.FirstName = 'Testfirst';
        C.LastName = 'Testlast';
        C.Account = A;
        C.Phone = '9999999999';
        insert C;
            
        Opportunity O = new Opportunity();
        O.AccountId = A.Id;
        O.Name = 'test';
        O.CloseDate = system.today();
        O.Deal_Contact__c = C.Id;
        O.StageName = 'Prospect';
        O.Implementation_Contact__c = C.id;
        //O.We_Owe__c = 'test we owe';
        O.Number_of_Installments__c = '1';
        O.Amount = 1000;
        
        insert O;
            
        OpportunityLineItem OLI1 = new OpportunityLineItem(); 
            
        Product2 product = new Product2(name = 'TEST');   
        product.Quantity_Exception__c = true;
        product.IsTraining__c = true;
        product.requiresWelcomePacket__c = true;
        product.ExpPaidByDealer__c = true;
        product.ProdProj_Default_Owner__c = userinfo.getUserId();                   
     	insert product;
            
        Pricebook2 PB = [select id from Pricebook2 where name = 'Standard Price Book' limit 1];     
        
        PricebookEntry PBE = new PricebookEntry();
        PBE.UnitPrice = 100.00;
        PBE.Pricebook2Id = PB.Id;
        PBE.Product2Id = product.Id;
        PBE.IsActive = true;        
        insert PBE;
        
        Product_Process__c pProc = new Product_Process__c();
        pProc.Product__c = product.Id;
        pProc.Milestone_1__c = 'Test1';
        pProc.Milestone_1_Stage__c = 'Introduction';
        pProc.Milestone_2__c = 'Test3';
        pProc.Milestone_2_Stage__c = 'Printing/Shipping/Uploading';         
        insert pProc;   
        
        OpportunityLineItem OLI = new OpportunityLineItem();
        OLI.PricebookEntryId = PBE.Id;
        OLI.OpportunityId = O.Id;
        OLI.Quantity = 2;
        OLI.TotalPrice = 100.00;
        insert OLI;
        
                
                
        ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(O);
        OpportunityPopupController OPC = new OpportunityPopupController(controller);
        OPC.Id = O.Id;
        OPC.setThisOpp();
        
        
        
        PageReference pageRef = Page.OpportunityPopupPage;
        pageRef.getParameters().put('id', O.Id);
        ApexPages.currentPage().getParameters().put('id', O.Id);
        Test.setCurrentPage(pageRef);
    }
}