objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <formula>VinPro2__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vin PM Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory State</label>
        <referenceTo>Territory_State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup the Project this Case is related to</inlineHelpText>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Create</fullName>
        <active>true</active>
        <businessProcess>VS Cases</businessProcess>
        <description>used when creating a Case</description>
        <label>Create</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Installment__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Contact__c</fullName>
        <formula>Opportunity__r.Deal_Contact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deal Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Installments</relationshipLabel>
        <relationshipName>Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Installment</label>
    <nameField>
        <label>Installment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the primary contact associated with the Opportunity</inlineHelpText>
        <label>Deal Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Deal Contact)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>look up the contact under the Salesforce account that Implementation will contact regarding the setup of the products purchased</inlineHelpText>
        <label>Implementation Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Implementation Contact)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <label>Implementation Manager</label>
        <picklist>
            <picklistValues>
                <fullName>Matt Bench</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travis Douglas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jennifer Merrick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kandy Richert</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Multi_Installments_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Multi-Installments Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Installments__c</fullName>
        <label>Number of Installments</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the user that initiated the opportunity: fishing pole, PM, etc</inlineHelpText>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>We_Owe__c</fullName>
        <inlineHelpText>Notes added to this field will automatically populate to the project when the sale is approved</inlineHelpText>
        <label>Implementation Notes</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ActualDescription__c</fullName>
        <label>ActualDescription</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProdProj_Default_Owner__c</fullName>
        <formula>PricebookEntry.Product2.ProdProj_Default_Owner__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProdProj Default Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProdProj_Default_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Default Owner of the Product Projects that will be generated for this product. A Project Piece will only be generated for this Product if this field is filled in.</description>
        <inlineHelpText>The Default Owner of the Product Projects that will be generated for this product. A Project Piece will only be generated for this Product if this field is filled in.</inlineHelpText>
        <label>ProdProj Default Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product relation required to Close Won an opportunity</inlineHelpText>
        <label>Related Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Related Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Piece_Issue__c</fullName>
        <inlineHelpText>Auto-populated from Products sold when Opportunity marked PAID</inlineHelpText>
        <label>Piece Issue</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <formula>Project__r.Team_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Team Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>We_Owe__c</fullName>
        <formula>Project__r.We_Owe__c</formula>
        <inlineHelpText>This is auto-populated from the Opportunity&gt;Project&gt;Project Pieces</inlineHelpText>
        <label>Implementation Notes</label>
        <type>Text</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <description>Vin_Performance_Manager__r.User_Full_Name__c</description>
        <formula>Vin_Performance_Manager__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Vin_Performance_Manager__r.User_Full_Name__c</inlineHelpText>
        <label>Vin PM (formula)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Packet_Sent__c</fullName>
        <label>Date Packet Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;&amp;Opportunity__r.Implementation_Contact__r.Id,  Opportunity__r.Implementation_Contact__r.FirstName&amp;&quot; &quot;&amp; Opportunity__r.Implementation_Contact__r.LastName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Implementation Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <inlineHelpText>updated by a trigger that looks at the Team Name assigned in the owner&apos;s user profile and updates the team name to this field for reporting</inlineHelpText>
        <label>Team Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Training_Included__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Training Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>We_Owe__c</fullName>
        <formula>Opportunity__r.We_Owe__c</formula>
        <inlineHelpText>this field is auto-populated from the Opportunity</inlineHelpText>
        <label>Implementation Notes</label>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Implementation</fullName>
        <active>true</active>
        <label>Basic Implementation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Territory_State__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DDM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Team_Name__c</fullName>
        <inlineHelpText>used for Sales and Implementation for reporting</inlineHelpText>
        <label>Team Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/handler_ProjectTrigger_test.cls
@isTest(SeeAllData=True)
private class handler_ProjectTrigger_test {

    static testMethod void myUnitTest() {
        
        Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
            emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
            localesidkey = 'en_US', profileid = pro.Id, 
            timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com', Team_Name__c = 'Test Name');
            
        insert u_testMethodUser;
        
        User u_testMethodUser2 = new User(alias = 'testMet2', email = 'testMetho2dUser@salesforce.com',
            emailencodingkey = 'UTF-8', lastname = 'Test Method User2', languagelocalekey = 'en_US',
            localesidkey = 'en_US', profileid = pro.Id, 
            timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser2@salesforce.com', Team_Name__c = 'Test Name2');
        
        insert u_testMethodUser2;
        
        System.runas(u_testMethodUser) {
            
            //Set your controller
            handler_ProjectTrigger controller = new handler_ProjectTrigger();
            
            /*Territory_State__c TS = new Territory_State__c();
            TS.Name = 'XX';
            TS.Account_Manager__c = userinfo.getUserId();
            TS.DDM__c = userinfo.getUserId();
            TS.Regional__c = userinfo.getUserId();
            TS.Implementation_Manager__c = userinfo.getUserId();
            TS.Implementation_Specialist__c = userinfo.getUserId();     
            insert TS;*/
            
            Account A = new Account();
            A.ShippingCity='test';
            A.ShippingStreet='test';
            A.ShippingState='XX';
            A.ShippingPostalCode='test';
            A.BillingState = 'XX';
            A.AccountNumber = '1';
            A.BillingCity = 'test';
            A.BillingCountry = 'USA';
            A.BillingPostalCode = '66212';
            A.BillingState = 'KS';
            A.BillingStreet = '1234';
            
            A.name = 'TestAccount';
            insert A;
            
            A.Type = 'Prospect';
            
            update A;
            string AcctId = A.Id;
            
            Contact Ctc = new Contact();
            Ctc.AccountId = A.Id;
            Ctc.FirstName = 'test';
            Ctc.LastName = 'test';
                
            insert Ctc;
            
            
            Opportunity O  = new Opportunity();
            O.AccountId = AcctId; //set the required fields
            O.Name = 'test';
            O.Deal_Contact__c = Ctc.id;
            O.CloseDate = System.today()+5;
            O.StageName = 'Prospect';
            O.Type = 'New Business';
            O.Salesperson__c = userinfo.getUserId();
            O.Implementation_Contact__c = Ctc.id;
            //O.We_Owe__c = 'N/A'; 
            
            insert O; //save it to SFDC (it will rollback after your test
            O.Multi_Installments_Approved__c=true;
            O.Number_of_Installments__c = '3';
            O.Amount= 1200;
            update O; //THIS WILL FIRE YOUR UPDATE TRIGGER, and make sure it's included in the test
            O.Amount = 1500;
            OpportunityClass.UpdateInvoiceInformation(O);
            update O;
        	Product2 product = [select Id, Related_Product__c,ProdProj_Default_Owner__c, isActive from Product2 where isActive = true AND (Related_Product__c = null OR Related_Product__c = '') limit 1];            

        	PricebookEntry PBE = [select id, Product2Id, Pricebook2Id, IsActive, UnitPrice, UseStandardPrice from PricebookEntry where IsActive = true AND Product2Id =: product.Id limit 1];
                      
        	OpportunityLineItem OLI = new OpportunityLineItem();
        	OLI.PricebookEntryId = PBE.Id;
        	OLI.Quantity = 1;       
        	OLI.ActualDescription__c = 'website';
        	OLI.OpportunityId = O.id;       
        	OLI.TotalPrice = 1000.00;       
        	insert OLI;            
            
            //Project
            SFDC_520_Quote__c prj = new SFDC_520_Quote__c();
            prj.Opportunity__c = O.Id;
            prj.Date_Packet_Sent__c = null;
            prj.RecordTypeId = '012700000005dgP';//implementation
            prj.Training_Included__c = TRUE;
            prj.OwnerId = u_testMethodUser.Id;  
            
            insert prj;
            
            Project_Piece__c PP = new Project_Piece__c();
            PP.Project__c = prj.Id;
            PP.Piece_Issue__c = 'TestPiece - Sticker';
            PP.Name = 'PP-Inventory Module-LYNNTEST';
            PP.Project_Piece_Stage__c = 'Introduction';
            insert PP;
            
            PP.Name ='PP-ILM Implementation-LYNNTEST';     
            update PP;      
             
            PP.Name ='PP-Launch Coordinator-LYNNTEST';     
            update PP;  
            
            PP.Name ='PP-Text messages-LYNNTEST';     
            update PP; 
                                       
            test.startTest();
            product.ProdProj_Default_Owner__c = '00570000001es9g';
            system.debug('TEST Project Owner change');
			update product;                              
            prj.OwnerID = '00570000001es9g';
            update prj;
            

            //Could not create a perfect storm to test updateProjectMilestoneNA 
			//Installments
			//Adding installment to get updateProjectMilestoneNA to run
			//Installment__c I = new Installment__c();
			//I.Opportunity__c = O.id;
			//I.Confirmed__c	= true;	
			//I.Paid__c = system.today();	
			//insert I;		
            //O.RecordTypeId = '01270000000Q9Me';
            //O.StageName = 'Closed or Won';          
            //update O;            
            //system.debug('TEST updateProjectMilestoneNA');
			

            // add a delete case
            delete PP;
            delete prj;
            
            
            u_testMethodUser.Team_Name__c = 'Name Name';
            update u_testMethodUser;
  
       
            test.stopTest();
        }
    }

}