objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <formula>VinPro2__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vin PM Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Date__c</fullName>
        <inlineHelpText>last time the customer had a product implemented (CRM, ILM, DIY, Website) - equals the Confirmed Training Start Date</inlineHelpText>
        <label>Implementation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Territory_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory State</label>
        <referenceTo>Territory_State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the primary contact associated with the Opportunity</inlineHelpText>
        <label>Deal Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Deal Contact)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Approval_Status__c</fullName>
        <inlineHelpText>Updated by approval processes for each area of approval.</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Leadership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Leadership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Implementation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>look up the contact under the Salesforce account that Implementation will contact regarding the setup of the products purchased</inlineHelpText>
        <label>Implementation Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Implementation Contact)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <label>Implementation Manager</label>
        <picklist>
            <picklistValues>
                <fullName>Matt Bench</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travis Douglas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jennifer Merrick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kandy Richert</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you DO NOT want this opportunity to create a Project when marked paid.</inlineHelpText>
        <label>Project Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the user that initiated the opportunity: fishing pole, PM, etc</inlineHelpText>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>We_Owe__c</fullName>
        <inlineHelpText>Notes added to this field will automatically populate to the project when the sale is approved</inlineHelpText>
        <label>Implementation Notes</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Piece_Issue__c</fullName>
        <inlineHelpText>Auto-populated from Products sold when Opportunity marked PAID</inlineHelpText>
        <label>Piece Issue</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>We_Owe__c</fullName>
        <formula>Project__r.We_Owe__c</formula>
        <inlineHelpText>This is auto-populated from the Opportunity&gt;Project&gt;Project Pieces</inlineHelpText>
        <label>Implementation Notes</label>
        <type>Text</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <description>Vin_Performance_Manager__r.User_Full_Name__c</description>
        <formula>Vin_Performance_Manager__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Vin_Performance_Manager__r.User_Full_Name__c</inlineHelpText>
        <label>Vin PM (formula)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Packet_Sent__c</fullName>
        <label>Date Packet Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;&amp;Opportunity__r.Implementation_Contact__r.Id,  Opportunity__r.Implementation_Contact__r.FirstName&amp;&quot; &quot;&amp; Opportunity__r.Implementation_Contact__r.LastName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Implementation Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Included__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Training Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>We_Owe__c</fullName>
        <formula>Opportunity__r.We_Owe__c</formula>
        <inlineHelpText>this field is auto-populated from the Opportunity</inlineHelpText>
        <label>Implementation Notes</label>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Territory_State__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DDM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UnitTestUtilities__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to help make code coverage easier.</description>
    <fields>
        <fullName>UnitTestAccountId__c</fullName>
        <label>UnitTestAccountId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestContactId__c</fullName>
        <label>UnitTestContactId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestOppRecordTypeId__c</fullName>
        <label>UnitTestOppRecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestPBEid__c</fullName>
        <label>UnitTestPBEid</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestPriceBookId__c</fullName>
        <label>UnitTestPriceBookId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestProduct2Id__c</fullName>
        <label>UnitTestProduct2Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestProjectRecordTypeImp__c</fullName>
        <label>UnitTestProjectRecordTypeImp</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>UnitTestUtilities</label>
</CustomObject>

classes/ProjectClasses_test.cls
@isTest(SeeAllData=True)
private class ProjectClasses_test {

    static testMethod void myUnitTest() {
        
        /*Profile pro = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
        	emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
        	localesidkey = 'en_US', profileid = pro.Id, 
        	timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com');
        	
        insert u_testMethodUser;
        
        System.runas(u_testMethodUser) {
        	
        	/*Account testAccount = [SELECT Id, Implementation_Date__c FROM Account LIMIT 1];
        	
        	testAccount.Implementation_Date__c = null;
        	update testAccount;
        	
        	
        	
        	Territory_State__c TS = new Territory_State__c();
	  		TS.Name = 'XX';
			TS.Account_Manager__c = userinfo.getUserId();
			TS.DDM__c = userinfo.getUserId();
			TS.Regional__c = userinfo.getUserId();
			TS.Implementation_Manager__c = userinfo.getUserId();
	        TS.Implementation_Specialist__c = userinfo.getUserId();		
			insert TS;
	  		
	  		Account A = new Account();
			A.ShippingCity='test';
			A.ShippingStreet='test';
			A.ShippingState='XX';
			A.ShippingPostalCode='test';
			A.BillingState = 'XX';
			A.AccountNumber = '1';
			A.BillingCity = 'test';
	        A.BillingCountry = 'USA';
	        A.BillingPostalCode = '66212';
	        A.BillingState = 'TS';
	        A.BillingStreet = '1234';
			
			A.name = 'TestAccount';
							
			insert A;
			
			
			Contact Ctc = new Contact();
			Ctc.AccountId = A.Id;
			Ctc.FirstName = 'test';
			Ctc.LastName = 'test';
				
			insert Ctc;*/
			UnitTestUtilities__c testId = UnitTestUtilities__c.getValues('UnitTestIds');
	        String acctId = testId.UnitTestAccountId__c;
			String rtId = testId.UnitTestOppRecordTypeId__c;
			String conId = testId.UnitTestContactId__c;
			String pbeId = testId.UnitTestPBEid__c;
			String pbId = testId.UnitTestPriceBookId__c;
			String prod2 = testId.UnitTestProduct2Id__c;
			String projRtIdImp = testId.UnitTestProjectRecordTypeImp__c;
			
			/*Opportunity O  = new Opportunity();
			O.AccountId = acctId; //set the required fields 
			O.Name = 'test';
			O.Deal_Contact__c = conId;
			O.CloseDate = System.today();
			O.StageName = 'Prospect';
			O.Type = 'New Business';
			O.Salesperson__c = userinfo.getUserId();
			O.Implementation_Contact__c = conId;
			//O.We_Owe__c = 'N/A'; 
			
			insert O; //save it to SFDC (it will rollback after your test*/
			Opportunity o = new Opportunity();
			o.AccountId = acctId;
			o.RecordTypeId = rtId;
			o.Name = 'TEST Custom Settings';
			o.Type = 'New Business';
			o.StageName = 'Prospect';
			o.CloseDate = system.today();
			o.Salesperson__c = userinfo.getUserId();
			o.Project_Exception__c = false;
			o.Discount_Approval_Status__c = 'Approved';
			o.Deal_Contact__c = conId;
			
			insert o;
			
			//Project
			SFDC_520_Quote__c prj = new SFDC_520_Quote__c();
			prj.Opportunity__c = o.Id;
			prj.Date_Packet_Sent__c = null;
			prj.RecordTypeId = '012700000005dgP';
			prj.Training_Included__c = TRUE;		
			
			insert prj;
			
			
			Project_Piece__c PP = new Project_Piece__c();
			PP.Project__c = prj.Id;
			PP.Piece_Issue__c = 'TestPiece - Sticker';
			PP.Name = 'VinSticker';
			PP.Project_Piece_Stage__c = 'Introduction';
			insert PP;
        	
        	
        	//Set your controller
        	ProjectClasses controller = new ProjectClasses();
        	
        	test.startTest();
        	
        	ProjectClasses.updateImplementationDate(acctId);
        	
        	ProjectClasses.updateCancelledProjectPieces(prj);
        	
        	test.stopTest();
        //}
    }
    
    
    
    public static testMethod void TestProject() {
    	
        /*Territory_State__c TS = new Territory_State__c();
        TS.Name = 'TS';
        TS.Regional__c = userinfo.getUserId();
		TS.Implementation_Manager__c = userinfo.getUserId();
        TS.Implementation_Specialist__c = userinfo.getUserId();        
        insert TS;*/
        
        Account A = new Account();
        A.Name = 'test';
        A.BillingCity = 'test';
        A.BillingCountry = 'USA';
        A.BillingPostalCode = '66212';
        A.BillingState = 'KS'; 
        A.BillingStreet = '1234';
        A.ShippingCity = 'test';
        A.ShippingCountry = 'USA';
        A.ShippingPostalCode = '66212';
        A.ShippingState = 'KS'; 
        A.ShippingStreet = '1234';
        
        insert A;

        Opportunity O = new Opportunity();
        O.AccountId = A.Id;
        O.Type = 'New Business';
        O.Name = 'test';
        O.CloseDate = System.today();
        O.StageName = 'Prospect';
        
        insert O;

        SFDC_520_Quote__c Proj = new SFDC_520_Quote__c();
        Proj.Opportunity__c = O.Id;
        Proj.RecordTypeId = '012700000005dgP';
        insert Proj;
        
        Project_Piece__c PP2 = new Project_Piece__c();
        PP2.OwnerId = userinfo.getUserId();
        PP2.Piece_Issue__c = 'test';
        PP2.Name = 'test';
        PP2.RecordTypeId = '012700000005e2z' ;
        PP2.Project__c = proj.Id;
        PP2.Requirements_Gathered__c = null;
        PP2.Contact_Made__c = null;
        PP2.Design_Completed__c = null;
        PP2.Proof_Approved__c = null;
        PP2.Uploaded_Printed_Shipped__c =null;
        PP2.Project_Piece_Stage__c = 'Requirement Gathering';
        //insert PP2;
        
        Project_Piece__c PP = new Project_Piece__c();
        PP.OwnerId = userinfo.getUserId();
        PP.Piece_Issue__c = 'test';
        PP.Name = 'test';
        PP.RecordTypeId = '012700000005e2z' ;
        PP.Project__c = proj.Id;
        PP.Requirements_Gathered__c = null;
        PP.Contact_Made__c = null;
        PP.Design_Completed__c = null;
        PP.Proof_Approved__c = null;
        PP.Uploaded_Printed_Shipped__c =null;
        PP.Project_Piece_Stage__c = 'Requirement Gathering';
        //insert PP;
         
               
        Task t = new Task();
        t.WhatId = Proj.Id;
        t.Subject = 'Send Packet';
        t.Status = 'Not Started';
        t.Type = 'Task';
        insert t;
        
        Task t2 = new Task();
        t2.WhatId = Proj.Id;
        t2.Subject = 'WFT-Intro Call/Intro Email/Send Packet';
        t2.Status = 'Not Started';
        t2.Type = 'Task';
        insert t2;
        
        Proj.Date_Packet_Sent__c = system.today();
        
        update Proj;   
        
        proj.Date_Graphics_Obtained__c = system.today();
        
        update proj;
        
        proj.Date_Packet_Ret_d__c = system.today();
        update proj;
        
        
        
    }
}