objects/Account.object
<CustomObject>
    <fields>
        <fullName>vAuto_Products__c</fullName>
        <description>This field will hold the status of all vAuto Products; mainly used to show as a account filed in searches and lists.</description>
        <inlineHelpText>vAuto Products and its status.</inlineHelpText>
        <label>vAuto Products</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Launch</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cloned_Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>check this box if the billed asset is being created from the clone button</inlineHelpText>
        <label>Cloned Asset?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <formula>Contract__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LOB_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned WriteOff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Needs Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Needs Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Pre Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - SVOC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Temp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transitioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Triage</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LOB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup to the BU POA only if the Product is a primary product: CRM, ILM, Webiste, Provision, Conquest, Auction Genius. A primary product has the field &quot;Base Asset&quot; set to True in the product record detail page</inlineHelpText>
        <label>Primary Product Status</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Product Status List</relationshipLabel>
        <relationshipName>Billing_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_SE_Date__c</fullName>
        <label>Last SE Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <description>The reference point for whether this Billed Asset is active or not. Based on the BI&apos;s record type.</description>
        <formula>IF( 
Business_Unit__c = &quot;VinSolutions&quot;, 
CASE(RecordType.DeveloperName, 
&quot;ADD&quot;, &quot;Inactive&quot;, 
&quot;CANCEL&quot;,&quot;Inactive&quot;, 
&quot;Locked&quot;, &quot;Inactive&quot; , 
&quot;Active&quot; 
), 
IF( 
Business_Unit__c = &quot;vAuto&quot;, 
IF( 
RecordType.DeveloperName = &quot;ADD&quot; &amp;&amp; ISBLANK(Active_Date__c), 
&quot;Pending&quot;, 
IF( 
RecordType.DeveloperName = &quot;ADD&quot; &amp;&amp; !ISBLANK(Active_Date__c), 
&quot;Active&quot;, 
IF( 
RecordType.DeveloperName = &quot;Process_Stop&quot; , 
&quot;Active&quot;, 
IF( 
RecordType.DeveloperName = &quot;MODIFY&quot; , 
&quot;Active&quot;, 
IF( 
RecordType.DeveloperName = &quot;Locked&quot; &amp;&amp;  !ISBLANK(Active_Date__c)  &amp;&amp;  ISBLANK(End_Date__c) , 
&quot;Active&quot;, 
&quot;Inactive&quot; 

) 
) 
) 
) 
), 
&quot;Not Applicable&quot; 
) 
)</formula>
        <inlineHelpText>The reference point for whether this Billed Asset is active or not. Based on the BI&apos;s record type.</inlineHelpText>
        <label>Billed Asset Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <formula>Related_Project_Piece__r.Project__r.Project_Type__c</formula>
        <inlineHelpText>Formula that pulls from the Project&apos;s Type</inlineHelpText>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Old_Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup the POA that the account manager will use to manage this asset</inlineHelpText>
        <label>Related POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Project_Piece__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project Asset</label>
        <referenceTo>Project_Piece__c</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suite_Name__c</fullName>
        <formula>TEXT(Product_Sold__r.Product_Suite__c)</formula>
        <inlineHelpText>Formula field that reads the Product Sold name and gives it a different column header for the related list on the POA</inlineHelpText>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vAuto_Activation_Date__c</fullName>
        <description>change requested per Michelle D 1/28/2105 per CR-00011658</description>
        <formula>Active_Date__c</formula>
        <inlineHelpText>formula field that reads the asset active date and sets it as the activation date</inlineHelpText>
        <label>vAuto Activation Date</label>
        <type>Date</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>Add a new line item to a billing contract</description>
        <label>ADD</label>
    </recordTypes>
    <recordTypes>
        <fullName>STOP</fullName>
        <active>false</active>
        <label>STOP</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/POA__c.object
<CustomObject>
    <description>used to handle Plan of Action items for an Account- gives the ability to group support or implementation issues together</description>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup the dealer that the plan of action is needed for</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan of Action(s)</relationshipLabel>
        <relationshipName>POA_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <inlineHelpText>how happy is the customer with the product you are managing for them. (Vin, use Log Solid Engagement button to update the status)</inlineHelpText>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Setup</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active and Happy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Risk in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low Risk in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Risk in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Rating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stockwave_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stockwave Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>POAs4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vAuto_Activation_Date__c</fullName>
        <label>vAuto Activation Date</label>
        <type>DateTime</type>
    </fields>
    <label>POA</label>
    <nameField>
        <label>Plan of Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POAs</pluralLabel>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Project_Type__c</fullName>
        <formula>Project__r.Project_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Project Pieces</relationshipLabel>
        <relationshipName>Project_Pieces</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Action__c</fullName>
        <formula>TEXT(Opportunity__r.Type)</formula>
        <inlineHelpText>Formula field that reads the field Type from the Opportunity</inlineHelpText>
        <label>Action</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <inlineHelpText>Uses the Opportunity&apos;s Product Suite and is updated by the Trigger</inlineHelpText>
        <label>Opp Product Suite</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup POA for this project</inlineHelpText>
        <label>Related POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <description>This is the type for all vAuto Projects</description>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/vAuto_No_Intro_Call__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used in code to disable the Intro Call task creation</description>
    <fields>
        <fullName>Action__c</fullName>
        <description>The action, for example Upsell or Swap</description>
        <inlineHelpText>The action, for example Upsell or Swap</inlineHelpText>
        <label>Action</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <description>The project type, for example Auction Genius - Stand Alone or Conquest Stand-Alone</description>
        <inlineHelpText>The project type, for example Auction Genius - Stand Alone or Conquest Stand-Alone</inlineHelpText>
        <label>Project Type</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>vAuto No Intro Calls</label>
</CustomObject>

classes/vAutoBillingItemHandler.cls
public class vAutoBillingItemHandler extends BillingItemHandler{ 

public virtual override void beforeDelete(Billing_Item__c billingItem){
		  billingItem = [Select Id,RecordTypeId 
  from Billing_Item__c where Id =: billingItem.Id ];
  system.debug('Deleting Billing Item with Record Type: '+StaticData.getInstance().BillingItemRecTypesMap.get(billingItem.RecordTypeId).Name);
  if( billingItem.RecordTypeId !=  StaticData.getInstance().BillingItemRecTypesMapByDevName.get('ADD').Id ){
  		Trigger.oldMap.get(billingItem.Id).addError('Can not delete Items of record Type: '+StaticData.getInstance().BillingItemRecTypesMap.get(billingItem.RecordTypeId).Name);
  }

 
 }
	
public override void afterInsert(Billing_Item__c newbillingItem){
   newbillingItem = [Select Id,Project_Type__c,LOB_Status__c,LOB__c,Related_POA__r.OwnerId, Related_POA__c,
   							Related_POA__r.Dealer__c,Related_Project_Piece__r.Project__r.Project_Type__c,
   							Related_Project_Piece__r.Project__r.Action__c,Cloned_Asset__c,Suite_Name__c, Related_POA__r.Stockwave_Manager__c
					   from Billing_Item__c
					  where Id =: newbillingItem.Id ];

	Map<string, vAuto_No_Intro_Call__c> NoIntroCalls = vAuto_No_Intro_Call__c.getAll();
	System.debug('================>>>>>> NoIntroCalls = ' + NoIntroCalls);
	if(newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c != null){
		for(vAuto_No_Intro_Call__c nic : NoIntroCalls.values()){
			if(newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c.contains('KBB')
				&& nic.Project_Type__c.contains('KBB')){
				if(newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c == nic.Project_Type__c){
					//do not create Intro for Sale Lines
	 				return;
				}
			}
			else if(newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c.contains('Conquest')
				&& nic.Project_Type__c.contains('Conquest')){
				if(newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c == nic.Project_Type__c
					&& newbillingItem.Related_Project_Piece__r.Project__r.Action__c == nic.Action__c){
					//do not create Intro for Conquest
	 				return;
				}
			}
			else if(newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c.contains('Auction')
				&& nic.Project_Type__c.contains('Auction')){
				if(newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c == nic.Project_Type__c
					&& newbillingItem.Related_Project_Piece__r.Project__r.Action__c == nic.Action__c){
					//do not create Intro for Auction Genius
	 				return;
				}
			}
		}
	}
	else{return;}
/* Commented out code and replaced with above code to use a custom setting
	if(
		(
			newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c == 'KBB PAR Used - Stand Alone'
		 	|| newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c == 'KBB PAR New - Stand Alone'
		 	|| newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c == 'KBB PAR Used - w/ vAuto'
		 	|| newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c == 'KBB PAR New - w/ vAuto'
	 	) 
	 	||(
	 		(
	 			newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c == 'Conquest'
		 		|| newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c == 'Conquest Stand-Alone'
				|| newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c == 'Auction Genius - Stand Alone'
			) && 
	 		(
 				newbillingItem.Related_Project_Piece__r.Project__r.Action__c == 'Sale'
		 		|| newbillingItem.Related_Project_Piece__r.Project__r.Action__c == 'Upsell'
		 		|| newbillingItem.Related_Project_Piece__r.Project__r.Action__c == 'Reactivate'
		 		|| newbillingItem.Related_Project_Piece__r.Project__r.Action__c == 'Swap'
	 		) ||
		
	 		//'Auction Genius - With Provision Client'
	  		(
	  			newbillingItem.Related_Project_Piece__r.Project__r.Project_Type__c == 'Auction Genius - With Provision Client' 
	  			&& 
				(
					newbillingItem.Related_Project_Piece__r.Project__r.Action__c == 'Upsell'
		 			|| newbillingItem.Related_Project_Piece__r.Project__r.Action__c == 'Swap'
		 		)
	 		)
	  	)
	){ 
 		//do not create Intro for Conquest , Auction Genius - Stand Alone and Sale Lines
 		return;
	}*/
 if(newbillingItem.LOB__c !=null){

 	try{
 	//update the Account field to show the latest status on vAuto products
	UpdateAccountvAutoProducts(newbillingItem.Related_POA__c,newbillingItem.Related_POA__r.Dealer__c );
	}
	catch(Exception e){
		UtilityClass.DebugException(e);
	}

	// create Intro call.
	if(	//If not a cloned line;
		!newbillingItem.Cloned_Asset__c){
		if(newbillingItem.Suite_Name__c =='Stockwave Stand Alone'){
			//create an intro call to the Stockwave Manager for assignment to an Acquisition Pro
			Task task = new Task();
			task.Subject =  '* Intro Call AP SW Stand Alone';
			task.Type = 'Call';
			task.Priority ='Normal';
			task.Description = 'A new account has been approved for Stockwave Stand Alone. AP to make Intro Call';
			task.ActivityDate = System.today();
			task.OwnerId = newbillingItem.Related_POA__r.Stockwave_Manager__c;
			task.WhatId = newbillingItem.Related_POA__c;
			System.debug('Creating Task: task.Subject: '+task.Subject+'; task.ActivityDate:'+task.ActivityDate+';task.OwnerId'+task.OwnerId+';task.WhatId'+task.WhatId);
			insert task;
		}
		if(newbillingItem.Suite_Name__c =='Stockwave'){
			//create an intro call to the Stockwave Manager for assignment to an Acquisition Pro
			Task task = new Task();
			task.Subject =  '* Intro Call AP SW';
			task.Type = 'Call';
			task.Priority ='Normal';
			task.Description = 'A new account has been approved for Stockwave. AP to make Intro Call';
			task.ActivityDate = System.today();
			task.OwnerId = newbillingItem.Related_POA__r.Stockwave_Manager__c;
			task.WhatId = newbillingItem.Related_POA__c;
			System.debug('Creating Task: task.Subject: '+task.Subject+'; task.ActivityDate:'+task.ActivityDate+';task.OwnerId'+task.OwnerId+';task.WhatId'+task.WhatId);
			insert task;
		}
		else{
		 	//create a intro call 	
		 	Task task = new Task();
			task.Subject =  '* Intro Call';
			task.Type = 'Call';
			task.Priority ='Normal';
			task.Description = 'A new account has been approved for integration PM task to include Step 1 - PM make Intro call to site Demo Info Future Users Next Step Step 2 - Close this task';
			task.ActivityDate = System.today();
			task.OwnerId = newbillingItem.Related_POA__r.OwnerId;
			task.WhatId = newbillingItem.Related_POA__c;
			System.debug('Creating Task: task.Subject: '+task.Subject+'; task.ActivityDate:'+task.ActivityDate+';task.OwnerId'+task.OwnerId+';task.WhatId'+task.WhatId);
			insert task;
		}
	}
 }
} 
  
public override void afterUpdate(Billing_Item__c newbillingItem, Billing_Item__c oldbillingItem){
 	newbillingItem = [Select Id,Project_Type__c,LOB_Status__c,LOB__c,Last_SE_Date__c,
 								Related_POA__r.OwnerId, Related_POA__c,Related_POA__r.Dealer__c,Suite_Name__c
 						from Billing_Item__c where Id =: newbillingItem.Id ];
	//if the status changes
	system.debug('newbillingItem.Suite_Name__c:'+newbillingItem.Suite_Name__c+';  oldbillingItem.Suite_Name__c:'+oldbillingItem.Suite_Name__c);
	system.debug('newbillingItem.LOB_Status__c:'+newbillingItem.LOB_Status__c+';  oldbillingItem.LOB_Status__c:'+oldbillingItem.LOB_Status__c);
	system.debug('newbillingItem.Last_SE_Date__c:'+newbillingItem.Last_SE_Date__c+';  oldbillingItem.Last_SE_Date__c:'+oldbillingItem.Last_SE_Date__c);

	//only in cases where the lineItem is nmarked as product suite
	if(newbillingItem.LOB_Status__c != oldbillingItem.LOB_Status__c && newbillingItem.LOB__c!=null){
	
		if(oldbillingItem.LOB_Status__c  != 'Good' && newbillingItem.LOB_Status__c  == 'Good'){
			system.debug('Creating task on Status set to Good on newbillingItem.Project_Type__c: '+newbillingItem.Project_Type__c);
			//Ramana: Stop comparing using the project type since this requires project assets
			//and not all converted or old assets have project assets
			//and start using the Suite_Name__c field
			//if(newbillingItem.Project_Type__c == 'Account Setup'){			
			if(newbillingItem.Suite_Name__c == 'Provision'){			
				CreateTask('# PM Review Call Good Status', 30,newbillingItem.Related_POA__r.OwnerId,newbillingItem.Related_POA__c );
			}
			//else if(newbillingItem.Project_Type__c == 'Conquest'){
			else if(newbillingItem.Suite_Name__c == 'Conquest'){
				CreateTask('# Conquest Review Call Good Status', 30,newbillingItem.Related_POA__r.OwnerId,newbillingItem.Related_POA__c );
			}
		}
		else if(oldbillingItem.LOB_Status__c  != 'At Risk' && newbillingItem.LOB_Status__c  == 'At Risk'){
			//if(newbillingItem.Project_Type__c == 'Account Setup'){
			if(newbillingItem.Suite_Name__c == 'Provision'){
				CreateTask('# PM Review Call At Risk Status', 7,newbillingItem.Related_POA__r.OwnerId,newbillingItem.Related_POA__c );
			}		
			//else if(newbillingItem.Project_Type__c == 'Conquest'){
			else if(newbillingItem.Suite_Name__c == 'Conquest'){
				CreateTask('# Conquest Review Call At Risk Status', 7,newbillingItem.Related_POA__r.OwnerId,newbillingItem.Related_POA__c );
			}
		}
		/*else if((oldbillingItem.LOB_Status__c  != 'Save - Account' && newbillingItem.LOB_Status__c  == 'Save - Account')
		||(oldbillingItem.LOB_Status__c  != 'Save - Pre Launch' && newbillingItem.LOB_Status__c  == 'Save - Pre Launch')
		||(oldbillingItem.LOB_Status__c  != 'Save - SVOC' && newbillingItem.LOB_Status__c  == 'Save - SVOC')
		||(oldbillingItem.LOB_Status__c  != 'Save - Temp' && newbillingItem.LOB_Status__c  == 'Save - Temp')
		){
			//if(newbillingItem.Project_Type__c == 'Account Setup'){
				if(newbillingItem.Suite_Name__c == 'Provision'){
					CreateTask('# PM Review Call Save Status', 7,newbillingItem.Related_POA__r.OwnerId,newbillingItem.Related_POA__c );
				}
				//else if(newbillingItem.Project_Type__c == 'Conquest'){
				else if(newbillingItem.Suite_Name__c == 'Conquest'){
					CreateTask('# Conquest Review Call Save Status', 7,newbillingItem.Related_POA__r.OwnerId,newbillingItem.Related_POA__c );
				}
		}*/
		//update the Account field to show the latest status on vAuto products
		UpdateAccountvAutoProducts(newbillingItem.Related_POA__c,newbillingItem.Related_POA__r.Dealer__c );
	}
	//in cases where the lineItem last solid emnganement changed update the vAuto Products
	else if (newbillingItem.Last_SE_Date__c != oldbillingItem.Last_SE_Date__c && newbillingItem.LOB__c!=null){
		//update the Account field to show the latest status on vAuto products
		UpdateAccountvAutoProducts(newbillingItem.Related_POA__c,newbillingItem.Related_POA__r.Dealer__c);
	}
}

private void UpdateAccountvAutoProducts(Id poaId , Id accountId){
	if(accountId == null){
		system.debug('No AccountId specified; Cannot update vAutp Products on Account');
		return;
	}
	//CR-00014210 replacing Last_SE_Date__c with vAuto_Activation_Date__c
	List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id, LOB_Status__c, Project_Type__c, Related_POA__c, Suite_Name__c,
	  															Related_POA__r.Dealer__c, Last_SE_Date__c, vAuto_Activation_Date__c,
	  															Related_Project_Piece__r.Project__r.Action__c
	  													   FROM Billing_Item__c 
	  													  WHERE Related_POA__c = :poaId
   	  														AND (Product_Status__c = 'Active'
   	  														 OR Product_Status__c = 'Pending')
   	  														AND LOB__c!=null];
   	  
   	system.debug('Collected: '+billingItemsMarkedWithLOB.size() +' billing items to update Account vAutp Products field');

	if(billingItemsMarkedWithLOB.size() > 0){
   		for(Billing_Item__c bi : billingItemsMarkedWithLOB){
   			if(bi.Related_Project_Piece__r.Project__r.Action__c != 'Swap'){
			   	String provisionStatus = '';
   	  			Date provisionLSE = null;
   	  			String conquestStatus = '';
   	  			Date conquestLSE = null;
			   	String vAutoProductStatus ='';

		   		for(Billing_Item__c item : billingItemsMarkedWithLOB){  
		   	  		system.debug('Processing: item.vAuto_Activation_Date__c: '+item.vAuto_Activation_Date__c);
		   	  		system.debug('Processing: item.Suite_Name__c: '+item.Suite_Name__c);
		   	  		//system.debug('Processing: item.Last_SE_Date__c: '+item.Last_SE_Date__c);
		   	  		system.debug('Processing: item.LOB_Status__c: '+item.LOB_Status__c);
		   	  		if(item.Suite_Name__c == 'Provision'){
		   	  			provisionStatus = item.LOB_Status__c;
		   	  			provisionLSE = item.Last_SE_Date__c;
		   	  		}
		   	  		else if(item.Suite_Name__c == 'Conquest'){
						conquestStatus = item.LOB_Status__c;
		   	  			conquestLSE = item.Last_SE_Date__c;
		   	  		}
		   	  		//}
		   	  		 /*String lseDate = 'LSE: None';
		   	  		 if(item.Last_SE_Date__c != null){
		   	  			lseDate = 'LSE: '+item.Last_SE_Date__c.month()+'-'+item.Last_SE_Date__c.day()+'-'+item.Last_SE_Date__c.year();	
		   	  		}
		   	  	 	vAutoProductStatus = vAutoProductStatus + item.Suite_Name__c +' : '+ item.LOB_Status__c +' : '+lseDate+'\r\n';*/
		   	  		String activationDate = 'Activation Date: None';
		   	  		if(item.vAuto_Activation_Date__c != null){
		   	  			activationDate = 'Activation Date: '+item.vAuto_Activation_Date__c.month()+'-'+item.vAuto_Activation_Date__c.day()+'-'+item.vAuto_Activation_Date__c.year();	
		   	  		}
		   	  	 	vAutoProductStatus = vAutoProductStatus + item.Suite_Name__c +' : '+ item.LOB_Status__c +' : '+activationDate+'\r\n';
		   	  	}  	  

			   	system.debug('Updating vAuto products: '+vAutoProductStatus);
			   	//update account field
			   	Account a = new Account(Id = accountId);
			   	a.vAuto_Products__c = vAutoProductStatus;
				update a;
			   	  
			   	//update poa Field
			   	POA__c poa = new POA__c(Id =poaId);
			   	if(provisionStatus != ''){ 	  
			   		poa.Provision_Status__c  = provisionStatus;
			   	}
			   	if(provisionLSE != null){
			   		poa.Provision_LSE__c = provisionLSE;
			   	}
			   	if(conquestStatus != ''){
			   		poa.Conquest_Status__c  = conquestStatus;
			   	}
			   	if(conquestLSE != null){
			   		poa.Conquest_LSE__c = conquestLSE;
			   	}

			   	update poa;
	   	  	}
   	  	}
	}
}

private void CreateTask(String subject, Integer dueInDays, Id ownerId, Id poaId){
  //check if the task created
  List<Task> tasks = [Select Id from Task where 
  ownerId=:ownerId
  and whatId=:poaId
  and Subject =: subject
  and Status =: 'Not Started'];

  

 if(tasks == null || tasks.size() == 0){
	Task task = new Task();
	task.Subject =  subject;
	task.ActivityDate = System.today().addDays(dueInDays);
	task.OwnerId = ownerId;
	task.WhatId = poaId;
	System.debug('Creating Task: task.Subject: '+task.Subject+'; task.ActivityDate:'+task.ActivityDate+';task.OwnerId'+task.OwnerId+';task.WhatId'+task.WhatId);
	insert task;
	}
}
}