objects/Account.object
<CustomObject>
    <fields>
        <fullName>ValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ValidationRules</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Installment__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Contact__c</fullName>
        <formula>Opportunity__r.Deal_Contact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deal Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ValidationRules</label>
        <type>Checkbox</type>
    </fields>
    <label>Installment</label>
    <nameField>
        <label>Installment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CRM_Vendor__c</fullName>
        <inlineHelpText>Who is the Dealer&apos;s Current CRM Vendor?</inlineHelpText>
        <label>CRM Vendor</label>
        <picklist>
            <picklistValues>
                <fullName>AAX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aeros</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction 123</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoAccelerator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoBase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoBytel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoConX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Jini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Jockey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Mate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoMatrix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoOne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Revo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoSoft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Soft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autostar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Tracker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autotrader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Uplink</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AVV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blue Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buzz Track</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Deal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the primary contact associated with the Opportunity</inlineHelpText>
        <label>Deal Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Deal Contact)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Approval_Status__c</fullName>
        <inlineHelpText>Updated by approval processes for each area of approval.</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Leadership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Leadership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Implementation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>look up the contact under the Salesforce account that Implementation will contact regarding the setup of the products purchased</inlineHelpText>
        <label>Implementation Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Implementation Contact)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Installments__c</fullName>
        <label>Number of Installments</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you DO NOT want this opportunity to create a Project when marked paid.</inlineHelpText>
        <label>Project Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the user that initiated the opportunity: fishing pole, PM, etc</inlineHelpText>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Type__c</fullName>
        <label>obsolete_Stage Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoice Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to bypass Validation Rules in unit tests.</description>
        <inlineHelpText>Used to bypass Validation Rules in unit tests.</inlineHelpText>
        <label>ValidationRules</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to bypass validation rules in unit tests.</description>
        <label>ValidationRules</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Stage_Type__c</fullName>
        <inlineHelpText>Contigent upon Stage = Billable-Not Completed</inlineHelpText>
        <label>Stage Type</label>
        <picklist>
            <controllingField>Approval_Stage__c</controllingField>
            <picklistValues>
                <fullName>Addon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Go Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost Pre-launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Closed Won Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Website Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Dealer Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Website Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ValidationRules</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UnitTestUtilities__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to help make code coverage easier.</description>
    <fields>
        <fullName>UnitTestAccountId__c</fullName>
        <label>UnitTestAccountId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestContactId__c</fullName>
        <label>UnitTestContactId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestOppRecordTypeId__c</fullName>
        <label>UnitTestOppRecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestPBEid__c</fullName>
        <label>UnitTestPBEid</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestPriceBookId__c</fullName>
        <label>UnitTestPriceBookId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestProduct2Id__c</fullName>
        <label>UnitTestProduct2Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestProjectRecordTypeImp__c</fullName>
        <label>UnitTestProjectRecordTypeImp</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>UnitTestUtilities</label>
</CustomObject>

classes/AttachInvoiceController_TEST.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seeAllData=true)
private class AttachInvoiceController_TEST {

  public static testmethod void testInvoicesingle(){
  		
  	 /*Account A = new Account();
  	 
		A.ShippingCity='test';
		A.ShippingStreet='test';
		A.ShippingState='XX';
		A.ShippingPostalCode='test';
		A.BillingState = 'XX';
		A.AccountNumber = '1';
		A.BillingCity = 'test';
        A.BillingCountry = 'USA';
        A.BillingPostalCode = '66212';
        A.BillingState = 'TS';
        A.BillingStreet = '1234';			
		A.name = 'TestAccount';
						
		insert A;
		
	Opportunity O = new Opportunity();
		O.AccountId = A.Id;
		O.Name = 'TEST Attachment';
		O.StageName = 'Prospect';
		O.Type = 'New Business';
		O.CloseDate = system.Today();
		
		insert O;
		
	PageReference pref = Page.AttachInvoice;
	pref.getParameters().put('id', O.id);
	Test.setCurrentPage(pref);
	
	
	
	//body = Blob.valueOf('TEST TEXT');
	ApexPages.StandardController cont = new ApexPages.Standardcontroller(O);
	
	AttachInvoiceController aic = new AttachInvoiceController(cont);
	
	Test.startTest();
	
	
	
	pref = aic.attachInvoice();
	
	test.stopTest();*/
	UnitTestUtilities__c testId = UnitTestUtilities__c.getValues('UnitTestIds');
        String acctId = testId.UnitTestAccountId__c;
		String rtId = testId.UnitTestOppRecordTypeId__c;
		String conId = testId.UnitTestContactId__c;
		String pbeId = testId.UnitTestPBEid__c;
		String pbId = testId.UnitTestPriceBookId__c;
		String prod2 = testId.UnitTestProduct2Id__c;
		String projRtIdImp = testId.UnitTestProjectRecordTypeImp__c;
		
		Opportunity o = new Opportunity();
		o.AccountId = acctId;
		o.RecordTypeId = rtId;
		o.Name = 'TEST Custom Settings';
		o.Type = 'New Business';
		o.StageName = 'Prospect';
		o.CloseDate = system.today();
		o.Salesperson__c = userinfo.getUserId();
		o.Project_Exception__c = false;
		o.Discount_Approval_Status__c = 'Approved';
		o.Deal_Contact__c = conId;
		o.ValidationRules__c = true;
		
		insert o;
	    
	    OpportunityLineItem oli = new OpportunityLineItem();
	    oli.PricebookEntryId = pbeId;
	    oli.OpportunityId = o.Id;
	    oli.Quantity = 1;
	    oli.TotalPrice = 0.00;
	    
	    insert oli; 
	        
	    o.Stage_Type__c = 'Closed or Won';
	    o.Number_of_Installments__c = '1';
	    o.Implementation_Contact__c = conId;
	    o.CRM_Vendor__c = 'AAX';
	    o.DMS_Vendor__c = 'AAX';
	    o.ILM_Vendor__c = 'AAX';
	    o.Inventory_Vendor__c = 'AAX';
	    o.Pricing_Vendor__c = 'AAX';
	    o.Website_Vendor__c = 'AAX';
	    
	    SFDC_520_Quote__c prj = new SFDC_520_Quote__c();
	    prj.Opportunity__c = o.Id;
	    prj.Date_Packet_Sent__c = null;
	    prj.RecordTypeId = projRtIdImp;
	    prj.Training_Included__c = true;
	    prj.Project_Worth__c = 1000;
	    prj.Name = 'Imp - WAS';
	    
	    insert prj;
	    
	    update o;
	    
	   	//Installment__c i = new Installment__c();
	   	//i.Opportunity__c = o.Id;
	   	//i.Paid__c = system.today();
	   	//i.Confirmed__c = true;
	   	
	   	//insert i;
	    
	    PageReference pref = Page.AttachInvoice;
		pref.getParameters().put('id', o.id);
		Test.setCurrentPage(pref);
		
		//body = Blob.valueOf('TEST TEXT');
		ApexPages.StandardController cont = new ApexPages.Standardcontroller(o);	
		AttachInvoiceController aic = new AttachInvoiceController(cont);
		
	    test.startTest();
	 		pref = aic.attachInvoice();
	    test.stopTest(); 
		
  }
}