objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status can only be updated from a first time Closed Won Paid Opportunity and by accounting when a customer cancel services</inlineHelpText>
        <label>Vin Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OOB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Cases__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Total number of cases (by weight) for this account</inlineHelpText>
        <label>Total Cases</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VS_Dealer_ID__c</fullName>
        <inlineHelpText>CAN BE DELETED when this is no longer referenced. This is an admin used in test code and batch jobs</inlineHelpText>
        <label>VS Dealer ID DONOTUSE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/scheduledAccountCaseUpdateInterface.cls
global class scheduledAccountCaseUpdateInterface implements Schedulable{
	global void execute(SchedulableContext ctx)
	{
		//scheduledAccountCaseUpdateJob.updateAccountCase();
		String query = 'select Id, Status__c, Total_Cases__c, VS_Dealer_ID__c from Account where Status__c = \'Active\' AND AccountNumber != null';
		scheduledAccountCaseUpdateJob batchApex = new scheduledAccountCaseUpdateJob(query);
		ID batchprocessid = Database.executeBatch(batchApex, 1);
		
	}

	public static void start()
	{
		System.schedule('Update Account Case Total', '0 0 0 * * ?', new scheduledAccountCaseUpdateInterface());
	}		
}