objects/Account.object
<CustomObject>
    <fields>
        <fullName>ATC_Status__c</fullName>
        <description>Field is updated by the system based on the product status in the ATG Product library.</description>
        <inlineHelpText>Field is updated by the system based on the product status in the ATG Product library.</inlineHelpText>
        <label>ATC Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HomeNet_Status__c</fullName>
        <label>HomeNet Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KBB_Status__c</fullName>
        <label>KBB PAR Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>vAuto_Status__c</fullName>
        <label>vAuto Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>An individual rooftop.</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Business_Unit__c.object
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <inlineHelpText>when a contact is created the BU = Shared, unless the user&apos;s profile has the company name = vAuto, then the BU is updated to vAuto. Validation rule prevents non vauto users from editing a vauto contact record</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Shared</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>vAuto_Status__c</fullName>
        <formula>TEXT(Account.vAuto_Status__c)</formula>
        <inlineHelpText>formula field that reads the status from the account</inlineHelpText>
        <label>vAuto Account Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ATC_Status__c</fullName>
        <description>Status of ATC from ATG Core SF org.</description>
        <inlineHelpText>Status of ATC from ATG Core SF org.</inlineHelpText>
        <label>ATC Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Affiliate_Email__c</fullName>
        <label>Affiliate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Affiliate_Name__c</fullName>
        <label>Affiliate Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Affiliate_Phone__c</fullName>
        <label>Affiliate Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Affiliate__c</fullName>
        <label>Affiliate</label>
        <picklist>
            <picklistValues>
                <fullName>AutoTrader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoTrader Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cox Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DealerTrack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Genius Labs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homenet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KBB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manheim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NextGear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VinSolutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Xtime</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <inlineHelpText>enter the Business Unit this lead applies to</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>AutoTrader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoTrader Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cox Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homenet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VinSolutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XTime</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HomeNet_Status__c</fullName>
        <label>HomeNet Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImportedNotes__c</fullName>
        <description>Imported notes for the current lead</description>
        <inlineHelpText>Imported notes for the current lead</inlineHelpText>
        <label>Imported Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>KBB_Status__c</fullName>
        <label>KBB Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_Type__c</fullName>
        <inlineHelpText>you must select the products the dealer is interested in</inlineHelpText>
        <label>Products of Interest</label>
        <picklist>
            <picklistValues>
                <fullName>ATC/KBB Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATC/KBB Non-Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AuctionGenius</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoTrader Classics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DIY / Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Genius Labs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Non-Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HomeNet Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HomeNet Non-Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ILM (Internet Lead Management)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KBB PAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Seller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Deal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stockwave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TIM Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TIM Non-Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto Non-Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VinSolutions Core</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vin_Status__c</fullName>
        <label>Vin Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vAuto_Status__c</fullName>
        <description>Status of vAuto from ATG Core SF org.</description>
        <inlineHelpText>Status of vAuto from ATG Core SF org.</inlineHelpText>
        <label>vAuto Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Haystak</fullName>
        <active>true</active>
        <businessProcess>Haystak</businessProcess>
        <description>Lead Process for Haystak BU</description>
        <label>Haystak</label>
    </recordTypes>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <businessProcess>vAuto</businessProcess>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ATLeadToVinSF.cls
/**
 * Email services are automated processes that use Apex classes
 * to process the contents, headers, and attachments of inbound
 * email.
 */
global class ATLeadToVinSF implements Messaging.InboundEmailHandler {

    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();

        //Set string to pull out HTML to insert in fields in VIN
        String companyNameString = 'Dealer Name:';
    	String contactFirstNameString = 'Dealer Contact First Name:';
    	String contactLastNameString = 'Dealer Contact Last Name:';
    	String phoneString ='Dealer Contact Number:';
        String billingStreetString = 'Dealer Billing Street:';
        String billingCityString = 'Dealer Billing City:';
        String billingStateString = 'Dealer Billing State:';
        String billingZipString = 'Dealer Billing Zip:';
        String vAutoStatusString = 'vAuto Status:';
        String vinStatusString = 'VinSolutions Status:';
        String homeNetStatusString = 'HomeNet Status:';
        String atcStatusString = 'ATC Status:';
        String kbbStatusString = 'KBB Status:';
        String productDesiredString = 'Product Type:';
        String referralNotesString = 'Referral Notes: \n';
        String leadOwnerString = 'Referral Submitted by:';
        String leadOwnerPhoneString = 'Submitter Phone:';
        String leadOwnerEmailString = 'Submitter Email:';

        String body = '';

        try{
        	body = removeHTML(email.htmlBody);
        }
        catch(Exception ex){
        	body = removeHTML(email.plainTextBody);
        }

        String nameValue = 'No Comapany/Account Provided';
        String contactValue = 'No Contact Provided';
        String contactFirstNameValue = '';
        String contactLastNameValue = '';
        String phoneValue = '0000000000';
        String streetValue = 'No Street Provided';
        String cityValue = 'No City Provided';
        String stateValue = 'NA';
        String zipValue = '';
        String vAutoStatusValue = '';
        String vinStatusValue = '';
        String homeNetStatusValue = '';
        String atcStatusValue = '';
        String kbbStatusValue = '';
        String productDesiredValue = '';
        String referralNotesValue = '';
        String leadOwnerValue = '';
        String leadOwnerPhoneValue = '';
        String leadOwnerEmailValue = '';

        Lead newLead = new Lead();
        //get dealer name
        nameValue = body.substringBetween(companyNameString, '\n');
        //get contact first name
        contactFirstNameValue = body.substringBetween(contactFirstNameString, '\n');
        //get contact last name
        contactLastNameValue = body.substringBetween(contactLastNameString, '\n');
    	//get phone
    	phoneValue = body.substringBetween(phoneString, '\n');
    	//get street
    	streetValue = body.substringBetween(billingStreetString, '\n');
    	//get city
    	cityValue = body.substringBetween(billingCityString, '\n');
    	//get state
    	stateValue = body.substringBetween(billingStateString, '\n');
    	//get zip
    	zipValue = body.substringBetween(billingZipString, '\n');
    	//get vAuto status
    	vAutoStatusValue = body.substringBetween(vAutoStatusString, '\n');
    	//get vin status
    	vinStatusValue = body.substringBetween(vinStatusString, '\n');
    	//get homeNet status
    	homeNetStatusValue = body.substringBetween(homeNetStatusString, '\n');
    	//get atc status
    	atcStatusValue = body.substringBetween(atcStatusString, '\n');
    	//get kbb status
    	kbbStatusValue = body.substringBetween(kbbStatusString, '\n');
    	//get desired product
    	productDesiredValue = body.substringBetween(productDesiredString, '\n');
    	//get notes
    	referralNotesValue = body.substringBetween(referralNotesString, leadOwnerString);
    	//get lead owner
    	leadOwnerValue = body.substringBetween(leadOwnerString, '\n');
    	//get lead owner cell phone
    	leadOwnerPhoneValue = body.substringBetween(leadOwnerPhoneString, '\n');
        //get lead owner email
        leadOwnerEmailValue = body.substringAfter(leadOwnerEmailString);
    	
    	newLead.Company = nameValue;
    	newLead.FirstName = contactFirstNameValue;
    	newLead.LastName = contactLastNameValue;
    	newLead.Phone = phoneValue;
    	newLead.Street = streetValue;
    	newLead.City = cityValue;
    	newLead.State = stateValue;
    	newLead.PostalCode = zipValue;
    	newLead.vAuto_Status__c = vAutoStatusValue;
    	newLead.Vin_Status__c = vinStatusValue;
    	newLead.HomeNet_Status__c = homeNetStatusValue;
    	newLead.ATC_Status__c = atcStatusValue;
    	newLead.KBB_Status__c = kbbStatusValue;
    	newLead.Opp_Type__c = productDesiredValue;
    	newLead.ImportedNotes__c = referralNotesValue;
        newLead.Affiliate__c = 'AutoTrader';
    	newLead.Affiliate_Name__c = leadOwnerValue;
    	newLead.Affiliate_Phone__c = leadOwnerPhoneValue;
        newLead.Affiliate_Email__c = leadOwnerEmailValue;
    	newLead.LeadSource = 'ATG';
    	if(productDesiredValue.contains('Haystak')){
            newLead.Business_Unit__c = 'Haystak';
        }
        else if(productDesiredValue.contains('vAuto')){
            newlead.Business_Unit__c = 'vAuto';
        }
        else{
            newLead.Business_Unit__c = 'VinSolutions';
        }

    	insert newLead;
    	
        // Add lead to the AutoTrader Campaign
        Campaign atcCampaign = [select Id, Name, IsActive from Campaign where Name = 'AutoTrader Leads' AND isActive = true limit 1];
    	CampaignMember mem = new CampaignMember (campaignid=atcCampaign.id, leadid=newlead.id);
        insert mem;

        return result;
        
        
    }
    
    public static String removeHTML(String source){
        	String html = source;
        	//replace all <br> tags with \n to support new lines
        	string result = html.replaceAll('<br/>', '\n');
        	result = result.replaceAll('<br/>', '\n');
        	result = result.replaceAll('</p>', '\n');
        	result = result.replaceAll('~~EOL~~', '\n');
        	result = result.replaceAll('&nbsp;', '');
        	
        	//regular expression to match all HTML/XML tags
        	string HTML_TAG_PATTERN = '<,*?>';
        	
        	//complie the pattern
        	pattern myPattern = pattern.compile(HTML_TAG_PATTERN);
        	
        	//get your matcher instance
        	matcher myMatcher = myPattern.matcher(result);
        	//remove tags
        	result = myMatcher.replaceAll('');
        	return result;
        }
}