objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>An individual rooftop.</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Business_Unit__c.object
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <inlineHelpText>when a contact is created the BU = Shared, unless the user&apos;s profile has the company name = vAuto, then the BU is updated to vAuto. Validation rule prevents non vauto users from editing a vauto contact record</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Shared</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>mkto2__Original_Referrer__c</fullName>
        <label>Original Referrer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Affiliate_Name__c</fullName>
        <label>Affiliate Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Affiliate__c</fullName>
        <label>Affiliate</label>
        <picklist>
            <picklistValues>
                <fullName>AutoTrader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoTrader Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cox Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DealerTrack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Genius Labs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homenet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KBB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manheim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NextGear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VinSolutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Xtime</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <inlineHelpText>enter the Business Unit this lead applies to</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>AutoTrader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoTrader Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cox Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homenet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VinSolutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XTime</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hot_Transfer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To flag urgency of VGL leads</description>
        <label>Hot Transfer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opp_Type__c</fullName>
        <inlineHelpText>you must select the products the dealer is interested in</inlineHelpText>
        <label>Products of Interest</label>
        <picklist>
            <picklistValues>
                <fullName>ATC/KBB Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATC/KBB Non-Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AuctionGenius</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoTrader Classics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DIY / Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Genius Labs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Non-Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HomeNet Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HomeNet Non-Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ILM (Internet Lead Management)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KBB PAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Seller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Deal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stockwave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TIM Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TIM Non-Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto Non-Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VinSolutions Core</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scheduled_WebEx__c</fullName>
        <label>Scheduled WebEx</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>mkto2__Original_Referrer__c</fullName>
        <label>Original Referrer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <businessProcess>vAuto</businessProcess>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/VGLLeadToSD.cls
/**
 * Email services are automated processes that use Apex classes
 * to process the contents, headers, and attachments of inbound
 * email.
 */

global class VGLLeadToSD implements Messaging.InboundEmailHandler {
    
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.inboundEmail email, Messaging.InboundEnvelope env) {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
        
        //Set string to pull out HTML to insert in fields in VIN
        String companyNameString = 'Dealer Name:';
        String contactFirstNameString = 'Dealer Contact First Name:';
        String contactLastNameString = 'Dealer Contact Last Name:';
        String phoneString ='Dealer Contact Phone:';
        String mobilePhoneString ='Dealer Contact Mobile Phone:';
        String contactEmail = 'Dealer Contact Email:';
        String streetString = 'Dealer Street:';
        String cityString = 'Dealer City:';
        String stateString = 'Dealer State:';
        String zipString = 'Dealer Zip:';
        String urgencyString = '*****Urgency:';
        String productInterestString = 'Product of Interest:';
        String notesString = 'Notes:';
        String demoString = 'Demo Scheduled:';
        String referredByString = 'Referred by:';
        String submitterString = 'Submitter :';
        String submitterBUString = 'Submitter BU:';
        String body = '';
        try{
            body = removeHTML(email.htmlBody);
        }
        catch(Exception ex){
            body = removeHTML(email.plainTextBody);
        }
        String nameValue = 'No Comapany/Account Provided';
        String contactValue = 'No Contact Provided';
        String contactFirstNameValue = '';
        String contactLastNameValue = '';
        String phoneValue = '0000000000';
        String mobilePhoneValue = '0000000000';
        String contactEmailValue = '';
        String streetValue = 'No Street Provided';
        String cityValue = 'No City Provided';
        String stateValue = 'NA';
        String zipValue = '';
        String urgencyValue = '';
        String productInterestValue = '';
        String notesValue = '';
        String demoValue = '';
        String referredValue = '';
        String submitterValue = '';
        String submitterBUValue = '';
        Date demoDate;

        Lead newLead = new Lead();
        //get dealer name
        nameValue = body.substringBetween(companyNameString, '\n');
        //get contact first name
        contactFirstNameValue = body.substringBetween(contactFirstNameString, '\n');
        //get contact last name
        contactLastNameValue = body.substringBetween(contactLastNameString, '\n');
        //get phone
        phoneValue = body.substringBetween(phoneString, '\n');
        //get mobile phone
        mobilePhoneValue = body.substringBetween(mobilePhoneString, '\n');
        //get email
        contactEmailValue = body.substringBetween(contactEmail, '\n');
        //get street
        streetValue = body.substringBetween(streetString, '\n');
        //get city
        cityValue = body.substringBetween(cityString, '\n');
        //get state
        stateValue = body.substringBetween(stateString, '\n');
        //get zip
        zipValue = body.substringBetween(zipString, '\n');
        //get urgency
        urgencyValue = body.substringBetween(urgencyString, '\n');
        //get interested product
        productInterestValue = body.substringBetween(productInterestString, '\n');
        //get notes
        notesValue = body.substringBetween(notesString, '\n');
        //get demo
        demoValue = body.substringBetween(demoString, '\n');
        //get referred by
        referredValue = body.substringBetween(referredByString, '\n');
        //get submitter
        submitterValue = body.substringBetween(submitterString, '\n');
        //get submitter bu
        submitterBUValue = body.substringAfter(submitterBUString);
        
        newLead.Company = nameValue;
        newLead.FirstName = contactFirstNameValue;
        newLead.LastName = contactLastNameValue;
        newLead.Phone = phoneValue;
        newLead.MobilePhone = mobilePhoneValue;
        newLead.Email = contactEmailValue;
        newLead.Street = streetValue;
        newLead.City = cityValue;
        newLead.State = stateValue;
        newLead.PostalCode = zipValue;
        newLead.Rating = urgencyValue;
        newLead.Opp_Type__c = productInterestValue;
        newLead.Description = notesValue;
        system.debug('==========================>>>>>> demoValue = ' + demoValue);
        try{
            demoDate = Date.valueOf(demoValue);
        }
        catch(Exception e){
            
        }
        if(demoDate != null){
            newLead.Scheduled_WebEx__c = datetime.newInstance(demoDate.year(), demoDate.month(), demoDate.day());
        system.debug('==========================>>>>>> Scheduled_WebEx__c = ' + newLead.Scheduled_WebEx__c);
        }
        newLead.mkto2__Original_Referrer__c = referredValue;
        newLead.Affiliate_Name__c = submitterValue;
        newLead.Affiliate__c = submitterBUValue;
        newLead.Business_Unit__c = 'vAuto';
        if(urgencyValue.contains('Hot Transfer')){
            newLead.Hot_Transfer__c = true;
        }

        insert newLead;
        
        // Add lead to the AutoTrader Campaign
        Campaign vglCampaign = [select Id, Name, IsActive from Campaign where Name = 'VGL Leads' AND isActive = true limit 1];
        CampaignMember mem = new CampaignMember (campaignid=vglCampaign.id, leadid=newlead.id);
        insert mem;

        return result;
    }
    
    public static String removeHTML(String source){
            String html = source;
            //replace all <br> tags with \n to support new lines
            string result = html.replaceAll('<br/>', '\n');
            result = result.replaceAll('<br/>', '\n');
            result = result.replaceAll('</p>', '\n');
            result = result.replaceAll('~~EOL~~', '\n');
            result = result.replaceAll('&nbsp;', '');
            
            //regular expression to match all HTML/XML tags
            string HTML_TAG_PATTERN = '<,*?>';
            
            //complie the pattern
            pattern myPattern = pattern.compile(HTML_TAG_PATTERN);
            
            //get your matcher instance
            matcher myMatcher = myPattern.matcher(result);
            //remove tags
            result = myMatcher.replaceAll('');
            return result;
    }

}