objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <formula>VinPro2__r.User_Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vin PM Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory State</label>
        <referenceTo>Territory_State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Other</fullName>
        <active>false</active>
        <description>Partners, Consultants,</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Sold__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Sold</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Originating Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the primary contact associated with the Opportunity</inlineHelpText>
        <label>Deal Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Deal Contact)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <label>Implementation Manager</label>
        <picklist>
            <picklistValues>
                <fullName>Matt Bench</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travis Douglas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jennifer Merrick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kandy Richert</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Initial_Load__c</fullName>
        <description>For Tier 1/Tier 2/OEM opps. For products that are Subject to Load, only THIS amount of project pieces will be generated when the opp is marked Closed Won.</description>
        <inlineHelpText>For products that are Subject to Load, only THIS amount of project pieces will be generated when the opp is marked Closed Won.</inlineHelpText>
        <label>Initial Load</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the user that initiated the opportunity: fishing pole, PM, etc</inlineHelpText>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TryCatchTest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TryCatchTest</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Territory_State__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DDM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DDM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Website_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Website Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territory_States9</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/handler_billingItemUpdateBillType_test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class handler_billingItemUpdateBillType_test {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        /*Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        UserRole role = [SELECT Id From UserRole WHERE Name = 'Director of Sales'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
        	emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
        	localesidkey = 'en_US', profileid = pro.Id, 
        	timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com',
        	UserRoleId = role.Id);
        	
        insert u_testMethodUser;
        
        //UserRoleId
        
        System.runas(u_testMethodUser) {*/
        	
        	
        	/*Territory_State__c TS = new Territory_State__c();
	  		TS.Name = 'TS';
			TS.Account_Manager__c = userinfo.getUserId();
			TS.DDM__c = userinfo.getUserId();
			TS.Regional__c = userinfo.getUserId();
			TS.Implementation_Manager__c = userinfo.getUserId();
	        TS.Implementation_Specialist__c = userinfo.getUserId();	
	        TS.Website_Manager__c = userInfo.getUserId();	
			insert TS;*/
	  		
	  		
	  		Account A = new Account();
			A.ShippingCity='test';
			A.ShippingStreet='test';
			A.ShippingState='XX';
			A.ShippingPostalCode='test';
			A.BillingState = 'XX';
			A.AccountNumber = '1';
			A.BillingCity = 'test';
	        A.BillingCountry = 'USA';
	        A.BillingPostalCode = '66212';
	        A.BillingState = 'KS';
	        A.BillingStreet = '1234';
			
			A.name = 'TestAccount';
							
			insert A;
			
			Contact Ctc = new Contact();
			Ctc.AccountId = A.Id;
			Ctc.FirstName = 'test';
			Ctc.LastName = 'test';
			Ctc.Phone = '9999999999';
					
			insert Ctc;
			
			
			Opportunity O  = new Opportunity();
			O.AccountId = A.Id; 
			O.Name = 'testILM';
			
			O.Deal_Contact__c = Ctc.id;
			O.CloseDate = system.today();
			O.StageName = 'Prospect';
			O.Type = 'New Business';
			O.Salesperson__c = userinfo.getUserId();
			//O.RecordTypeId = '012S00000008rGjIAI';   //generalsales//01270000000Q7t7  //t1/t2//01270000000Q9Me
			O.RecordTypeId = '01270000000Q7t7';
			//O.Initial_Load__c = 5; 
			O.TryCatchTest__c = true;
			insert O;

			
			Contract ctr = new Contract();
			ctr.AccountId = A.Id;
			ctr.RecordTypeId = '01270000000Q9vW';
			insert ctr;
					
			Billing_Item__c bi1 = new Billing_Item__c(Contract__c = ctr.Id,Product_Sold__c = '01t70000004ZFKw');
			//bi1.Contract__c = ctr.Id;
			//bi1.Product_Sold__c = '01t70000004ZFKw'; //Other
			insert bi1;
			
			Billing_Item__c bi5 = new Billing_Item__c(Contract__c = ctr.Id,Product_Sold__c ='01t70000004ZJVT');
			//bi5.Contract__r.AccountId  = A.Id;
			//bi5.Product_Sold__c = '01t70000004ZJVT'; //Inventory
			//bi5.Contract__r = ctr;
			insert bi5;			
						
			Billing_Item__c bi4 = new Billing_Item__c(Contract__c = ctr.Id,Product_Sold__c ='01t70000004ZFMy');
			//bi4.Contract__r = ctr;			
			//bi4.Product_Sold__c = '01t70000004ZFMy'; //website
			insert bi4;		

			Billing_Item__c bi3 = new Billing_Item__c(Contract__c = ctr.Id,Product_Sold__c ='01t70000004ZFL1');
			//bi3.Contract__r = ctr;						
			//bi3.Product_Sold__c = '01t70000004ZFL1'; //ILM
			insert bi3;			
						
			//Billing_Item__c bi2 = new Billing_Item__c(Contract__c = ctr.Id,Product_Sold__c ='01t70000004ZFJp');
			//bi2.Contract__r = ctr;						
			bi3.Product_Sold__c = '01t70000004ZFJp'; //CRM
			update bi3;
			
			
			
			test.startTest();
        	handler_updateContractCancel.updateRelatedBillingItemsCancel(new List<Contract> { ctr });        	
        	test.stopTest();
        //}        
    }
}