objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Project_Piece__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Piece</label>
        <referenceTo>Project_Piece__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Names__c</fullName>
        <inlineHelpText>what is the core product being sold</inlineHelpText>
        <label>Product Suite</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Account Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Inventory with MPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Bundle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Genius - Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Genius - With Provision Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoVisor - Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoVisor - With Provision Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUX Account Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR New Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR Used Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR Used w/ vAuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest Stand-Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Plus Desking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Plus MPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Premier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Pro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Marketing Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment Coop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak CLLC SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak CLLC SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak DM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/POA__c.object
<CustomObject>
    <description>used to handle Plan of Action items for an Account- gives the ability to group support or implementation issues together</description>
    <label>POA</label>
    <nameField>
        <label>Plan of Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POAs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup the contact at the dealership related to this specific product and assign to piece</inlineHelpText>
        <label>Product Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Pieces (Contact)</relationshipLabel>
        <relationshipName>Product_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Make__c</fullName>
        <inlineHelpText>vAuto field used by the conquest product</inlineHelpText>
        <label>Product Make</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <inlineHelpText>automatically populated from the Opportunity Products Sold</inlineHelpText>
        <label>Product Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Project Pieces</relationshipLabel>
        <relationshipName>Project_Pieces</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Approval_Stage__c</fullName>
        <inlineHelpText>Updated by the system upon milestone completion</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>1-Initiating</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>2-Planning and Design</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>3-Executing</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>4-Review</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>5-Finalizing</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Launched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-ILM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GO LIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Intro Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Strategy Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Dealer Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (Contact)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup POA for this project</inlineHelpText>
        <label>Related POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/vAuto__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting will hold anything specific to vAuto BU.</description>
    <fields>
        <fullName>Conquest_Advanced_Setup_Call_Assignee__c</fullName>
        <defaultValue>&quot;jdougherty@vauto.com&quot;</defaultValue>
        <description>User with this email will be assignee to all &quot;Advanced Setup Call&quot; tasks created for conquest project.</description>
        <inlineHelpText>User with this email will be assignee to all &quot;Advanced Setup Call&quot; tasks created for conquest project.</inlineHelpText>
        <label>Conquest Advanced Setup Call Assignee</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Integration_C_Task_Assignee__c</fullName>
        <defaultValue>&quot;mwheet@vauto.com&quot;</defaultValue>
        <description>The user with this email address will be used as Assignee when Conquest - Integration C tasks are created.</description>
        <inlineHelpText>The user with this email address will be used as Assignee when Conquest - Integration C tasks are created.</inlineHelpText>
        <label>Integration C Task Assignee</label>
        <type>Email</type>
    </fields>
    <label>vAuto</label>
</CustomObject>

classes/vAutoAsynHandler.cls
global class vAutoAsynHandler{
@future
public static void handleProjectCreation(Id projectId){
	

	
	try{

List<SFDC_520_Quote__c> projectList = [Select Id from SFDC_520_Quote__c where Id =: projectId];
  if(projectList != null && projectList.size() > 0){
  	     SFDC_520_Quote__c project = projectList[0];
  	     project.Approval_Stage__c = 'Integration';
  	     update project;
  		 handleTasksByProjectPieces(project.Id);               
  }
  else{
      System.debug('No Project found with Id: '+projectId);
  }
  
	}
	catch(Exception ex){
		 try{
		  string errorDetails = UtilityClass.DebugException(ex);
          string message = 'There has been an error in vAutoAsynHandler.handleProjectCreation '+ errorDetails;
		  Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
          String[] toAddresses = new String[] {'ramana.mosali@autotradergroup.com'};
          mail.setToAddresses(toAddresses);
          mail.setSubject('vAutoAsynHandler.handleProjectCreation Error');
          mail.setPlainTextBody(message);
          Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
		  }catch(Exception e){
		  	//Ignore if anything else fail
		  }
	}
  
     
}



private static void handleTasksByProjectPieces(Id projectId){
List<SFDC_520_Quote__c> projectList = [Select Id
, Opportunity__r.Opportunity_Names__c
, Opportunity__r.Type 
, Related_POA__c
, Related_POA__r.OwnerId 
, OwnerId
from SFDC_520_Quote__c where Id =: projectId];

  if(projectList != null && projectList.size() > 0){
	     SFDC_520_Quote__c project = projectList[0];
	     
	     if( (project.Opportunity__r.Opportunity_Names__c == 'Conquest' || project.Opportunity__r.Opportunity_Names__c == 'Conquest Stand-Alone')
	     && (
	     project.Opportunity__r.Type == 'Sale'
	     || project.Opportunity__r.Type == 'Upsell'
       || project.Opportunity__r.Type == 'Reactivate'
	     )
	     ){ 
         List<Project_Piece__c> projectPieces = [Select Id,  Product_Make__c, Product_Name__c, Contact__c from Project_Piece__c 
         where Project__c =: project.Id
         and  Product_Name__c = 'Conquest Franchise'];
         		
				//* Conquest Intro Call – Make(s)
				//Make 1 task for each unique contact from the project assets (product name = Conquest Franchise)
  				handlePOATasks(project, projectPieces);
  				
  				//* Advance Setup Call – Make(s)
  				//Make 1 task for each unique contact from the project assets (product name = Conquest Franchise)
  				handleProjectAdvSetupCallTasks(project, projectPieces);
  				
  				//* Integration C - Make
  				//1 task for each make
                handleProjectIntegarionCTasks(project, projectPieces);
	     }
  }
  else {
      System.debug('No Project found with Id: '+projectId);
  }  
}


private Static void handleProjectIntegarionCTasks(SFDC_520_Quote__c project, List<Project_Piece__c> projectPieces){
	
	
	     if(projectPieces != null && projectPieces.size() > 0){
			//get assignee user from custom setttings			
			String assigneeEmail = vAuto__c.getOrgDefaults().Integration_C_Task_Assignee__c;
			List<User> users = [Select Id from User where email =:assigneeEmail];	
			Id assigneeUserId = project.OwnerId;
			if(users!= null && users.size() > 0){
				assigneeUserId = users[0].Id;
			}
	
         	//create intro calls for each contact
         	Map<Id, Set<String>> makesByContact = new Map<Id, Set<String>>();
         	List<Task> introCallTasks = new List<Task>();
         	for(Project_Piece__c piece : projectPieces){
				//Create a task task for make
	         			Task t =CreateTask('* Integration C - '+piece.Product_Make__c, 0, assigneeUserId, project.Id,piece.Contact__c);
	         			//only add if there is a task that needs to be created
	         			if(t != null){	    
	         			introCallTasks.add(t);
	         			}		
         	}
         	
         	if(introCallTasks.size() >0){
	         			insert introCallTasks;
	         		}
	         		
         
	         	 
	         }      
	
}
/*

An intro call needs to be created on the Project for each unique product contact related to a project asset
Example: 
Project Asset Make 1 – jane doe
Project Asset Make 2 – john doe
Project Make 3 – john doe
You would create 2 intro calls
If
Make 1 – jane doe
Make 2 – john doe
Make 3 – jim doe
You would create 3 intro calls
Make 1 – jane doe
Make 2 – jane doe
Make 3 – jane doe
You would create 1 intro call
The task subject line should be formatted “* Advance Setup Call – Make(s) and the assigned to on the task would be equal to the product contact from the project asset

*/
private Static void handleProjectAdvSetupCallTasks(SFDC_520_Quote__c project, List<Project_Piece__c> projectPieces){
	
	     if(projectPieces != null && projectPieces.size() > 0){
			//get assignee user from custom setttings			
			String assigneeEmail = vAuto__c.getOrgDefaults().Conquest_Advanced_Setup_Call_Assignee__c;
			List<User> users = [Select Id from User where email =:assigneeEmail];	
			Id assigneeUserId = project.OwnerId;
			if(users!= null && users.size() > 0){
				assigneeUserId = users[0].Id;
			}
	
         	//create intro calls for each contact
         	Map<Id, Set<String>> makesByContact = new Map<Id, Set<String>>();
         	
         	for(Project_Piece__c piece : projectPieces){
         		if(!makesByContact.containsKey(piece.Contact__c)){
         			Set<String> makes = new Set<String>(); 
         			if(piece.Product_Make__c != null){    			
         			makes.add(piece.Product_Make__c);
         			}else{
         			makes.add('');}
         			makesByContact.put(piece.Contact__c,makes);
         		}
         		else{
         			//If the contact already exists
         			//get the makes list
         			Set<String> makes  = makesByContact.get(piece.Contact__c);
         			String make = '';
         			if(piece.Product_Make__c != null){    			
         			make = piece.Product_Make__c;}
         			
         			
         			if(!makes.contains(make)){
         				makes.add(make);
         			}
         			makesByContact.put(piece.Contact__c,makes);
         		}		
         	}
         	
	         //if there are contacts and makes that we need to send a intro call for
	         if(!makesByContact.isEmpty()){
	         	
	         	List<Task> introCallTasks = new List<Task>();
	         		//for each contact
	         		for(Id contactId : makesByContact.keySet()){
	         			Set<String> makes = makesByContact.get(contactId);
	         			String csvMakes ='';
	         			//build a comma saperated makes list
	         			for(String make : makes){
	         				csvMakes += (csvMakes ==''? '':',')+make;
	         			}
	         			
	         			//Create a task for the contact
	         			Task t =CreateTask('* Advance Setup Call  – '+csvMakes, 0, assigneeUserId, project.Id,contactId);
	         			//only add if there is a task that needs to be created
	         			if(t != null){	         				
	         			introCallTasks.add(t);
	         			}
	         		}
	         		
	         		if(introCallTasks.size() >0){
	         			insert introCallTasks;
	         		}
	         }
	         	 
	         }      
	
}

/*

An intro call needs to be created on the POA for each unique product contact related to a project asset
Example: 
Project Asset Make 1 – jane doe
Project Asset Make 2 – john doe
Project Make 3 – john doe
You would create 2 intro calls
If
Make 1 – jane doe
Make 2 – john doe
Make 3 – jim doe
You would create 3 intro calls
Make 1 – jane doe
Make 2 – jane doe
Make 3 – jane doe
You would create 1 intro call
The task subject line should be formatted “*Conquest Intro Call – Make and the assigned to on the task would be equal to the product contact from the project asset

*/
private Static void handlePOATasks(SFDC_520_Quote__c project, List<Project_Piece__c> projectPieces){
	         if(projectPieces != null && projectPieces.size() > 0){
         	//create intro calls for each contact
         	Map<Id, Set<String>> makesByContact = new Map<Id, Set<String>>();
         	
         	for(Project_Piece__c piece : projectPieces){
         		if(!makesByContact.containsKey(piece.Contact__c)){
         			Set<String> makes = new Set<String>(); 
         			if(piece.Product_Make__c != null){    			
         			makes.add(piece.Product_Make__c);
         			}else{
         			makes.add('');}
         			makesByContact.put(piece.Contact__c,makes);
         		}
         		else{
         			//If the contact already exists
         			//get the makes list
         			Set<String> makes  = makesByContact.get(piece.Contact__c);
         			String make = '';
         			if(piece.Product_Make__c != null){    			
         			make = piece.Product_Make__c;}
         			
         			
         			if(!makes.contains(make)){
         				makes.add(make);
         			}
         			makesByContact.put(piece.Contact__c,makes);
         		}		
         	}
         	
         //if there are contacts and makes that we need to send a intro call for
         if(!makesByContact.isEmpty()){
         	
         	List<Task> introCallTasks = new List<Task>();
         		//for each contact
         		for(Id contactId : makesByContact.keySet()){
         			Set<String> makes = makesByContact.get(contactId);
         			String csvMakes ='';
         			//build a comma saperated makes list
         			for(String make : makes){
         				csvMakes += (csvMakes ==''? '':',')+make;
         			}
         			
         			//Create a task an intro call for the contact
         			Task t =CreateTask('*Conquest Intro Call – '+csvMakes, 0, project.Related_POA__r.OwnerId, project.Related_POA__c,contactId);
         			//only add if there is a task that needs to be created
         			if(t != null){
         			introCallTasks.add(t);
         			}
         		}
         		
         		if(introCallTasks.size() >0){
         			insert introCallTasks;
         		}
         }
         	 
         }      
}

   private Static Task CreateTask(String subject, Integer dueInDays, Id ownerId, Id whatId, Id whoId){
   	
   	      //check if the task created
      List<Task> tasks = [Select Id from Task where 
      ownerId=:ownerId
      and whatId=:whatId
      and Subject =: subject
      and Status =: 'Not Started'
      and WhoId =: whoId];
      
      if(tasks == null || tasks.size() == 0){
		Task task = new Task();
		task.Subject =  subject;
		task.ActivityDate = System.today().addDays(dueInDays);
		task.OwnerId = ownerId;
		task.WhatId = whatId;
		task.WhoId = whoId;
		return task;
      }
      else{
      	System.debug('Task with subject:'+subject+ 'already exists;');
      	return null;
      }
}

}