objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Project_Piece__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Piece</label>
        <referenceTo>Project_Piece__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>LOB_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned WriteOff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Needs Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Needs Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Pre Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - SVOC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Temp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transitioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Triage</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Old_Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Project_Piece__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project Asset</label>
        <referenceTo>Project_Piece__c</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>Add a new line item to a billing contract</description>
        <label>ADD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Product_Name__c</fullName>
        <inlineHelpText>automatically populated from the Opportunity Products Sold</inlineHelpText>
        <label>Product Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Approval_Stage__c</fullName>
        <inlineHelpText>Updated by the system upon milestone completion</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>1-Initiating</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>2-Planning and Design</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>3-Executing</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>4-Review</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>5-Finalizing</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Launched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-ILM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GO LIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Intro Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Strategy Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Dealer Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training 1</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Complete_Date__c</fullName>
        <inlineHelpText>When the Stage is updated to Completed, Go Live, or Design, workflow updates the date through workflow rule</inlineHelpText>
        <label>Work Complete Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/handler_Project.cls
public with sharing class handler_Project {
    
    
    //Pavan Hegde--- Start--> W-1157,W-1140,W-1158 ---> Converted The process Builders, Flows to below method
    public static void BuildAssetRecUpdate(List<SFDC_520_Quote__c> project){
        Set<Id> projectId = new Set<Id>();
        Set<Id> projectAssetId = new Set<Id>();
        Map<Id,List<Project_Piece__c>> projectAssetMap = new Map<Id,List<Project_Piece__c>>();
        Map<Id,List<Billing_Item__c>> BilledAssetMap = new Map<Id,List<Billing_Item__c>>();
        for(SFDC_520_Quote__c proj: project){
            projectId.add(proj.id); // add projectIds to a set
        }     
        //querying projectAsset records
        List<Project_Piece__c> projectAssets = [select id,name,Project__c,Product_Name__c from Project_Piece__c where Project__c in : projectId ];
        // processing all projectAsset records
        for(Project_Piece__c ps :projectAssets ){
        
        // Creating a temporary List for copying the Project Asset data, as duplicate keys cannot be inserted in the map,
        // One Project may have multiple Project Assets, hence Temporary list is needed.
            if( !projectAssetMap.containsKey(ps.Project__c))
            {   
                List<Project_Piece__c> tempList = new List<Project_Piece__c>();
                tempList.add(ps);
                projectAssetMap.put(ps.Project__c, tempList);   
            }
            else
            {
                List<Project_Piece__c> tempList = projectAssetMap.get(ps.Project__c);
                tempList.add(ps);
                projectAssetMap.put(ps.Project__c, tempList);
            }   
            
            projectAssetId.add(ps.id);
        }
        // get the Billed assets records, related to project asset.
        List<Billing_Item__c> billingItems = [select id,name,Related_Project_Piece__c from Billing_Item__c where Related_Project_Piece__c in : projectAssetId];
        for(Billing_Item__c bi : billingItems){
            if( !BilledAssetMap.containsKey(bi.Related_Project_Piece__c))
            {   
                List<Billing_Item__c> tempList = new List<Billing_Item__c>();
                tempList.add(bi);
                BilledAssetMap.put(bi.Related_Project_Piece__c, tempList);   
            }
            else
            {
                List<Billing_Item__c> tempList = BilledAssetMap.get(bi.Related_Project_Piece__c);
                tempList.add(bi);
                BilledAssetMap.put(bi.Related_Project_Piece__c, tempList);
            }       
        }   
        Map<ID,Billing_Item__c> BillingAssetUpdateMap = new Map<ID,Billing_Item__c>{};
            for(SFDC_520_Quote__c proj: project){ 
            
            // Setting the Status of Billed asset, based on Project's Stage and also if the Completed date on Project is not null
            // Setting of status of Billed asset is based on stories--> W-1157,W-1140,W-1158
               
                if(proj.Project_Complete_Date__c != null){
                    List<Project_Piece__C> pAssetsPendLaunchApp = projectAssetMap.get(proj.id);
                    if( pAssetsPendLaunchApp != null){
                        for(Project_Piece__c pAsset : pAssetsPendLaunchApp){
                            if(pAsset.Product_Name__c == 'Stockwave'){
                                List<Billing_Item__c> BillingAssets = BilledAssetMap.get(pAsset.id);
                                for(Billing_Item__c bi :BillingAssets){
                                    bi.LOB_Status__c = 'Pending Launch Approval';
                                    BillingAssetUpdateMap.put(bi.id, bi);
                                    system.debug('entered completed date');
                                }
                            }
                        }
                    }
                }
                    if(proj.Approval_Stage__c == 'Integration'){
                        List<Project_Piece__C> pAssets = projectAssetMap.get(proj.id);
                        if(pAssets != null){
                            for(Project_Piece__c pAsset : pAssets){
                                if(pAsset.Product_Name__c == 'Stockwave'){
                                    List<Billing_Item__c> BillingAssets = BilledAssetMap.get(pAsset.id);
                                    for(Billing_Item__c bi :BillingAssets){
                                        bi.LOB_Status__c = 'Pending Needs Data';
                                        BillingAssetUpdateMap.put(bi.id, bi);    
                                        system.debug('entered integration');
                                    }
                                }
                            }
                        }
                    }
                    if(proj.Approval_Stage__c == 'Training 1'){
                        List<Project_Piece__C> pAssets = projectAssetMap.get(proj.id);
                        if(pAssets.size()>0 && pAssets != null){
                            for(Project_Piece__c pAsset : pAssets){
                                if(pAsset.Product_Name__c == 'Stockwave'){
                                    List<Billing_Item__c> BillingAssets = BilledAssetMap.get(pAsset.id);
                                    for(Billing_Item__c bi :BillingAssets){
                                        bi.LOB_Status__c = 'Pending needs Training';
                                        BillingAssetUpdateMap.put(bi.id, bi);  
                                        system.debug('entered training 1');
                                    }
                                }
                            }
                        }
                    }
                
                if(BillingAssetUpdateMap.values().size()>0 ){
                    update BillingAssetUpdateMap.values();
                }
            }    
    }
}