objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>LOB_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned WriteOff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Needs Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Needs Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Pre Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - SVOC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Temp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transitioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Triage</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <description>The reference point for whether this Billed Asset is active or not. Based on the BI&apos;s record type.</description>
        <formula>IF( 
Business_Unit__c = &quot;VinSolutions&quot;, 
CASE(RecordType.DeveloperName, 
&quot;ADD&quot;, &quot;Inactive&quot;, 
&quot;CANCEL&quot;,&quot;Inactive&quot;, 
&quot;Locked&quot;, &quot;Inactive&quot; , 
&quot;Active&quot; 
), 
IF( 
Business_Unit__c = &quot;vAuto&quot;, 
IF( 
RecordType.DeveloperName = &quot;ADD&quot; &amp;&amp; ISBLANK(Active_Date__c), 
&quot;Pending&quot;, 
IF( 
RecordType.DeveloperName = &quot;ADD&quot; &amp;&amp; !ISBLANK(Active_Date__c), 
&quot;Active&quot;, 
IF( 
RecordType.DeveloperName = &quot;Process_Stop&quot; , 
&quot;Active&quot;, 
IF( 
RecordType.DeveloperName = &quot;MODIFY&quot; , 
&quot;Active&quot;, 
IF( 
RecordType.DeveloperName = &quot;Locked&quot; &amp;&amp;  !ISBLANK(Active_Date__c)  &amp;&amp;  ISBLANK(End_Date__c) , 
&quot;Active&quot;, 
&quot;Inactive&quot; 

) 
) 
) 
) 
), 
&quot;Not Applicable&quot; 
) 
)</formula>
        <inlineHelpText>The reference point for whether this Billed Asset is active or not. Based on the BI&apos;s record type.</inlineHelpText>
        <label>Billed Asset Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>physical location of the asset</inlineHelpText>
        <label>Subscriber Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billed Assets (Subscriber Account)</relationshipLabel>
        <relationshipName>Billed_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suite_Name__c</fullName>
        <formula>TEXT(Product_Sold__r.Product_Suite__c)</formula>
        <inlineHelpText>Formula field that reads the Product Sold name and gives it a different column header for the related list on the POA</inlineHelpText>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isBaseAsset__c</fullName>
        <description>This lookup identifies if the Asset is a Base or not</description>
        <formula>Product_Sold__r.Base_Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isBaseAsset</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vAuto_Activation_Date__c</fullName>
        <description>change requested per Michelle D 1/28/2105 per CR-00011658</description>
        <formula>Active_Date__c</formula>
        <inlineHelpText>formula field that reads the asset active date and sets it as the activation date</inlineHelpText>
        <label>vAuto Activation Date</label>
        <type>Date</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>Add a new line item to a billing contract</description>
        <label>ADD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/vAutoSubscriberProductInfo.cls
public with sharing class vAutoSubscriberProductInfo {

	// Class Variables 
    public List<Billing_Item__c> billedAssets{get;set;}
    public String ACCTId{get;set;}
    public SubscriberAssetWrapper SAWrap{get;set;}//Class
    public List<SubscriberAssetWrapper> SAWrapList{get;set;}//List of records in the class
    public Integer numOfRows{get;set;}
	private ApexPages.StandardController stdController;

	// Constructor
	public vAutoSubscriberProductInfo(ApexPages.StandardController stdController){
		this.stdController = stdController;
        ACCTId = String.valueOf(stdController.getRecord().get('id'));
        getBilledAssets();
        initializeSubscriberAssetWrapper();
	}

	//Grabbing the vAuto Billed Assets from the Account.
    public void getBilledAssets(){
        if (ACCTId != null) {
	        try{
                billedAssets = 	[SELECT Id, Name, Subscriber_Account__c, Suite_Name__c, LOB_Status__c, vAuto_Activation_Date__c, isBaseAsset__c, Product_Status__c
                               	   FROM Billing_Item__c
                               	  WHERE Subscriber_Account__c =: ACCTId AND isBaseAsset__c = true AND Product_Status__c = 'Active'];
            	numOfRows = billedAssets.size();
            }
	        catch (exception e) {
	            System.debug('getBilledAssets() encountered an exception: ' + e.getMessage());
	            throw e;
	        }
        }
        else{
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Unable to retrieve an AccountId.');
            ApexPages.addMessage(myMsg);
        }
    }
	
    public void initializeSubscriberAssetWrapper() {
        SAWrapList = null;
        if (billedAssets != null && billedAssets.size() > 0){
            SAWrapList = new List<SubscriberAssetWrapper>();
            for (Billing_Item__c bi : billedAssets) {
            	if(bi.Suite_Name__c == 'Auction Genius'
            	|| bi.Suite_Name__c == 'Provision'
            	|| bi.Suite_Name__c == 'Conquest'
            	|| bi.Suite_Name__c == 'KBB PAR Used'
            	|| bi.Suite_Name__c == 'KBB PAR New'){
            		SAWrap = new SubscriberAssetWrapper();
                	SAWrap.ProductName = bi.Suite_Name__c;
                	SAWrap.ProductStatus = bi.LOB_Status__c;
                	SAWrap.ActivationDate = bi.vAuto_Activation_Date__c.format();
                	SAWrapList.add(SAWrap);
                }
                else{
                	continue;
                }
            }
        }
    }

    // Class
    public class SubscriberAssetWrapper{
        public String ProductName{get;set;}
        public String ProductStatus{get;set;}
        public String ActivationDate{get;set;}
    }

}