objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ready_to_Bill__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This field is updated when you are ready to send the Contract and Billed Assets to AutoTrader for billing</inlineHelpText>
        <label>Ready to Bill</label>
        <type>Checkbox</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>Add a new line item to a billing contract</description>
        <label>ADD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Ready_to_Bill__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>updated by the user when the contract and billing items are ready to bill to RMB</inlineHelpText>
        <label>Ready to Bill</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>use to add a new contract (order) to the AutoTrader Billing System</description>
        <label>ADD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/handler_updateContractReadyToBill.cls
public with sharing class handler_updateContractReadyToBill {
	
	public static void updateRelatedBillingItemsReadyToBill(List<Contract> contracts) {
		
		Set<Id> contractIds = new Set<Id>();
		
		for(Contract c : contracts) {
								//add 012V00000000FaA
			if(c.RecordTypeId == '01270000000Q9vU' && c.Ready_To_Bill__c == true) {
				
				contractIds.add(c.Id);
			}
		}
		
		if(contractIds.size() > 0) {
		
			List<Billing_Item__c> updateBillingItems = new List<Billing_Item__c>();
			
			updateBillingItems = [SELECT Id, Ready_To_Bill__c
								  FROM Billing_Item__c
								  WHERE Contract__c IN :contractIds];
								  
			for(Billing_Item__c bi : updateBillingItems) {
				
				bi.Ready_To_Bill__c = true;
			}							  
			
			try {
				
				update updateBillingItems;
				
				//Exception Testing and handling
	        	if(utility.throwExceptionError() == true){
	        		string Ex = null;
	        		Ex.tolowercase();
	        	}
			}
			catch(Exception e) {
				//do nothing
			}
		
		}
	}

}