objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Project_Type__c</fullName>
        <formula>Related_Project_Piece__r.Project__r.Project_Type__c</formula>
        <inlineHelpText>Formula that pulls from the Project&apos;s Type</inlineHelpText>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Old_Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup the POA that the account manager will use to manage this asset</inlineHelpText>
        <label>Related POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>Add a new line item to a billing contract</description>
        <label>ADD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Add_Deposit__c</fullName>
        <inlineHelpText>default set to Yes, please update to No if the deposit is being waived</inlineHelpText>
        <label>Add Deposit?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Names__c</fullName>
        <inlineHelpText>what is the core product being sold</inlineHelpText>
        <label>Product Suite</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Account Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Inventory with MPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Bundle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Genius - Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Genius - With Provision Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoVisor - Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoVisor - With Provision Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUX Account Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR New Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR Used Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR Used w/ vAuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest Stand-Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Plus Desking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Plus MPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Premier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Pro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Marketing Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment Coop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak CLLC SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak CLLC SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Module Upsell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <businessProcess>vAuto</businessProcess>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Opportunity_Line_Item_ID__c</fullName>
        <label>Opportunity Line Item ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <formula>Project__r.Project_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Project Pieces</relationshipLabel>
        <relationshipName>Project_Pieces</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Approval_Stage__c</fullName>
        <inlineHelpText>Updated by the system upon milestone completion</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>1-Initiating</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>2-Planning and Design</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>3-Executing</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>4-Review</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>5-Finalizing</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Launched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-ILM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GO LIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Intro Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Strategy Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Dealer Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training 2</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <inlineHelpText>Uses the Opportunity&apos;s Product Suite and is updated by the Trigger</inlineHelpText>
        <label>Opp Product Suite</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup POA for this project</inlineHelpText>
        <label>Related POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <description>This is the type for all vAuto Projects</description>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/vAutoProjectHandler_Test.cls
@isTest(SeeAllData=true) 
public  class vAutoProjectHandler_Test {


  static testMethod void CheckingProjectNames() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
    
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
      opp.Opportunity_Names__c = 'Trial';                       
      opp.Add_Deposit__c = 'No';
      opp.Type = 'Site Module Upsell';  
                      
      update opp;
      Product2 prod1 = Test_vAutoOpportunity.getProduct('ProVisioning');

        
      OpportunityLineItem  oppLine1 = Test_vAutoOpportunity.createOppProduct(opp,prod1);
      
      List<OpportunityLineItem> oppLines = new List<OpportunityLineItem>();
      oppLines.add(oppLine1);
            insert oppLines;
             
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Name,Approval_Stage__c ,Project_Type__c,RecordTypeId,Related_POA__c  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];

      //check that project names are valid
      for(SFDC_520_Quote__c proj : projects){
        system.debug('Proj.Name: '+proj.Name);
        //System.assert(proj.Name == '', '')
      }
  }



  static testMethod void AutionGenius_ApprovalStage_IntegrationComplete() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
    
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
    Test_vAutoOpportunity.setupAuctionGeniusOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Project_Type__c,RecordTypeId,Related_POA__c  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        

                  
      //update the project Approval statge 
      system.assert( project.Approval_Stage__c != 'Integration Complete','Project is already in Integration Complete Stage');
      project.Approval_Stage__c = 'Integration Complete';
      update project;
      
                 //find all the related billing Items for above project pieces
   //which are marked with LOB; to showup as product suites/status in POA
   List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id,LOB_Status__c from Billing_Item__c where Related_Project_Piece__c IN :projPieces
                  AND LOB__c !=null];
                  
  System.Assert(billingItemsMarkedWithLOB != null,'No Billing Items Marked as product suites');
    System.Assert(billingItemsMarkedWithLOB.size() > 0,'No Billing Items Marked as product suites'); 
                  
      //check if the related LOB Billed Items status updated.
   for(Billing_Item__c item : billingItemsMarkedWithLOB){
      system.assert(item.LOB_Status__c=='Pending Needs Training','Project Approval Stage set to Intergation Complete but LOB Billed Items Status not chaanged to Pending Needs Training');        
   }
           

      
      
  }

    static testMethod void AutionGenius_ApprovalStage_Completed() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
    
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
    Test_vAutoOpportunity.setupAuctionGeniusOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Status__c,Project_Type__c,RecordTypeId,Related_POA__c,Related_POA__r.OwnerId  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        

                  
      //update the project Approval statge 
      system.assert( project.Status__c != 'Completed','Project status is already completed; Approval_Stage__c changes will not be triggered');
      system.assert( project.Approval_Stage__c != 'Completed','Project is already in Completed Stage');
      project.Approval_Stage__c = 'Completed';
      update project;
      
                 //find all the related billing Items for above project pieces
   //which are marked with LOB; to showup as product suites/status in POA
   List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id,LOB_Status__c from Billing_Item__c where Related_Project_Piece__c IN :projPieces
                  AND LOB__c !=null];

  System.Assert(billingItemsMarkedWithLOB != null,'No Billing Items Marked as product suites');
    System.Assert(billingItemsMarkedWithLOB.size() > 0,'No Billing Items Marked as product suites'); 
    System.Assert(billingItemsMarkedWithLOB.size() ==1,'Expecting only one Billing Item Marked as product suites found:'+billingItemsMarkedWithLOB.size()); 
                      
      //check if the related LOB Billed Items status updated.
   for(Billing_Item__c item : billingItemsMarkedWithLOB){
      system.assert(item.LOB_Status__c=='Good','Project Approval Stage set to Completed but LOB Billed Items Status not chaanged to Good');        
   }

  }

static testMethod void Provision_ApprovalStage_IntegrationComplete() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
  	
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
	  Test_vAutoOpportunity.setupProvisionOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Project_Type__c,RecordTypeId,Related_POA__c  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        

   								
      //update the project Approval statge 
      system.assert( project.Approval_Stage__c != 'Integration Complete','Project is already in Integration Complete Stage');
      project.Approval_Stage__c = 'Integration Complete';
      update project;
      
                 //find all the related billing Items for above project pieces
   //which are marked with LOB; to showup as product suites/status in POA
   List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id,LOB_Status__c from Billing_Item__c where Related_Project_Piece__c IN :projPieces
   								AND LOB__c !=null];
   								
  System.Assert(billingItemsMarkedWithLOB != null,'No Billing Items Marked as product suites');
    System.Assert(billingItemsMarkedWithLOB.size() > 0,'No Billing Items Marked as product suites'); 
   								
      //check if the related LOB Billed Items status updated.
   for(Billing_Item__c item : billingItemsMarkedWithLOB){
   		system.assert(item.LOB_Status__c=='Pending Needs Training','Project Approval Stage set to Intergation Complete but LOB Billed Items Status not chaanged to Pending Needs Training');	   	  
   }
           

      
      
	}
      	static testMethod void Provision_ApprovalStage_Training2() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
  	
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
	  Test_vAutoOpportunity.setupProvisionOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Project_Type__c,RecordTypeId,Related_POA__c,Related_POA__r.OwnerId  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        

   								
      //update the project Approval statge
      system.assert( project.Approval_Stage__c != 'Training 2','Project is already in Training 2 Stage');
      project.Approval_Stage__c = 'Training 2';
      update project;
      
                 //find all the related billing Items for above project pieces
   //which are marked with LOB; to showup as product suites/status in POA
   List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id,LOB_Status__c from Billing_Item__c where Related_Project_Piece__c IN :projPieces
   								AND LOB__c !=null];

  System.Assert(billingItemsMarkedWithLOB != null,'No Billing Items Marked as product suites');
    System.Assert(billingItemsMarkedWithLOB.size() > 0,'No Billing Items Marked as product suites');
       								
      //check if the related LOB Billed Items status updated.
   for(Billing_Item__c item : billingItemsMarkedWithLOB){
   		system.assert(item.LOB_Status__c=='Pending Launch Approval','Project Approval Stage set to Training 2 but LOB Billed Items Status not chaanged to Pending Launch Apporoval');	   	  
   }
      
      //check if the task created
      List<Task> tasks = [Select Id from Task where 
      ownerId=:project.Related_POA__r.OwnerId 
      and whatId=:project.Related_POA__c
      and Subject = '* 1st PM Call'];
      
    System.Assert(tasks != null,'No Tasks got created as expected');
    System.Assert(tasks.size() > 0,'No Tasks got created as expected');
      System.Assert(tasks.size() ==1 ,'More than one Task got created');
	}
	
	static testMethod void Conquest_ApprovalStage_IntegrationComplete() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
  	
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
	  Test_vAutoOpportunity.setupConquestOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Project_Type__c,RecordTypeId,Related_POA__c  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        

   								
      //update the project Approval statge 
      system.assert( project.Approval_Stage__c != 'Integration Complete','Project is already in Integration Complete Stage');
      project.Approval_Stage__c = 'Integration Complete';
      update project;
      
                 //find all the related billing Items for above project pieces
   //which are marked with LOB; to showup as product suites/status in POA
   List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id,LOB_Status__c from Billing_Item__c where Related_Project_Piece__c IN :projPieces
   								AND LOB__c !=null];
   								
  System.Assert(billingItemsMarkedWithLOB != null,'No Billing Items Marked as product suites');
    System.Assert(billingItemsMarkedWithLOB.size() > 0,'No Billing Items Marked as product suites'); 
    
   								
      //check if the related LOB Billed Items status updated.
   for(Billing_Item__c item : billingItemsMarkedWithLOB){
   		system.assert(item.LOB_Status__c=='Pending Needs Training','Project Approval Stage set to Intergation Complete but LOB Billed Items Status not chaanged to Pending Needs Training');	   	  
   }
           

      
      
	}
	
		static testMethod void Conquest_ApprovalStage_Completed() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
  	
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
	  Test_vAutoOpportunity.setupConquestOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Status__c,Project_Type__c,RecordTypeId,Related_POA__c,Related_POA__r.OwnerId  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        

   								
      //update the project Approval statge 
      system.assert( project.Status__c != 'Completed','Project status is already completed; Approval_Stage__c changes will not be triggered');
      system.assert( project.Approval_Stage__c != 'Completed','Project is already in Completed Stage');
      project.Approval_Stage__c = 'Completed';
      update project;
      
                 //find all the related billing Items for above project pieces
   //which are marked with LOB; to showup as product suites/status in POA
   List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id,LOB_Status__c from Billing_Item__c where Related_Project_Piece__c IN :projPieces
   								AND LOB__c !=null];

  System.Assert(billingItemsMarkedWithLOB != null,'No Billing Items Marked as product suites');
    System.Assert(billingItemsMarkedWithLOB.size() > 0,'No Billing Items Marked as product suites'); 
    System.Assert(billingItemsMarkedWithLOB.size() ==1,'Expecting only one Billing Item Marked as product suites found:'+billingItemsMarkedWithLOB.size()); 
       								
      //check if the related LOB Billed Items status updated.
   for(Billing_Item__c item : billingItemsMarkedWithLOB){
   		system.assert(item.LOB_Status__c=='Pending Launch Approval','Project Approval Stage set to Completed but LOB Billed Items Status not chaanged to Pending Launch Apporoval');	   	  
   }
      
      //check if the task created
      List<Task> tasks = [Select Id from Task where 
      ownerId=:project.Related_POA__r.OwnerId 
      and whatId=:project.Related_POA__c
      and Subject = '* 1st PM Call'];
      
    System.Assert(tasks.size() == 0,'Unexcpected Tasks got created');
	}
	
	
			static testMethod void ConquestFranchise_IntroCallsByContactAndMake() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
  	
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
	  Test_vAutoOpportunity.setupConquestFranchiseSaleOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Status__c,Project_Type__c,RecordTypeId,Related_POA__c,Related_POA__r.OwnerId  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      //since the Opportunity as 3 makes and 2 contacts 
      // we expect the code to generate 2 Intro calls one for each contact and combine the makes for same contact
       Product2 prod2 = Test_vAutoOpportunity.getProduct('Conquest Franchise');
       PricebookEntry pe =  Test_vAutoOpportunity.getPricebookEntry(prod2);
      
      List<OpportunityLineItem> conquestFranchiseLines = [Select Product_Contact__c,Make__c from OpportunityLineItem where OpportunityId=: opp.Id
      and PricebookEntryId =: pe.Id];
      
      System.Assert(conquestFranchiseLines.size() ==3,'There are 3 lines expected but found:'+conquestFranchiseLines.size());
      
      Map<Id, Set<String>> makesByContact = new Map<Id, Set<String>>();
      
      	for(OpportunityLineItem line : conquestFranchiseLines){
      		
      		system.debug('Test Processing: '+line.Product_Contact__c + ' Make: '+line.Make__c);
         		if(!makesByContact.containsKey(line.Product_Contact__c)){
         			Set<String> makes = new Set<String>(); 
         			if(line.Make__c != null){    			
         			makes.add(line.Make__c);
         			}else{
         			makes.add('');}
         			makesByContact.put(line.Product_Contact__c,makes);
         		}
         		else{
         			//If the contact already exists
         			//get the makes list
         			Set<String> makes  = makesByContact.get(line.Product_Contact__c);
         			String make = '';
         			if(line.Make__c != null){    			
         			make = line.Make__c;}
         			
         			
         			if(!makes.contains(make)){
         				makes.add(make);
         			}
         			makesByContact.put(line.Product_Contact__c,makes);
         		}		
         	}
         	
         	System.Assert( makesByContact.size()==2, 'There are 2 contacts expected but found: '+makesByContact.size());
         	
         	//for each contact
         		for(Id contactId : makesByContact.keySet()){
         	Set<String> makes = makesByContact.get(contactId);
         			String csvMakes ='';
         			//build a comma saperated makes list
         			for(String make : makes){
         				csvMakes += (csvMakes ==''? '':',')+make;
         			}
      String subject = '*Conquest Intro Call – '+csvMakes;
            List<Task> tasks = [Select Id from Task where 
      ownerId=:project.Related_POA__r.OwnerId
      and whatId=:project.Related_POA__c
      and Subject =: subject 
      and Status =: 'Not Started'
      and WhoId =: contactId];
      
      	  System.Assert(tasks != null,'No Tasks got created as expected for contact:'+contactId + ' and makes: '+ csvMakes);
    System.Assert(tasks.size() > 0,'No Tasks got created as expected for contact:'+contactId + ' and makes: '+ csvMakes);
      System.Assert(tasks.size() ==1 ,'No Tasks got created as expected for contact:'+contactId + ' and makes: '+ csvMakes);
         		}
      
}

	static testMethod void ConquestFranchise_AdvanceSetupCallByContactAndMake() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
  	
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
	  Test_vAutoOpportunity.setupConquestFranchiseSaleOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.      
      List<SFDC_520_Quote__c> projects = [Select Id,OwnerId, Approval_Stage__c ,Status__c,Project_Type__c,RecordTypeId,Related_POA__c,Related_POA__r.OwnerId  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      //since the Opportunity as 3 makes and 2 contacts 
      // we expect the code to generate 2 Intro calls one for each contact and combine the makes for same contact
       Product2 prod2 = Test_vAutoOpportunity.getProduct('Conquest Franchise');
       PricebookEntry pe =  Test_vAutoOpportunity.getPricebookEntry(prod2);
      
      List<OpportunityLineItem> conquestFranchiseLines = [Select Product_Contact__c,Make__c from OpportunityLineItem where OpportunityId=: opp.Id
      and PricebookEntryId =: pe.Id];
      
      System.Assert(conquestFranchiseLines.size() ==3,'There are 3 lines expected but found:'+conquestFranchiseLines.size());
      
      Map<Id, Set<String>> makesByContact = new Map<Id, Set<String>>();
      
      	for(OpportunityLineItem line : conquestFranchiseLines){
      		
      		system.debug('Test Processing: '+line.Product_Contact__c + ' Make: '+line.Make__c);
         		if(!makesByContact.containsKey(line.Product_Contact__c)){
         			Set<String> makes = new Set<String>(); 
         			if(line.Make__c != null){    			
         			makes.add(line.Make__c);
         			}else{
         			makes.add('');}
         			makesByContact.put(line.Product_Contact__c,makes);
         		}
         		else{
         			//If the contact already exists
         			//get the makes list
         			Set<String> makes  = makesByContact.get(line.Product_Contact__c);
         			String make = '';
         			if(line.Make__c != null){    			
         			make = line.Make__c;}
         			
         			
         			if(!makes.contains(make)){
         				makes.add(make);
         			}
         			makesByContact.put(line.Product_Contact__c,makes);
         		}		
         	}
         	
         	System.Assert( makesByContact.size()==2, 'There are 2 contacts expected but found: '+makesByContact.size());
         	
         	//get assignee user from custom setttings			
			String assigneeEmail = vAuto__c.getOrgDefaults().Conquest_Advanced_Setup_Call_Assignee__c;
				SYstem.Assert(assigneeEmail != null,'NO value for Conquest_Advanced_Setup_Call_Assignee__c in vAuto__c custom setting');
	SYstem.Assert(assigneeEmail != '','Empty value for Conquest_Advanced_Setup_Call_Assignee__c in vAuto__c custom setting');
	
			List<User> users = [Select Id,User_Full_Name__c from User where email =:assigneeEmail];	
			Id assigneeUserId = project.OwnerId;
				system.assert(users!= null,'No users with email: '+assigneeEmail);
	system.assert(users.size() != 0,'No users with email: '+assigneeEmail);
			if(users!= null && users.size() > 0){
				system.assert(users[0].User_Full_Name__c == 'Joe Dougherty','* Conquest Monthly Billing Task (MM) task  is not assigned to Joe Dougherty');
				assigneeUserId = users[0].Id;
			}
			
         	//for each contact
         		for(Id contactId : makesByContact.keySet()){
         	Set<String> makes = makesByContact.get(contactId);
         			String csvMakes ='';
         			//build a comma saperated makes list
         			for(String make : makes){
         				csvMakes += (csvMakes ==''? '':',')+make;
         			}
      String subject = '* Advance Setup Call  – '+csvMakes;
            List<Task> tasks = [Select Id from Task where 
      ownerId=:assigneeUserId
      and whatId=:project.Id
      and Subject =: subject 
      and Status =: 'Not Started'
      and WhoId =: contactId];
      
      	  System.Assert(tasks != null,'No Tasks got created as expected for contact:'+contactId + ' and makes: '+ csvMakes);
    System.Assert(tasks.size() > 0,'No Tasks got created as expected for contact:'+contactId + ' and makes: '+ csvMakes);
      System.Assert(tasks.size() ==1 ,'No Tasks got created as expected for contact:'+contactId + ' and makes: '+ csvMakes);
         		}
      
}

	static testMethod void ConquestFranchise_IntegrationCallTask() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
  	
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
	  Test_vAutoOpportunity.setupConquestFranchiseSaleOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.      
      List<SFDC_520_Quote__c> projects = [Select Id,OwnerId, Approval_Stage__c ,Status__c,Project_Type__c,RecordTypeId,Related_POA__c,Related_POA__r.OwnerId  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      //since the Opportunity as 3 makes and 2 contacts 
      // we expect the code to generate 2 Intro calls one for each contact and combine the makes for same contact
       Product2 prod2 = Test_vAutoOpportunity.getProduct('Conquest Franchise');
       PricebookEntry pe =  Test_vAutoOpportunity.getPricebookEntry(prod2);
      
      List<OpportunityLineItem> conquestFranchiseLines = [Select Product_Contact__c,Make__c from OpportunityLineItem where OpportunityId=: opp.Id
      and PricebookEntryId =: pe.Id];
      
      System.Assert(conquestFranchiseLines.size() ==3,'There are 3 lines expected but found:'+conquestFranchiseLines.size());
      
      Map<String,Id> mapMakes = new Map<String,Id>();
      
      	for(OpportunityLineItem line : conquestFranchiseLines){
      		
      		
      		system.debug('Test Processing: '+line.Product_Contact__c + ' Make: '+line.Make__c);
         		if(!mapMakes.containsKey(line.Make__c)){			
         			mapMakes.put(line.Make__c,line.Product_Contact__c);
         		}
         	}
         	
         	System.Assert( mapMakes.size()==3, 'There are 3 makes expected but found: '+mapMakes.size());
         	
         	//get assignee user from custom setttings			
			String assigneeEmail = vAuto__c.getOrgDefaults().Integration_C_Task_Assignee__c;
			List<User> users = [Select Id from User where email =:assigneeEmail];	
			Id assigneeUserId = project.OwnerId;
			if(users!= null && users.size() > 0){
				assigneeUserId = users[0].Id;
			}
			
         	//for each contact
         		for(String make : mapMakes.keySet()){      
         			  Id contactId =  mapMakes.get(make);  	
				      String subject = '* Integration C - '+make;
				      List<Task> tasks = [Select Id from Task where 
				      ownerId=:assigneeUserId
				      and whatId=:project.Id
				      and Subject =: subject 
				      and Status =: 'Not Started'
				      and WhoId =:contactId ];
				      
				      	  System.Assert(tasks != null,'No Tasks got created as expected for make: '+ make + ' contact:'+contactId);
				    System.Assert(tasks.size() > 0,'No Tasks got created as expected for make: '+ make + ' contact:'+contactId);
				      System.Assert(tasks.size() ==1 ,'No Tasks got created as expected for make: '+ make + ' contact:'+contactId);
         		}
      
}

}