objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>Contract__r.Business_Unit__c</formula>
        <inlineHelpText>Which Business Unit is associated with this Billed Asset. Pulls from the Contract field, which in turn pulls from the Opp.</inlineHelpText>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Business_Unit__c.object
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BillingItemTriggerHandler.cls
public class BillingItemTriggerHandler  extends TriggerHandler{
 public BillingItemTriggerHandler() { 
    //this.setMaxLoopCount(10);
  }
  
  
      protected override void afterInsert() {
    	System.debug('BillingItem Handler afterInsert');    	
    	
    	  for(Id itemId : Trigger.newMap.keySet()) {
      	System.debug('BillingItem Business Unit: '+((Billing_Item__c)Trigger.newMap.get(itemId)).Business_Unit__c);
      	
	      if(((Billing_Item__c)Trigger.newMap.get(itemId)).Business_Unit__c == 'vAuto') {	      
			//vAuto
			System.debug('vAuto Billing Item');    
	      new vAutoBillingItemHandler().afterInsert((Billing_Item__c)Trigger.newMap.get(itemId));
	      }
    	  }
    }
  
    protected override void afterUpdate() {
    	System.debug('BillingItem Handler afterUpdate');    	
    	
    	  for(Id itemId : Trigger.newMap.keySet()) {
      	System.debug('BillingItem Business Unit: '+((Billing_Item__c)Trigger.newMap.get(itemId)).Business_Unit__c);
      	
	      if(((Billing_Item__c)Trigger.newMap.get(itemId)).Business_Unit__c == 'vAuto') {	      
			//vAuto
			System.debug('vAuto Billing Item');    
	      new vAutoBillingItemHandler().afterUpdate((Billing_Item__c)Trigger.newMap.get(itemId),(Billing_Item__c)Trigger.oldMap.get(itemId));
	      }
    	  }
    }

     protected override void beforeDelete() {
      System.debug('BillingItem Handler beforeDelete');
        for(Id itemId : Trigger.oldMap.keySet()) {
        System.debug('BillingItem Business Unit: '+((Billing_Item__c)Trigger.oldMap.get(itemId)).Business_Unit__c);
        
        if(((Billing_Item__c)Trigger.oldMap.get(itemId)).Business_Unit__c == 'vAuto') {       
      //vAuto
      System.debug('vAuto Billing Item');    
        new vAutoBillingItemHandler().beforeDelete((Billing_Item__c)Trigger.oldMap.get(itemId));
        }
        }

     }
}