objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Project_Definition__c</fullName>
        <description>Used by Vin Accounting to report on which project Billed Assets are linked to.</description>
        <formula>Product_Sold__r.Project_Definition__r.Project_Short_Code__c</formula>
        <label>Project Short Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <formula>Related_Project_Piece__r.Project__r.Project_Type__c</formula>
        <inlineHelpText>Formula that pulls from the Project&apos;s Type</inlineHelpText>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>Add a new line item to a billing contract</description>
        <label>ADD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup the POA related to this Case</inlineHelpText>
        <label>POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Related Cases</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>use to add a new contract (order) to the AutoTrader Billing System</description>
        <label>ADD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>POA_Type__c</fullName>
        <description>This field controls which type of POA this Opportunity gets assigned to.</description>
        <inlineHelpText>Controls the type of POA this Opportunity gets Assigned to</inlineHelpText>
        <label>POA Type</label>
        <picklist>
            <picklistValues>
                <fullName>Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Genius Labs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red Wagon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOT DEFINED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Digital_Marketing</fullName>
        <active>true</active>
        <businessProcess>Haystak</businessProcess>
        <label>Haystak DM</label>
    </recordTypes>
    <recordTypes>
        <fullName>General_Sales</fullName>
        <active>true</active>
        <businessProcess>Vin3</businessProcess>
        <label>Vin</label>
    </recordTypes>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <businessProcess>vAuto</businessProcess>
        <label>vAuto</label>
    </recordTypes>
    <recordTypes>
        <fullName>vAuto_Conquest</fullName>
        <active>true</active>
        <businessProcess>vAuto</businessProcess>
        <description>displays fields specific to the vAuto conquest product</description>
        <label>vAuto Conquest</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/POA__c.object
<CustomObject>
    <description>used to handle Plan of Action items for an Account- gives the ability to group support or implementation issues together</description>
    <fields>
        <fullName>POA_Type__c</fullName>
        <formula>CASE(RecordTypeId, 
   &quot;01270000000Q8PX&quot;, &quot;New Account F/U&quot;, 
   &quot;01270000000Q8Fw&quot;, &quot;Support&quot;,
   &quot;01270000000Q8G1&quot;, &quot;Cancellation&quot;,
   &quot;01270000000Q8G6&quot;, &quot;AutoTrader&quot;,
   &quot;01270000000Q8QL&quot;, &quot;CRM Followup&quot;,
   &quot;01270000000Q8QG&quot;, &quot;Implementation&quot;,
   &quot;01270000000Q8SH&quot;, &quot;VinSocial&quot;,
   &quot;01270000000Q9Pi&quot;,&quot;New Website Followup&quot;,
   &quot;01270000000Q9a7&quot;,&quot;New Website Followup&quot;,
   &quot;01270000000QARz&quot;,&quot;Account Mgmt POA&quot;,
   &quot;01270000000QB6U&quot;,&quot;Haystak SEM&quot;,
   &quot;01270000000QB5g&quot;,&quot;Haystak SEO&quot;,
   &quot;012Q000000095t4&quot;, &quot;vAuto Provision&quot;,
   &quot;NOT DEFINED, EDIT FIELD&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>looks up the record type id and converts it to text</inlineHelpText>
        <label>POA Type</label>
        <type>Text</type>
    </fields>
    <label>POA</label>
    <nameField>
        <label>Plan of Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POAs</pluralLabel>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Base_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Set to have product show on a POA related list &quot;Base Asset&quot;</inlineHelpText>
        <label>Base Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This feild will control which project will be created</description>
        <label>Project Definition</label>
        <referenceTo>Project_Definition__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <label>vAuto</label>
    </recordTypes>
</CustomObject>

objects/Project_Definition__c.object
<CustomObject>
    <description>This object will hold the attributes of the project.</description>
    <fields>
        <fullName>Default_POA_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default POA Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Definitions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Project_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Project Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Definitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NeedProjectPieces__c</fullName>
        <defaultValue>false</defaultValue>
        <description>DEPRECATED</description>
        <label>NeedProjectPieces DEPRECATED</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>POA_Type__c</fullName>
        <inlineHelpText>Sets the record type of the POA that is generated. If this is blank, no POA will be generated.</inlineHelpText>
        <label>POA Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Haystak ADVD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Account Mgmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Behavioral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Website</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Category__c</fullName>
        <inlineHelpText>Determines how many projects are created. Each separate Project Category called by sold products will create 1 project. If two sold products have the same Project Category, one project will be created for them to share.</inlineHelpText>
        <label>Project Definition Category</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEM CLLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vin Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Presence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Websites</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Priority__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Used to decide which project, if more than one Project Definition with the same project category is found on the Opp&apos;s Products, should take priority for generating values (e.g. Project Type, Project Record Type). Highest value wins.</inlineHelpText>
        <label>Definition Priority</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Record_Type__c</fullName>
        <label>Project Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Basic Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FROZEN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phased Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staged Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Websites</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Short_Code__c</fullName>
        <inlineHelpText>Determines the first 3 characters of the Project&apos;s name for HAY and VIN.</inlineHelpText>
        <label>Project Short Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <inlineHelpText>Sets the Project field &quot;Project Type&quot; when the project is generated.</inlineHelpText>
        <label>Project Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Definition</label>
    <nameField>
        <label>Project Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Project_Type__c</fullName>
        <formula>Project__r.Project_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Project_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates which Project Category was used to generate this project.</description>
        <inlineHelpText>Indicates which Project Category was used to generate this project.</inlineHelpText>
        <label>Project Category</label>
        <referenceTo>Project_Definition__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <inlineHelpText>Uses the Opportunity&apos;s Product Suite and is updated by the Trigger</inlineHelpText>
        <label>Opp Product Suite</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Digital_Marketing</fullName>
        <active>true</active>
        <label>Dealer Marketing</label>
    </recordTypes>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <description>This is the type for all vAuto Projects</description>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TriggerDisable__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This Setting will control if the trigger is run for a partcular user/profile..etc</description>
    <fields>
        <fullName>ListOfTriggerToDisable__c</fullName>
        <description>Comma Sapreated Trigger Name to stop its code from running</description>
        <inlineHelpText>Comma Sapreated Trigger Name to stop its code from running</inlineHelpText>
        <label>ListOfTriggerToDisable</label>
        <type>TextArea</type>
    </fields>
    <label>TriggerDisable</label>
</CustomObject>

classes/StaticData.cls
public class StaticData { 
private static StaticData instance = null;
public static final string vAutoIdenitifer = 'VAT';
public static final string vinIdenitifer = 'VIN';
public static final string hayStakIdenitifer = 'HAY';

// The constructor is private
private StaticData(){

}



public Boolean isVAutoOppRecType(Id recTypeId){
	 
	 return (recTypeId == StaticData.getInstance().OpportunityRecTypesMapByDevName.get('vAuto').Id
	 
	 || recTypeId == StaticData.getInstance().OpportunityRecTypesMapByDevName.get('vAuto_Conquest').Id);
}
public  Boolean isVINOppRecType(Id recTypeId){
		      return ( recTypeId == StaticData.getInstance().OpportunityRecTypesMapByDevName.get('General_Sales').Id);
}

public  Boolean isHayStakOppRecType(Id recTypeId){
      return (recTypeId == StaticData.getInstance().OpportunityRecTypesMapByDevName.get('Digital_Marketing').Id);      	      	
}


public  String getBUIdentifierByOppRecType(Id recTypeId){	
	if(isVAutoOppRecType(recTypeId)){
		return vAutoIdenitifer;
	}
	else if(isVINOppRecType(recTypeId)){
		return vinIdenitifer;
	}
	else if(isHayStakOppRecType(recTypeId)){
		return hayStakIdenitifer;
	}
	return '';
}

// a static method that returns the instance of the record type
public static StaticData getInstance(){
// lazy load the record type - only initialize if it doesn't already exist
if(instance == null) instance = new StaticData();
	return instance;
}

//Opportunity Record Types
//Usage: StaticData.getInstance().OpportunityRecTypesMap
private Map<Id,RecordType> oppRecTypesMap;
public Map<Id,RecordType> OpportunityRecTypesMap{
get{
		if(oppRecTypesMap == null){
			LoadOpportunityTypes();
		}		
		return oppRecTypesMap;
}
}

private Map<String,RecordType> oppRecTypesMapByDevName;
public Map<String,RecordType> OpportunityRecTypesMapByDevName{
get{
		if(oppRecTypesMapByDevName == null){
			LoadOpportunityTypes();
		}		
		return oppRecTypesMapByDevName;
}
}

	
private void LoadOpportunityTypes(){	
	oppRecTypesMap = new Map<Id,RecordType>();	
    oppRecTypesMapByDevName = new Map<String,RecordType>();
	for(RecordType recType: [Select Id,DeveloperName,Name,SObjectType from RecordType where SObjectType = 'Opportunity' and IsActive = true]){				
		oppRecTypesMap.put(recType.Id,recType);
		oppRecTypesMapByDevName.put(recType.DeveloperName,recType);
	}
}
	
//Project Record Types
private Map<Id,RecordType> projRecTypesMap;
public Map<Id,RecordType> ProjectRecTypesMap{
get{
		if(projRecTypesMap == null){
			LoadProjectTypes();
		}		
		return projRecTypesMap;
}
}

private Map<String,RecordType> projRecTypesMapByDevName;
public Map<String,RecordType> ProjectRecTypesMapByDevName{
get{
		if(projRecTypesMapByDevName == null){
			LoadProjectTypes();
		}		
		return projRecTypesMapByDevName;
}
}

private Map<String,RecordType> projRecTypesMapByName;
public Map<String,RecordType> ProjectRecTypesMapByName{
get{
		if(projRecTypesMapByName == null){
			LoadProjectTypes();
		}		
		return projRecTypesMapByName;
}
}	 
private void LoadProjectTypes(){	
	projRecTypesMap = new Map<Id,RecordType>();	
    projRecTypesMapByDevName = new Map<String,RecordType>();
    projRecTypesMapByName = new Map<String,RecordType>(); 
	for(RecordType recType: [Select Id,DeveloperName,Name,SObjectType from RecordType where SObjectType = 'SFDC_520_Quote__c' and IsActive = true]){				
		projRecTypesMap.put(recType.Id,recType);
		projRecTypesMapByDevName.put(recType.DeveloperName,recType);
		projRecTypesMapByName.put(recType.Name,recType);
	}
}

//ProjectPieces Record Types
private Map<Id,RecordType> projPiecesRecTypesMap;
public Map<Id,RecordType> ProjectPiecesRecTypesMap{
get{
		if(projPiecesRecTypesMap == null){
			LoadProjectPiecesTypes();
		}		
		return projPiecesRecTypesMap;
}
}

private Map<String,RecordType> projPiecesRecTypesMapByDevName;
public Map<String,RecordType> ProjectPiecesRecTypesMapByDevName{
get{
		if(projPiecesRecTypesMapByDevName == null){
			LoadProjectPiecesTypes();
		}		
		return projPiecesRecTypesMapByDevName;
}
}
	
private void LoadProjectPiecesTypes(){	
	projPiecesRecTypesMap = new Map<Id,RecordType>();	
    projPiecesRecTypesMapByDevName = new Map<String,RecordType>();
	for(RecordType recType: [Select Id,DeveloperName,Name,SObjectType from RecordType where SObjectType = 'Project_Piece__c' and IsActive = true]){				
		projPiecesRecTypesMap.put(recType.Id,recType);
		projPiecesRecTypesMapByDevName.put(recType.DeveloperName,recType);
	}
}

//POA Record Types
private Map<Id,RecordType> poa_RecTypesMap;
public Map<Id,RecordType> POARecTypesMap{
get{
		if(poa_RecTypesMap == null){
			LoadPOATypes();
		}		
		return poa_RecTypesMap;
}
}

private Map<String,RecordType> poa_RecTypesMapByDevName;
public Map<String,RecordType> POARecTypesMapByDevName{
get{
		if(poa_RecTypesMapByDevName == null){
			LoadPOATypes();
		}		
		return poa_RecTypesMapByDevName;
}
}

private Map<String,RecordType> poa_RecTypesMapByName;
public Map<String,RecordType> POARecTypesMapByName{
get{
		if(poa_RecTypesMapByName == null){
			LoadPOATypes();
		}		
		return poa_RecTypesMapByName;
}
}
	
private void LoadPOATypes(){	
	poa_RecTypesMap = new Map<Id,RecordType>();	
    poa_RecTypesMapByDevName = new Map<String,RecordType>();
    poa_RecTypesMapByName= new Map<String,RecordType>();
	for(RecordType recType: [Select Id,DeveloperName,Name,SObjectType from RecordType where SObjectType = 'POA__c' and IsActive = true]){				
		poa_RecTypesMap.put(recType.Id,recType);
		poa_RecTypesMapByDevName.put(recType.DeveloperName,recType);
		poa_RecTypesMapByName.put(recType.Name,recType);
	}
}


//Contract Record Types
private Map<Id,RecordType> contract_RecTypesMap;
public Map<Id,RecordType> ContractRecTypesMap{
get{
		if(contract_RecTypesMap == null){
			LoadContractTypes();
		}		
		return contract_RecTypesMap;
}
}

private Map<String,RecordType> contract_RecTypesMapByDevName;
public Map<String,RecordType> ContractRecTypesMapByDevName{
get{
		if(contract_RecTypesMapByDevName == null){
			LoadContractTypes();
		}		
		return contract_RecTypesMapByDevName;
}
}
	
private void LoadContractTypes(){	
	contract_RecTypesMap = new Map<Id,RecordType>();	
    contract_RecTypesMapByDevName = new Map<String,RecordType>();
	for(RecordType recType: [Select Id,DeveloperName,Name,SObjectType from RecordType where SObjectType = 'Contract' and IsActive = true]){				
		contract_RecTypesMap.put(recType.Id,recType);
		contract_RecTypesMapByDevName.put(recType.DeveloperName,recType);
	}
}

//BillingItem Record Types
private Map<Id,RecordType> billingItem_RecTypesMap;
public Map<Id,RecordType> BillingItemRecTypesMap{
get{
		if(billingItem_RecTypesMap == null){
			LoadBillingItemTypes();
		}		
		return billingItem_RecTypesMap;
}
}

private Map<String,RecordType> billingItem_RecTypesMapByDevName;
public Map<String,RecordType> BillingItemRecTypesMapByDevName{
get{
		if(billingItem_RecTypesMapByDevName == null){
			LoadBillingItemTypes();
		}		
		return billingItem_RecTypesMapByDevName;
}
}
	
private void LoadBillingItemTypes(){	
	billingItem_RecTypesMap = new Map<Id,RecordType>();	
    billingItem_RecTypesMapByDevName = new Map<String,RecordType>();
	for(RecordType recType: [Select Id,DeveloperName,Name,SObjectType from RecordType where SObjectType = 'Billing_Item__c' and IsActive = true]){				
		billingItem_RecTypesMap.put(recType.Id,recType);
		billingItem_RecTypesMapByDevName.put(recType.DeveloperName,recType);
	}
}

private Map<Id,Project_Definition__c> ProjDefinitions;
public Map<Id,Project_Definition__c> ProjectDefinitions(){
 	if(ProjDefinitions == null){ 	
 		ProjDefinitions = new Map<Id,Project_Definition__c> ();
 		for (Project_Definition__c projDef :[SELECT isActive__c
 			,POA_Type__c
 			, Project_Category__c
 			, Project_Record_Type__c
 			, Name
 			, Id
 			, Default_Project_Owner__c
 			, Default_POA_Owner__c
 			, NeedProjectPieces__c
 			, Project_Short_Code__c
 			, Project_Priority__c
 			, Project_Type__c
 			 FROM Project_Definition__c where isActive__c = true]){
 			ProjDefinitions.put(projDef.Id, projDef);
 		} 
 	}
	return ProjDefinitions;
}


private Map<String,RecordType> task_RecordTypesMapByDevName;
public Map<String,RecordType> TaskRecordTypeMapByDevName{
get{
		if(task_RecordTypesMapByDevName == null){
			LoadTaskRecordTypes();
		}		
		return task_RecordTypesMapByDevName;
}
}
	
private void LoadTaskRecordTypes(){	
    task_RecordTypesMapByDevName = new Map<String,RecordType>();
	for(RecordType recType: [Select Id,DeveloperName,Name,SObjectType from RecordType where SObjectType = 'Task' and IsActive = true]){				
		task_RecordTypesMapByDevName.put(recType.DeveloperName,recType);
	}
}

//Case Record Types
//Usage: StaticData.getInstance().CaseRecTypesMap
private Map<Id,RecordType> case_RecordTypesMap;
public Map<Id,RecordType> CaseRecTypesMap{
get{
		if(case_RecordTypesMap == null){
			LoadCaseTypes();
		}		
		return case_RecordTypesMap;
}
}

private Map<String,RecordType> case_RecordTypesMapByDevName;
public Map<String,RecordType> CaseRecTypesMapByDevName{
get{
		if(case_RecordTypesMapByDevName == null){
			LoadCaseTypes();
		}		
		return case_RecordTypesMapByDevName;
}
}

private Map<String,RecordType> case_RecordTypesMapByName;
public Map<String,RecordType> CaseRecTypesMapByName{
get{
		if(case_RecordTypesMapByName == null){
			LoadCaseTypes();
		}		
		return case_RecordTypesMapByName;
}
}
	
private void LoadCaseTypes(){
	case_RecordTypesMap = new Map<Id,RecordType>();	
    case_RecordTypesMapByDevName = new Map<String,RecordType>();
	case_RecordTypesMapByName = new Map<String,RecordType>();
	for(RecordType recType: [Select Id, DeveloperName, Name, SObjectType from RecordType where SObjectType = 'Case' and IsActive = true]){				
		case_RecordTypesMap.put(recType.Id, recType);
		case_RecordTypesMapByDevName.put(recType.DeveloperName, recType);
		case_RecordTypesMapByName.put(recType.Name,recType);
	}
}

//Account Record Types
private Map<Id,RecordType> acctRecTypesMap;
public Map<Id,RecordType> AccountRecTypesMap{
get{
		if(acctRecTypesMap == null){
			LoadAccountTypes();
		}		
		return acctRecTypesMap;
}
}

private Map<String,RecordType> acctRecTypesMapByDevName;
public Map<String,RecordType> AccountRecTypesMapByDevName{
get{
		if(acctRecTypesMapByDevName == null){
			LoadAccountTypes();
		}		
		return acctRecTypesMapByDevName;
}
}

private Map<String,RecordType> acctRecTypesMapByName;
public Map<String,RecordType> AccountRecTypesMapByName{
get{
		if(acctRecTypesMapByName == null){
			LoadProjectTypes();
		}		
		return acctRecTypesMapByName;
}
}	 
private void LoadAccountTypes(){	
	acctRecTypesMap = new Map<Id,RecordType>();	
    acctRecTypesMapByDevName = new Map<String,RecordType>();
    acctRecTypesMapByName = new Map<String,RecordType>(); 
	for(RecordType recType: [Select Id,DeveloperName,Name,SObjectType from RecordType where SObjectType = 'Account' and IsActive = true]){				
		acctRecTypesMap.put(recType.Id,recType);
		acctRecTypesMapByDevName.put(recType.DeveloperName,recType);
		acctRecTypesMapByName.put(recType.Name,recType);
	}
}

private Map<String, Pricebook2> priceBook_ByName;
public Map<String,Pricebook2> PriceBookByName{
get{
		if(priceBook_ByName == null){
			LoadPriceBooks();
		}		
		return priceBook_ByName;
}
}

private void LoadPriceBooks(){	
    priceBook_ByName = new Map<String,Pricebook2>();
	for(Pricebook2 priceBook: [SELECT IsActive, Description, IsStandard, Id, Name FROM Pricebook2
	where IsActive = true]){				
		priceBook_ByName.put(priceBook.Name,priceBook);
	}
}

private Map<String, PricebookEntry> productsByCodeAndPriceBook;
public  PricebookEntry GetPricebookEntry(string priceBookName,String productCode){
   Pricebook2 priceBook = PriceBookByName.get(priceBookName);
   if(priceBook == null){
   		throw new CoxAutomotiveException('Could not find Price Book: '+priceBookName);
   }
   string productKey = productCode+'_'+priceBook.Name;

   if(productsByCodeAndPriceBook == null || !productsByCodeAndPriceBook.containsKey(productKey)){
	List<PricebookEntry> priceBookEntry = [SELECT IsActive, UnitPrice, Id, Pricebook2Id, ProductCode, Product2Id, Name, UseStandardPrice, Product2.Project_Definition__c,Product2.Base_Product__c FROM PricebookEntry 
	where Pricebook2Id =: priceBook.Id and ProductCode =: productCode and IsActive = true];
   	if(priceBookEntry== null || priceBookEntry.size() ==0){
      throw new CoxAutomotiveException('Could not find Product: '+productCode+ ' in Price Book: '+priceBook.Name);
   	}
   	if(productsByCodeAndPriceBook == null){ productsByCodeAndPriceBook = new Map<String, PricebookEntry>();}
   	productsByCodeAndPriceBook.put(productKey,priceBookEntry[0]);   
	}
 	return productsByCodeAndPriceBook.get(productKey);   
}


public Static Set<String> DisabledTriggers {
	get{
	Set<string> setOfDisabledTriggers = new Set<string>();
	TriggerDisable__c CS = TriggerDisable__c.getValues(UserInfo.getUserId());
	if(CS != null && CS.ListOfTriggerToDisable__c != null && CS.ListOfTriggerToDisable__c !=''){
		String[]  results = CS.ListOfTriggerToDisable__c.split('\r\n', 0);
		for(string item : results){				
		    //system.debug('item: '+ item);
		    if(!setOfDisabledTriggers.contains(item)){
		    	setOfDisabledTriggers.add(item);
		    }
		}

		//list
		//for(string setitem : setOfDisabledTriggers){		
		// system.debug('setitem: '+ setitem);		
		//}
	}		
	return setOfDisabledTriggers;
}
}

}