objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>LOB_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned WriteOff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Needs Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Needs Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Pre Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - SVOC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save - Temp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transitioned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Triage</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LOB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup to the BU POA only if the Product is a primary product: CRM, ILM, Webiste, Provision, Conquest, Auction Genius. A primary product has the field &quot;Base Asset&quot; set to True in the product record detail page</inlineHelpText>
        <label>Primary Product Status</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Product Status List</relationshipLabel>
        <relationshipName>Billing_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <formula>Related_Project_Piece__r.Project__r.Project_Type__c</formula>
        <inlineHelpText>Formula that pulls from the Project&apos;s Type</inlineHelpText>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Old_Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup the POA that the account manager will use to manage this asset</inlineHelpText>
        <label>Related POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Project_Piece__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Project Asset</label>
        <referenceTo>Project_Piece__c</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>Add a new line item to a billing contract</description>
        <label>ADD</label>
    </recordTypes>
    <recordTypes>
        <fullName>Locked</fullName>
        <active>true</active>
        <description>after a one time or setup product is active in RMB update layout to Locked</description>
        <label>Locked</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <businessProcess>vAuto</businessProcess>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/POA__c.object
<CustomObject>
    <description>used to handle Plan of Action items for an Account- gives the ability to group support or implementation issues together</description>
    <label>POA</label>
    <nameField>
        <label>Plan of Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POAs</pluralLabel>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Opportunity_Line_Item_ID__c</fullName>
        <label>Opportunity Line Item ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <formula>Project__r.Project_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Project Pieces</relationshipLabel>
        <relationshipName>Project_Pieces</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Approval_Stage__c</fullName>
        <inlineHelpText>Updated by the system upon milestone completion</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>1-Initiating</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>2-Planning and Design</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>3-Executing</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>4-Review</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>5-Finalizing</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Launched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-ILM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GO LIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Intro Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Strategy Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Dealer Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <inlineHelpText>Uses the Opportunity&apos;s Product Suite and is updated by the Trigger</inlineHelpText>
        <label>Opp Product Suite</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup POA for this project</inlineHelpText>
        <label>Related POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <description>This is the type for all vAuto Projects</description>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/vAutoBillingItemHandler_Test.cls
@isTest(SeeAllData=true) 
public class vAutoBillingItemHandler_Test {

static testMethod void Provision_LOB_Status_Good() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
  	
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
	  Test_vAutoOpportunity.setupProvisionOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Project_Type__c,RecordTypeId,Related_POA__c  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        


      
                 //find all the related billing Items for above project pieces
   //which are marked with LOB; to showup as product suites/status in POA
   List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id,LOB_Status__c,Project_Type__c,Related_POA__c,Related_POA__r.OwnerId from Billing_Item__c where Related_Project_Piece__c IN :projPieces
   								AND LOB__c !=null];
   								
  System.Assert(billingItemsMarkedWithLOB != null,'No Billing Items Marked as product suites');
    System.Assert(billingItemsMarkedWithLOB.size() > 0,'No Billing Items Marked as product suites'); 
    
    
   	
   	      //check if the related LOB Billed Items sproject types are set correctly
   for(Billing_Item__c item : billingItemsMarkedWithLOB){
   		system.assert(item.Project_Type__c == 'Account Setup','Project_Type__c is not valid');	   	  
   }
         
         
              //check if the intro call task is created
    List<Task>  introCalltasks = [Select Id from Task where 
      ownerId=:billingItemsMarkedWithLOB[0].Related_POA__r.OwnerId 
      and whatId=:billingItemsMarkedWithLOB[0].Related_POA__c
      and Subject = '* Intro Call'];
      
    System.Assert(introCalltasks != null,'No Intro Call Tasks got created as expected');
    System.Assert(introCalltasks.size() > 0,'No Intro Call Tasks got created as expected');
     System.Assert(introCalltasks.size() == billingItemsMarkedWithLOB.size() ,'Number of intro calls created does not match  Billing Items Marked as product suites');
       
           							
   	Billing_Item__c billingItem = 	billingItemsMarkedWithLOB[0];						
      //update the LOB_Status__c 
      system.assert(billingItem.LOB_Status__c != 'Good','Billing Item LOB_Status__c is already set to Good');
      billingItem.LOB_Status__c = 'Good';
      update billingItem;
           

         //check if the task created
      List<Task> tasks = [Select Id from Task where 
      ownerId=:billingItem.Related_POA__r.OwnerId 
      and whatId=:billingItem.Related_POA__c
      and Subject = '# PM Review Call Good Status'];
      
    System.Assert(tasks != null,'No Tasks got created as expected');
    System.Assert(tasks.size() > 0,'No Tasks got created as expected');
     System.Assert(tasks.size() ==1 ,'More than one Task got created');
     
     

     
      
	}
	
	static testMethod void Provision_LOB_Status_AtRisk() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
  	
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
	  Test_vAutoOpportunity.setupProvisionOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Project_Type__c,RecordTypeId,Related_POA__c  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        


      
                 //find all the related billing Items for above project pieces
   //which are marked with LOB; to showup as product suites/status in POA
   List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id,LOB_Status__c,Project_Type__c,Related_POA__c,Related_POA__r.OwnerId from Billing_Item__c where Related_Project_Piece__c IN :projPieces
   								AND LOB__c !=null];
   								
  System.Assert(billingItemsMarkedWithLOB != null,'No Billing Items Marked as product suites');
    System.Assert(billingItemsMarkedWithLOB.size() > 0,'No Billing Items Marked as product suites'); 
   	
   	      //check if the related LOB Billed Items sproject types are set correctly
   for(Billing_Item__c item : billingItemsMarkedWithLOB){
   		system.assert(item.Project_Type__c == 'Account Setup','Project_Type__c is not valid');	   	  
   }
           
                         //check if the intro call task is created
    List<Task>  introCalltasks = [Select Id from Task where 
      ownerId=:billingItemsMarkedWithLOB[0].Related_POA__r.OwnerId 
      and whatId=:billingItemsMarkedWithLOB[0].Related_POA__c
      and Subject = '* Intro Call'];
      
    System.Assert(introCalltasks != null,'No Intro Call Tasks got created as expected');
    System.Assert(introCalltasks.size() > 0,'No Intro Call Tasks got created as expected');
     System.Assert(introCalltasks.size() == billingItemsMarkedWithLOB.size() ,'Number of intro calls created does not match  Billing Items Marked as product suites');
       
           							
   	Billing_Item__c billingItem = 	billingItemsMarkedWithLOB[0];						
      //update the LOB_Status__c 
      system.assert(billingItem.LOB_Status__c != 'At Risk','Billing Item LOB_Status__c is already set to At Risk');
      billingItem.LOB_Status__c = 'At Risk';
      update billingItem;
           

         //check if the task created
      List<Task> tasks = [Select Id from Task where 
      ownerId=:billingItem.Related_POA__r.OwnerId 
      and whatId=:billingItem.Related_POA__c
      and Subject = '# PM Review Call At Risk Status'];
      
    System.Assert(tasks != null,'No Tasks got created as expected');
    System.Assert(tasks.size() > 0,'No Tasks got created as expected');
      System.Assert(tasks.size() ==1 ,'More than one Task got created');
      
	}
		static testMethod void Provision_LOB_Status_SaveAccount() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
  	
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
	  Test_vAutoOpportunity.setupProvisionOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Project_Type__c,RecordTypeId,Related_POA__c  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        


      
                 //find all the related billing Items for above project pieces
   //which are marked with LOB; to showup as product suites/status in POA
   List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id,LOB_Status__c,Project_Type__c,Related_POA__c,Related_POA__r.OwnerId from Billing_Item__c where Related_Project_Piece__c IN :projPieces
   								AND LOB__c !=null];
   								
  System.Assert(billingItemsMarkedWithLOB != null,'No Billing Items Marked as product suites');
    System.Assert(billingItemsMarkedWithLOB.size() > 0,'No Billing Items Marked as product suites'); 
   	
   	      //check if the related LOB Billed Items sproject types are set correctly
   for(Billing_Item__c item : billingItemsMarkedWithLOB){
   		system.assert(item.Project_Type__c == 'Account Setup','Project_Type__c is not valid');	   	  
   }

     /*Commented since we are not creating tasks for this status
                 //check if the intro call task is created
    List<Task>  introCalltasks = [Select Id from Task where 
      ownerId=:billingItemsMarkedWithLOB[0].Related_POA__r.OwnerId 
      and whatId=:billingItemsMarkedWithLOB[0].Related_POA__c
      and Subject = '* Intro Call'];
      
    System.Assert(introCalltasks != null,'No Intro Call Tasks got created as expected');
    System.Assert(introCalltasks.size() > 0,'No Intro Call Tasks got created as expected');
     System.Assert(introCalltasks.size() == billingItemsMarkedWithLOB.size() ,'Number of intro calls created does not match  Billing Items Marked as product suites');
               
           							
   	Billing_Item__c billingItem = 	billingItemsMarkedWithLOB[0];						
      //update the LOB_Status__c 
      system.assert(billingItem.LOB_Status__c != 'Save - Account','Billing Item LOB_Status__c is already set to Save - Account');
      billingItem.LOB_Status__c = 'Save - Account';
      update billingItem;
           

         //check if the task created
      List<Task> tasks = [Select Id from Task where 
      ownerId=:billingItem.Related_POA__r.OwnerId 
      and whatId=:billingItem.Related_POA__c
      and Subject = '# PM Review Call Save Status'];
      
    System.Assert(tasks != null,'No Tasks got created as expected');
    System.Assert(tasks.size() > 0,'No Tasks got created as expected');
      System.Assert(tasks.size() ==1 ,'More than one Task got created');
      */
      
	}
	static testMethod void Conquest_LOB_Status_Good() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
  	
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
	  Test_vAutoOpportunity.setupConquestOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Project_Type__c,RecordTypeId,Related_POA__c  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        


      
                 //find all the related billing Items for above project pieces
   //which are marked with LOB; to showup as product suites/status in POA
   List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id,LOB_Status__c,Project_Type__c,Related_POA__c,Related_POA__r.OwnerId from Billing_Item__c where Related_Project_Piece__c IN :projPieces
   								AND LOB__c !=null];
   								
  System.Assert(billingItemsMarkedWithLOB != null,'No Billing Items Marked as product suites');
    System.Assert(billingItemsMarkedWithLOB.size() > 0,'No Billing Items Marked as product suites'); 
   	
   	      //check if the related LOB Billed Items sproject types are set correctly
   for(Billing_Item__c item : billingItemsMarkedWithLOB){
   		system.assert(item.Project_Type__c == 'Conquest','Project_Type__c is not valid');	   	  
   }
                  //check if the intro call task is created
    List<Task>  introCalltasks = [Select Id from Task where 
      ownerId=:billingItemsMarkedWithLOB[0].Related_POA__r.OwnerId 
      and whatId=:billingItemsMarkedWithLOB[0].Related_POA__c
      and Subject = '* Intro Call'];
      
 	System.Assert(introCalltasks.size() == 0,'Intro Call Tasks got created which is not expected');
              
           							
   	Billing_Item__c billingItem = 	billingItemsMarkedWithLOB[0];						
      //update the LOB_Status__c 
      system.assert(billingItem.LOB_Status__c != 'Good','Billing Item LOB_Status__c is already set to Good');
      billingItem.LOB_Status__c = 'Good';
      update billingItem;
           

         //check if the task created
      List<Task> tasks = [Select Id from Task where 
      ownerId=:billingItem.Related_POA__r.OwnerId 
      and whatId=:billingItem.Related_POA__c
      and Subject = '# Conquest Review Call Good Status'];
      
    System.Assert(tasks != null,'No Tasks got created as expected');
    System.Assert(tasks.size() > 0,'No Tasks got created as expected');
      System.Assert(tasks.size() ==1 ,'More than one Task got created');
      
	}
	
		static testMethod void Conquest_LOB_Status_AtRisk() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
  	
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
	  Test_vAutoOpportunity.setupConquestOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Project_Type__c,RecordTypeId,Related_POA__c  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        


      
                 //find all the related billing Items for above project pieces
   //which are marked with LOB; to showup as product suites/status in POA
   List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id,LOB_Status__c,Project_Type__c,Related_POA__c,Related_POA__r.OwnerId from Billing_Item__c where Related_Project_Piece__c IN :projPieces
   								AND LOB__c !=null];
   								
  System.Assert(billingItemsMarkedWithLOB != null,'No Billing Items Marked as product suites');
    System.Assert(billingItemsMarkedWithLOB.size() > 0,'No Billing Items Marked as product suites'); 
   	
   	      //check if the related LOB Billed Items sproject types are set correctly
   for(Billing_Item__c item : billingItemsMarkedWithLOB){
   		system.assert(item.Project_Type__c == 'Conquest','Project_Type__c is not valid');	   	  
   }
           
               //check if the intro call task is created
    List<Task>  introCalltasks = [Select Id from Task where 
      ownerId=:billingItemsMarkedWithLOB[0].Related_POA__r.OwnerId 
      and whatId=:billingItemsMarkedWithLOB[0].Related_POA__c
      and Subject = '* Intro Call'];
      
 	System.Assert(introCalltasks.size() == 0,'Intro Call Tasks got created which is not expected');
                 							
   	Billing_Item__c billingItem = 	billingItemsMarkedWithLOB[0];						
      //update the LOB_Status__c 
      system.assert(billingItem.LOB_Status__c != 'At Risk','Billing Item LOB_Status__c is already set to At Risk');
      billingItem.LOB_Status__c = 'At Risk';
      update billingItem;
           

         //check if the task created
      List<Task> tasks = [Select Id from Task where 
      ownerId=:billingItem.Related_POA__r.OwnerId 
      and whatId=:billingItem.Related_POA__c
      and Subject = '# Conquest Review Call At Risk Status'];
      
    System.Assert(tasks != null,'No Tasks got created as expected');
    System.Assert(tasks.size() > 0,'No Tasks got created as expected');
      System.Assert(tasks.size() ==1 ,'More than one Task got created');
      
	}
	
		static testMethod void Conquest_LOB_Status_SaveAccount() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
  	
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
	  Test_vAutoOpportunity.setupConquestOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Project_Type__c,RecordTypeId,Related_POA__c  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        


      
                 //find all the related billing Items for above project pieces
   //which are marked with LOB; to showup as product suites/status in POA
   List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id,LOB_Status__c,Project_Type__c,Related_POA__c,Related_POA__r.OwnerId from Billing_Item__c where Related_Project_Piece__c IN :projPieces
   								AND LOB__c !=null];
   								
  System.Assert(billingItemsMarkedWithLOB != null,'No Billing Items Marked as product suites');
    System.Assert(billingItemsMarkedWithLOB.size() > 0,'No Billing Items Marked as product suites'); 
   	
   	      //check if the related LOB Billed Items sproject types are set correctly
   for(Billing_Item__c item : billingItemsMarkedWithLOB){
   		system.assert(item.Project_Type__c == 'Conquest','Project_Type__c is not valid');	   	  
   }
           

           /*Commented since we are not creating tasks for this status
                 //check if the intro call task is created
    List<Task>  introCalltasks = [Select Id from Task where 
      ownerId=:billingItemsMarkedWithLOB[0].Related_POA__r.OwnerId 
      and whatId=:billingItemsMarkedWithLOB[0].Related_POA__c
      and Subject = '* Intro Call'];
      
 	System.Assert(introCalltasks.size() == 0,'Intro Call Tasks got created which is not expected');
               							
   	Billing_Item__c billingItem = 	billingItemsMarkedWithLOB[0];						
      //update the LOB_Status__c 
      system.assert(billingItem.LOB_Status__c != 'Save - Account','Billing Item LOB_Status__c is already set to Save - Account');
      billingItem.LOB_Status__c = 'Save - Account';
      update billingItem;
           

         //check if the task created
      List<Task> tasks = [Select Id from Task where 
      ownerId=:billingItem.Related_POA__r.OwnerId 
      and whatId=:billingItem.Related_POA__c
      and Subject = '# Conquest Review Call Save Status'];
      
    System.Assert(tasks != null,'No Tasks got created as expected');
    System.Assert(tasks.size() > 0,'No Tasks got created as expected');
      System.Assert(tasks.size() ==1 ,'More than one Task got created');
      */
      
	}


      static testMethod void AuctionGeniuswithvAutoandProvisioningClient_NoIntroCalls() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
    
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
    Test_vAutoOpportunity.setupAuctionGeniuswithvAutoandProvisioningClientOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Project_Type__c,RecordTypeId,Related_POA__c  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        


      
                 //find all the related billing Items for above project pieces
   //which are marked with LOB; to showup as product suites/status in POA
   List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id,LOB_Status__c,Project_Type__c,Related_POA__c,Related_POA__r.OwnerId from Billing_Item__c where Related_Project_Piece__c IN :projPieces
                  AND LOB__c !=null];
                  
  System.Assert(billingItemsMarkedWithLOB != null,'No Billing Items Marked as product suites');
    System.Assert(billingItemsMarkedWithLOB.size() > 0,'No Billing Items Marked as product suites'); 
    
          //check if the related LOB Billed Items sproject types are set correctly
   for(Billing_Item__c item : billingItemsMarkedWithLOB){
      system.assert(item.Project_Type__c == 'Auction Genius - With Provision Client','Project_Type__c is not valid');       
   }
           
                 //check if the intro call task is created
    List<Task>  introCalltasks = [Select Id from Task where 
      ownerId=:billingItemsMarkedWithLOB[0].Related_POA__r.OwnerId 
      and whatId=:billingItemsMarkedWithLOB[0].Related_POA__c
      and Subject = '* Intro Call'];
      
    
    System.Assert(introCalltasks.size() == 0,'Intro Call Tasks got created which is not expected');
     
                            
      
  }

	
		static testMethod void ConquestFranchise_NoIntroCalls() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
  	
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
	  Test_vAutoOpportunity.setupConquestFranchiseSaleOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Project_Type__c,RecordTypeId,Related_POA__c  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        


      
                 //find all the related billing Items for above project pieces
   //which are marked with LOB; to showup as product suites/status in POA
   List<Billing_Item__c> billingItemsMarkedWithLOB = [Select Id,LOB_Status__c,Project_Type__c,Related_POA__c,Related_POA__r.OwnerId from Billing_Item__c where Related_Project_Piece__c IN :projPieces
   								AND LOB__c !=null];
   								
  System.Assert(billingItemsMarkedWithLOB != null,'No Billing Items Marked as product suites');
    System.Assert(billingItemsMarkedWithLOB.size() > 0,'No Billing Items Marked as product suites'); 
   	
   	      //check if the related LOB Billed Items sproject types are set correctly
   for(Billing_Item__c item : billingItemsMarkedWithLOB){
   		system.assert(item.Project_Type__c == 'Conquest','Project_Type__c is not valid');	   	  
   }
           
                 //check if the intro call task is created
    List<Task>  introCalltasks = [Select Id from Task where 
      ownerId=:billingItemsMarkedWithLOB[0].Related_POA__r.OwnerId 
      and whatId=:billingItemsMarkedWithLOB[0].Related_POA__c
      and Subject = '* Intro Call'];
      
    
    System.Assert(introCalltasks.size() == 0,'Intro Call Tasks got created which is not expected');
     
               							
      
	}

      static testMethod void DoNotDeleteNonAddRecordTypes() {

  Contact cont =  Test_vAutoOpportunity.setupContact();
    
      Account acct = Test_vAutoOpportunity.setupAccount();
      Opportunity opp= Test_vAutoOpportunity.setupOpportunity(acct, cont, 'vAuto');
    Test_vAutoOpportunity.setupConquestFranchiseSaleOpportunity(opp);
      Test.startTest();
      UtilityClass.debugSystemLimits();
      //set the opp to Closed Own
      opp.StageName= 'Closed or Won';
      update opp;     
        Test.stopTest();
      System.Assert(opp.StageName== 'Closed or Won','Opportunity is not Closed or Won');
      Test_vAutoOpportunity.ValidateOpportunity(opp);
      Test_vAutoOpportunity.ValidatePOA(opp);
      Test_vAutoOpportunity.ValidateProject(opp);      
      Test_vAutoOpportunity.ValidateContract(opp); 
      
      
      //Now update the project Approval stage and confirm that the LOB Billed Items are also updated.
      
      List<SFDC_520_Quote__c> projects = [Select Id,Approval_Stage__c ,Project_Type__c,RecordTypeId,Related_POA__c  from SFDC_520_Quote__c where Opportunity__c  =: opp.Id];
      SFDC_520_Quote__c project = projects[0];
      
            
          // first find all project pieces
   List<Project_Piece__c> projPieces = [SELECT Id, Opportunity_Line_Item_ID__c
        FROM Project_Piece__c
        WHERE Project__c =: project.Id];
        


      
                 //find all the related billing Items for above project pieces with record type ADD
  List<Billing_Item__c> billingItemsWithRecordTypeADD = [Select Id,LOB_Status__c,Project_Type__c,Related_POA__c,Related_POA__r.OwnerId from Billing_Item__c where Related_Project_Piece__c IN :projPieces
  and RecordTypeId =:  StaticData.getInstance().BillingItemRecTypesMapByDevName.get('ADD').Id ];
                  
  System.Assert(billingItemsWithRecordTypeADD != null,'No Billing Items with record type ADD');
  System.Assert(billingItemsWithRecordTypeADD.size() > 0,'No Billing Items with record type ADD');


//change the status to Locked
          billingItemsWithRecordTypeADD[0].RecordTypeId =  StaticData.getInstance().BillingItemRecTypesMapByDevName.get('Locked').Id ;
          update billingItemsWithRecordTypeADD[0];

  //try deleting it
      try {
         delete billingItemsWithRecordTypeADD[0];
        System.assert(false, 'exception expected for Deleting BillingItem with RecordType ADD');
    } catch (Exception e) {
      string expectedError = 'Can not delete Items';
        System.assert(e.getMessage().contains(expectedError), 'Expected Error Message containing message='+expectedError+', but found message is :' + e.getMessage());
    }
 

           
                            
      
  }
  
	
}