objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>aka Stop Date Provide an End Date to stop billing for this item.  Cannot be after Contract End Date. Default to 12/31/2100 if not provided on Add or Modify action.</inlineHelpText>
        <label>Billing End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LOB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup to the BU POA only if the Product is a primary product: CRM, ILM, Webiste, Provision, Conquest, Auction Genius. A primary product has the field &quot;Base Asset&quot; set to True in the product record detail page</inlineHelpText>
        <label>Primary Product Status</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Product Status List</relationshipLabel>
        <relationshipName>Billing_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vin_Dealer_Id__c</fullName>
        <formula>Contract__r.Vin_Dealer_Id1__c</formula>
        <label>Vin Dealer Id</label>
        <type>Text</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>Add a new line item to a billing contract</description>
        <label>ADD</label>
    </recordTypes>
    <recordTypes>
        <fullName>CANCEL</fullName>
        <active>true</active>
        <description>record type is updated by the system when the contract is cancelled</description>
        <label>CANCELLED</label>
    </recordTypes>
    <recordTypes>
        <fullName>MODIFY</fullName>
        <active>true</active>
        <description>used to modify an exisiting billing items</description>
        <label>MODIFY</label>
    </recordTypes>
    <recordTypes>
        <fullName>Process_Stop</fullName>
        <active>true</active>
        <label>Process Stop</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Billing_Log__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Item__c</fullName>
        <label>Billing Item</label>
        <referenceTo>Billing_Item__c</referenceTo>
        <relationshipLabel>Billing Logs</relationshipLabel>
        <relationshipName>Billing_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Log_Message__c</fullName>
        <label>Log Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Log_Status__c</fullName>
        <label>Log Status</label>
        <picklist>
            <picklistValues>
                <fullName>Processed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Billing Log</label>
    <nameField>
        <displayFormat>Log-{YYYY}{MM}-{0}</displayFormat>
        <label>Billing Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>LOB__c</fullName>
        <label>LOB</label>
        <picklist>
            <picklistValues>
                <fullName>VAUTO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VINSOLUTIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIN-CAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vin_Dealer_Id__c</fullName>
        <label>Vin Dealer Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>use to add a new contract (order) to the AutoTrader Billing System</description>
        <label>ADD</label>
    </recordTypes>
    <recordTypes>
        <fullName>Cancel</fullName>
        <active>true</active>
        <description>read only field page layout after contract end date and reason is entered</description>
        <label>CANCELLED</label>
    </recordTypes>
    <recordTypes>
        <fullName>Modify</fullName>
        <active>true</active>
        <description>used when adding or changing product to an existing contract</description>
        <label>MODIFY</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/handler_BillingItem_test.cls
@isTest(SeeAllData=true)
private class handler_BillingItem_test {
    public static testMethod void Test_MototosnapStop_Sucess() {
    	Account testAcct =TestData.setupAccount();
		insert testAcct;

		Contract testContract = TestData.setupContract(testAcct, StaticData.getInstance().ContractRecTypesMapByDevName.get('ADD'));
		testContract.LOB__c = 'VINSOLUTIONS';
		testContract.Status = 'Draft';
		testContract.Vin_Dealer_Id__c = '5886';
		insert testContract;

		Billing_Item__c bl1 = TestData.setUpBillingItem(testContract, TestData.getProduct('700 Credit Inc','VinSolutions'));
		bl1.RecordTypeId = StaticData.getInstance().BillingItemRecTypesMapByDevName.get('Process_Stop').Id;
		insert bl1;	

		Test.startTest();
		// Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MotosnapCalloutMock());
        TestData.isMotoSnapCalloutSuccess = true;

        // Updating the recordType on the Billing_Item__c causes the trigger to fire the HTTP.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
		bl1.RecordTypeId = StaticData.getInstance().BillingItemRecTypesMapByDevName.get('CANCEL').Id;
		bl1.End_Date__c = system.today();
		Database.update(bl1);

		Test.stopTest();

		//Check if a succesful log was created with a success
		List<Billing_Log__c> logs = [Select Log_Status__c,Log_Message__c,Billing_Item__c from Billing_Log__c where Billing_Item__c=: bl1.Id];
		system.assertEquals('Processed', logs[0].Log_Status__c);
		system.assertNotEquals(logs[0].Log_Message__c, null);

    }
    public static testMethod void Test_MototosnapStop_Error() {
    	Account testAcct =TestData.setupAccount();
		insert testAcct;

		Contract testContract = TestData.setupContract(testAcct, StaticData.getInstance().ContractRecTypesMapByDevName.get('ADD'));
		testContract.LOB__c = 'VINSOLUTIONS';
		testContract.Status = 'Draft';
		testContract.Vin_Dealer_Id__c = '5886';
		insert testContract;

		Billing_Item__c bl1 = TestData.setUpBillingItem(testContract, TestData.getProduct('700 Credit Inc','VinSolutions'));
		bl1.RecordTypeId = StaticData.getInstance().BillingItemRecTypesMapByDevName.get('Process_Stop').Id;
		insert bl1;	

		Test.startTest();
		// Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MotosnapCalloutMock());
        TestData.isMotoSnapCalloutSuccess = false;
        TestData.isMotoSnapTimeOutError = true;

        // Updating the recordType on the Billing_Item__c causes the trigger to fire the HTTP.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
		bl1.RecordTypeId = StaticData.getInstance().BillingItemRecTypesMapByDevName.get('CANCEL').Id;
		bl1.End_Date__c = system.today();
		Database.update(bl1);
		
		Test.stopTest();

		//Check if a succesful log was created with an error
		List<Billing_Log__c> logs = [Select Log_Status__c,Log_Message__c,Billing_Item__c from Billing_Log__c where Billing_Item__c=: bl1.Id];
		system.assertEquals('Error', logs[0].Log_Status__c);
		system.assertNotEquals(logs[0].Log_Message__c, null);

    }
    public static testMethod void Test_MototosnapActive_Error() {
		Account testAcct =TestData.setupAccount();
		insert testAcct;

		Contract testContract = TestData.setupContract(testAcct, StaticData.getInstance().ContractRecTypesMapByDevName.get('ADD'));
		testContract.LOB__c = 'VINSOLUTIONS';
		testContract.Status = 'Draft';
		testContract.Vin_Dealer_Id__c = '5886';
		insert testContract;

		Billing_Item__c bl1 = TestData.setUpBillingItem(testContract, TestData.getProduct('700 Credit Inc','VinSolutions'));
		bl1.RecordTypeId = StaticData.getInstance().BillingItemRecTypesMapByDevName.get('ADD').Id;
		insert bl1;	

		Test.startTest();
		// Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MotosnapCalloutMock());
        TestData.isMotoSnapCalloutSuccess = false;
        TestData.isMotoSnapTimeOutError = true;

        // Updating the recordType on the Billing_Item__c causes the trigger to fire the HTTP.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
		bl1.RecordTypeId = StaticData.getInstance().BillingItemRecTypesMapByDevName.get('MODIFY').Id;
		Database.update(bl1);
		
		Test.stopTest();

		//Check if a succesful log was created with an error
		List<Billing_Log__c> logs = [Select Log_Status__c,Log_Message__c,Billing_Item__c from Billing_Log__c where Billing_Item__c=: bl1.Id];
		system.assertEquals('Error', logs[0].Log_Status__c);
		system.assertNotEquals(logs[0].Log_Message__c, null);
	}

    public static testMethod void Test_MototosnapActive_Success() {
    	Account testAcct =TestData.setupAccount();
		insert testAcct;

		Contract testContract = TestData.setupContract(testAcct, StaticData.getInstance().ContractRecTypesMapByDevName.get('ADD'));
		testContract.LOB__c = 'VINSOLUTIONS';
		testContract.Status = 'Draft';
		testContract.Vin_Dealer_Id__c = '5886';
		insert testContract;

		Billing_Item__c bl1 = TestData.setUpBillingItem(testContract, TestData.getProduct('700 Credit Inc','VinSolutions'));
		bl1.RecordTypeId = StaticData.getInstance().BillingItemRecTypesMapByDevName.get('ADD').Id;
		insert bl1;	

		Test.startTest();
		// Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MotosnapCalloutMock());
        TestData.isMotoSnapCalloutSuccess = true;

        // Updating the recordType on the Billing_Item__c causes the trigger to fire the HTTP.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
		bl1.RecordTypeId = StaticData.getInstance().BillingItemRecTypesMapByDevName.get('MODIFY').Id;
		Database.update(bl1);

		Test.stopTest();

		//Check if a succesful log was created with a success
		List<Billing_Log__c> logs = [Select Log_Status__c,Log_Message__c,Billing_Item__c from Billing_Log__c where Billing_Item__c=: bl1.Id];
		system.assertEquals('Processed', logs[0].Log_Status__c);
		system.assertNotEquals(logs[0].Log_Message__c, null);

    }
}