objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Project_Definition__c</fullName>
        <description>Used by Vin Accounting to report on which project Billed Assets are linked to.</description>
        <formula>Product_Sold__r.Project_Definition__r.Project_Short_Code__c</formula>
        <label>Project Short Code</label>
        <type>Text</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup the POA related to this Case</inlineHelpText>
        <label>POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Related Cases</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/POA__c.object
<CustomObject>
    <description>used to handle Plan of Action items for an Account- gives the ability to group support or implementation issues together</description>
    <label>POA</label>
    <nameField>
        <label>Plan of Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POAs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Definition__c.object
<CustomObject>
    <description>This object will hold the attributes of the project.</description>
    <label>Project Definition</label>
    <nameField>
        <label>Project Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/StaticData_Test.cls
@isTest(SeeAllData=True) 
public class StaticData_Test { 
    static testMethod void testOpportunityRecTypesMap() {    	
    	Map<Id,RecordType> recTypes = StaticData.getInstance().OpportunityRecTypesMap;
    	System.Assert(recTypes != null,'No Opportunity record types returned');
    	System.Assert(recTypes.size() >0,'No Opportunity record types returned');
    	System.Assert(recTypes.values()[0].sObjectType == 'Opportunity','Did not return Opportunity recordTypes');
    	Map<String,RecordType> recTypesMapByDevName = StaticData.getInstance().OpportunityRecTypesMapByDevName;
    	System.Assert(recTypesMapByDevName != null,'No Opportunity record types returned');
    	System.Assert(recTypesMapByDevName.size() >0,'No Opportunity record types returned');
    	System.Assert(recTypesMapByDevName.values()[0].sObjectType == 'Opportunity','Did not return Opportunity recordTypes');
    }
    
    static testMethod void testProjectRecTypesMap() {    	
    	Map<Id,RecordType> recTypes = StaticData.getInstance().ProjectRecTypesMap;
    	System.Assert(recTypes != null,'No Project record types returned');
    	System.Assert(recTypes.size() >0,'No Project record types returned');
    	System.Assert(recTypes.values()[0].sObjectType == 'SFDC_520_Quote__c','Did not return Project recordTypes');
    	Map<String,RecordType> recTypesMapByDevName = StaticData.getInstance().ProjectRecTypesMapByDevName;    	
    	System.Assert(recTypesMapByDevName != null,'No Project record types returned');
    	System.Assert(recTypesMapByDevName.size() >0,'No Project record types returned');
    	System.Assert(recTypesMapByDevName.values()[0].sObjectType == 'SFDC_520_Quote__c','Did not return Project recordTypes');
    	Map<String,RecordType> recTypesMapByName = StaticData.getInstance().ProjectRecTypesMapByName;    	
    	System.Assert(recTypesMapByName != null,'No Project record types returned');
    	System.Assert(recTypesMapByName.size() >0,'No Project record types returned');
    	System.Assert(recTypesMapByName.values()[0].sObjectType == 'SFDC_520_Quote__c','Did not return Project recordTypes');
    }
    
    static testMethod void testProjectPiecesRecTypesMap() {    	
    	Map<Id,RecordType> recTypes = StaticData.getInstance().ProjectPiecesRecTypesMap;
    	System.Assert(recTypes != null,'No ProjectPieces record types returned');
    	System.Assert(recTypes.size() >0,'No ProjectPieces record types returned');
    	System.Assert(recTypes.values()[0].sObjectType == 'Project_Piece__c','Did not return ProjectPieces recordTypes');
    	Map<String,RecordType> recTypesMapByDevName = StaticData.getInstance().ProjectPiecesRecTypesMapByDevName;    	
    	System.Assert(recTypesMapByDevName != null,'No ProjectPieces record types returned');
    	System.Assert(recTypesMapByDevName.size() >0,'No ProjectPieces record types returned');
    	System.Assert(recTypesMapByDevName.values()[0].sObjectType == 'Project_Piece__c','Did not return ProjectPieces recordTypes');
    }
    
   static testMethod void testPOARecTypesMap() {    	
    	Map<Id,RecordType> recTypes = StaticData.getInstance().POARecTypesMap;
    	System.Assert(recTypes != null,'No POA record types returned');
    	System.Assert(recTypes.size() >0,'No POA record types returned');
    	System.Assert(recTypes.values()[0].sObjectType == 'POA__c','Did not return POA recordTypes');
    	Map<String,RecordType> recTypesMapByDevName = StaticData.getInstance().POARecTypesMapByDevName;    	
    	System.Assert(recTypesMapByDevName != null,'No POA record types returned');
    	System.Assert(recTypesMapByDevName.size() >0,'No POA record types returned');
    	System.Assert(recTypesMapByDevName.values()[0].sObjectType == 'POA__c','Did not return POA recordTypes');
    }
   static testMethod void testContractRecTypesMap() {    	
    	Map<Id,RecordType> recTypes = StaticData.getInstance().ContractRecTypesMap;
    	System.Assert(recTypes != null,'No Contract record types returned');
    	System.Assert(recTypes.size() >0,'No Contract record types returned');
    	System.Assert(recTypes.values()[0].sObjectType == 'Contract','Did not return Contract recordTypes');
    	Map<String,RecordType> recTypesMapByDevName = StaticData.getInstance().ContractRecTypesMapByDevName;    	
    	System.Assert(recTypesMapByDevName != null,'No Contract record types returned');
    	System.Assert(recTypesMapByDevName.size() >0,'No Contract record types returned');
    	System.Assert(recTypesMapByDevName.values()[0].sObjectType == 'Contract','Did not return Contract recordTypes');
    }
       static testMethod void testBillinItemRecTypesMap() {    	
    	Map<Id,RecordType> recTypes = StaticData.getInstance().BillingItemRecTypesMap;
    	System.Assert(recTypes != null,'No BillingItem record types returned');
    	System.Assert(recTypes.size() >0,'No BillingItem record types returned');
    	System.Assert(recTypes.values()[0].sObjectType == 'Billing_Item__c','Did not return BillingItem recordTypes');
    	Map<String,RecordType> recTypesMapByDevName = StaticData.getInstance().BillingItemRecTypesMapByDevName;    	
    	System.Assert(recTypesMapByDevName != null,'No BillingItem record types returned');
    	System.Assert(recTypesMapByDevName.size() >0,'No BillingItem record types returned');
    	System.Assert(recTypesMapByDevName.values()[0].sObjectType == 'Billing_Item__c','Did not return BillingItem recordTypes');
    }
    
           static testMethod void testProjectDefinitionsMap() {    	
    	Map<Id,Project_Definition__c> projDefList = StaticData.getInstance().ProjectDefinitions();
    	System.Assert(projDefList != null,'No Project Definitions returned');
    	System.Assert(projDefList.size() >0,'No Project Definitions returned');    	
    }
    static testmethod void testTaskRecordTypesMapByDevName() {
        Map<String,RecordType> recTypesMapByDevName = StaticData.getInstance().TaskRecordTypeMapByDevName;     
        System.Assert(recTypesMapByDevName != null,'No Task record types returned');
        System.Assert(recTypesMapByDevName.size() >0,'No Task record types returned');
        System.Assert(recTypesMapByDevName.values()[0].sObjectType == 'Task','Did not return Task recordTypes');
    }
    static testMethod void testCaseRecordTypesMap() {       
        Map<Id,RecordType> recTypes = StaticData.getInstance().CaseRecTypesMap;
        System.Assert(recTypes != null,'No Case record types returned');
        System.Assert(recTypes.size() >0,'No Case record types returned');
        System.Assert(recTypes.values()[0].sObjectType == 'Case','Did not return Case recordTypes');
        Map<String,RecordType> recTypesMapByDevName = StaticData.getInstance().CaseRecTypesMapByDevName;     
        System.Assert(recTypesMapByDevName != null,'No Case record types returned');
        System.Assert(recTypesMapByDevName.size() >0,'No Case record types returned');
        System.Assert(recTypesMapByDevName.values()[0].sObjectType == 'Case','Did not return Case recordTypes');
        Map<String,RecordType> recTypesMapByName = StaticData.getInstance().CaseRecTypesMapByName;       
        System.Assert(recTypesMapByName != null,'No Case record types returned');
        System.Assert(recTypesMapByName.size() >0,'No Case record types returned');
        System.Assert(recTypesMapByName.values()[0].sObjectType == 'Case','Did not return Case recordTypes');
    }
    static testMethod void testAccountRecordTypesMap() {       
        Map<Id,RecordType> recTypes = StaticData.getInstance().AccountRecTypesMap;
        System.Assert(recTypes != null,'No Account record types returned');
        System.Assert(recTypes.size() >0,'No Account record types returned');
        System.Assert(recTypes.values()[0].sObjectType == 'Account','Did not return Account recordTypes');
        Map<String,RecordType> recTypesMapByDevName = StaticData.getInstance().AccountRecTypesMapByDevName;     
        System.Assert(recTypesMapByDevName != null,'No Account record types returned');
        System.Assert(recTypesMapByDevName.size() >0,'No Account record types returned');
        System.Assert(recTypesMapByDevName.values()[0].sObjectType == 'Account','Did not return Account recordTypes');
        Map<String,RecordType> recTypesMapByName = StaticData.getInstance().AccountRecTypesMapByName;       
        System.Assert(recTypesMapByName != null,'No Account record types returned');
        System.Assert(recTypesMapByName.size() >0,'No Account record types returned');
        System.Assert(recTypesMapByName.values()[0].sObjectType == 'Account','Did not return Account recordTypes');
    }

     static testMethod void testPricebookEntry() {             
        System.Assert(StaticData.getInstance().GetPricebookEntry('2014 Standard Price Book','SVC-MSDIAPAC') != null,'No product entry is returned');
        //check invalid pricebook data
        try{
                StaticData.getInstance().GetPricebookEntry('NonExistingPriceBook','SVC-MSDIAPAC');
        }
        catch(Exception ex){
            System.assert(ex.getMessage().contains('Could not find Price Book'));
        }

        //check invalid product
        try{
                StaticData.getInstance().GetPricebookEntry('2014 Standard Price Book','NonExistingProduct');
        }
        catch(Exception ex){
            System.assert(ex.getMessage().contains('Could not find Product'));
        }                
    }

    static testMethod void testDisabledTriggers() {             
        Set<String> results = StaticData.DisabledTriggers;
        system.assert(results != null ,'Did not return a valid object');
    }
}