objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Debug__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Debug</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>aka Stop Date Provide an End Date to stop billing for this item.  Cannot be after Contract End Date. Default to 12/31/2100 if not provided on Add or Modify action.</inlineHelpText>
        <label>Billing End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MSDelayRemovedDONOTCHANGE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MSDelayRemovedDONOTCHANGE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>Product_Sold__r.ProductCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vin_Dealer_Id__c</fullName>
        <formula>Contract__r.Vin_Dealer_Id1__c</formula>
        <label>Vin Dealer Id</label>
        <type>Text</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>Add a new line item to a billing contract</description>
        <label>ADD</label>
    </recordTypes>
    <recordTypes>
        <fullName>STOP</fullName>
        <active>false</active>
        <label>STOP</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/job_updateDelayStop.cls
global with sharing class job_updateDelayStop implements Database.Batchable<sObject>, Database.AllowsCallouts { 
	
	global integer items {get;set;}
	global integer totalItems {get;set;}
	
	// Constructor
	global job_updateDelayStop() {
		
		items = 0;
		totalItems = 0;
	}
	
	// Start
	global Database.QueryLocator start(Database.Batchablecontext BC) {
		
		return Database.getQueryLocator([SELECT Id, Debug__c, End_Date__c, MSDelayRemovedDONOTCHANGE__c, Contract__c, Vin_Dealer_Id__c, Product_Code__c FROM Billing_Item__c WHERE MSDelayRemovedDONOTCHANGE__c = true]);
	}
	
	// Execute
	global void execute(Database.Batchablecontext BC, List<Billing_Item__c> scope) {
		
		List<Billing_Item__c> updateBillingItems = new List<Billing_Item__c>();
		
		for(Billing_Item__c bi : scope) {
			
			if(bi.End_Date__c < system.today()) {
				
				bi.MSDelayRemovedDONOTCHANGE__c = false;
				//bi.Debug__c = true;
				
				updateBillingItems.add(bi);
				
				items++;
			}
		}
		
		totalItems = scope.size();
		
		handler_BillingItem.prepareDataForActivateDeactivateFeaturesCallout(true, false, updateBillingItems);
		
		update updateBillingItems;
	}
	
	// Finish
	global void finish(Database.Batchablecontext BC) {
		
		AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
            				TotalJobItems, CreatedBy.Email
            			  FROM AsyncApexJob WHERE Id = :BC.getJobId()];

        string message = 'Delay Stop batch apex job: processed ' + a.JobItemsProcessed + ' out of ' + a.TotalJobItems + ' batches with '+ a.NumberOfErrors + ' failures.';

        // Send an email to the Apex job's submitter notifying of job completion.
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'dean.lukowski@vinsolutions.com', 'maggie.jolitz@vinsolutions.com'};
        mail.setToAddresses(toAddresses);
        mail.setSubject('Salesforce Batch Delay Stop Job ' + a.Status);
        mail.setPlainTextBody(message);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });  
	}
	
}