objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Launch</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>aka Stop Date Provide an End Date to stop billing for this item.  Cannot be after Contract End Date. Default to 12/31/2100 if not provided on Add or Modify action.</inlineHelpText>
        <label>Billing End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LOB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup to the BU POA only if the Product is a primary product: CRM, ILM, Webiste, Provision, Conquest, Auction Genius. A primary product has the field &quot;Base Asset&quot; set to True in the product record detail page</inlineHelpText>
        <label>Primary Product Status</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Product Status List</relationshipLabel>
        <relationshipName>Billing_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>Add a new line item to a billing contract</description>
        <label>ADD</label>
    </recordTypes>
    <recordTypes>
        <fullName>CANCEL</fullName>
        <active>true</active>
        <description>record type is updated by the system when the contract is cancelled</description>
        <label>CANCELLED</label>
    </recordTypes>
    <recordTypes>
        <fullName>MODIFY</fullName>
        <active>true</active>
        <description>used to modify an exisiting billing items</description>
        <label>MODIFY</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <description>field label changed from Cancellation Reason to Churn Reason - 10/30 for vauto migration</description>
        <label>Churn Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Brand compliancy/OEM Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Correction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cutting Expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealership Closed/Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did Not Receive Functionality That Was Expected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lack of Communication/Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial/Reduction of Service(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Performance Related Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Too Expensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Went w/Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V2V Buy/Sell</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LOB__c</fullName>
        <label>LOB</label>
        <picklist>
            <picklistValues>
                <fullName>VAUTO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VINSOLUTIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIN-CAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>use to add a new contract (order) to the AutoTrader Billing System</description>
        <label>ADD</label>
    </recordTypes>
    <recordTypes>
        <fullName>Cancel</fullName>
        <active>true</active>
        <description>read only field page layout after contract end date and reason is entered</description>
        <label>CANCELLED</label>
    </recordTypes>
    <recordTypes>
        <fullName>Cancel_Contract</fullName>
        <active>true</active>
        <description>use to initiate the full cancellation of a contract</description>
        <label>Cancel Contract</label>
    </recordTypes>
    <recordTypes>
        <fullName>Modify</fullName>
        <active>true</active>
        <description>used when adding or changing product to an existing contract</description>
        <label>MODIFY</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/vAutoContractHandler_Test.cls
@isTest(SeeAllData=true) 
public class vAutoContractHandler_Test {
	static testMethod void  Cancel() {
		Account a =TestData.setupAccount();
		insert a;
		Contract  c = TestData.setupContract(a, StaticData.getInstance().ContractRecTypesMapByDevName.get('ADD'));
		c.LOB__c = 'VAUTO';
		c.Action__c = 'Modify';
        c.Status = 'Draft';
		insert c;
		Billing_Item__c bl1 = TestData.setUpBillingItem(c, TestData.getProduct('Appraisal Tool','vAuto'));
		insert bl1;		
				Billing_Item__c bl2 = TestData.setUpBillingItem(c, TestData.getProduct('Pricing Tool','vAuto'));
		insert bl2;		
				Billing_Item__c bl3 = TestData.setUpBillingItem(c, TestData.getProduct('30 Day Deposit','vAuto'));
		insert bl3;		
				Billing_Item__c bl4 = TestData.setUpBillingItem(c, TestData.getProduct('PriceGuide.KelleyBlueBook (KarPower)','vAuto'));
		insert bl4;		
				Billing_Item__c bl5 = TestData.setUpBillingItem(c, TestData.getProduct('PriceGuide.KBBOnline','vAuto'));
		insert bl5;		
				Billing_Item__c bl6 = TestData.setUpBillingItem(c, TestData.getProduct('AutoWriter','vAuto'));
		insert bl6;		
				Billing_Item__c bl7 = TestData.setUpBillingItem(c, TestData.getProduct('Listings/Photos/Syndication','vAuto'));
		insert bl7;						
	   Test.startTest();
        
        /*
        //update the contract and set end date
        c.RecordTypeId = StaticData.getInstance().ContractRecTypesMapByDevName.get('Cancel_Contract').Id;
        c.Action__c = 'Modify';
        c.Status = 'Draft';
        c.Cancellation_Reason__c = 'Cutting Expenses';
        c.Integration_Status__c = 'Pending';
        c.StartDate = Date.today().addDays(-2);
        c.EndDate = Date.today();
        update c;
        List<Billing_Item__c> bLines = [Select Id, Action__c,End_Date__c,RecordTypeId from Billing_Item__c where Contract__c=: c.Id];
        System.assert(bLines.size() ==7 , 'Incorrect Billing Lines');
        for(Billing_Item__c item : bLines){
        	System.assert(item.Action__c == 'Cancelled', 'Action__c is not set to Cancelled after the contract was Cancelled');
        	System.assert(item.End_Date__c == c.EndDate, 'End_Date__c is not same as contract EndDate');
        	System.assert(item.RecordTypeId == StaticData.getInstance().BillingItemRecTypesMapByDevName.get('CANCEL').Id, 'RecordTypeId is not set to Cancel after the contract was Cancelled');        	
        }
        */
	   Test.stopTest();		

	}
}