objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Launch</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>aka Stop Date Provide an End Date to stop billing for this item.  Cannot be after Contract End Date. Default to 12/31/2100 if not provided on Add or Modify action.</inlineHelpText>
        <label>Billing End Date</label>
        <type>Date</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>Add a new line item to a billing contract</description>
        <label>ADD</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>use to add a new contract (order) to the AutoTrader Billing System</description>
        <label>ADD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/handler_updateContractCancel.cls
public with sharing class handler_updateContractCancel {
	
	public static void updateRelatedBillingItemsCancel(List<Contract> contracts) {
		
		Set<Id> contractIds = new Set<Id>();
		
		for(Contract c : contracts) {
									//cancelled 012V00000000FaB
			if(c.RecordTypeId == '01270000000Q9vW') {
				
				contractIds.add(c.Id);
			}
		}
		
		if(contractIds.size() > 0) {
			
			List<Billing_Item__c> updateBillingItems = new List<Billing_Item__c>();
			
			updateBillingItems = [SELECT Id, RecordTypeId, End_Date__c, Contract__c, Action__c
								  FROM Billing_Item__c
								  WHERE Contract__c IN :contractIds];
			
			for(Contract c : contracts) {
				
				for(Billing_Item__c bi : updateBillingItems) {
		  		
		  			if(bi.Contract__c == c.Id) {
		  				
		  				bi.Action__c = 'Cancelled';
		  				bi.RecordTypeId = '01270000000Q9wT'; //cancelled 012V00000000FmG
		  				bi.End_Date__c = c.EndDate; 
		  			}
		  		}
			}
			
			try {
				
				update updateBillingItems;
				
				//Exception Testing and handling
	        	if(utility.throwExceptionError() == true){
	        		string Ex = null;
	        		Ex.tolowercase();
	        	}
			}
			catch(Exception e) {
				//do nothing
			}			  
		  	
		}
	}
}