objects/Billing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Launch</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>Contract__r.Business_Unit__c</formula>
        <inlineHelpText>Which Business Unit is associated with this Billed Asset. Pulls from the Contract field, which in turn pulls from the Opp.</inlineHelpText>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Billed Assets</relationshipLabel>
        <relationshipName>Billing_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>aka Stop Date Provide an End Date to stop billing for this item.  Cannot be after Contract End Date. Default to 12/31/2100 if not provided on Add or Modify action.</inlineHelpText>
        <label>Billing End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LOB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup to the BU POA only if the Product is a primary product: CRM, ILM, Webiste, Provision, Conquest, Auction Genius. A primary product has the field &quot;Base Asset&quot; set to True in the product record detail page</inlineHelpText>
        <label>Primary Product Status</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Product Status List</relationshipLabel>
        <relationshipName>Billing_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ready_to_Bill__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This field is updated when you are ready to send the Contract and Billed Assets to AutoTrader for billing</inlineHelpText>
        <label>Ready to Bill</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Default to Contract Start Date for all one time. Cannot be after Contract Stop Date or before Contract Start Date. Must be on or after Line Start Date. For Deposits, default to Contract Start Date.</inlineHelpText>
        <label>Billing Start Date</label>
        <type>Date</type>
    </fields>
    <label>Billed Asset</label>
    <nameField>
        <displayFormat>LI-{0000000}</displayFormat>
        <label>Asset Link</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billed Assets</pluralLabel>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>Add a new line item to a billing contract</description>
        <label>ADD</label>
    </recordTypes>
    <recordTypes>
        <fullName>CANCEL</fullName>
        <active>true</active>
        <description>record type is updated by the system when the contract is cancelled</description>
        <label>CANCELLED</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Business_Unit__c.object
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>What BU this Contract is associated with.</description>
        <formula>IF( 
   ISPICKVAL(Contract_Type__c, &quot;vAuto&quot;), 
   &quot;vAuto&quot;,
   IF(
      !ISBLANK(Related_Opportunity__c),
      Related_Opportunity__r.Business_Unit__c,
      IF(
         ISPICKVAL(CreatedBy.Business_Unit__c, &quot;VIN&quot;) ||
         (
            CONTAINS(CreatedBy.Username, &quot;maggie.jolitz@vinsolutions.com&quot;) &amp;&amp;
            DATEVALUE(CreatedDate) &lt; DATE(2014,1,1)
         ),
         &quot;VinSolutions&quot;,
         IF(
            ISPICKVAL(CreatedBy.Business_Unit__c, &quot;HAY&quot;),
            &quot;Haystak&quot;,
            &quot;NOT DEFINED - SEE ADMIN&quot;
         )
      )
   )
)</formula>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LOB__c</fullName>
        <label>LOB</label>
        <picklist>
            <picklistValues>
                <fullName>VAUTO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VINSOLUTIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIN-CAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ready_to_Bill__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>updated by the user when the contract and billing items are ready to bill to RMB</inlineHelpText>
        <label>Ready to Bill</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>use to add a new contract (order) to the AutoTrader Billing System</description>
        <label>ADD</label>
    </recordTypes>
    <recordTypes>
        <fullName>Cancel</fullName>
        <active>true</active>
        <description>read only field page layout after contract end date and reason is entered</description>
        <label>CANCELLED</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <inlineHelpText>Needed by many fields and automation. Please fill out!</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>VIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Test_Contract.cls
/*
Ramana Mosali: 10/28/2014
Adding this test class to improve the test coverage for contract trigger and its classes
handler_updateContractReadyToBill.cls
handler_updateContractCancel.cls
*/

@isTest(SeeAllData=true)
public with sharing class Test_Contract {
	static testMethod void  VINContractReadyToBill() {
		User testUser = TestData.setupUser();
		testUser.Business_Unit__c = 'VIN';
		update testUser;

	   System.runAs(testUser){
		Account a =TestData.setupAccount();
		insert a;
		Contract  c = TestData.setupContract(a, StaticData.getInstance().ContractRecTypesMapByDevName.get('ADD'));
		c.LOB__c = 'VINSOLUTIONS';
		insert c;
		Billing_Item__c bl1 = TestData.setUpBillingItem(c, TestData.getProduct('700 Credit Inc','VinSolutions'));
		bl1.Ready_to_Bill__c = true;
		bl1.Start_Date__c = system.today();
		Database.SaveResult SR1 = Database.insert(bl1);	
		Billing_Item__c bl2 = TestData.setUpBillingItem(c, TestData.getProduct('Advanced Inventory with Website and MPT Package','VinSolutions'));
		bl2.Ready_to_Bill__c = true;
		bl2.Start_Date__c = system.today();
		Database.SaveResult SR2 = Database.insert(bl2);
 

	   Test.startTest();
		    //update the contract and set Ready_To_Bill__c to true
		    c.Ready_To_Bill__c = TRUE;
		    c.StartDate = Date.today();
		    update c;
		    List<Billing_Item__c> bLines = [Select Id, Ready_To_Bill__c from Billing_Item__c where Contract__c=: c.Id];
		    System.assert(bLines.size() ==2 , 'Incorrect Billing Lines');
		    for(Billing_Item__c item : bLines){
		    	System.assert(item.Ready_To_Bill__c, 'Ready_To_Bill__c is not set to true; after the contractis set for ready to bill');
		    }
		
	   Test.stopTest();		
	}
	}

/*
	static testMethod void  VINContractCancel() {
		Account a =TestData.setupAccount();
		insert a;
		Contract  c = TestData.setupContract(a, StaticData.getInstance().ContractRecTypesMapByDevName.get('ADD'));
		c.LOB__c = 'VINSOLUTIONS';
		insert c;
		Billing_Item__c bl1 = TestData.setUpBillingItem(c, TestData.getProduct('700 Credit Inc','VinSolutions'));
		insert bl1;		
		Billing_Item__c bl2 = TestData.setUpBillingItem(c, TestData.getProduct('Advanced Inventory with Website and MPT Package','VinSolutions'));
		insert bl2;
 

	   Test.startTest();
        
        //update the contract and set end date
        c.RecordTypeId = StaticData.getInstance().ContractRecTypesMapByDevName.get('Cancel').Id;
        c.EndDate = Date.today();
        update c;
        List<Billing_Item__c> bLines = [Select Id, Action__c,End_Date__c,RecordTypeId from Billing_Item__c where Contract__c=: c.Id];
        System.assert(bLines.size() ==2 , 'Incorrect Billing Lines');
        for(Billing_Item__c item : bLines){
        	System.assert(item.Action__c == 'Cancelled', 'Action__c is not set to Cancelled after the contract was Cancelled');
        	System.assert(item.End_Date__c == c.EndDate, 'End_Date__c is not same as contract EndDate');
        	System.assert(item.RecordTypeId == StaticData.getInstance().BillingItemRecTypesMapByDevName.get('CANCEL').Id, 'RecordTypeId is not set to Cancel after the contract was Cancelled');        	
        }
	   Test.stopTest();		

	}
*/
}