objects/Business_Unit__c.object
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <inlineHelpText>when a contact is created the BU = Shared, unless the user&apos;s profile has the company name = vAuto, then the BU is updated to vAuto. Validation rule prevents non vauto users from editing a vauto contact record</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Shared</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gone__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if this contact is no longer with this dealership.</inlineHelpText>
        <label>Gone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Appraiser Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Appends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Car Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Car Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricer Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMM Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UCM / UCD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Website</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Trained_Date__c</fullName>
        <description>Date this contact was trained by vAuto staff</description>
        <label>Provision Trained Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>vAuto_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>this field is populated by workflow so that vauto contacts will show in the vauto contact related list on the account</inlineHelpText>
        <label>vAuto Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>vAuto Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/POA__c.object
<CustomObject>
    <description>used to handle Plan of Action items for an Account- gives the ability to group support or implementation issues together</description>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>CASE(
   RecordType.DeveloperName,
   &quot;Vin_Account_Mgmt&quot;, &quot;VinSolutions&quot;,
   &quot;Account_Mgmt_POA&quot;, &quot;VinSolutions&quot;,
   &quot;AutoTrader&quot;, &quot;VinSolutions&quot;,
   &quot;CRM_Followup&quot;, &quot;VinSolutions&quot;,
   &quot;Cancellation&quot;, &quot;VinSolutions&quot;,
   &quot;Implementation&quot;, &quot;VinSolutions&quot;,
   &quot;New_Account_Follow_up&quot;, &quot;VinSolutions&quot;,
   &quot;New_Website_Followup&quot;, &quot;VinSolutions&quot;,
   &quot;Support&quot;, &quot;VinSolutions&quot;,
   &quot;VinSocial&quot;, &quot;VinSolutions&quot;,
   &quot;Vin Analytics&quot;, &quot;VinSolutions&quot;,
   &quot;Vin Behavioral&quot;,&quot;VinSolutions&quot;,
   &quot;New_Website_POA&quot;, &quot;VinSolutions&quot;,
   &quot;Haystak_SEM&quot;, &quot;Haystak&quot;,
   &quot;Haystak_SEO&quot;, &quot;Haystak&quot;,
   &quot;Haystak&quot;, &quot;Haystak&quot;,
   &quot;vAuto&quot;,&quot;vAuto&quot;,
   &quot;Haystak_Search_Essentials&quot;, &quot;Haystak&quot;,
   &quot;NOT DEFINED - SEE ADMIN&quot;
)</formula>
        <inlineHelpText>What BU controls this record. Set by Record Type.</inlineHelpText>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup the dealer that the plan of action is needed for</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan of Action(s)</relationshipLabel>
        <relationshipName>POA_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>POA</label>
    <nameField>
        <label>Plan of Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POAs</pluralLabel>
    <recordTypes>
        <fullName>vAuto</fullName>
        <active>true</active>
        <label>vAuto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ViewKeyContacts.cls
/*
 * Class/Method Name: ViewKeyContacts
 * Author/Date: Dean Lukowski November 7, 2014
 * Purpose: To create a visualforce related list on the vAuto POA page layout,
 * as to filter out contacts that are not vAuto on the associated account.
 */

public with sharing class ViewKeyContacts {

    public String POAId{get;set;}
    public POA__c poaObj{get;set;}
    public String poaAccount{get;set;}
    public String poaAccountName{get;set;}
    public List<Contact> keyContacts{get;set;}
    public List<KeyContactsWrapper> keyContactWrapList{get;set;}
    public KeyContactsWrapper keyContactsWrap{get;set;}
    public String removeKCId {get;set;}
    public String editKCId {get;set;}
    public String viewKCId {get;set;}
    public Integer numOfKCRows {get;set;}
    public Boolean sendEmails {get;set;}
    public String pageURL {get;set;}

    private ApexPages.StandardController stdController;
    public ViewKeyContacts(ApexPages.StandardController stdController) {
        this.stdController = stdController;
        POAId = String.valueOf(stdController.getRecord().get('id'));
        pageURL = ApexPages.currentPage().getUrl();
        if(pageURL.contains('&inline')){
            sendEmails = true;
        }
        else{
            sendEmails = false;
        }
        getAccount();
        getvAutoContacts();
        initializeKeyContactsWrapper();
    }

    public PageReference Refresh(){
        getvAutoContacts();
        initializeKeyContactsWrapper();
        return null;
    }

    //Grabbing the Account on the POA.
    public void getAccount(){
        try {
            if (POAId != null){
                poaObj = [SELECT Id, Name, Dealer__r.Id,Dealer__r.Name, Business_Unit__c
                          FROM   POA__c
                          WHERE  Id =: POAId LIMIT 1];

                if (poaObj != null){
                    poaAccount = poaObj.Dealer__r.Id;
                }
            }
            else{
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Unable to retrieve an ID for a POA.');
                ApexPages.addMessage(myMsg);
            }
        }
        catch (exception e) {
            System.debug('getAccount() encountered an exception: ' + e.getMessage());
            throw e;
        }
    }

    //Grabbing the vAuto Contacts from the Account on the POA.
    public void getvAutoContacts(){
        try{
            if (poaAccount != null) {
                keyContacts = [SELECT Id, Name, Email, MobilePhone, Phone, Title, Business_Unit__c, Gone__c, Trained_Date__c,
                                      vAuto_Account__c, Role__c
                               FROM   Contact
                               WHERE  AccountId =: poaAccount AND vAuto_Account__c != null ORDER BY Gone__c Asc, Name Asc];
            numOfKCRows = keyContacts.size();
            }
            else{
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Unable to retrieve an AccountId from the POA.');
                ApexPages.addMessage(myMsg);
            }
        }
        catch (exception e) {
            System.debug('getvAutoContacts() encountered an exception: ' + e.getMessage());
            throw e;
        }
    }

    //Utilizing a class to setup each record to appear in a custom related list.
    public void initializeKeyContactsWrapper(){
        keyContactWrapList = null;
        if(keyContacts != null && keyContacts.size() > 0){
            keyContactWrapList = new List<KeyContactsWrapper>();
            for(Contact thisContact : keyContacts){
                keyContactsWrap = new KeyContactsWrapper();
                keyContactsWrap.contactId = thisContact.Id;
                keyContactsWrap.contactName = thisContact.Name;
                keyContactsWrap.contactTitle = thisContact.Title;
                keyContactsWrap.contactPhone = thisContact.Phone;
                keyContactsWrap.contactMobilePhone = thisContact.MobilePhone;
                keyContactsWrap.contactEmail = thisContact.Email;
                keyContactsWrap.contactGone = thisContact.Gone__c;
                keyContactsWrap.contactTrainedDate = thisContact.Trained_Date__c;
                keyContactsWrap.contactRole = thisContact.Role__c;
                keyContactWrapList.add(keyContactsWrap);
            }
        }
    }

    //The class for all related contacts
    public class KeyContactsWrapper{
        public String contactId{get;set;}
        public String contactName{get;set;}
        public String contactEmail{get;set;}
        public String contactMobilePhone{get;set;}
        public String contactPhone{get;set;}
        public String contactTitle{get;set;}
        public Boolean contactGone{get;set;}
        public String vAutoAccount{get;set;}
        public String vAutoAccountStatus{get;set;}
        public Date contactTrainedDate{get;set;}
        public String contactRole{get;set;}
    }
}