objects/Business_Unit__c.object
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <inlineHelpText>when a contact is created the BU = Shared, unless the user&apos;s profile has the company name = vAuto, then the BU is updated to vAuto. Validation rule prevents non vauto users from editing a vauto contact record</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Shared</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>vAuto</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>vAuto_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>this field is populated by workflow so that vauto contacts will show in the vauto contact related list on the account</inlineHelpText>
        <label>vAuto Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>vAuto Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <inlineHelpText>Needed by many fields and automation. Please fill out!</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>VIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Contact_Test.cls
@isTest
private class Contact_Test {
	
	@isTest static void test_SetvAutoAccount_Create_vAutoBUUser() {
		Account a = TestData.setupAccount();
		insert a;
		User u = TestData.setupUser();
		u.Business_Unit__c = 'VAT';
		update u;
		System.runAs(u){

			Contact c = TestData.setupContact(a, null);
			insert c;
			c = [Select Id, vAuto_Account__c , AccountId from Contact where Id=: c.Id];
			System.assert(c.vAuto_Account__c == c.AccountId,'vAuto_Account__c is not populated');
		}
	}

	@isTest static void test_SetvAutoAccount_Edit_vAutoBUUser() {
		Account a = TestData.setupAccount();
		insert a;
		User u = TestData.setupUser();
		u.Business_Unit__c = 'VAT';
		update u;
		Contact c = TestData.setupContact(a, null);
		insert c;
		//reset the vAuto_Account__c filed to test trigger funtionality for sure.
		c.vAuto_Account__c = null;
		update c;		
		System.runAs(u){
			c.FirstName = 'TestFirstNameChanged';
			update c;
			c = [Select Id, vAuto_Account__c , AccountId from Contact where Id=: c.Id];
			System.assert(c.vAuto_Account__c == c.AccountId,'vAuto_Account__c is not populated');
		}
	}

	@isTest static void test_SetvAutoAccount_Create_NonvAutoBUUser() {
		Account a = TestData.setupAccount();
		insert a;
		User u = TestData.setupUser();
		u.Business_Unit__c = 'VIN';
		update u;
		System.runAs(u){

			Contact c = TestData.setupContact(a, null);
			insert c;
			c = [Select Id, vAuto_Account__c , AccountId from Contact where Id=: c.Id];
			System.assert(c.vAuto_Account__c ==null,'vAuto_Account__c is not populated');
		}
	}

	@isTest static void test_SetvAutoAccount_Edit_NonvAutoBUUser() {
		Account a = TestData.setupAccount();
		insert a;
		User u = TestData.setupUser();
		u.Business_Unit__c = 'VIN';
		update u;
		Contact c = TestData.setupContact(a, null);
		insert c;
		//reset the vAuto_Account__c filed to test trigger funtionality for sure.
		c.vAuto_Account__c = null;
		update c;		
		System.runAs(u){
			c.FirstName = 'TestFirstNameChanged';
			update c;
			c = [Select Id, vAuto_Account__c , AccountId from Contact where Id=: c.Id];
			System.assert(c.vAuto_Account__c == null,'vAuto_Account__c is not populated');
		}
	}


	
}