objects/Case.object
<CustomObject>
    <fields>
        <fullName>Defect__c</fullName>
        <label>Defect Id #</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Runner__c.object
<CustomObject>
    <fields>
        <fullName>Case_Description__c</fullName>
        <label>Case Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Runners</relationshipLabel>
        <relationshipName>Case_Runners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Defect_Id__c</fullName>
        <label>Defect Id#</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Case Runner</label>
    <nameField>
        <displayFormat>CR-{YYYY}{MM}-{0}</displayFormat>
        <label>Case Runner Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Runners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/caseHandler.cls
public class caseHandler {
	
	/*
	public static void updateCaseDescriptionOnRunner(List<Case_Runner__c> runners){
		List<Case> updateCases = new List<Case>();
		Set<Id> caseIds = new Set<Id>();
		for(Case_Runner__c r : runners){
			if(r.case__c != null){
				caseIds.add(r.case__c);
			}
		}
		
		Map<Id, Case> caseMap = new Map<Id, Case>([Select Id, Defect__c, Description 
													FROM Case 
													WHERE Id = :caseIds]);
		for(Case_Runner__c r : runners){
			//Begin old logic
			if(r.RecordTypeId == '012700000005eL7' && r.Defect_Id__c != null && caseMap.containsKey(r.case__c)){
				//Case D = [Select Id, Defect__c, Description from Case where Id = : r.Case__c];
				Case c = caseMap.get(r.case__c);
				r.Case_Description__c = c.Description;
				
				if(c.Defect__c == null){
					c.Defect__c = r.Defect_Id__c;
					updateCases.add(c);
					//update D;
				}
			}
			//end old logic
		}
		update updateCases;
	}
	*/
	
	@future	
	public static void updateRelatedCases (Set<Id> caseIds){
		List<Case> updateCases = [select Id from Case where Id IN :caseIds];
		update updateCases;
	}
		
}