objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date_Escalated__c</fullName>
        <inlineHelpText>updated by workflow when the escalation case runner is created and saved</inlineHelpText>
        <label>Date Escalated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Escalate_To__c</fullName>
        <label>Escalate To</label>
        <picklist>
            <picklistValues>
                <fullName>App Request Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Extract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhancement Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export Setup Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gatekeeper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Questions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Support Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - Creative Requests</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - Paid Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - SEO Requests</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - Tech Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jira Request Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L1-Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Creative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-CRM Admin/Settings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Desking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Escalations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Exports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Forms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Phone System(PBX)</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Escalation_Type__c</fullName>
        <label>Escalation Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1_What_is_happening__c</fullName>
        <inlineHelpText>Why do you believe there&apos;s a bug/defect?</inlineHelpText>
        <label>1) What is happening &amp; how to replicate?</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X2_What_did_you_expect_to_happen__c</fullName>
        <inlineHelpText>Indicate the proper functionality and NOT just the opposite of Question #1</inlineHelpText>
        <label>2) What is normally expected to happen?</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X3_When_did_it_start_happening__c</fullName>
        <label>3) When did it  start happening?</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X4_What_do_you_think_the_problem_is__c</fullName>
        <inlineHelpText>What type of problem do you think this is? and what data are you  basing this on? (EXAMPLE: &quot;This may be related to IE as it appears to only be an issue while using IE&quot;)</inlineHelpText>
        <label>4) What do you think the problem is?</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X5_What_have_you_tried_so_far__c</fullName>
        <inlineHelpText>Where have you looked and what have you tried in order to fix/workaround the issue and what did/didn&apos;t work?</inlineHelpText>
        <label>5) What have you tried so far?</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vAuto_Case_Reason__c</fullName>
        <label>vAuto Case Reason</label>
        <picklist>
            <controllingField>vAuto_Product_Line__c</controllingField>
            <picklistValues>
                <fullName>ADP Write Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appraisal Custom Voucher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appraisal Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Genius</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoWriter Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitive Set Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist/eBay/Smart Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM New Vendor Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deal Finder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete Duplicate VIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Description/Disclaimer issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Switch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Switch FROM CDK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Switch FROM Reynolds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Switch - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Switch TO CDK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Switch TO Reynolds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entity Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export Vehicle Setting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed Export</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GeniusSync</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Homenet Migration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Age/Vin/Other Data Change</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>vAuto_Product_Line__c</fullName>
        <label>vAuto Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>Appraisal Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Genius</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoCheck/Carfax/CarProof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Export/Syndication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Switch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhancement Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GeniusSync</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory/Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KBB Price Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Listing Logic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merchandising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Deal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stockwave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subprime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TIM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VinSolutions Appraisal Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>vNetwork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Window Stickers</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Support</fullName>
        <active>true</active>
        <businessProcess>VS Cases</businessProcess>
        <label>Support</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/handler_caseTrigger_Test.cls
@isTest
private class handler_caseTrigger_Test {
	
	@isTest static void testInsertingCase() {
		Account testAccount = TestData.setupAccount();
		insert testAccount;
		Contact testContact = TestData.setupContact(testAccount, 'Shared');
		insert testContact;
		Case testCase = TestData.setupCase(testAccount, testContact);
		Database.SaveResult SR1 = Database.insert(testCase);
		System.assertEquals(true, SR1.isSuccess());
	}
	
	@isTest static void testInsertParentInsertUpdateChild() {
		Account testAccount = TestData.setupAccount();
		insert testAccount;
		Contact testContact = TestData.setupContact(testAccount, 'Shared');
		insert testContact;
		Case testParentCase = TestData.setupCase(testAccount, testContact);
		Database.SaveResult SR1 = Database.insert(testParentCase);

		Test.startTest();

		//insert child with parent
		Case testChildCase1 = TestData.setupCaseWithParent(testAccount, testContact, testParentCase);
		Database.SaveResult SR2 = Database.insert(testChildCase1);
		System.assertEquals(true, SR1.isSuccess());
		System.assertEquals(true, SR2.isSuccess());

		//insert child then update with parent
		Case testChildCase2 = TestData.setupCase(testAccount, testContact);
		Database.SaveResult SR3 = Database.insert(testChildCase2);
		System.assertEquals(true, SR3.isSuccess());
		testChildCase2.ParentId = SR1.getId();
		Database.UpsertResult UR1 = Database.upsert(testChildCase2);
		System.assertEquals(true, UR1.isSuccess());

		Test.stopTest();
	}

	@isTest static void testUpdateChildrenWithChangesToParent() {
		Account testAccount = TestData.setupAccount();
		insert testAccount;
		Contact testContact = TestData.setupContact(testAccount, 'Shared');
		insert testContact;
		Case testParentCase = TestData.setupCase(testAccount, testContact);
		Database.SaveResult SR1 = Database.insert(testParentCase);
		//insert children
		Case testChildCase1 = TestData.setupCaseWithParent(testAccount, testContact, testParentCase);
		Database.SaveResult SR2 = Database.insert(testChildCase1);
		Case testChildCase2 = TestData.setupCaseWithParent(testAccount, testContact, testParentCase);
		Database.SaveResult SR3 = Database.insert(testChildCase2);
		System.assertEquals(true, SR1.isSuccess());
		System.assertEquals(true, SR2.isSuccess());
		System.assertEquals(true, SR3.isSuccess());

		Test.startTest();

		testParentCase.Escalation_Type__c = 'Test Case';
		testParentCase.Escalate_To__c = 'Gatekeeper';
		testParentCase.Status = 'Escalate';
		testParentCase.Date_Escalated__c = date.Today();
		testParentCase.X1_What_is_happening__c = 'This a test.';
		testParentCase.X2_What_did_you_expect_to_happen__c = 'This a test.';
		testParentCase.X3_When_did_it_start_happening__c = 'This a test.';
		testParentCase.X4_What_do_you_think_the_problem_is__c = 'This a test.';
		testParentCase.X5_What_have_you_tried_so_far__c = 'This a test.';
		Database.UpsertResult UR1 = Database.upsert(testParentCase);
		System.assertEquals(true, UR1.isSuccess());

		Test.stopTest();
	}

	@isTest static void testvAutoCaseInsert() {
		Account testAccount = TestData.setupAccount();
		insert testAccount;
		Contact testContact = TestData.setupContact(testAccount, 'vAuto');
		insert testContact;
		Case testCase = TestData.setupCase(testAccount, testContact);
		testCase.RecordTypeId = StaticData.getInstance().CaseRecTypesMapByName.get('vAuto Support').Id;
		testCase.vAuto_Case_Reason__c = 'ADP Write Back';
		testCase.vAuto_Product_Line__c = 'Appraisal Tool';
		Database.SaveResult SR1 = Database.insert(testCase);
		System.assertEquals(true, SR1.isSuccess());
	}	

	@isTest static void testCaseWithTask() {
		Account testAccount = TestData.setupAccount();
		insert testAccount;
		Contact testContact = TestData.setupContact(testAccount, 'Shared');
		insert testContact;
		Case testCase = TestData.setupCase(testAccount, testContact);
		Database.SaveResult SR1 = Database.insert(testCase);
		System.assertEquals(true, SR1.isSuccess());
		Task testTask = TestData.setupTaskCase(testCase);
		testTask.Subject = 'Email: 0';
		Database.SaveResult SR2 = Database.insert(testTask);
		System.assertEquals(true, SR1.isSuccess());

		Test.startTest();

		//update the case to cover the task code
		Database.UpsertResult UR1 = Database.upsert(testCase);
		System.assertEquals(true, UR1.isSuccess());
		//update the task to get the last lines
		testTask.Subject = 'Resolve Notice Sent to Customer';
		Database.UpsertResult UR2 = Database.upsert(testTask);
		System.assertEquals(true, UR2.isSuccess());
		//update the case again to get the coverage
		//Note: I think this task code should be in the task trigger not the case
		Database.UpsertResult UR3 = Database.upsert(testCase);
		System.assertEquals(true, UR3.isSuccess());

		Test.stopTest();
	}
}