objects/Case.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is updated by a trigger when the Case Runner assign is used to assign a user to an escalated Case</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Runner__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Runners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Runners</relationshipLabel>
        <relationshipName>Case_Runners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Escalated_To__c</fullName>
        <label>Escalated To</label>
        <picklist>
            <picklistValues>
                <fullName>App Request Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Extract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhancement Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export Setup Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gatekeeper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Questions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Support Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - Creative Requests</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - Paid Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - Tech Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jira Request Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L1-Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Creative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-CRM Admin/Settings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Desking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Escalations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Exports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Forms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Phone System(PBX)</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Runner_Action__c</fullName>
        <label>Runner Action</label>
        <picklist>
            <picklistValues>
                <fullName>Additional Information Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Dev Work to Do</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Post</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redirect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolve/Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved from Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitting Additional Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresolved</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Runner</label>
    <nameField>
        <displayFormat>CR-{YYYY}{MM}-{0}</displayFormat>
        <label>Case Runner Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Runners</pluralLabel>
    <recordTypes>
        <fullName>Escalate</fullName>
        <active>true</active>
        <description>case runner used for escalating cases</description>
        <label>Escalate</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/case_ctrl_listView_test.cls
@isTest(SeeAllData=True)
private class case_ctrl_listView_test {

    static testMethod void myUnitTest() {
        
        Profile pro = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
        	emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
        	localesidkey = 'en_US', profileid = pro.Id, 
        	timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com');
        	
        insert u_testMethodUser;
        
        System.runas(u_testMethodUser) {
        	
        	Case c = new Case();
        	
        	insert c;
        	
        	Case_Runner__c cr = new Case_Runner__c();
			cr.Runner_Action__c = 'Escalate';
			cr.Escalated_To__c = 'Creative';
			//cr.Assigned_To__c = userinfo.getUserId();
			cr.Case__c = c.Id;
			 
			insert cr;  
			
			CaseComment cc = new CaseComment();
			cc.CommentBody = 'Test Comment Public';
			cc.IsPublished = true;
			cc.ParentId = c.Id;
			
			insert cc;
        	
        	CaseComment cc2 = new CaseComment();
			cc2.CommentBody = 'Test Comment Private';
			cc2.IsPublished = false;
			cc2.ParentId = c.Id;
			
			insert cc2;
			
			EmailMessage em = new EmailMessage();
			em.Status = '3';
			em.Subject = 'Test';
			em.ToAddress = 'dean.lukowski@vinsolutions.com';
			em.TextBody = 'TestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTestTest';
			em.ParentId = c.Id;
			
			insert em;
			
			EmailMessage em2 = new EmailMessage();
			em2.Status = '3';
			em2.Subject = 'Test'; 
			em2.ToAddress = 'dean.lukowski@vinsolutions.com';
			em2.TextBody = 'Test';
			em2.ParentId = c.Id;
			
			insert em2;
        	
        	
        	ApexPages.StandardController sc = new ApexPages.Standardcontroller(c);
        	
        	
        	case_ctrl_listView controller = new case_ctrl_listView(sc);
        	
        	/*
        	ApexPages.currentPage().getParameters().put('toDate', '2013-03-25');        	
        	*/
        	test.startTest();
        	
        	controller.selectedFilter = 'displayCaseRunners';
        	controller.toggleFilter();
        	controller.toggleFilter();
        	
			controller.displayCaseComments = true;
        	controller.selectedFilter = 'displayCaseComments';
        	controller.toggleFilter();
        	controller.toggleFilter();
        	
			controller.displayCaseHistory = true;
        	controller.selectedFilter = 'displayCaseHistory';
        	controller.toggleFilter();
        	controller.toggleFilter();
        	
			controller.displayActivityHistory = true;
        	controller.selectedFilter = 'displayActivityHistory';
        	controller.toggleFilter();
        	controller.toggleFilter();
        	
			controller.displayCaseEmails = true;
        	controller.selectedFilter = 'displayCaseEmails';
        	controller.toggleFilter();
        	controller.toggleFilter();
        	
        	controller.showAllNone();
        	controller.isShowAll = false;
        	controller.showAllNone();
        	
        	controller.toggleSort();
        	controller.isASC = true;
        	controller.toggleSort();
        	
        	controller.nullPR();
        	controller.showMoreLess();
        	controller.isScroll = true;
        	controller.showMoreLess();
        	
        	test.stopTest();
        }
    }
}