objects/Case.object
<CustomObject>
    <fields>
        <fullName>POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup the POA related to this Case</inlineHelpText>
        <label>POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Related Cases</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup the Project this Case is related to</inlineHelpText>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Create</fullName>
        <active>true</active>
        <businessProcess>VS Cases</businessProcess>
        <description>used when creating a Case</description>
        <label>Create</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/POA__c.object
<CustomObject>
    <description>used to handle Plan of Action items for an Account- gives the ability to group support or implementation issues together</description>
    <fields>
        <fullName>Case_Count__c</fullName>
        <label>Case Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>POA</label>
    <nameField>
        <label>Plan of Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POAs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Haystak_CaseTriggerHandler.cls
/**
 * @author			Pranav Raulkar
 * @date            28/05/2015
 * @version			1.0
 * @description     Handler class for the Haystak_CaseTrigger.
 */
public with sharing class Haystak_CaseTriggerHandler {
	/**
	 * @author			Pranav Raulkar
	 * @date            28/05/2015
	 * @version			1.0
	 * @description     This method updates the opportunity with the related (via Project__c) case count.
	 */
	public static void updateCaseCountOnPOA() {
		if(Trigger.isExecuting) {
			// Make sure we initialize the case list depending on the proper event
			List<Case> caseList;
			if(Trigger.isInsert || Trigger.isUndelete || Trigger.isUpdate) {
				caseList = (List<Case>) Trigger.new;
			} else {
				caseList = (List<Case>) Trigger.old;
			}
			
			// Create a unique set of POA ids
			Set<Id> poaIdSet = new Set<Id>();
			for(Case c : caseList) {
				poaIdSet.add(c.POA__c);
			}
			
			// Get all the cases for unique POA's
			List<POA__c> poaCaseList = [SELECT Id, Case_Count__c, (SELECT Id FROM Tickets__r) 
									    FROM POA__c c
									    WHERE Id IN :poaIdSet];
			
			// Set the POA case count
			for(POA__c poa : poaCaseList) {
				poa.Case_Count__c = poa.Tickets__r == null ? 0 : poa.Tickets__r.size();
			}
			
			try {
				// Update the POAs
				update poaCaseList;	
			} catch(Exception ex) {
				System.debug('## Exception: ' + ex.getStackTraceString());
			}			
		}
	}
}