objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date_Escalated__c</fullName>
        <inlineHelpText>updated by workflow when the escalation case runner is created and saved</inlineHelpText>
        <label>Date Escalated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Escalate_To__c</fullName>
        <label>Escalate To</label>
        <picklist>
            <picklistValues>
                <fullName>App Request Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Extract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhancement Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export Setup Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gatekeeper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Questions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Support Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - Creative Requests</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - Paid Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - SEO Requests</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAY - Tech Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jira Request Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L1-Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Creative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-CRM Admin/Settings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Desking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Escalations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Exports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Forms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L2-Phone System(PBX)</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Escalation_Type__c</fullName>
        <label>Escalation Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feature_request_ID__c</fullName>
        <label>Feature request ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Child_Tickets__c</fullName>
        <label>Number of Child Cases</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OT_Feature_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OT Feature Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ParentEscDate__c</fullName>
        <formula>Parent.Date_Escalated__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ParentEscDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ParentEscTo__c</fullName>
        <formula>TEXT( Parent.Escalate_To__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ParentEscTo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentEscType__c</fullName>
        <formula>Parent.Escalation_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ParentEscType</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentFRID__c</fullName>
        <formula>Parent.Feature_request_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ParentFRID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentOTD__c</fullName>
        <formula>if( Parent.OT_Defect__c = TRUE, &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ParentOTD</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentOTFR__c</fullName>
        <formula>if(Parent.OT_Feature_Request__c=true, &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ParentOTFR</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentStatus__c</fullName>
        <formula>text(Parent.Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ParentStatus</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/handler_caseTrigger.cls
public with sharing class handler_caseTrigger {

	public static void SetChildInfoFromParentChange(Case parentCase){
		boolean parentFR = false;
		List<Case> casesToUpdate = new List<Case>();
		for(Case c : [SELECT Id, ParentOTFR__c, Escalation_Type__c, ParentEscType__c, Escalate_To__c, ParentEscTo__c,
							 Status, ParentStatus__c, OT_Feature_Request__c, Feature_request_ID__c, ParentFRID__c,
							 Date_Escalated__c, ParentEscDate__c, ParentOTD__c
						FROM Case
					   WHERE ParentId =: parentCase.Id]){
			if(c.Escalation_Type__c != c.ParentEscType__c
			|| c.Escalate_To__c != c.ParentEscTo__c
			|| c.Status != c.ParentStatus__c
			|| c.Date_Escalated__c != c.ParentEscDate__c){	
				SetParentInfoOnChild(c);
				casesToUpdate.add(c);
			}
		}
		if(casesToUpdate.size() > 0){
			update casesToUpdate;
		}
	}

	public static Case SetParentInfoOnChild(Case newCase){
		//Update this child from it's parent				
		if(newCase.Escalation_Type__c != newCase.ParentEscType__c) {					
			newCase.Escalation_Type__c = newCase.ParentEscType__c;
		}				
		if(newCase.Escalate_To__c != newCase.ParentEscTo__c) {					
			newCase.Escalate_To__c = newCase.ParentEscTo__c;
		}				
		if(newCase.Status != newCase.ParentStatus__c) {					
			newCase.Status = newCase.ParentStatus__c;
		}					
		if(newCase.Date_Escalated__c != newCase.ParentEscDate__c) {				
			newCase.Date_Escalated__c = newCase.ParentEscDate__c;
		}
		
		return newCase;
	}
	
	public static void calculateNumberOfChildTickets(Set<Id> parents) {
		List<AggregateResult> groupedResults = [SELECT Count(Id)TotalChildren, ParentId parent
											  	  FROM Case
										     	 WHERE ParentId IN :parents
										  	  group by ParentId];

  		Map<Id, Integer> childrenPerParent = new Map<Id, Integer>();
  		for(AggregateResult ar : groupedResults){
  			childrenPerParent.put((Id)ar.get('parent'), (Integer)ar.get('TotalChildren'));
  		}
		if(childrenPerParent.size() > 0){
			for(Case p : [SELECT Number_of_Child_Tickets__c
					    FROM Case
					   WHERE Id IN :childrenPerParent.KeySet()]){
				p.Number_of_Child_Tickets__c = childrenPerParent.get(p.Id);
				update p;
			}
		}
		else{
			for(Case p : [SELECT Number_of_Child_Tickets__c
					    FROM Case
					   WHERE Id IN :parents]){
				p.Number_of_Child_Tickets__c = 0;
				update p;
			}
		}
	}
}