objects/Case.object
<CustomObject>
    <fields>
        <fullName>POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup the POA related to this Case</inlineHelpText>
        <label>POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Related Cases</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <inlineHelpText>Where are you seeing the symptom appear?</inlineHelpText>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>Appraisal Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Genius</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoCheck/Carfax/CarProof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Books</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns-Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM-ILM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Export/Syndication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Sites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhancement Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Genius Labs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration-Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory/Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KBB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KBB Price Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Listing Logic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merchandising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Product Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Deal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red Wagon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TIM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VinSolutions Appraisal Integration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Haystak</fullName>
        <active>true</active>
        <businessProcess>Haystak</businessProcess>
        <description>Haystak</description>
        <label>Haystak</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/POA__c.object
<CustomObject>
    <description>used to handle Plan of Action items for an Account- gives the ability to group support or implementation issues together</description>
    <fields>
        <fullName>Case_Count__c</fullName>
        <label>Case Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>POA</label>
    <nameField>
        <label>Plan of Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POAs</pluralLabel>
    <recordTypes>
        <fullName>Haystak</fullName>
        <active>true</active>
        <description>Unified POA for Haystak</description>
        <label>Haystak ADVD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Haystak_CaseTriggerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Haystak_CaseTriggerTest {
	// Set the test data size
	static final Integer DATA_SET_SIZE = 10;
	
	// Account 
	static Account acc;
	
	// Contact
	static Contact con;
	
	// The list of POA as setup data
	static List<POA__c> poaList;
	
	// The list of Cases related to POA
	static List<Case> caseList;
	
	static void setupData() {
		// Setup Account
		acc = new Account(Name = 'Haystak Test Account');
		insert acc;
		
		// Setup Contact
		con = new Contact(LastName = 'Haystak Contact', AccountId = acc.Id);
		insert con;
		
		// Setup POA data
		poaList = new List<POA__c>();
		for(Integer i = 0; i < DATA_SET_SIZE; i++) {
			poaList.add(new POA__C(
				Name = 'Haystak SEO-Integrity Motors-' + i
			));
		}
		insert poaList;
		
		// Setup Case Data
		caseList = new List<Case>();
		for(Integer i = 0; i < DATA_SET_SIZE * 5; i++) {
			caseList.add(new Case(
				AccountId = acc.Id,
				ContactId = con.Id,
				Origin = 'Phone',
				Product_Line__c = 'Service',
				Type = 'Problem',
				Status = 'New',
				POA__c = poaList[i / 5].Id
			));
		}
	}
	
    static testMethod void testUpdateCaseCountOnPOA() {
    	setupData();
    	
    	Test.startTest();
    	
    	poaList = [SELECT Id, Name, Case_Count__c FROM POA__c];
    	
    	Set<Id> poaIdSet = new Set<Id>();
        for(POA__c poa : poaList) {
        	System.assert(poa.Id <> null);
        	System.assert(poa.Case_Count__c == null);
        	poaIdSet.add(poa.Id);
        }
        
        insert caseList;       
        
        for(POA__c poa : [SELECT Case_Count__c FROM POA__c WHERE Id IN :poaIdSet]) {
        	System.assert(poa.Case_Count__c == 5);
        }
        
        delete caseList;
        
        for(POA__c poa : [SELECT Case_Count__c FROM POA__c WHERE Id IN :poaIdSet]) {
        	System.assert(poa.Case_Count__c == 0);
        }
        
        Test.stopTest();
    }
}