objects/Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>Date_Completed__c</fullName>
        <label>Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Publish_to_Release_Notes__c</fullName>
        <inlineHelpText>When in doubt, YES.</inlineHelpText>
        <label>Publish to Release Notes</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_Object__c</fullName>
        <label>Related Object</label>
        <picklist>
            <picklistValues>
                <fullName>Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appeals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Requests</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Object</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dashboards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense Tracker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecasts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outlook Connector</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Time Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PANs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POAs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Pieces</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Release_Notes_Details__c</fullName>
        <label>Release Notes Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>For users to create a CR</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/admin_ctrl_pdfReleaseNotesGenerator.cls
public with sharing class admin_ctrl_pdfReleaseNotesGenerator {
	
	//start and end date passed via querystring
	
	//example..
	//?fromDate=2013-03-03&toDate=2013-03-25
	
	//display all CRs w/ publish to release notes = true... and in the date range passed
	//..
	
	
	//get a list of CRs.. display and group them by related object
	//..
	public string tFromDate {get;set;}
	public string tToDate {get;set;}
	
	public string fromDate {get;set;}
	public string toDate {get;set;}
	
	public string crSoql {get;set;}
	
	public List<Change_Request__c> changeRequests {get;set;}
	
	
	public admin_ctrl_pdfReleaseNotesGenerator() {
		
		fromDate = ApexPages.currentPage().getParameters().get('fromDate');
		toDate = ApexPages.currentPage().getParameters().get('toDate');
		
		tFromDate = fromDate.substring(5, 7) + '/' + fromDate.substring(8, 10) + '/' + fromDate.substring(0, 4);
		tToDate = toDate.substring(5, 7) + '/' + toDate.substring(8, 10) + '/' + toDate.substring(0, 4);
		
		crSoql = 'SELECT Id, Name, Publish_to_Release_Notes__c, Related_Object__c, Release_Notes_Details__c, Subject__c, Date_Completed__c FROM Change_Request__c WHERE Publish_to_Release_Notes__c = \'Yes\'';
		
		runQuery();
	}
	
	
	
	
	public void runQuery() {
		
		changeRequests = Database.query(crSoql + ' AND Date_Completed__c >= ' + fromDate + ' AND Date_Completed__c <= ' + toDate + ' ORDER BY Related_Object__c, Date_Completed__c ASC');
		
		organizeTable();
	}
	
	
	public void organizeTable() {
		
		//create map method instead mapping related object to record
		
		releaseNotesTables = new List<releaseNotesTable>();
		
		string tObjectName = '';
		
		List<Change_Request__c> tCRs;
		
		for(Change_Request__c cr : changeRequests) {
			
			system.debug('Bazinga... crName: ' + cr.Name);
			system.debug('Bazinga... crRelatedObject: ' + cr.Related_Object__c);
			
			if(cr.Related_Object__c != tObjectName) {
				
				system.debug('Bazinga... 1');
				
				if(tCRs != null) {
					
					system.debug('Bazinga... 2');
					
					releaseNotesTables.add(new releaseNotesTable(tObjectName, tCRs));
				}
				
				system.debug('Bazinga... 3');
				
				tCRs = new List<Change_Request__c>();
				
				tObjectName = cr.Related_Object__c;
				tCRs.add(cr);
			}
			else {
				
				system.debug('Bazinga... 4');
				
				tCRs.add(cr);
			}
		}
		
		releaseNotesTables.add(new releaseNotesTable(tObjectName, tCRs));
	}
	
	
	
	//
	//..
	public List<releaseNotesTable> releaseNotesTables {get;set;}
	
	public class releaseNotesTable {
		
		public string objectName {get;set;}
		
		public List<Change_Request__c> relatedCRs {get;set;}
		
		public releaseNotesTable(string tmpObjectName, List<Change_Request__c> tmpRelatedCRs) {
			
			objectName = tmpObjectName;
			
			relatedCRs = tmpRelatedCRs;
		}
	}
	
	
	
	
	
	
	
	
}