objects/Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>Are_All_Stories_Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checks if associated user stories are closed or not.  verified in the flow</description>
        <label>Are All Stories Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Change_Request_Status__c</fullName>
        <inlineHelpText>Dismissed means we cannot do this. Deferred means we cannot do it anytime soon.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preliminary Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Curator Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comprehensive Discovery</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Request_Details__c</fullName>
        <description>The field has been deprecated</description>
        <inlineHelpText>The first 124 characters will be visible in all your list views</inlineHelpText>
        <label>Internal Notes</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>For users to create a CR</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/handler_ChangeRequest_test.cls
@isTest(SeeAllData=true)
private class handler_ChangeRequest_test {

    static testMethod void myUnitTest() {
        
        Profile pro = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        Profile pro2 = [SELECT Id From Profile WHERE Name = 'VinSystem Admin'];
        
        User u_testMethodUser = new User(alias = 'testMeth',
                                            email = 'testMethodUser@salesforce.com',
                                            emailencodingkey = 'UTF-8',
                                            lastname = 'Test Method User',
                                            languagelocalekey = 'en_US',
                                            localesidkey = 'en_US',
                                            profileid = pro.Id,
                                            timezonesidkey = 'America/Los_Angeles',
                                            username = 'testMethodUser@salesforce.com');
        User u_testMethodUser2 = new User(alias = 'testMet2',
                                            email = 'testMethodUser2@salesforce.com',
                                            emailencodingkey = 'UTF-8',
                                            lastname = 'Test Method User2',
                                            languagelocalekey = 'en_US',
                                            localesidkey = 'en_US',
                                            profileid = pro2.Id,
                                            timezonesidkey = 'America/Los_Angeles',
                                            username = 'testMethodUser2@salesforce.com');
        insert u_testMethodUser;
        insert u_testMethodUser2;
        
        System.runas(u_testMethodUser) {
        	
        	//Set your controller
        	handler_ChangeRequest controller = new handler_ChangeRequest();
        	
        	Change_Request__c c = new Change_Request__c();
        	c.Request_Details__c = 'Owner(Mark Ross) Test Test Test';
        	insert c;
            c.OwnerId = u_testMethodUser2.Id;
            update c;
            c.Are_All_Stories_Closed__c = true;
        	c.Change_Request_Status__c = 'Closed';
        	update c;
        	
        	test.startTest();
        	
        	
        	
        	test.stopTest();
        }
    }
}