objects/Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>Date_Completed__c</fullName>
        <label>Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Publish_to_Release_Notes__c</fullName>
        <inlineHelpText>When in doubt, YES.</inlineHelpText>
        <label>Publish to Release Notes</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Request_Details__c</fullName>
        <description>The field has been deprecated</description>
        <inlineHelpText>The first 124 characters will be visible in all your list views</inlineHelpText>
        <label>Internal Notes</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>For users to create a CR</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/admin_ctrl_releaseNotes2_test.cls
@isTest(SeeAllData=True)
private class admin_ctrl_releaseNotes2_test {

    static testMethod void myUnitTest() {
        
        Profile pro = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
        	emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
        	localesidkey = 'en_US', profileid = pro.Id, 
        	timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com');
        	
        insert u_testMethodUser;
        
        System.runas(u_testMethodUser) {
        	
        	
        	Change_Request__c c = new Change_Request__c();
        	c.Request_Details__c = 'Owner(Mark Ross) Test Test Test';
        	c.Publish_to_Release_Notes__c = 'No';
        	c.Date_Completed__c = Date.newInstance(2013, 03, 08);
        	
        	insert c;
        	
        	
        	ApexPages.currentPage().getParameters().put('fromDatePicker', '03/03/2013');
        	ApexPages.currentPage().getParameters().put('toDatePicker', '03/25/2013');
        	
        	ApexPages.currentPage().getParameters().put('publishCRId', c.Id);
        	
        	
        	//Set your controller
        	admin_ctrl_releaseNotes2 controller = new admin_ctrl_releaseNotes2();
        	
        	test.startTest();
        	
        	controller.toggleSort();
        	controller.nullPR();
        	controller.publishCR();
        	controller.runFilter();
        	
        	
        	test.stopTest();
        }
    }
}