objects/Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>Change_Type__c</fullName>
        <label>Change Type</label>
        <picklist>
            <picklistValues>
                <fullName>Discovery</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Break-Fix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Routine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mini Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Change__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Change</label>
        <referenceTo>Change_Request__c</referenceTo>
        <relationshipLabel>Change Requests</relationshipLabel>
        <relationshipName>Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publish_to_Release_Notes__c</fullName>
        <inlineHelpText>When in doubt, YES.</inlineHelpText>
        <label>Publish to Release Notes</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Request_Details__c</fullName>
        <description>The field has been deprecated</description>
        <inlineHelpText>The first 124 characters will be visible in all your list views</inlineHelpText>
        <label>Internal Notes</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>For users to create a CR</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ctrl_trainMe.cls
public with sharing class ctrl_trainMe {
	
	public string parentCRSubject {get;set;}
	public string parentCRId {get;set;}
	
	public string subject {get;set;}
	
	public string requestDetails {get;set;}
	
	
	public ctrl_trainMe() {
		
		parentCRSubject = Apexpages.currentPage().getParameters().get('parentCRSubject');
		parentCRId = Apexpages.currentPage().getParameters().get('parentCRId');
		
		
		subject = 'Training requested - ' + parentCRSubject;
		
		requestDetails = 'Assistance requested on associated Change Request';
	}
	
	public PageReference saveCR() {
		
		Change_Request__c newCR = new Change_Request__c();
		
		newCR.Subject__c = subject;
		newCR.Change_Type__c = 'Salesforce Training';
		newCR.Publish_to_Release_Notes__c = 'No';
		newCR.Request_Details__c = requestDetails;
		newCR.Parent_Change__c = parentCRId;
		
		insert newCR;
		
		PageReference pr = new PageReference('/' + newCR.Id);
        return pr.setRedirect(true);
	}
	
	
	public PageReference nullPR() {
		
		return null;
	}

}