objects/Classes__c.object
<CustomObject>
    <description>used to hold the list of classes that are offerred for online training</description>
    <label>Class</label>
    <nameField>
        <label>Classes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Certifications_Issued__c</fullName>
        <inlineHelpText>field is manually updated by a user</inlineHelpText>
        <label>Certifications Issued</label>
        <picklist>
            <picklistValues>
                <fullName>BD Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet Salesman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory &amp; Website Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Writer</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Online_Class__c.object
<CustomObject>
    <description>object used to hold classes offered online</description>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Classes__c</referenceTo>
        <relationshipLabel>Online Classes</relationshipLabel>
        <relationshipName>Online_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Online Class</label>
    <nameField>
        <label>Online Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Online Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Service_Timecard__c.object
<CustomObject>
    <description>tracks who is using available webex training</description>
    <fields>
        <fullName>Certifications_Issued__c</fullName>
        <formula>IF( INCLUDES( Contact__r.Certifications_Issued__c , &quot;Salesman&quot;) , &quot;Salesman&quot;, null) &amp; &quot;, &quot; &amp;
IF( INCLUDES( Contact__r.Certifications_Issued__c , &quot;Finance Manager&quot;) , &quot;Finance Manager&quot;, null) &amp; &quot;, &quot; &amp;
IF( INCLUDES( Contact__r.Certifications_Issued__c , &quot;Sales Manager&quot;) , &quot;Sales Manager&quot;, null) &amp; &quot;, &quot; &amp;
IF( INCLUDES( Contact__r.Certifications_Issued__c , &quot;Master Admin&quot;) , &quot;Master Admin&quot;, null) &amp; &quot;,&quot; &amp;
IF( INCLUDES( Contact__r.Certifications_Issued__c , &quot;Bd Agent&quot;) , &quot;BD Agent&quot;, null) &amp; &quot;,&quot; &amp;
IF( INCLUDES( Contact__r.Certifications_Issued__c , &quot;Internet Director&quot;) , &quot;Internet Director&quot;, null) &amp; &quot;,&quot; &amp;
IF( INCLUDES( Contact__r.Certifications_Issued__c , &quot;Internet Salesman&quot;) , &quot;Internet Salesman&quot;, null) &amp; &quot;,&quot; &amp;
IF( INCLUDES( Contact__r.Certifications_Issued__c , &quot;Service Director&quot;) , &quot;Service Director&quot;, null) &amp; &quot;,&quot; &amp;
IF( INCLUDES( Contact__r.Certifications_Issued__c , &quot;Service Writer&quot;) , &quot;Service Writer&quot;, null) &amp; &quot;,&quot; &amp;
IF( INCLUDES( Contact__r.Certifications_Issued__c , &quot;Inventory &amp; Website Specialist&quot;) , &quot;Inventory &amp; Website Specialist&quot;, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>auto poplulated by a formula that looks at certifications the contact currently holds</inlineHelpText>
        <label>Certifications Issued</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Status__c</fullName>
        <label>Class Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Class/Failed Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer/Phone Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Test Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Test Results</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Very Late / Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted and Completed.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Completed - Verify</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <formula>Online_Class__r.Class__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>auto populated by a formula that pulls the class name linked to the class number into the training timecard</inlineHelpText>
        <label>Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Training Timecards</relationshipLabel>
        <relationshipName>R00N70000002CQStEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Online_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Online Class</label>
        <referenceTo>Online_Class__c</referenceTo>
        <relationshipLabel>Training Timecards</relationshipLabel>
        <relationshipName>Training_Timecards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Training Timecard</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>Training Timecard</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Timecards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateCertificationClass_Test.cls
@isTest
private class CreateCertificationClass_Test {

    static testMethod void myUnitTest() {
    	User testUser = TestData.setupUser('VinSystem Admin', 'Business Analyst');
    	Contact testContact = TestData.setupContact();
    	testContact.Certifications_Issued__c = 'BD Agent';
    	insert testContact;
        System.runas(testUser) {
        	
	    	Classes__c testClass1 = new Classes__c();
	    	testClass1.Name = 'Sales Consultant Level 1';
	    	insert testClass1;
	    	Classes__c testClass2 = new Classes__c();
	    	testClass2.Name = 'Sales Consultant Level 2';
	    	insert testClass2;
	    	Classes__c testClass3 = new Classes__c();
	    	testClass3.Name = 'Sales Consultant Level 3';
	    	insert testClass3;
	    	
	    	Online_Class__c testOnlineClass1 = new Online_Class__c();
	    	testOnlineClass1.Name = 'Test1';
	    	testOnlineClass1.Class__c = testClass1.Id;
	    	insert testOnlineClass1;
	    	Online_Class__c testOnlineClass2 = new Online_Class__c();
	    	testOnlineClass2.Name = 'Test2';
	    	testOnlineClass2.Class__c = testClass2.Id;
	    	insert testOnlineClass2;
	    	Online_Class__c testOnlineClass3 = new Online_Class__c();
	    	testOnlineClass3.Name = 'Test3';
	    	testOnlineClass3.Class__c = testClass3.Id;
	    	insert testOnlineClass3;
	    	
	    	
	    	SFDC_Service_Timecard__c tc1 = new SFDC_Service_Timecard__c();
	    	tc1.Contact__c = testcontact.Id;
	    	tc1.Online_Class__c = testOnlineClass1.Id;
	    	tc1.Class_Status__c = 'Completed';
	    	insert tc1;
	    	SFDC_Service_Timecard__c tc2 = new SFDC_Service_Timecard__c();
	    	tc2.Contact__c = testcontact.Id;
	    	tc2.Online_Class__c = testOnlineClass2.Id;
	    	tc2.Class_Status__c = 'Completed';
	    	insert tc2;
	    	SFDC_Service_Timecard__c tc3 = new SFDC_Service_Timecard__c();
	    	tc3.Contact__c = testcontact.Id;
	    	tc3.Online_Class__c = testOnlineClass3.Id;
	    	tc3.Class_Status__c = 'Completed';
	    	insert tc3;
	    	
        	//Set your controller
        	CreateCertificationClass cccTest = new CreateCertificationClass();
	    	CreateCertificationClass.CreateCertification(new List<Id>{testcontact.Id});
        	
        	test.startTest();
        	
        	
        	test.stopTest();
        }
    }
    
    static testMethod void myUnitTest2() {
        User testUser = TestData.setupUser('VinSystem Admin', 'Business Analyst');
    	Contact testContact = TestData.setupContact();
    	testContact.Certifications_Issued__c = null;
    	insert testContact;
        System.runas(testUser) {
	    	
	    	Classes__c testClass1 = new Classes__c();
	    	testClass1.Name = 'Sales Consultant Level 1';
	    	insert testClass1;
	    	Classes__c testClass2 = new Classes__c();
	    	testClass2.Name = 'Sales Consultant Level 2';
	    	insert testClass2;
	    	Classes__c testClass3 = new Classes__c();
	    	testClass3.Name = 'Sales Consultant Level 3';
	    	insert testClass3;
	    	
	    	Online_Class__c testOnlineClass1 = new Online_Class__c();
	    	testOnlineClass1.Name = 'Test1';
	    	testOnlineClass1.Class__c = testClass1.Id;
	    	insert testOnlineClass1;
	    	Online_Class__c testOnlineClass2 = new Online_Class__c();
	    	testOnlineClass2.Name = 'Test2';
	    	testOnlineClass2.Class__c = testClass2.Id;
	    	insert testOnlineClass2;
	    	Online_Class__c testOnlineClass3 = new Online_Class__c();
	    	testOnlineClass3.Name = 'Test3';
	    	testOnlineClass3.Class__c = testClass3.Id;
	    	insert testOnlineClass3;
	    	
	    	
	    	SFDC_Service_Timecard__c tc1 = new SFDC_Service_Timecard__c();
	    	tc1.Contact__c = testcontact.Id;
	    	tc1.Online_Class__c = testOnlineClass1.Id;
	    	tc1.Class_Status__c = 'Completed';
	    	insert tc1;
	    	SFDC_Service_Timecard__c tc2 = new SFDC_Service_Timecard__c();
	    	tc2.Contact__c = testcontact.Id;
	    	tc2.Online_Class__c = testOnlineClass2.Id;
	    	tc2.Class_Status__c = 'Completed';
	    	insert tc2;
	    	SFDC_Service_Timecard__c tc3 = new SFDC_Service_Timecard__c();
	    	tc3.Contact__c = testcontact.Id;
	    	tc3.Online_Class__c = testOnlineClass3.Id;
	    	tc3.Class_Status__c = 'Completed';
	    	insert tc3;
	    	
        	//Set your controller
        	CreateCertificationClass cccTest = new CreateCertificationClass();
	    	CreateCertificationClass.CreateCertification(new List<Id>{testContact.Id});
        	
        	test.startTest();
        	
        	
        	test.stopTest();
        }
    }
    
}