objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MotoSnap_User_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The Motosnap database record ID for this Contact</inlineHelpText>
        <label>MotoSnap User Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/eAcademy__c.object
<CustomObject>
    <description>Object to hold data from nightly reports from Brainshark.</description>
    <label>eAcademy</label>
    <nameField>
        <displayFormat>eA-{0000000}</displayFormat>
        <label>eAcademy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eAcademies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/eAcademyBatchJob_Test.cls
@isTest
private class eAcademyBatchJob_Test {
	
	static testmethod void test() {
		Account testAcct = TestData.setupAccount();
		insert testAcct;
		Contact testCon = TestData.setupContact(testAcct, 'VIN');
		testCon.MotoSnap_User_Id__c = 'TestID';
		insert testCon;

       // Load some test eAcademy__c records from a static resource to be deleted by the batch job.
       List<sObject> ls = Test.loadData(eAcademy__c.sObjectType, 'eAcademyTestData');
       System.assert(ls.size() == 10);
       Test.startTest();
       eAcademyBatchJob eb = new eAcademyBatchJob();
       Database.executeBatch(eb);
       Test.stopTest();

       // Verify eAcademy__c records got deleted 
       Integer i = [SELECT COUNT() FROM eAcademy__c];
       System.assertEquals(i, 0);
    }
	
}