objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MotoSnap_User_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The Motosnap database record ID for this Contact</inlineHelpText>
        <label>MotoSnap User Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/eAcademy__c.object
<CustomObject>
    <description>Object to hold data from nightly reports from Brainshark.</description>
    <fields>
        <fullName>Date_Time__c</fullName>
        <description>Change of label to match new input fields, 2/29/2016.</description>
        <label>Completed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Dealership_Name__c</fullName>
        <description>Holds the value of the GBCustom6 field from the Brainshark data import.
Change of label to match new input fields, 2/29/2016.</description>
        <label>Student Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort3__c</fullName>
        <label>Sort3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Title__c</fullName>
        <description>Change of label to match new input fields, 2/29/2016.</description>
        <label>Course Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_ViewerInfo__c</fullName>
        <description>Change of label to match new input fields, 2/29/2016.</description>
        <label>Student</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_Code__c</fullName>
        <label>Tracking Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>View_Total_Pct_of_Duration__c</fullName>
        <description>Change of label to match new input fields, 2/29/2016.</description>
        <label>Percent Duration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>View_Total_Pct_of_Slides__c</fullName>
        <description>Change of label to match new input fields, 2/29/2016.</description>
        <label>Percent Slides Viewed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>View_Total_Points__c</fullName>
        <description>Change of label to match new input fields, 2/29/2016.</description>
        <label>Points</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>View_Total_Score__c</fullName>
        <description>Change of label to match new input fields, 2/29/2016.</description>
        <label>Score</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>View_Total_Slides_Viewed__c</fullName>
        <description>Change of label to match new input fields, 2/29/2016.</description>
        <label>Slides Viewed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>View_Type__c</fullName>
        <description>Change of label to match new input fields, 2/29/2016.</description>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ViewerInfo__c</fullName>
        <label>ViewerInfo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewing_Time__c</fullName>
        <description>Change of label to match new input fields, 2/29/2016.</description>
        <label>SCORM Duration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vin_User_ID__c</fullName>
        <description>Holds the value of the GBCustom5 field from the Brainshark data. 
Change of label to match new input fields, 2/29/2016.</description>
        <label>Student UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>eAcademy</label>
    <nameField>
        <displayFormat>eA-{0000000}</displayFormat>
        <label>eAcademy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eAcademies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/eAcademyTriggerHandler_Test.cls
@isTest
private class eAcademyTriggerHandler_Test {
	
	@isTest static void testWithMotoSnapIdSync() {
		Account testAccount = TestData.setupAccount();
		insert testAccount;
		Contact testContact = TestData.setupContact(testAccount, 'Shared');
		testContact.MotoSnap_User_Id__c = 'TestID';
		insert testContact;
		eAcademy__c testeAcademy = new eAcademy__c(Sort_ViewerInfo__c = 'Test, Johnny',
  														ViewerInfo__c = 'Test, Johnny',
  														Vin_User_ID__c = 'TestID',//Inserting a matching sync
										  				Dealership_Name__c = 'Test Dealership',
										  				Tracking_Code__c = 'Code',
										  				Date_Time__c = datetime.now(),
  														Sort_Title__c = 'Quick help',
										  				Sort3__c = 'Sorted',
										  				Viewing_Time__c = '35',
										  				View_Type__c = 'Test',
										  				View_Total_Pct_of_Duration__c = '50',
										  				View_Total_Slides_Viewed__c = '10',
										  				View_Total_Pct_of_Slides__c = '35',
										  				View_Total_Points__c = '20',
										  				View_Total_Score__c = '50');
		Database.SaveResult SR1 = Database.insert(testeAcademy);
		System.assert(true, SR1.isSuccess());

	}
	
	@isTest static void testWithOUTMotoSnapIdSync() {
		Account testAccount = TestData.setupAccount();
		insert testAccount;
		Contact testContact = TestData.setupContact(testAccount, 'Shared');
		testContact.MotoSnap_User_Id__c = 'TestID';
		insert testContact;
		eAcademy__c testeAcademy = new eAcademy__c(Sort_ViewerInfo__c = 'Test, Johnny',
  														ViewerInfo__c = 'Test, Johnny',
  														Vin_User_ID__c = 'IDTest', //Inserting a non-matching sync
										  				Dealership_Name__c = 'Test Dealership',
										  				Tracking_Code__c = 'Code',
										  				Date_Time__c = datetime.now(),
  														Sort_Title__c = 'Quick help',
										  				Sort3__c = 'Sorted',
										  				Viewing_Time__c = '35',
										  				View_Type__c = 'Test',
										  				View_Total_Pct_of_Duration__c = '50',
										  				View_Total_Slides_Viewed__c = '10',
										  				View_Total_Pct_of_Slides__c = '35',
										  				View_Total_Points__c = '20',
										  				View_Total_Score__c = '50');
		Database.SaveResult SR1 = Database.insert(testeAcademy);
		System.assert(true, SR1.isSuccess());
	}
	
}