objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Originating Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>use to add a new contract (order) to the AutoTrader Billing System</description>
        <label>ADD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Installment__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Installments</relationshipLabel>
        <relationshipName>Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Paid__c</fullName>
        <label>Paid</label>
        <type>DateTime</type>
    </fields>
    <label>Installment</label>
    <nameField>
        <label>Installment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Cloned_with_Products__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cloned with Products</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Confirmed__c</fullName>
        <label>Confirmed</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contract_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>set to true by the system when a contract is created from this opportunity</inlineHelpText>
        <label>Contract Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Freight_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Updated when the Generate Invoice is hit.</description>
        <inlineHelpText>Updated when the Generate Invoice is hit.</inlineHelpText>
        <label>Freight Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InstallmentsGenerated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>InstallmentsGenerated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Total of invoice generated when Generate Invoice button is hit.</inlineHelpText>
        <label>Invoice Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Multi_Installments_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Multi-Installments Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Installments__c</fullName>
        <label>Number of Installments</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Override_Related_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>check to override the whole product of the related product error</inlineHelpText>
        <label>Override Related Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PAID__c</fullName>
        <inlineHelpText>Account paid</inlineHelpText>
        <label>PAID</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Paid_Date__c</fullName>
        <description>The date the opportunity was paid to us by the dealer</description>
        <inlineHelpText>Set by the Vin Opportunity Approval Process being fully approved</inlineHelpText>
        <label>Paid Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Parent_Clone_ID__c</fullName>
        <inlineHelpText>updated by a trigger</inlineHelpText>
        <label>Parent Clone ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phased_Project__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>updated by a trigger when a product has the solution product checkbox checked</inlineHelpText>
        <label>Phased Project</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you DO NOT want this opportunity to create a Project when marked paid.</inlineHelpText>
        <label>Project Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if a project has been generated from this opportunity by marking the first installment PAID</inlineHelpText>
        <label>Project Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the user that initiated the opportunity: fishing pole, PM, etc</inlineHelpText>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Type__c</fullName>
        <label>obsolete_Stage Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoice Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Fulfillment</fullName>
        <active>false</active>
        <businessProcess>Vin3</businessProcess>
        <label>Fulfillment</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Freight_Cost__c</fullName>
        <description>Cost to ship product</description>
        <formula>PricebookEntry.Product2.Freight_Cost__c * Quantity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Cost to ship product</inlineHelpText>
        <label>Freight Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Override_Related_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>check box to override the related product error</inlineHelpText>
        <label>Override Related Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <formula>PricebookEntry.Product2.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_ProductId__c</fullName>
        <formula>PricebookEntry.Product2.Related_Product__r.Id</formula>
        <label>Related ProductId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solution_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this is a major product for Vin. Ensures the generated project is set to the Staged layout.</description>
        <label>Vin Keystone Product</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Freight_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Cost to ship product</description>
        <inlineHelpText>Cost to ship product</inlineHelpText>
        <label>Freight Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductId</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Type__c</fullName>
        <inlineHelpText>Contigent upon Stage = Billable-Not Completed</inlineHelpText>
        <label>Stage Type</label>
        <picklist>
            <controllingField>Approval_Stage__c</controllingField>
            <picklistValues>
                <fullName>Addon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Go Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost Pre-launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Closed Won Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Website Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Dealer Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Website Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/handler_Opportunity.cls
public with sharing class handler_Opportunity {
    
    // AFTER UPDATE
    public static void afterUpdate(List<Opportunity> opps, Map<Id, Opportunity> oldMap) {
        
        checkToUpdateInstallments(opps, oldMap);
        checkToDeleteInstallments(opps, oldMap);
    }
    
    // AFTER INSERT
    public static void afterInsert(List<Opportunity> opps) {
        
        cloneDemos(opps);
        deleteRelatedInstallments(opps);
        checkToGenerateInstallments(opps);
    }
    
    // BEFORE DELETE
    public static void beforeDelete(List<Opportunity> oldOpps) {
        
        checkIfProjectsExistBeforeDelete(oldOpps);
    }
    
    // BEFORE UPDATE
    public static void beforeUpdate(List<Opportunity> opps, Set<Id> oppIds, Map<Id, Opportunity> oldMap) {
        
        Map<Id, List<OpportunityLineItem>> oppMap = new Map<Id, List<OpportunityLineItem>>();
        
        for(OpportunityLineItem oli : [SELECT Id, OpportunityId, Quantity, Freight_Cost__c, Related_ProductId__c, ProductId__c,
                                            Override_Related_Product__c, Solution_Product__c
                                       FROM OpportunityLineItem
                                       WHERE OpportunityId IN :oppIds]) {
                                        
            if(oppMap.containsKey(oli.OpportunityId)) {
                
                oppMap.get(oli.OpportunityId).add(oli);
            } 
            else {
                
                oppMap.put(oli.OpportunityId, new List<OpportunityLineItem>{oli});
            }                               
        }
        
        UpdateInvoiceTotal(oppMap, opps);
        //UpdateInitialWebexCompleteDate(opps);
        updatePhasedProject(oppMap, opps, oldMap);
        updateOwnerRoleSalespersonRole(opps, oldMap);
        checkIfUpdateAccountTypeAndCheckRelatedProducts(opps, oppMap, oldMap);
        checkInstallmentsGenerated(opps, oldMap);
        checkToCreateContractBillingItems(opps);
    }
    
    
    // BEFORE INSERT
    public static void beforeInsert(List<Opportunity> opps) {
        
        Set<Id> oppIds = new Set<Id>();
        
        for(Opportunity opp : opps) {
            
            oppIds.add(opp.Id);
        }
        
        system.debug('Bazinga.... Bazinga2');
        
        Map<Id, List<OpportunityLineItem>> oppMap = new Map<Id, List<OpportunityLineItem>>();
        
        for(OpportunityLineItem oli : [SELECT Id, OpportunityId, Quantity, Freight_Cost__c, Related_ProductId__c, ProductId__c,
                                            Override_Related_Product__c, Solution_Product__c
                                       FROM OpportunityLineItem
                                       WHERE OpportunityId IN :oppIds]) {
                                        
            if(oppMap.containsKey(oli.OpportunityId)) {
                
                oppMap.get(oli.OpportunityId).add(oli);
            }
            else {
                
                oppMap.put(oli.OpportunityId, new List<OpportunityLineItem>{oli});
            }                               
        }
        
        UpdateInvoiceTotal(oppMap, opps); //
        UpdateClonedWithProducts(oppMap, opps); //
        OneOpportunityPerAccount(opps);
        setRegionalOwner(opps);
        updateAccountType(opps);
        checkToCreateContractBillingItems(opps);
    }
    
    //Contract Management Method
    public static void checkToCreateContractBillingItems(List<Opportunity> opps) {
        
        //Datetime hardCodedPaidDate = datetime.newInstance(2013, 05, 31);
        
        for(Opportunity opp : opps) {
            
            //if(opp.StageName == 'Closed or Won' && opp.PAID__c == 'Yes' && opp.Contract_Generated__c == false && opp.Paid_Date__c > hardCodedPaidDate) {
            //if(opp.StageName == 'Closed or Won' && opp.Confirmed__c == 'Yes' && opp.Contract_Generated__c == false && opp.Paid_Date__c > hardCodedPaidDate) {
            if(opp.StageName == 'Closed or Won' && opp.Confirmed__c == 'Yes' && opp.Contract_Generated__c == false) {
                
                contractBillingItems.createContractAndBillingItems(opp);
            }
        }
    } 
    
    public static void checkToDeleteInstallments(List<Opportunity> opps, Map<Id, Opportunity> oldMap) {
        
        Set<Id> oppIds = new Set<Id>();
        
        for(Opportunity opp : opps) {
            
            if(oldMap.get(opp.Id).InstallmentsGenerated__c != false && oldMap.get(opp.Id).StageName != 'Closed or Lost' && opp.StageName == 'Closed or Lost') {
                
                oppIds.add(opp.Id);
            }
            
            //if(oldMap.get(opp.Id).InstallmentsGenerated__c != false && oldMap.get(opp.Id).StageName == 'Closed or Won' && opp.StageName != 'Closed or Won' && (opp.PAID__c == null || opp.PAID__c == 'No')) {
            if(oldMap.get(opp.Id).InstallmentsGenerated__c != false && oldMap.get(opp.Id).StageName == 'Closed or Won' && opp.StageName != 'Closed or Won' && (opp.Confirmed__c == null || opp.Confirmed__c == 'No')) {
            
                oppIds.add(opp.Id);     
            }
        }
        
        if(oppIds.size() > 0) {
            
            List<Installment__c> deleteInstallments = [SELECT Id 
                                                       FROM Installment__c 
                                                       WHERE Opportunity__c IN :oppIds];
                                                       
            if(deleteInstallments.size() > 0) {
                
                delete deleteInstallments;
            }
        }
    }
    
    public static void checkToUpdateInstallments(List<Opportunity> opps, Map<Id, Opportunity> oldMap) {
        
        for(Opportunity opp : opps) {
            
            if(oldMap.get(opp.Id).InstallmentsGenerated__c == false && ((opp.Number_of_Installments__c != null && 
                opp.StageName=='Closed or Won' && oldMap.get(opp.Id).StageName != 'Closed or Won') || 
                (opp.Number_of_Installments__c != null && oldMap.get(opp.Id).Number_of_Installments__c == null && opp.StageName == 'Closed or Won'))) {
                                            
                OpportunityClass.UpdateInstallments(opp);               
            }                                                           
            
            /*
            if((oldMap.get(opp.Id).PAID__c == null || oldMap.get(opp.Id).PAID__c == 'No') && oldMap.get(opp.Id).InstallmentsGenerated__c == true &&
                ((opp.Number_of_Installments__c != null && opp.StageName == 'Closed or Won' && oldMap.get(opp.Id).StageName != 'Closed or Won') || 
                (opp.Number_of_Installments__c != null && oldMap.get(opp.Id).Number_of_Installments__c == null && opp.StageName == 'Closed or Won'))) {
            */
            if((oldMap.get(opp.Id).Confirmed__c == null || oldMap.get(opp.Id).Confirmed__c == 'No') && oldMap.get(opp.Id).InstallmentsGenerated__c == true &&
                ((opp.Number_of_Installments__c != null && opp.StageName == 'Closed or Won' && oldMap.get(opp.Id).StageName != 'Closed or Won') || 
                (opp.Number_of_Installments__c != null && oldMap.get(opp.Id).Number_of_Installments__c == null && opp.StageName == 'Closed or Won'))) {
                
                OpportunityClass.UpdateInstallments(opp);               
            }
        }
    }
    
    
    // Will need to rewrite the GenerateInstallments method in "OpportunityClass.cls" eventually. This will work for now. (NCJ 5/29/13)
    public static void checkToGenerateInstallments(List<Opportunity> opps) {
        
        for(Opportunity opp : opps) {
            
            if(opp.Number_of_Installments__c != null && opp.Amount != null) {
                
                //Bad practice.. fix later
                OpportunityClass.GenerateInstallments(opp);
            }
        }
    }
    
    public static void cloneDemos(List<Opportunity> opps) {
        
        // Will need to rewrite the CloneDemos method in "OpportunityClass.cls" eventually. This will work for now. (NCJ 5/29/13)
        for(Opportunity opp : opps) {
            
            if(opp.Parent_Clone_ID__c != null && opp.Parent_Clone_ID__c != opp.Id) {
                
                //Bad practice.. fix later
                OpportunityClass.CloneDemos(opp);
            }
        }
    }
    
    public static void deleteRelatedInstallments(List<Opportunity> opps) {
        
        Set<Id> oppIds = new Set<Id>();
        
        for(Opportunity opp : opps) {
            
            if(opp.Parent_Clone_ID__c != null && opp.Parent_Clone_ID__c != opp.Id) {
                
                oppIds.add(opp.Id);
            }
        }
        
        if(oppIds.size() > 0) {
        
            List<Installment__c> deleteInstallments = [SELECT Id, Opportunity__c 
                                                       FROM Installment__c 
                                                       WHERE Opportunity__c IN :oppIds];
                                                       
            if(deleteInstallments.size() > 0) {
                
                delete deleteInstallments;
            }
        }
    }
    
    public static void checkIfProjectsExistBeforeDelete(List<Opportunity> oldOpps) {
        
        for(Opportunity opp : oldOpps) {
            
            List<SFDC_520_Quote__c> projects = [SELECT Id
                                                FROM SFDC_520_Quote__c
                                                WHERE Opportunity__c = :opp.Id];
                                                
            if(projects.size() > 0) {
                
                opp.addError('An Opportunity cannot be deleted without first deleting the related Projects.');
            }
        }
    }
    
    public static void UpdateInvoiceTotal(Map<Id, List<OpportunityLineItem>> oppMap, List<Opportunity> opps) {
        
        for(Opportunity opp : opps) {
            
            double totalFreight = 0;
            
            if(oppMap.get(opp.Id) != null) { 
            
                for(OpportunityLineItem oli : oppMap.get(opp.Id)) {
                    
                    totalFreight += oli.Freight_Cost__c;
                }
            }
            
            opp.Freight_Cost__c = totalFreight;
        }
    }
    
    public static void UpdateClonedWithProducts(Map<Id, List<OpportunityLineItem>> oppMap, List<Opportunity> opps) {
        
        for(Opportunity opp : opps) {
            
            if(oppMap.get(opp.Id) != null) {
                for(OpportunityLineItem oli : oppMap.get(opp.Id)) {
                    
                    if(opp.Id == oli.OpportunityId) {
                        
                        opp.Cloned_with_Products__c = true;
                    }
                }
            }
            
            opp.Phased_Project__c = false;
            opp.Project_Generated__c = false;
            opp.Project_Exception__c = false;
            opp.InstallmentsGenerated__c = false;
            opp.Invoice_Total__c = 0;
            opp.Multi_Installments_Approved__c = false;
            opp.Stage_Type__c = null;
            opp.Salesperson__c = userinfo.getUserId();
        }
    }
    
    public static void OneOpportunityPerAccount(List<Opportunity> opps) {
        /* -
        Set<Id> accountIds = new Set<Id>();
        
        for(Opportunity opp : opps) {
            
            accountIds.add(opp.AccountId);
        //}
        
        for(Opportunity opp1 : [SELECT Id, Opportunity_Names__c, StageName, AccountId, Multiple_Opportunity_Override__c,
                                IsClosed
                               FROM Opportunity
                               WHERE AccountId IN :accountIds]) {
        
            if(opp.Opportunity_Names__c != 'Fulfillment' && opp.Opportunity_Names__c != 'Hardware' && opp.Opportunity_Names__c != 'Printed Materials' &&
               opp.IsClosed == false && opp.Multiple_Opportunity_Override__c != true) {
                
                opp.addError('There is already an Opportunity open for this account. Please see a manager if you need this error to be overriden.');
            }                   
        }
      }
      */
    }
    
    /*public static void setRegionalOwner(List<Opportunity> opps) {
        
        for(Opportunity opp : opps) {
            
            if(opp.Account.Territory_State__r.Regional__c != null && userinfo.getUserRoleId() == '00E70000000xk01') {
                
                opp.OwnerId = opp.Account.Territory_State__r.Regional__c;
            }
            
            opp.Owner_Role__c = userinfo.getUserRoleId();
            opp.Salesperson_Role__c = userinfo.getUserRoleId();
        }
    }*/
    
    public static void setRegionalOwner(List<Opportunity> opps) {
        
        string roleId = userinfo.getUserRoleId();
        string roleName;
        User ui = [Select UserRole.Name FROM User WHERE UserRoleId =: roleId Limit 1];
        roleName = ui.UserRole.Name;
        
        string ownerRoleName = ui.UserRole.Name;
        
        //string roleName = [SELECT Name FROM UserRole WHERE Id =:userinfo.getUserRoleId()].Name;
        
        
        for(Opportunity opp : opps) {
            
            if(opp.Account.Territory_State__r.Regional__c != null && userinfo.getUserRoleId() == '00E70000000xk01') {
                
                opp.OwnerId = opp.Account.Territory_State__r.Regional__c;
            }
            
            opp.Owner_Role__c = ownerRoleName;
            //opp.Salesperson_Role__c = userinfo.getUserRoleId();
            opp.Salesperson_Role__c = roleName;
        }
    }
    
    public static void checkIfUpdateAccountTypeAndCheckRelatedProducts(List<Opportunity> opps, Map<Id, List<OpportunityLineItem>> oppMap, Map<Id, Opportunity> oldMap) {
        
        List<Opportunity> updateAccountOpps = new List<Opportunity>();
        List<Opportunity> checkRelatedProductsOpps = new List<Opportunity>();
        
        for(Opportunity opp : opps) {
            
            if(oldMap.get(opp.Id).StageName != 'Closed or Won' && opp.StageName == 'Closed or Won') {
                
                updateAccountOpps.add(opp);
                
                if(opp.Override_Related_Product__c != true) {
                    
                    checkRelatedProductsOpps.add(opp);
                }
            }
        }
        
        if(updateAccountOpps.size() > 0) {
            
            updateAccountType(updateAccountOpps);
        }
        
        if(checkRelatedProductsOpps.size() > 0) {
            
            checkRelatedProducts(checkRelatedProductsOpps, oppMap);
        }
    }
    
    public static void checkInstallmentsGenerated(List<Opportunity> opps, Map<Id, Opportunity> oldMap) {
        
        for(Opportunity opp : opps) {
            
            if(oldMap.get(opp.Id).InstallmentsGenerated__c == false && ((opp.Number_of_Installments__c != null &&
                opp.StageName == 'Closed or Won' && oldMap.get(opp.Id).StageName != 'Closed or Won') ||
                (opp.Number_of_Installments__c != null && oldMap.get(opp.Id).Number_of_Installments__c == null && opp.StageName == 'Closed or Won'))) {
                    
                opp.InstallmentsGenerated__c = true;        
            }
        }
    }
    
    public static void checkRelatedProducts(List<Opportunity> opps, Map<Id, List<OpportunityLineItem>> oppMap) {
        
        List<Id> listOfRelatedProductIds = new List<Id>();
        Map<Id, OpportunityLineItem> mapOfAllProductIds = new Map<Id, OpportunityLineItem>();
        
        for(Opportunity opp : opps) {
            
            if(oppMap.get(opp.Id) != null) {
            
                for(OpportunityLineItem oli : oppMap.get(opp.Id)) {
                    
                    if(oli.Related_ProductId__c != null && oli.Override_Related_Product__c != true) {
                        
                        listOfRelatedProductIds.add(oli.Related_ProductId__c);
                    }
                    
                    mapOfAllProductIds.put(oli.ProductId__c, oli);
                }
                
                for(Id thisRelatedId : listOfRelatedProductIds) {
                    
                    if(mapOfAllProductIds.get(thisRelatedId) == null) {
                        
                        Product2 errorProduct = [SELECT Id, Name
                                                 FROM Product2
                                                 WHERE Id =:thisRelatedId
                                                 limit 1];
                                                 
                        opp.addError('Opportunity has a product on it that has a REQUIRED RELATED PRODUCT. Product Name Required: ' + errorProduct.Name);
                    }
                }
            }
        }
    }
    
    public static void updateAccountType(List<Opportunity> opps) {
        
        Set<Id> accountIds = new Set<Id>();
        
        for(Opportunity opp : opps) {
            
            if(opp.StageName == 'Closed or Won' && opp.Account.Type != 'Customer') {
                
                accountIds.add(opp.AccountId);
            }
        }
        
        List<Account> updateAccounts = new List<Account>();
        
        if(accountIds.size() > 0) {
            
            for(Account a : [SELECT Id, Type
                             FROM Account
                             WHERE Id IN :accountIds]) {
                                
                a.Type = 'Customer';
                
                updateAccounts.add(a);                  
            }
            
            update updateAccounts;
        }
    }
    
    public static void UpdateInitialWebexCompleteDate(List<Opportunity> opps) {
        
        for(Opportunity opp : opps) {
            
            if(opp.StageName == 'Webex Complete') {
                
                opp.Initial_Webex_Completed__c = system.today();
            }
        }
    }
    
    public static void updatePhasedProject(Map<Id, List<OpportunityLineItem>> oppMap, List<Opportunity> opps, Map<Id, Opportunity> oldMap) {
        
        for(Opportunity opp : opps) {
            
            if(opp.StageName == 'Closed or Won' && oldMap.get(opp.Id).StageName != 'Closed or Won') {
                
                if(oppMap.get(opp.Id) != null) {
                
                    for(OpportunityLineItem oli : oppMap.get(opp.Id)) {
                        
                        if(oli.Solution_Product__c == true) {
                            
                            opp.Phased_Project__c = true;
                        }
                    }
                }
            }
        }
    }
    
    /*public static void updateOwnerRoleSalespersonRole(List<Opportunity> opps, Map<Id, Opportunity> oldMap) {
        
        for(Opportunity opp : opps) {
            
            if(((oldMap.get(opp.Id).OwnerId != null) && (oldMap.get(opp.Id).OwnerId != opp.OwnerId)) || (opp.OwnerId != null && opp.Owner_Role__c == null)) {
                
                opp.Owner_Role__c = userinfo.getUserRoleId();
            }
            
            if((oldMap.get(opp.Id).Salesperson__c != opp.Salesperson__c) || (opp.Salesperson__c != null && opp.Salesperson_Role__c == null)) {
                
                opp.Salesperson_Role__c = userinfo.getUserRoleId();
            }
        }
    }*/
    
    public static void updateOwnerRoleSalespersonRole(List<Opportunity> opps, Map<Id, Opportunity> oldMap) {
        
        string spID;
        string owID;
        Set<Id> userIDs = new Set<Id>();
        
        for(Opportunity opp : opps){
            if(oldMap.get(opp.Id).OwnerId != opp.OwnerId || oldMap.get(opp.Id).Salesperson__c != opp.Salesperson__c){
                userIDs.add(opp.Salesperson__c);
                userIDs.add(opp.OwnerId);
            }
        }
        if(userIDs.size() > 0){
            MAP<Id, String> roleMap = new MAP<Id, String>();
            
                for(User u : [SELECT Id, UserRole.Name FROM User WHERE Id IN : userIds]){
                    roleMap.put(u.Id, u.UserRole.Name);
                }
            
            
            for(Opportunity opp : opps) {
                
                
                if(((oldMap.get(opp.Id).OwnerId != null) && (oldMap.get(opp.Id).OwnerId != opp.OwnerId)) || (opp.OwnerId != null && opp.Owner_Role__c == null)) {
                    
                    //opp.Owner_Role__c = userinfo.getUserRoleId();
                    //opp.Owner_Role__c = owInfo.UserRole.Name;
                    //opp.Owner_Role__c = opp.OwnerId.UserRole.Name;
                    opp.Owner_Role__c = roleMap.get(opp.OwnerId);
                }
                if(opp.Salesperson_Exception__c == true){
                    //opp.Salesperson_Role__c = opp.Salesperson__c;
                    //opp.Salesperson_Role__c = spInfo.UserRole.Name;
                    opp.Salesperson_Role__c = roleMap.get(opp.Salesperson__c);
                }
                //if((oldMap.get(opp.Id).Salesperson__c != opp.Salesperson__c) || (opp.Salesperson__c != null && opp.Salesperson_Role__c == null)) {
                    
                //      opp.Salesperson_Role__c = userinfo.getUserRoleId();
                    //opp.Salesperson_Role__c = opp.Salesperson__r.UserRole.Name;
                    //opp.Salesperson_Role__c = opp.Salesperson__c.UserRoleId();
                //}
            }
        }
    }
    
    
}