objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MotoSnap_User_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The Motosnap database record ID for this Contact</inlineHelpText>
        <label>MotoSnap User Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>account_name__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/eAcademy__c.object
<CustomObject>
    <description>Object to hold data from nightly reports from Brainshark.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account that is on the Contact for the Brainshark data.</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>eAcademies</relationshipLabel>
        <relationshipName>eAcademies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Title__c</fullName>
        <description>Change of label to match new input fields, 2/29/2016.</description>
        <label>Course Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_ViewerInfo__c</fullName>
        <description>Change of label to match new input fields, 2/29/2016.</description>
        <label>Student</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>View_Total_Score__c</fullName>
        <description>Change of label to match new input fields, 2/29/2016.</description>
        <label>Score</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ViewerInfo__c</fullName>
        <label>ViewerInfo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vin_User_ID__c</fullName>
        <description>Holds the value of the GBCustom5 field from the Brainshark data. 
Change of label to match new input fields, 2/29/2016.</description>
        <label>Student UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>eAcademy</label>
    <nameField>
        <displayFormat>eA-{0000000}</displayFormat>
        <label>eAcademy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eAcademies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/eAcademyCustomerView_Test.cls
@isTest
private class eAcademyCustomerView_Test {
	
	@isTest static void test_method_one() {
		Account testAcct = TestData.setupAccount();
		insert testAcct;
		Contact testCon = TestData.setupContact(testAcct, 'VIN');
		testCon.FirstName = 'James';
		testCon.LastName = 'Bond';
		testCon.MotoSnap_User_Id__c = 'TestID';
		insert testCon;
		User testUser = TestData.setupUser('Vin Overage Customer Portal Manager', 'Customer');
		testUser.FirstName = 'James';
		testUser.LastName = 'Bond';
		testUser.ContactId = testCon.Id;
		insert testUser;
		User testUser2 = TestData.setupUser();
		testUser2.FirstName = 'James';
		testUser2.LastName = 'Bond';
		update testUser2;
		eAcademy__c eA1 = new eAcademy__c(Account_Name__c = testAcct.Id,
											Sort_ViewerInfo__c = 'Bond, James',
											ViewerInfo__c = 'Bond, James',
											Sort_Title__c = 'Test Class 1',
											View_Total_Score__c = '100',
											Vin_User_ID__c = 'TestID');
		insert eA1;
		eAcademy__c eA2 = new eAcademy__c(Account_Name__c = testAcct.Id,
											Sort_ViewerInfo__c = 'Bond, James',
											ViewerInfo__c = 'Bond, James',
											Sort_Title__c = 'Test Class 2',
											View_Total_Score__c = '90',
											Vin_User_ID__c = 'TestID');
		insert eA2;
		eAcademy__c eA3 = new eAcademy__c(Account_Name__c = testAcct.Id,
											Sort_ViewerInfo__c = 'Bond, James',
											ViewerInfo__c = 'Bond, James',
											Sort_Title__c = 'Test Class 3',
											View_Total_Score__c = '80',
											Vin_User_ID__c = 'TestID');
		insert eA3;

		Test.startTest();

		//As a portal user
		system.runAs(testUser){
			ApexPages.standardController controller;
			eAcademyCustomerView ctrl = new eAcademyCustomerView(controller);
			system.assertEquals(3, ctrl.eAcademyRLWrpList.size());
			ctrl.showMore();
			ApexPages.currentPage().getParameters().put('detailParam', eA1.Id);
			ctrl.showPopup();
			ctrl.closePopup();
			ctrl.searchInput = 'xyz';
			ctrl.search();
			ctrl.searchInput = 'Bond';
			ctrl.search();
			ctrl.cancelSearch();
		}

		//As an admin user
		system.runAs(testUser2){
			ApexPages.standardController controller;
			eAcademyCustomerView ctrl1 = new eAcademyCustomerView(controller);
			system.assertEquals(3, ctrl1.eAcademyRLWrpList.size());
		}

		Test.stopTest();

	}
	
}