objects/Contract.object
<CustomObject>
    <recordTypes>
        <fullName>ADD</fullName>
        <active>true</active>
        <description>use to add a new contract (order) to the AutoTrader Billing System</description>
        <label>ADD</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>National_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>National Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Names__c</fullName>
        <inlineHelpText>what is the core product being sold</inlineHelpText>
        <label>Product Suite</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Account Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Inventory with MPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Bundle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Genius - Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Genius - With Provision Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoVisor - Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoVisor - With Provision Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUX Account Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR New Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR Used Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR Used w/ vAuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest Stand-Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Plus Desking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Plus MPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Premier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Pro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Marketing Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment Coop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak CLLC SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak CLLC SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak DM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Package_Type__c</fullName>
        <label>With Website?</label>
        <picklist>
            <controllingField>Opportunity_Names__c</controllingField>
            <picklistValues>
                <fullName>With Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Without Website</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Generated_by_Product_Flow__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates that this product was created by Flow designed to add products</inlineHelpText>
        <label>Generated by Product Flow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsBeingCloned__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this is checked, the package product population will not fire off. This is used when the custom clone button is working to ensure no duplicate products are created.</description>
        <label>IsBeingCloned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPackageChild__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only applicable to Monthly items.</description>
        <inlineHelpText>Only applicable to Monthly items.</inlineHelpText>
        <label>IsPackageChild</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Package_Discount_Percentage__c</fullName>
        <label>Package Discount Percentage</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <formula>PricebookEntry.Product2.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <description>Used by Flow, reports, and workflow that needs to access the Product Name without diving down another layer or two just to get it.</description>
        <formula>PricebookEntry.Product2.Name</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Package_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by code. Indicates what product was added to this opp, that lead to the creation of this opp product.</description>
        <label>Source Package Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserPriceChange__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UserPriceChange</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/OppClone.cls
public with sharing class OppClone {
	
	public string oppId {get;set;}
	
	public string clonedOppName {get;set;}
	
	public boolean showNewURL {get;set;}
	
	
	public Opportunity clonedOpp {get;set;}
	
	
	public OppClone() {
		
		clonedOpp = new Opportunity();
		
		showNewURL = false;
		
		oppId = ApexPages.currentPage().getParameters().get('oppId');
		
		queryOppOlis();
	}
	
	public list<newClonedLink> newLinks {get;set;}
	
	public class newClonedLink {
		
		public string oppId {get;set;}
		public string oppName {get;set;}
		
		public newClonedLink(string tOppId, string tOppName) {
			
			oppId = tOppId;
			oppName = tOppName;
		}
	}
	
	
	public Opportunity originalOpp {get;set;}
	public List<OpportunityLineItem> originalOlis {get;set;}
	
	
	public void queryOppOlis() {
		
		newLinks = new List<newClonedLink>();
		
		originalOpp = [SELECT Id, Name, CloseDate, AccountId, Account.Name, Opportunity_Names__c, National_Rep__c, Package_Type__c
					   FROM Opportunity
					   WHERE Id = :oppId];
					   
		//clonedOppName = originalOpp.Name + ' - Clone';
		
		
		originalOlis = [SELECT Id, UserPriceChange__c, Quantity, OpportunityId, UnitPrice, PriceBookEntryId, ProductId__c,
							IsPackageChild__c, Package_Discount_Percentage__c, Source_Package_Product__c, Product_Name__c,
							Generated_by_Product_Flow__c
						FROM OpportunityLineItem
						WHERE OpportunityId = :oppId];
						
		clonedOpp = originalOpp;				
	}
	
	public PageReference performClone() {
		
		showNewURL = true; 
		cloneOpp();
		
		return null;
	}
	
	
	public List<OpportunityLineItem> clonedOlis {get;set;}
	
	public void cloneOpp() {
		
		
		
		//clonedOpp = new Opportunity();
		clonedOlis = new List<OpportunityLineItem>();
		
		clonedOpp.Id = null;
		
		clonedOpp.Opportunity_Names__c = originalOpp.Opportunity_Names__c;
		
		if(clonedOpp.AccountId == null) {
			
			clonedOpp.AccountId = originalOpp.AccountId;
			
			clonedOppName = originalOpp.Account.Name + ' - ' + originalOpp.Opportunity_Names__c;
		}
		else {
			
			clonedOppName = clonedOpp.Account.Name + ' - ' + clonedOpp.Opportunity_Names__c;
		}
		
		clonedOpp.StageName = 'Prospect';
		clonedOpp.Name = clonedOppName;
		clonedOpp.CloseDate = originalOpp.CloseDate;
		clonedOpp.National_Rep__c = originalOpp.National_Rep__c;
		clonedOpp.Package_Type__c = originalOpp.Package_Type__c;
		
		system.debug('Bazinga... clonedOpp.Name: ' + clonedOpp.Name);
		
		insert clonedOpp;
		
		
		for(OpportunityLineItem oli : originalOlis) {
			
			OpportunityLineItem cloneOli = new OpportunityLineItem();
			
			cloneOli.OpportunityId = clonedOpp.Id;
						
			cloneOli.Quantity = oli.Quantity;
			cloneOli.UnitPrice = oli.UnitPrice;
			cloneOli.PriceBookEntryId = oli.PriceBookEntryId;
			cloneOli.IsPackageChild__c = oli.IsPackageChild__c;
			cloneOli.Package_Discount_Percentage__c = oli.Package_Discount_Percentage__c;
			
			cloneOli.IsBeingCloned__c = true;
			cloneOli.UserPriceChange__c = true;
			cloneOli.Source_Package_Product__c = oli.Source_Package_Product__c;
			//Code to turn off validtion rule, Opportunity Product Validation Rule: CannotCreateVinDIWithoutFlow,  when cloning
			if(String.valueOf(oli.Product_Name__c).contains('Data Integration')){
				cloneOli.Generated_by_Product_Flow__c = true;
			}
			clonedOlis.add(cloneOli);
		}
		
		insert clonedOlis;
		
		string newCloneOppName = [SELECT Id, Name FROM Opportunity WHERE Id = :clonedOpp.Id].Name;
		
		newLinks.add(new newClonedLink(clonedOpp.Id, newCloneOppName));
		
		//
		string message = 'User Id: ' + UserInfo.getUserId() + ' ... User Name: ' + UserInfo.getUserName(); 
	
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'dean.lukowski@vinsolutions.com'};
        mail.setToAddresses(toAddresses);
        mail.setSubject('Opp Clone performed');
        mail.setPlainTextBody(message);
        
        try {
        	
        	//Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
        catch(Exception e) {
        	
        }
	}
	
	
	
	public void nullPR() {
		
		//return null;
	}
	
	
	/*
	
	 - build the new opportunity name using the "account name - opportunity type"
	
	
	- Check UserPriceChange on OLIs when cloning, then uncheck them afterwards
	- Reset Stage to Prospect
	- Reset Paid_1 to No
	- Clear out Paid Date_1
	- Clear out Proposals Sent, Proposal Previewed
	- Clear out # Webex Events
	- Uncheck InstallmentsGenerated, Contract Generated, Project Exception, Project Generated
	- Reset Confirmed to No
	
	
	*/
}