objects/Contact.object
<CustomObject>
    <fields>
        <fullName>account_name__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the primary contact associated with the Opportunity</inlineHelpText>
        <label>Deal Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Deal Contact)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>look up the contact under the Salesforce account that Implementation will contact regarding the setup of the products purchased</inlineHelpText>
        <label>Implementation Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Implementation Contact)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <label>Implementation Manager</label>
        <picklist>
            <picklistValues>
                <fullName>Matt Bench</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travis Douglas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jennifer Merrick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kandy Richert</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (Contact)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Manager__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;&amp;Opportunity__r.Implementation_Contact__r.Id,  Opportunity__r.Implementation_Contact__r.FirstName&amp;&quot; &quot;&amp; Opportunity__r.Implementation_Contact__r.LastName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Implementation Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <inlineHelpText>short description about project</inlineHelpText>
        <label>Project Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PhoneScreenPopController.cls
public with sharing class PhoneScreenPopController {
	public String incomingNumber {get; set;}
	public LIST<Account> relatedAccounts {get; set;}
	public LIST<Contact> relatedContacts {get; set;}
	public LIST<Case> relatedCases {get; set;}
	public LIST<Opportunity> relatedOpportunities {get; set;}
	public LIST<SFDC_520_Quote__c> relatedProjects {get; set;}
	public Map<Id, String> theseObjectsIdMap {get; set;}
	public Map<Id, Contact> theseContactsIdMap {get; set;}
	public Map<Id, Account> theseAccountsIdMap {get; set;}
	
	public LIST<LIST<sObject>> theseObjectsQuery {get; set;}
	
		
	
	public PhoneScreenPopController ()
	{
		init();
	}
	
	public void init(){
		
		populateIncomingNumber();
		if (incomingNumber.length() > 9)
		{
			setTheseObjectsQuery();
			setTheseObjectsIdMap();
			setRelatedContacts();
			setRelatedAccounts();
			
			setTheseContactsIdMap();
			setTheseAccountsIdMap();					
			
			setRelatedCases();
			setRelatedOpportunities();		
			setRelatedProjects();
		}
	}
	
	
	public Map<Id, Contact> getTheseContactsIdMap(){
		return theseContactsIdMap;
	}
	
	public Map<Id, Account> getTheseAccountsIdMap(){
		return theseAccountsIdMap;
	}
	
	public Map<Id, String> getTheseObjectsIdMap(){
		return theseObjectsIdMap;
	}	
	public LIST<Account> getRelatedAccounts(){
		return relatedAccounts;
	}
	public LIST<Contact> getRelatedContacts(){
		return relatedContacts;
	}
	public LIST<Case> getRelatedCases(){
		return relatedCases;
	}
	public LIST<Opportunity> getRelatedOpportunities(){
		return relatedOpportunities;
	}
	public LIST<SFDC_520_Quote__c> getRelatedProjects(){
		return relatedProjects;
	}

	
	public void setTheseObjectsQuery(){
		if(incomingNumber != null)
		{
			String searchquery='FIND \'' + incomingNumber + '*\' IN ALL FIELDS RETURNING Account, Case, Contact';
			theseObjectsQuery = search.query(searchQuery);	
		}
				
	}
	
	public void setTheseObjectsIdMap(){
		theseObjectsIdMap = new MAP<Id, String>();
		for (LIST<sObject> theseListObjects: theseObjectsQuery)
		{
			for (sObject thisObject: theseListObjects)
			{
				system.debug('thisObject.Id DEBUG: '+ thisObject.Id);
				theseObjectsIdMap.put(thisObject.Id, null);
			}			
		}
	}
	
	public void setTheseContactsIdMap(){
		theseContactsIdMap = new MAP<Id, Contact>(relatedContacts);		
	}
	
	public void setTheseAccountsIdMap(){
		theseAccountsIdMap = new MAP<Id, Account>(relatedAccounts);
	}
	public void setRelatedAccounts(){
		relatedAccounts = [select Id, Name, Phone, BillingCity, BillingState, AccountNumber from Account where Id IN :theseObjectsIdMap.keyset()];				
	}
	public void setRelatedContacts(){
		relatedContacts = [select Id, Name, Phone, MobilePhone,AssistantPhone, 	HomePhone, account_name__c, OtherPhone, AccountId 
		from Contact where Id IN :theseObjectsIdMap.keyset()];				
	}
	public void setRelatedCases(){
		relatedCases = [select Id, CaseNumber, Subject, ContactId, AccountId, Status, CreatedDate from Case 
		where (ContactId IN: theseContactsIdMap.keyset() OR AccountId IN: theseAccountsIdMap.keyset()) AND
		CreatedDate > :(system.today()-30) ORDER BY CreatedDate DESC limit 20];
		
		//relatedCases = [select Id, AccountId, CaseNumber, Subject from Case where Id IN :theseObjectsIdMap.keyset()];		
	}
	public void setRelatedOpportunities(){
		relatedOpportunities = [select Id, AccountId, CreatedDate from Opportunity where (Deal_Contact__c IN: theseContactsIdMap.keyset() OR Implementation_Contact__c IN :theseContactsIdMap.keyset()) AND CreatedDate > :(system.today()-30) ORDER BY CreatedDate DESC limit 20];
		
	}
	public void setRelatedProjects(){		
		relatedProjects = [select Id, Account__c, Contact__c, Implementation_Manager__c, Project_Name__c, CreatedDate from SFDC_520_Quote__c where 
		(Contact__c IN: theseContactsIdMap.keyset() OR Implementation_Manager__c IN: theseContactsIdMap.keyset()) ORDER BY CreatedDate DESC limit 20];	
	}
	
	public PageReference populateIncomingNumber()
	{
		incomingNumber = Apexpages.currentPage().getParameters().get('phonenumber');
		return null;	
	}
	
}