objects/DashboardTaskStatus__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Primary_Subject__c</fullName>
        <label>Primary Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Subject__c</fullName>
        <label>Secondary Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Status__c</fullName>
        <label>Task Status</label>
        <type>TextArea</type>
    </fields>
    <label>DashboardTaskStatus</label>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Approval_Stage__c</fullName>
        <inlineHelpText>Updated by the system upon milestone completion</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>1-Initiating</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>2-Planning and Design</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>3-Executing</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>4-Review</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>5-Finalizing</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Launched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-ILM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GO LIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Intro Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Strategy Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Dealer Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <formula>IF(!ISPICKVAL(Approval_Stage__c, &quot;Go Live&quot;) &amp;&amp; Project_Due_Date__c &gt;today() , &quot;Working&quot;,
IF(!ISPICKVAL(Approval_Stage__c, &quot;Go Live&quot;) &amp;&amp; Project_Due_Date__c &lt;Today() , &quot;Past Due&quot;, 
IF(ISPICKVAL(Approval_Stage__c, &quot;Go Live&quot;)&amp;&amp; Project_Due_Date__c &lt;  Project_Complete_Date__c , &quot;Goal Missed&quot;, 
IF(ISPICKVAL(Approval_Stage__c, &quot;Go Live&quot;) &amp;&amp; Project_Due_Date__c &gt;=  Project_Complete_Date__c , &quot;Goal Completed&quot;, 
&quot;Log Change Request&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>this field looks at the Project Due Date and formulates a status</inlineHelpText>
        <label>Project Status</label>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FOD_BatchTest.cls
@isTest
public class FOD_BatchTest {
    
    static testmethod void testNewUserAggregation(){
        customSettingData();
        SFDC_520_Quote__c proj = new SFDC_520_Quote__c(Name = 'Conquest 1', Approval_Stage__c = 'Integration');
        insert proj;
        proj.Name = 'Conquest 1';
        update proj;
        List<Task> tskList = new List<Task>();
        Task tsk1 = new Task(Subject = 'New User Session', Status = 'Not Started', WhatId = proj.id, Date_Time_Completed__c = System.today());
        tskList.add(tsk1);
        insert tskList;
            
        Test.StartTest();
            FOD_NewUserAggregation batch = new FOD_NewUserAggregation();
            Database.BatchableContext a;
            batch.start(a);
            batch.execute(a, [select WhatId, subject, Status from Task]);
        batch.finish(a);
        Test.StopTest();
        
        FOD_NewUserAggregationSchedule batchSch = new FOD_NewUserAggregationSchedule();
        SchedulableContext sc;
        batchSch.execute(sc);
    }
    
    static testmethod void testNewUserCompletedAggregation(){
        customSettingData();
        SFDC_520_Quote__c proj = new SFDC_520_Quote__c(Name = 'Conquest 1', Approval_Stage__c = 'Integration');
        insert proj;
        proj.Name = 'Conquest 1';
        update proj;
        List<Task> tskList = new List<Task>();
        Task tsk1 = new Task(Subject = 'New User Session', Status = 'Completed', WhatId = proj.id, Date_Time_Completed__c = System.today());
        tskList.add(tsk1);
        insert tskList;
        
        Test.StartTest();
            FOD_NewUserCompletedAggregation batch = new FOD_NewUserCompletedAggregation();
            Database.BatchableContext a;
            batch.start(a);
            String subjectCondition = 'New User Session';
            batch.execute(a, [select WhatId, subject, Status, Date_Time_Completed__c from Task where Subject = 'New User Session' and Status = 'Completed' and Date_Time_Completed__c = THIS_QUARTER]);
        batch.finish(a);
        Test.StopTest();
    }
    
    public static void customSettingData() {
        List<DashboardTaskStatus__c> dbList = new List<DashboardTaskStatus__c>();
        
        dbList.add(new DashboardTaskStatus__c(Name = 'New User1', Project__c = 'New User', Stage__c = '', Project_Status__c = 'Active', Task_Status__c = 'Not Started', Primary_Subject__c = 'New User Session', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'New User2', Project__c = 'New User', Stage__c = '', Project_Status__c = 'Deferred', Task_Status__c = 'Deferred', Primary_Subject__c = 'New User Session', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'New User3', Project__c = 'New User', Stage__c = '', Project_Status__c = 'Escalated', Task_Status__c = 'Escalated', Primary_Subject__c = 'New User Session', Secondary_Subject__c = ''));
        dbList.add(new DashboardTaskStatus__c(Name = 'New User4', Project__c = 'New User', Stage__c = '', Project_Status__c = 'Completed', Task_Status__c = 'Completed', Primary_Subject__c = 'New User Session', Secondary_Subject__c = ''));
        
        insert dbList;
    }
}