objects/Demo__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Demos</relationshipLabel>
        <relationshipName>Demos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Webex_Event_ID__c</fullName>
        <label>Webex Event ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webexer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Webexer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Demos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Demo</label>
    <nameField>
        <label>Demo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Webex</fullName>
        <active>true</active>
        <label>Webex</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Hard_Coded_Ids__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Place to keep hard coded Ids</description>
    <fields>
        <fullName>HayStakOppRecordTypeId__c</fullName>
        <description>Haystak Record Type Id for Opportunities.</description>
        <inlineHelpText>Haystak Record Type Id for Opportunities.</inlineHelpText>
        <label>HayStakOppRecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Hard Coded Ids</label>
</CustomObject>

objects/Installment__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Installment_Amount__c</fullName>
        <label>Installment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Installment_Due_Date__c</fullName>
        <label>Installment Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Installment_Number__c</fullName>
        <label>Installment Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <formula>Opportunity__r.Opportunity_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Installments</relationshipLabel>
        <relationshipName>Installments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Paid2__c</fullName>
        <label>Paid2</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>installmentAmtPlusSalesTax__c</fullName>
        <label>installmentAmtPlusSalesTax</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Installment</label>
    <nameField>
        <label>Installment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Contact_Email__c</fullName>
        <formula>Deal_Contact__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deal Contact Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freight_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Updated when the Generate Invoice is hit.</description>
        <inlineHelpText>Updated when the Generate Invoice is hit.</inlineHelpText>
        <label>Freight Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Initial_Webex_Completed__c</fullName>
        <inlineHelpText>Date Field updated by a trigger when the initial demo event is updated to completed</inlineHelpText>
        <label>Initial Demo Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when an invoice is generated so that we can make sure nothing gets paid without an invoice being created.</description>
        <label>Invoice Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Total of invoice generated when Generate Invoice button is hit.</inlineHelpText>
        <label>Invoice Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Completed_Webex_Date__c</fullName>
        <inlineHelpText>updated by the system when a Demo Event is updated to completed - uses the webex start date as the last completed Demo date</inlineHelpText>
        <label>Last Completed Demo Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Installments__c</fullName>
        <label>Number of Installments</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <description>Auto number ID for opportunities</description>
        <displayFormat>OP#-{00000000}</displayFormat>
        <inlineHelpText>Auto number ID for opportunities, used by accounting to track invoicing</inlineHelpText>
        <label>Opportunity #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Override_Related_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>check to override the whole product of the related product error</inlineHelpText>
        <label>Override Related Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Clone_ID__c</fullName>
        <inlineHelpText>updated by a trigger</inlineHelpText>
        <label>Parent Clone ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TNOPPST__Sales_Tax__c</fullName>
        <inlineHelpText>Total Sales Tax for This Opportunity</inlineHelpText>
        <label>Sales Tax</label>
        <summarizedField>OpportunityLineItem.TNOPPST__LineTax__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Webexer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Webexer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Freight_Cost__c</fullName>
        <description>Cost to ship product</description>
        <formula>PricebookEntry.Product2.Freight_Cost__c * Quantity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Cost to ship product</inlineHelpText>
        <label>Freight Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Override_Related_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>check box to override the related product error</inlineHelpText>
        <label>Override Related Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <formula>PricebookEntry.Product2.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_ProductId__c</fullName>
        <formula>PricebookEntry.Product2.Related_Product__r.Id</formula>
        <label>Related ProductId</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Freight_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Cost to ship product</description>
        <inlineHelpText>Cost to ship product</inlineHelpText>
        <label>Freight Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductId</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/OpportunityClass.cls
public class OpportunityClass {
	
    //This Method is used for Cloning Demos whenever an Oppty is created or updated
    //public Opportunity oppty = new Opportunity();
    public double salesTax2 {get; set;}
        
    public static void CloneDemos(Opportunity Oppty) {   
    	
        List<Demo__c> cloneEvents = new List<Demo__c>();
        
        for(Event webexEvents : [SELECT Id, StartDateTime, OwnerId, Subject, WhatId 
                                 FROM Event 
                                 WHERE WhatId=:Oppty.Parent_Clone_ID__c 
                                 AND (NOT subject like '%Meeting%') 
                                 AND (subject like '%WebEx%')]) {
                                 	
            Demo__c D = new Demo__c();
            D.Name = 'WebEx' + ' - ' + webexEvents.StartDateTime;
            D.Webex_Event_ID__c = webexEvents.Id;
            D.Webexer__c = webexEvents.OwnerId;
            D.Opportunity__c = Oppty.Id;   
                    
            cloneEvents.add(D); 
        }   
        
        try {
        	
            insert cloneEvents;
        }
        catch(Exception Ex) {
        	
            system.debug(Ex);
        }       
    }
    
    
    //This method is used for Generating installments when an Oppty is marked "Closed or Won"
    public static void GenerateInstallments(Opportunity oppty) {     
    	
    	Hard_Coded_Ids__c hcid = Hard_Coded_Ids__c.getValues('HCIDS');
    	String hsrtid = hcid.HayStakOppRecordTypeId__c;
    	  
        integer i = 0;
        double installmentAmount = oppty.Amount / decimal.valueOf(oppty.Number_of_Installments__c);
        double numberInstallments = decimal.valueOf(oppty.Number_of_Installments__c);
        double salesTax = oppty.TNOPPST__Sales_Tax__c / decimal.valueOf(oppty.Number_of_Installments__c);
        double totalSplit = 0;
        Date installmentDue = oppty.CloseDate;      
        
        List<Installment__c> Inst = new List<Installment__c>();
        
        if(oppty.RecordTypeId == hsrtid){
        	do {
            	
                Installment__c a = new Installment__c();
                a.Installment_Number__c = i + 1;              
                a.Contact_Email__c = oppty.Deal_Contact_Email__c;
                a.Installment_Due_Date__c = installmentDue + (30 * i);
                a.Opportunity__c = oppty.id;
                a.Name = oppty.Name + ' - Installment ' + (i + 1);
                
                if(a.Name.length() > 80) {
                	
                	a.Name = a.Name.substring(0,80);
                }
                
                if(i + 1 == numberInstallments) {
                	
                    //calculate final payment to trim off division excess
                    installmentAmount = oppty.Amount - totalSplit;
                }
                
                a.Installment_Amount__c = installmentAmount;
                a.installmentAmtPlusSalesTax__c = installmentAmount + salesTax;
                Inst.add(a);
                totalSplit += installmentAmount;  
                
                i++;            
            }   
            while(i < numberInstallments);
        }
        
        if(oppty.CloseDate == system.today()) {
        	
            do {
            	
                Installment__c a = new Installment__c();
                a.Installment_Number__c = i + 1;              
                a.Contact_Email__c = oppty.Deal_Contact_Email__c;
                a.Installment_Due_Date__c = installmentDue + (30 * i);
                a.Opportunity__c = oppty.id;
                a.Name = oppty.Name + ' - Installment ' + (i + 1);
                
                if(a.Name.length() > 80) {
                	
                	a.Name = a.Name.substring(0,80);
                }
                
                if(i + 1 == numberInstallments) {
                	
                    //calculate final payment to trim off division excess
                    installmentAmount = oppty.Amount - totalSplit;
                }
                
                a.Installment_Amount__c = installmentAmount;
                a.installmentAmtPlusSalesTax__c = installmentAmount + salesTax;
                Inst.add(a);
                totalSplit += installmentAmount;  
                
                i++;            
            }   
            while(i < numberInstallments);
        }
        
        
        try { 
        	  
            insert Inst;
        }
        catch(Exception Ex) {
        	
            system.debug(ex);
        }
        
    }
    
    public static void UpdateInstallments(Opportunity oppty) {
    	
    	system.debug('Bazinga... oppty.Amount: ' + oppty.Amount);
    	system.debug('Bazinga... oppty.Number_of_Installments__c: ' + oppty.Number_of_Installments__c);
    	double installmentAmount;
    	double numberInstallments;
    	double salesTax;
    	double totalSplit;
    	Date installmentDue;
    	
        integer i = 0;
        if(oppty.Amount != null){
	        //double installmentAmount = oppty.Amount / decimal.valueOf(oppty.Number_of_Installments__c);
	        //double numberInstallments = decimal.valueOf(oppty.Number_of_Installments__c);
	        //double salesTax = oppty.TNOPPST__Sales_Tax__c / decimal.valueOf(oppty.Number_of_Installments__c);
	        //double totalSplit = 0;
	        //Date installmentDue = oppty.CloseDate;
	        installmentAmount = oppty.Amount / decimal.valueOf(oppty.Number_of_Installments__c);
	        numberInstallments = decimal.valueOf(oppty.Number_of_Installments__c);
	        salesTax = oppty.TNOPPST__Sales_Tax__c / decimal.valueOf(oppty.Number_of_Installments__c);
	        totalSplit = 0;
	        installmentDue = oppty.CloseDate;
        }      
        
        List<Installment__c> Inst = new List<Installment__c>();
    
        List<Installment__c> oldInst = [SELECT Id, Opportunity_ID__c, Opportunity__c 
        								FROM Installment__c 
        								WHERE Opportunity__c = :oppty.Id];
    
        if(oldInst != null) {
        	
            try {
            	
                delete oldInst;
            }
            catch(Exception Ex) {
            	
                system.debug(ex);
            }
        }
        
        if(oppty.CloseDate == system.today()) {
        	
            do {
            	
                Installment__c a = new Installment__c();
                a.Installment_Number__c = i + 1;              
                a.Contact_Email__c = oppty.Deal_Contact_Email__c;
                a.Installment_Due_Date__c = installmentDue + (30 * i);
                a.Opportunity__c = oppty.id;
                a.Name = oppty.Name + ' - Installment ' + (i + 1);
                
                if(a.Name.length() > 80) {
                	
                	a.Name = a.Name.substring(0,80);
                }
                
                if(i + 1 == numberInstallments) {
                	
                    //calculate final payment to trim off division excess
                    installmentAmount = oppty.Amount - totalSplit;
                }
                
                a.Installment_Amount__c = installmentAmount;
               	a.installmentAmtPlusSalesTax__c = installmentAmount + salesTax;
                Inst.add(a);
                totalSplit += installmentAmount;  
                
                i++;            
            }   
            while(i < numberInstallments);
        }
        
        try {  
        	 
            insert Inst;
        }
        catch(Exception Ex) {
        	
            system.debug(ex);
        }
    }
    //method that updated freight charges in whenever the opportunity is updated 
    public static void UpdateInvoiceTotal(Opportunity opp) {
    	
    	double totalFreight = 0;
    	double totalAmount = 0; 
    	//double salesTax2 = opp.TNOPPST__Sales_Tax__c/decimal.valueOf(opp.Number_of_Installments__c); 
    	
    	List<OpportunityLineItem> theseOLIs = [SELECT Id, OpportunityId, Quantity, Freight_Cost__c 
											   FROM OpportunityLineItem 
											   WHERE OpportunityId = :opp.Id];
    	
    	for(OpportunityLineItem thisOLI : theseOLIs) {
    		
            totalFreight += thisOLI.Freight_Cost__c;
        }
        
        opp.Freight_Cost__c = totalFreight;
        
        //update opp;
    	
    }
    
   	public static void UpdateInitialWebexCompleteDate(Opportunity opp) {
    	
    	if(opp.StageName == 'Webex Complete') {
    		
    		opp.Initial_Webex_Completed__c = system.today();
    	}
    	/*if(opp.StageName == 'Second WX Complete'){
    		
    		opp.Last_Completed_Webex_Date__c = system.today();
    	}*/
    }
    
    public static void UpdateInvoiceInformation(Opportunity O) {
    	
        //class updates Freight Cost and invoice total for invoice generation.
        
        double totalFreight = 0;
        double totalInstallment = 0;
        
        List<OpportunityLineItem> theseOLIs = [SELECT Id, OpportunityId, Quantity, Freight_Cost__c 
    										   FROM OpportunityLineItem 
    										   WHERE OpportunityId = :O.Id];
        
        for(OpportunityLineItem thisOLI : theseOLIs) {
        	
            totalFreight += thisOLI.Freight_Cost__c;
        }
        
        O.Freight_Cost__c = totalFreight;
        
        List<Installment__c> theseInstallments = [SELECT ID, Opportunity__c, Installment_Amount__c, Installment_Number__c, Paid2__c, installmentAmtPlusSalesTax__c 
            									  FROM Installment__c 
            									  WHERE Opportunity__c = :O.Id 
            									  ORDER BY Installment_Number__c DESC];           
        
        if(Double.valueOf(O.Number_of_Installments__c) > 1) {
            
            double lowestUnpaidFound = Double.valueOf(O.Number_of_Installments__c) + 1;
                
            for(Installment__c thisInstallment : theseInstallments) {
                
                //this Installment loop finds the lowest unpaid installment and puts it as the AMOUNT DUE NOW
                if(thisInstallment.Paid2__c == null && thisInstallment.Installment_Number__c <= lowestUnpaidFound) {
                    
                    totalInstallment = thisInstallment.Installment_Amount__c;
                    lowestUnpaidFound = thisInstallment.Installment_Number__c;              
                }
                
                system.debug('Installment Number: ' + thisInstallment.Installment_Number__c);
                system.debug('Lowest Unpaid Found: ' + lowestUnpaidFound);
                system.debug('totalInstallmentPaid: '+ totalInstallment);                           
            }
        }
        else {
        	
            for(Installment__c thisInstallment : theseInstallments) {
            	
                if(thisInstallment.Installment_Number__c == 1) {
                	
                    totalInstallment = thisInstallment.Installment_Amount__c;               
                }               
            }           
        }   
        
        O.Invoice_Total__c = (totalFreight + totalInstallment);
        O.Invoice_Generated__c = true;
        
        update O;
    }  
    
    public static void checkRelatedProducts(Opportunity O) {
    		
        List<Id> ListOfRelatedProductIds = new List<Id>();
        
        MAP<Id, OpportunityLineItem> mapOfAllProductIds = new MAP<Id, OpportunityLineItem>();
    
        List<OpportunityLineItem> theseOLIs = [SELECT Id, Related_ProductId__c, ProductId__c, OpportunityId, Override_Related_Product__c 
    										   FROM OpportunityLineItem 
    										   WHERE OpportunityId = :O.Id];
        
        for(OpportunityLineItem thisOLI : theseOLIs) {
        	
            system.debug('OLI ID: ' + thisOLI.Id);
            
            if(thisOLI.Related_ProductId__c != null && thisOLI.Override_Related_Product__c != true) {
            	
            	listOfRelatedProductIds.add(thisOLI.Related_ProductId__c);
            }
                       
            mapOfAllProductIds.put(thisOLI.ProductId__c, thisOLI);          
        }
        
        for(Id thisRelatedId : ListOfRelatedProductIds) {
        	           
            if(mapOfAllProductIds.get(thisRelatedId) == null) {
            	               
                Product2 errorProduct = [SELECT Id, Name 
                						 FROM Product2 
                						 WHERE Id = :thisRelatedId 
                						 limit 1];              
                
                O.addError('Opportunity has a product on it that has a REQUIRED RELATED PRODUCT.  Product Name Required:  ' + errorProduct.Name);
            }
        }
    }
}