objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Names__c</fullName>
        <inlineHelpText>what is the core product being sold</inlineHelpText>
        <label>Product Suite</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Account Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Inventory with MPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Bundle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Genius - Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction Genius - With Provision Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoVisor - Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AutoVisor - With Provision Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUX Account Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR New Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR Used Stand Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV to KBB PAR Used w/ vAuto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conquest Stand-Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Plus Desking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Plus MPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Premier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM Pro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Marketing Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment Coop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak CLLC SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak CLLC SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haystak DM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Comment__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_Piece__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Piece</label>
        <referenceTo>Project_Piece__c</referenceTo>
        <relationshipLabel>Project Comments</relationshipLabel>
        <relationshipName>Project_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipLabel>Project Comments</relationshipLabel>
        <relationshipName>Project_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Comment</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Project Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Product_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Comment__c</fullName>
        <label>Last Comment</label>
        <length>163</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Piece_Issue__c</fullName>
        <inlineHelpText>Auto-populated from Products sold when Opportunity marked PAID</inlineHelpText>
        <label>Piece Issue</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Piece_Stage__c</fullName>
        <label>Project Asset Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Travel Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer&apos;s Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Website Approval-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Shipment Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing/Shipping/Uploading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial QA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Stage__c</fullName>
        <inlineHelpText>Updated by the system upon milestone completion</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>1-Initiating</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>2-Planning and Design</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>3-Executing</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>4-Review</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>5-Finalizing</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Launched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-ILM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GO LIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Intro Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Strategy Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Dealer Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProjComments.cls
public with sharing class ProjComments 
{
	
	public static void UpdateLastComment(Project_Comment__c[] pc)
	{	
		if(pc[0].Project_Piece__c!=null)
		{
			Project_Piece__c pp = [select id, Last_Comment__c from Project_Piece__c where id =:pc[0].Project_Piece__c];
		
			for (Project_Comment__c p:pc)
			{ 		
				string Comment;
				if (p.Comments__c == null) Comment = '...';
				else Comment = p.Comments__c;
				string LastComment;
				
				if(Comment.length()<=160)
				{
					LastComment = Comment;
				}
				if(Comment.length()>160)
				{
					LastComment = Comment.substring(0,160)+'...';
				}
				
				pp.Last_Comment__c =  LastComment;			
				update pp;
			}
		}
	}



	/*public static testMethod void TestProjectComments()
	{	
		Account Ac = new Account();
		Ac.Name = 'test'; 
		insert Ac;
	
		Opportunity Opt = new Opportunity();
		Opt.AccountId = Ac.Id;
		Opt.StageName = 'test'; 
		Opt.CloseDate = system.today();
		Opt.Opportunity_Names__c = 'test';
		Opt.Type = 'New Business';
		Opt.Name = 'test';
		insert Opt;
		
		SFDC_520_Quote__c Pro = new SFDC_520_Quote__c();
		Pro.Approval_Stage__c = 'Introduction';
		Pro.Name = 'test';
		Pro.Opportunity__c = Opt.Id;
		Pro.Account__c = Ac.Id;
		//Pro.DDM__c = userinfo.getUserId();
		insert Pro;
		
		Project_Piece__c PP = new Project_Piece__c();
		PP.Project__c = Pro.Id;
		PP.Piece_Issue__c = 'TestPiece - Sticker';
		PP.Name = 'VinSticker';
		PP.Project_Piece_Stage__c = 'Introduction';
		insert PP;
	
		Project_Comment__c PjctC = new Project_Comment__c();
		PjctC.Comments__c = 'test';
		PjctC.Project__c = Pro.Id;
		PjctC.Project_Piece__c = PP.Id;	
	
		insert PjctC;
	}*/
}