objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the primary contact associated with the Opportunity</inlineHelpText>
        <label>Deal Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Deal Contact)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuoteNumber__c</fullName>
        <formula>mid(text(Today()), 1,4)&amp;mid(text(Today()), 6,2)&amp;mid(text(Today()), 9,2)&amp;&quot;-&quot;&amp;RIGHT((Mid(TEXT(Now()), 12,2))&amp;Mid(TEXT(Now()), 15,2)&amp;text(value(Mid(TEXT(Now()), 18,2))),6)&amp;&quot;-&quot;&amp;CASE(Opportunity_Names__c,
&quot;ACH Bank Withdrawal&quot;,&quot;ACH Bank Withdrawal&quot;,
&quot;Black Book&quot;,&quot;Black Book&quot;,
&quot;Buyers Guides&quot;,&quot;Buyers Guides&quot;,
&quot;Click for chat&quot;,&quot;Click for chat&quot;,
&quot;Craigslist&quot;,&quot;Craigslist&quot;,
&quot;Credit Card Auto Patment&quot;,&quot;Credit Card Auto Patment&quot;,
&quot;CRM&quot;,&quot;CRM&quot;,
&quot;DIY&quot;,&quot;DIY&quot;,
&quot;Forms&quot;,&quot;Forms&quot;,
&quot;Gold Solution&quot;,&quot;Gold Solution&quot;,
&quot;ILM&quot;,&quot;ILM&quot;,
&quot;Intellisweeps&quot;,&quot;Intellisweeps&quot;,
&quot;KBB&quot;,&quot;KBB&quot;,
&quot;Knowme&quot;,&quot;Knowme&quot;,
&quot;Lead Converter (Live Chat)&quot;,&quot;Lead Converter (Live Chat)&quot;,
&quot;Market Pricing Tool&quot;,&quot;Market Pricing Tool&quot;,
&quot;Moto Blast&quot;,&quot;Moto Blast&quot;,
&quot;Multiple Adds&quot;,&quot;Multiple Adds&quot;,
&quot;NADA&quot;,&quot;NADA&quot;,
&quot;On Line Training&quot;,&quot;On Line Training&quot;,
&quot;Photo Overlay&quot;,&quot;Photo Overlay&quot;,
&quot;Platinum Solution&quot;,&quot;Platinum Solution&quot;,
&quot;Plug-In&quot;,&quot;Plug-In&quot;,
&quot;Police Book&quot;,&quot;Police Book&quot;,
&quot;Scanner&quot;,&quot;Scanner&quot;,
&quot;SEO&quot;,&quot;SEO&quot;,
&quot;SEO - WSO&quot;,&quot;SEO - WSO&quot;,
&quot;Silver Solution&quot;,&quot;Silver Solution&quot;,
&quot;Stickers&quot;,&quot;Stickers&quot;,
&quot;Stickers / Buyers Guides&quot;,&quot;Stickers / Buyers Guides&quot;,
&quot;Talking heads&quot;,&quot;Talking heads&quot;,
&quot;Training&quot;,&quot;Training&quot;,
&quot;Unlimited Ebay&quot;,&quot;Unlimited Ebay&quot;,
&quot;Up Grade&quot;,&quot;Up Grade&quot;,
&quot;V.I.D.&quot;,&quot;V.I.D.&quot;,
&quot;VinBDC&quot;,&quot;VinBDC&quot;,
&quot;VinCamera&quot;,&quot;VinCamera&quot;,
&quot;VinVideo&quot;,&quot;VinVideo&quot;,
&quot;Website&quot;,&quot;Website&quot;,

&quot;&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quote Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuoteVersion__c</fullName>
        <label>Quote Version</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>the user that initiated the opportunity: fishing pole, PM, etc</inlineHelpText>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VS_ID__c</fullName>
        <formula>Account.AccountNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vin Account Number</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/pdfGeneratorController.cls
public with sharing class pdfGeneratorController{
    
    public Id ParentId {get; set;}
    public String pdfName {get; set;}
    public String fileName {get; set;}
    
    public Opportunity opp {get; set;}
    public Document doc;
    
     
    
    
    public pdfGeneratorController(){
        
        updateOppInfo();
        
    }
    
    public Document getPdfName(){
        
        doc = new Document();
        return doc;
    }
    
    public PageReference savePdf(){
        
        
        
        
        PageReference pdf = Page.QuoteShell;
        pdf.getParameters().put('id', ApexPages.currentPage().getParameters().get('id'));
        datetime myDateTime = dateTime.Now();
        //datetime newDate =myDateTime.addHours(-5);
        String convertedDate = myDateTime.format('MMMM d, yyyy hh:mm a');
        
        fileName = opp.VS_ID__c + ' ' + opp.Account.Name + ' ' + convertedDate + '.pdf';
        
        //create the new attachment
        Attachment attach = new Attachment();
        //create the new document
        Document doc = new Document();
        
        //the contents of the attachment from the pdf
        Blob body = !Test.isRunningTest() ? pdf.getContentAsPDF() : Blob.ValueOf('dummy text');
            
        attach.Body = body;
        attach.Name = fileName;
        attach.IsPrivate = false;
        attach.contentType = 'pdf' ;
        //attach pdf to the opportunity
        attach.ParentId  = ApexPages.currentPage().getParameters().get('Id');
        insert attach;
            
        //save pdf in My Documents folder
        doc.FolderId = UserInfo.getUserId();
        doc.Body = body;
        doc.Name = fileName;
        doc.contentType = 'pdf';
            
        insert doc;
            
        PageReference returnPage = new Pagereference('/'+attach.Id);
        //return returnPage;    
        return pdf;
            
        
    }
    
    public void updateOppInfo(){
        
        opp = [SELECT Id, Name, Account.Name, VS_ID__c, Deal_Contact__r.Name, Deal_Contact__r.Email, 
               Salesperson__r.Email, Salesperson__r.Name, QuoteNumber__c, QuoteVersion__c
               FROM Opportunity
               WHERE Id =: ApexPages.currentPage().getParameters().get('id')];
               
            
    }
    
    
    
    
}