objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ActualDescription__c</fullName>
        <label>ActualDescription</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <description>The amount this line item has been discounted by.</description>
        <formula>IF(
   OR(
      Total_List_Price__c = 0,
      VS_Sale_Price__c &gt; Total_List_Price__c
   ),
   0,
   (VS_Sale_Price__c - Total_List_Price__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>List_Price_Formula__c</fullName>
        <formula>IF(
   !ISBLANK(Package_Discount_Percentage__c),
   IF(
      IsPackageChild__c &amp;&amp; One_Time_Fee__c = FALSE, 
      (ListPrice*Quantity*Package_Discount_Percentage__c), 
      (ListPrice*Quantity)  
   ),
   IF(
      IsPackageChild__c,
      0,
      (ListPrice*Quantity)
   )
)</formula>
        <inlineHelpText>If PDP is filled in, check to see if IsPackageChild is TRUE and OneTimeFee is FALSE. If so, apply PDP to the List Price. Otherwise, straight List Price.
If PDP is not filled in, check if PackageChild is TRUE. If so, this is 0. If not straight List Price.</inlineHelpText>
        <label>List Price Pkg&apos;d</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>One_Time_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>One Time Fee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Sort_Order__c</fullName>
        <formula>if( One_Time_Fee__c =TRUE||Setup_Fee__c =TRUE|| Fulfillment__c =TRUE, 2, if( Hardware_Product__c =TRUE, 3, if( Solution_Product__c = TRUE, 1, 4)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Setup_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Setup Fee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Solution_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this is a major product for Vin. Ensures the generated project is set to the Staged layout.</description>
        <label>Vin Keystone Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TNOPPST__LineTax__c</fullName>
        <inlineHelpText>Sales Tax Calculated For This Line - Cannot Be Edited</inlineHelpText>
        <label>Sales Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

classes/SortedLineItemsController.cls
public class SortedLineItemsController 
{
    public Opportunity opportunity { get; set; }
    
    public OpportunityLineItem[] getSorted1() 
    {
        if (opportunity == null || opportunity.opportunityLineItems== null) 
        {
            return null;
        }
        
        // TODO: Add your sorting logic here (demo just reverses the list)
        LIST<OpportunityLineItem> result = new LIST<OpportunityLineItem>();
        for (OpportunityLineItem item : [select Discount_Amount__c, ListPrice, List_Price_Formula__c, PricebookEntry.Product2.Description, PricebookEntry.Product2.Name, Quantity, TotalPrice, ActualDescription__c, TNOPPST__LineTax__c  from OpportunityLineItem where OpportunityLineItem.OpportunityId=:opportunity.Id and Product_Sort_Order__c = 1 order by TotalPrice desc])//opportunity.opportunityLineItems) 
        {          
           result.add(item);
        }
        
        return result;
   }
   public OpportunityLineItem[] getSorted2() 
    {
        if (opportunity == null || opportunity.opportunityLineItems== null) 
        {
            return null;
        }
        
        // TODO: Add your sorting logic here (demo just reverses the list)
        LIST<OpportunityLineItem> result = new LIST<OpportunityLineItem>();
        for (OpportunityLineItem item : [select Discount_Amount__c, ListPrice, List_Price_Formula__c, PricebookEntry.Product2.Description, PricebookEntry.Product2.Name, Quantity, TotalPrice, ActualDescription__c, TNOPPST__LineTax__c from OpportunityLineItem where OpportunityLineItem.OpportunityId=:opportunity.Id  and Product_Sort_Order__c = 2 order by TotalPrice desc])//opportunity.opportunityLineItems) 
        {   
        	       
           result.add(item);
        }
        
        return result;
   }
   public OpportunityLineItem[] getSorted3() 
    {
        if (opportunity == null || opportunity.opportunityLineItems== null) 
        {
            return null;
        }
        
        // TODO: Add your sorting logic here (demo just reverses the list)
        LIST<OpportunityLineItem> result = new LIST<OpportunityLineItem>();
        for (OpportunityLineItem item : [select Discount_Amount__c, ListPrice, List_Price_Formula__c, PricebookEntry.Product2.Description, PricebookEntry.Product2.Name, Quantity, TotalPrice, ActualDescription__c, TNOPPST__LineTax__c from OpportunityLineItem where OpportunityLineItem.OpportunityId=:opportunity.Id  and Product_Sort_Order__c = 3 order by TotalPrice desc])//opportunity.opportunityLineItems) 
        {          
           result.add(item);
        }
        
        return result;
   }
   public OpportunityLineItem[] getSorted4() 
    {
        if (opportunity == null || opportunity.opportunityLineItems== null) 
        {
            return null;
        }
        
        // TODO: Add your sorting logic here (demo just reverses the list)
        LIST<OpportunityLineItem> result = new LIST<OpportunityLineItem>();
        for (OpportunityLineItem item : [select Discount_Amount__c, ListPrice, List_Price_Formula__c, PricebookEntry.Product2.Description, PricebookEntry.Product2.Name, Quantity, TotalPrice, ActualDescription__c, TNOPPST__LineTax__c from OpportunityLineItem where OpportunityLineItem.OpportunityId=:opportunity.Id  and Product_Sort_Order__c = 4 order by TotalPrice desc])//opportunity.opportunityLineItems) 
        {   
        	
        	result.add(item);
        }
        
        return result;
   }
   
   public OpportunityLineItem[] getSorted5(){
   	
   		if(opportunity == null || opportunity.opportunityLineItems == null){
   			
   			return null;
   		}
   		
   		//TODO:  Add your sorting logic here (demo just reverse the list)
   		LIST<OpportunityLineItem> result = new LIST<OpportunityLineItem>();
   		for (OpportunityLineItem item : [SELECT Discount_Amount__c, ListPrice, List_Price_Formula__c, 
   												 PricebookEntry.Product2.Description, PricebookEntry.Product2.Name,
   												 Quantity, TotalPrice, ActualDescription__c, TNOPPST__LineTax__c
   										  FROM OpportunityLineItem
   										  WHERE OpportunityLineItem.OpportunityId =: opportunity.Id and Product_Sort_Order__c = 5 order by TotalPrice desc]){
   		
   			result.add(item);								  	
   										  	
   		}
   										  	
   			return result;							  	
   }
  public static testmethod void testSortedLine()
  {
  	Opportunity Opp = new Opportunity();
  	OpportunityLineItem oli = new OpportunityLineItem(One_Time_Fee__c = true, Setup_Fee__c = true, Solution_Product__c = true, OpportunityId = Opp.id);
  	  		
  	Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(oli);
  	
  	SortedLineItemsController SLIC = new SortedLineItemsController();
  	
  	SLIC.opportunity = Opp;
  	SLIC.getSorted1();
  	SLIC.getSorted2();
  	SLIC.getSorted3();
  	SLIC.getSorted4();
  	SLIC.getSorted5();
  }
}