objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Implementation_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>look up the contact under the Salesforce account that Implementation will contact regarding the setup of the products purchased</inlineHelpText>
        <label>Implementation Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Implementation Contact)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Load_Counter__c</fullName>
        <description>For Tier 1/Tier 2/OEM opps only. Keeps track of the amount of project pieces generated so far on this opp.</description>
        <inlineHelpText>Keeps track of the amount of project pieces generated so far on this opp.</inlineHelpText>
        <label>Load Counter</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Override_Related_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>check to override the whole product of the related product error</inlineHelpText>
        <label>Override Related Product</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Override_Related_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>check box to override the related product error</inlineHelpText>
        <label>Override Related Product</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Subject_to_Load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this product will be counted by the Initial Load/Generate More Load system used by Tier 1/Tier 2/OEM opportunities.</description>
        <inlineHelpText>If checked, this product will be counted by the Initial Load/Generate More Load system used by Tier 1/Tier 2/OEM opportunities.</inlineHelpText>
        <label>Subject to Load</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Product_Process__c.object
<CustomObject>
    <fields>
        <fullName>Milestone_1_Stage__c</fullName>
        <label>Milestone 1 Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer&apos;s Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Travel Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing/Shipping/Uploading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Milestone_1__c</fullName>
        <label>Milestone 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_2_Stage__c</fullName>
        <label>Milestone 2 Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer&apos;s Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Travel Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing/Shipping/Uploading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Milestone_2__c</fullName>
        <label>Milestone 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_3_Stage__c</fullName>
        <label>Milestone 3 Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer&apos;s Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Travel Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing/Shipping/Uploading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Milestone_3__c</fullName>
        <label>Milestone 3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_4_Stage__c</fullName>
        <label>Milestone 4 Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer&apos;s Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Travel Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing/Shipping/Uploading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Milestone_4__c</fullName>
        <label>Milestone 4</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_5__c</fullName>
        <label>Milestone 5</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Product Process</label>
    <nameField>
        <label>Product Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/generatemoreload_test.cls
@isTest
private class generatemoreload_test {

    static testMethod void myUnitTest(){
    	Account testAcct = TestData.setupAccount();
    	Contact testContact = TestData.setupContact();
    	insert testAcct;
    	insert testContact;
    	Opportunity testOppty = TestData.setupOpportunity(testAcct, testContact);
    	testOppty.Implementation_Contact__c = testContact.Id;
    	testOppty.Load_Counter__c = 4;
    	insert testOppty;
    	Product2 testProduct = TestData.getProduct();
    	testProduct.Subject_to_Load__c = true;
    	insert testProduct;
    	PricebookEntry testPBE = TestData.setupPricebookEntry(testProduct);
    	insert testPBE;
    	Product_Process__c testProcess = TestData.getProductProcess(testProduct);
        testProcess.Milestone_1__c = '';
        testProcess.Milestone_1_Stage__c = '';
    	insert testProcess;
    	SFDC_520_Quote__c testProject = TestData.setupProject(testOppty);
    	insert testProject;
    	OpportunityLineItem testOLI = TestData.setupOpportunityLineItem(testPBE, testOppty);
    	testOLI.Override_Related_Product__c = true;

		ApexPages.currentPage().getParameters().put('opportunityId', testOppty.Id);
		
		//Set your controller
		generatemoreload cont = new generatemoreload();
		
		test.startTest();
		insert testOLI;
		cont.backToOpp();
		cont.nullPR();
		cont.checkLoadToGenerate();
		
		//cont.opportunity.Load_Counter__c = 4;
		cont.amountToGenerate = 5;
		cont.availableLoad = 10;
        cont.doLoad();
        testProcess.Milestone_1__c = 'Test1';
        testProcess.Milestone_1_Stage__c = 'Introduction';
        update testProcess;
        cont.doLoad();
        testProcess.Milestone_2__c = 'Test2';
        testProcess.Milestone_2_Stage__c = 'Introduction';
        update testProcess;
        cont.doLoad();
        testProcess.Milestone_3__c = 'Test3';
        testProcess.Milestone_3_Stage__c = 'Introduction';
        update testProcess;
        cont.doLoad();
        testProcess.Milestone_4__c = 'Test4';
        testProcess.Milestone_4_Stage__c = 'Introduction';
        update testProcess;
        cont.doLoad();
        testProcess.Milestone_5__c = 'Test5';
        testProcess.Milestone_5_Stage__c = 'Introduction';
        update testProcess;
        cont.doLoad();
        testProcess.Milestone_6__c = 'Test6';
        testProcess.Milestone_6_Stage__c = 'Introduction';
        update testProcess;
        cont.doLoad();
        testProcess.Milestone_7__c = 'Test7';
        testProcess.Milestone_7_Stage__c = 'Introduction';
        update testProcess;
        cont.doLoad();
        testProcess.Milestone_8__c = 'Test8';
        testProcess.Milestone_8_Stage__c = 'Introduction';
        update testProcess;
        cont.doLoad();
        testProcess.Milestone_9__c = 'Test9';
        testProcess.Milestone_9_Stage__c = 'Introduction';
        update testProcess;
        cont.doLoad();
        testProcess.Milestone_10__c = 'Test10';
        testProcess.Milestone_10_Stage__c = 'Introduction';
        update testProcess;
        cont.doLoad();
        testProcess.Milestone_3__c = 'Test3';
        testProcess.Milestone_3_Stage__c = 'Introduction';
        update testProcess;
        cont.doLoad();
		
		test.stopTest();
    }
    
     
}