objects/PAN__c.object
<CustomObject>
    <description>PAN= Personnel Action Notice - used to manage new hires, changes to existing employees and separation of employees</description>
    <fields>
        <fullName>Bonus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bonus</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Commission_to_Non_Commission__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Commission to Non Commission</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Department__c</fullName>
        <formula>Vin_Employee__r.Department</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Department</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Manager__c</fullName>
        <formula>Vin_Employee__r.Reports_To__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Role__c</fullName>
        <formula>Vin_Employee__r.UserRole.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Salary__c</fullName>
        <label>Current Salary</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Title__c</fullName>
        <formula>Vin_Employee__r.Title</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Demotion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Demotion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Department_Change__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Department Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>HY17691000 HY Ad Ops - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17676000 HY Ad Ops - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17690000 HY Content - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17675000 HY Content - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17697000 HY Development - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17682000 HY Development - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17698000 HY Executive - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17683000 HY Executive - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17687000 HY Finance - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17672000 HY Finance - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17699000 HY Human Resources - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17684000 HY Human Resources - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17696000 HY Implementation - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17681000 HY Implementation - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17688000 HY IT - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17673000 HY IT - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17671000 HY Marketing - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17686000 HY Marketing - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17692000 HY Operations - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17677000 HY Operations - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17695000 HY Performance Mgmnt - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17680000 HY Perform. Mgmnt - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17670000  HY Product - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17685000 HY Product - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17689000 HY Sales – SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17674000 HY Sales - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17693000 HY Support - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17678000 HY Support - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17694000 HY Training - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17679000 HY Training - Websites</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Exempt_to_Non_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exempt to Non Exempt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Home_Address__c</fullName>
        <description>Employee&apos;s home address.</description>
        <label>Home Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <description>Employee&apos;s job title.</description>
        <label>Job Title</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MI__c</fullName>
        <inlineHelpText>Middle Initial Only</inlineHelpText>
        <label>MI</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Job_Title__c</fullName>
        <description>To be used when a new job title is needed.</description>
        <inlineHelpText>To be used when a new job title is needed.</inlineHelpText>
        <label>New Job Title</label>
        <picklist>
            <picklistValues>
                <fullName>S1135 - Account Mgr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1171 - Accounting Associate I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1172 - Accounting Associate II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1002 - Accounts Receivable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1003 - Admin Assist Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1173 - Admin Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1214 - Application Support Mgr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1337 - Associate Data Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1264 – Associate Mgr, Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1254 - Assoc Mgr, Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1168 - Associate Program Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1260 - Assoc Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1169 - Associate Software Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1163 - Brand Coord</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1005 - Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1275 – Business Development Mgr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1335 - Certified Technician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1229 - Compliance Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1009 - Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1143 - Corporate Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1222 - Corporate Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1013 - Creative Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1014 - Creative Designer Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1106 - Creative Project Mgr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1177 - Cust. Service Rep II- Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1178 - Cust. Service Rep II- Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1176 - Customer Service Rep I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1162 - Data Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1124 - Database Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1225 - Dealer Relations Assistant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Non_Commission_to_Commission__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non Commission to Commission</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Non_Exempt_to_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non Exempt to Exempt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Promotion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Relocation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Relocation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reporting_Change__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reporting Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reports_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup manager the new employee will report to.</inlineHelpText>
        <label>Reports To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Department in which the employee will work within the company.</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Creative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Salary_Amount_Encrypted__c</fullName>
        <label>New Salary Amount</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Salary_Change__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Salary Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Change__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Title Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vin_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>look-up existing VinSolutions Employee to modify</inlineHelpText>
        <label>Vin Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Employees1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PAN</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAN</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <description>used to a request to add a new employee</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Home_Address__c</fullName>
        <description>Employee&apos;s Home Address</description>
        <inlineHelpText>Employee&apos;s Home Address</inlineHelpText>
        <label>Home Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MI__c</fullName>
        <label>MI</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reports_To__c</fullName>
        <formula>Manager.FirstName &amp;&quot; &quot;&amp; Manager.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reports To</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PanCustomController.cls
public with sharing class PanCustomController {
    public LIST<PersonnelChanges> personnelChangesList {get; set;}
    public PAN__c panForm {get; set;}
    String PANID {get; set;}
    public String EmpSalary {get; set;}
    public String SalChange {get; set;}
    
    public PageReference next(){
		
		PageReference nextPage = new PageReference('/apex/PanForm');  
		nextPage.setRedirect(False);
		return nextPage;
	}
	
	public PageReference next2(){
		PageReference nextPage = new PageReference('/apex/PanFormNotNewEmp');
		nextPage.setRedirect(False);
		return nextPage;
	}

    public PanCustomController(ApexPages.StandardController controller) {
		PANID = Apexpages.currentPage().getParameters().get('id');           
        setPanForm();
        setPersonnelChangesList();
    }
    
    public LIST<PersonnelChanges> getPersonnelChangesList(){
        if (personnelChangesList == null) setPersonnelChangesList();
        return personnelChangesList;
    }
    
    public PAN__c getPanForm(){
    	if (panForm == null) setPanForm();
    	return panForm;
    }
    public void setPanForm(){
    	panForm = new PAN__c();
    	panForm = [select Id, Relocation__c, Department_Change__c, Title_Change__c, Demotion__c, 
    					Reporting_Change__c, Salary_Change__c, Bonus__c, Commission_to_Non_Commission__c, 
    					Non_Commission_to_Commission__c, Non_Exempt_to_Exempt__c, Exempt_to_Non_Exempt__c,
    					Current_Department__c, Current_Manager__c, Current_Role__c, Current_Title__c, 
    					Department__c, Reports_To__c, Current_Salary__c, Salary_Amount_Encrypted__c,
    					Reports_To__r.Name, Role__c, Job_Title__c, Vin_Employee__r.Home_Address__c, New_Job_Title__c,
    					Promotion__c, MI__c, Justification__c 					
    					from Pan__c where Id =: PANID];
    					
    }
    public void setPersonnelChangesList(){
    	personnelChangesList = new LIST<PersonnelChanges>();    	
    	if (panForm.Relocation__c == true){
    		PersonnelChanges personnelChange = new PersonnelChanges();
    		personnelChange.ActionRequired = 'Relocation';
    		personnelChange.CurrentInformation = '';
    		personnelChange.NewInformation = '';
    		personnelChangesList.add(personnelChange);    	
    	}
    	if (panForm.Department_Change__c == true) {
    		PersonnelChanges personnelChange = new PersonnelChanges();
    		personnelChange.ActionRequired = 'Department Change';
    		personnelChange.CurrentInformation = panForm.Current_Department__c;
    		personnelChange.NewInformation = panForm.Department__c;
    		personnelChangesList.add(personnelChange);    	
    	}
    	if (panForm.Title_Change__c == true){
    		PersonnelChanges personnelChange = new PersonnelChanges();
    		personnelChange.ActionRequired = 'Title Change';
    		personnelChange.CurrentInformation = panForm.Current_Title__c;
    		personnelChange.NewInformation = panForm.New_Job_Title__c;
    		personnelChangesList.add(personnelChange);    	
    	}
    	if (panForm.Reporting_Change__c == true){
    		PersonnelChanges personnelChange = new PersonnelChanges();
    		personnelChange.ActionRequired = 'Reporting Change';
    		personnelChange.CurrentInformation = panForm.Current_Manager__c;
    		personnelChange.NewInformation = panForm.Reports_To__r.Name;
    		personnelChangesList.add(personnelChange);    	
    	}
    	if (panForm.Salary_Change__c == true){
    		PersonnelChanges personnelChange = new PersonnelChanges();
    		personnelChange.ActionRequired = 'Salary Change';
    		personnelChange.CurrentInformation = String.valueOf(panform.Current_Salary__c);
    		personnelChange.NewInformation = String.valueOf(panform.Salary_Amount_Encrypted__c);
    		personnelChangesList.add(personnelChange);    	
    	}
    	if (panForm.Bonus__c == true){
    		PersonnelChanges personnelChange = new PersonnelChanges();
    		personnelChange.ActionRequired = 'Bonus';
    		personnelChange.CurrentInformation = '';
    		personnelChange.NewInformation = '';
    		personnelChangesList.add(personnelChange);    	
    	}
    	if (panForm.Commission_to_Non_Commission__c == true){
    		PersonnelChanges personnelChange = new PersonnelChanges();
    		personnelChange.ActionRequired = 'Commission to Non Commission';
    		personnelChange.CurrentInformation = '';
    		personnelChange.NewInformation = '';
    		personnelChangesList.add(personnelChange);    	
    	}
    	if (panForm.Non_Commission_to_Commission__c == true){
    		PersonnelChanges personnelChange = new PersonnelChanges();
    		personnelChange.ActionRequired = 'Non Commission to Commission';
    		personnelChange.CurrentInformation = '';
    		personnelChange.NewInformation = '';
    		personnelChangesList.add(personnelChange);    	
    	}
    	if (panForm.Non_Exempt_to_Exempt__c == true){
    		PersonnelChanges personnelChange = new PersonnelChanges();
    		personnelChange.ActionRequired = 'Non Exempt to Exempt';
    		personnelChange.CurrentInformation = '';
    		personnelChange.NewInformation = '';
    		personnelChangesList.add(personnelChange);    	
    	}
    	if (panForm.Exempt_to_Non_Exempt__c == true){
    		PersonnelChanges personnelChange = new PersonnelChanges();
    		personnelChange.ActionRequired = 'Exempt to Non Exempt';
    		personnelChange.CurrentInformation = '';
    		personnelChange.NewInformation = '';
    		personnelChangesList.add(personnelChange);    	
    	}
    	if (panForm.Demotion__c == true){
    		PersonnelChanges personnelChange = new PersonnelChanges();
    		personnelChange.ActionRequired = 'Demotion';
    		personnelChange.CurrentInformation = '';
    		personnelChange.NewInformation = '';
    		personnelChangesList.add(personnelChange);    	
    	}
    	if (panForm.Promotion__c == true){
    		PersonnelChanges personnelChange = new PersonnelChanges();
    		personnelChange.ActionRequired = 'Promotion';
    		personnelChange.CurrentInformation = '';
    		personnelChange.NewInformation = '';
    		personnelChangesList.add(personnelChange);    	
    	}
    	if (personnelChangesList.isEmpty()){
    		PersonnelChanges personnelChange = new PersonnelChanges();
    		personnelChange.ActionRequired = 'No Changes';
    		personnelChange.CurrentInformation = 'No Changes';
    		personnelChange.NewInformation = 'No Changes';
    		personnelChangesList.add(personnelChange); 
    	}
    }
    
    public class PersonnelChanges{
        public String ActionRequired {get; set;}
        public String CurrentInformation {get; set;}
        public String NewInformation {get;  set;}
        
    }
}