objects/POA__c.object
<CustomObject>
    <description>used to handle Plan of Action items for an Account- gives the ability to group support or implementation issues together</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending PM Assignment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Intro Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Needs Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 1 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 2 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 3 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 4 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 5 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Week 6 Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation - LOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Churned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failure to Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>POA</label>
    <nameField>
        <label>Plan of Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POAs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Approval_Stage__c</fullName>
        <inlineHelpText>Updated by the system upon milestone completion</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>1-Initiating</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>2-Planning and Design</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>3-Executing</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>4-Review</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>5-Finalizing</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Launched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-ILM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GO LIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Intro Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Strategy Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Dealer Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <inlineHelpText>Uses the Opportunity&apos;s Product Suite and is updated by the Trigger</inlineHelpText>
        <label>Opp Product Suite</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_POA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup POA for this project</inlineHelpText>
        <label>Related POA</label>
        <referenceTo>POA__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>CASE( Approval_Stage__c , 
&quot;Go Live&quot;,&quot;Closed&quot;, 
&quot;Completed&quot;,&quot;Closed&quot;, 
&quot;Billable-Not Complete&quot;,&quot;Closed&quot;,
&quot;Cancelled&quot;,&quot;Closed&quot;,
&quot;No Launch&quot;,&quot;Closed&quot;,
&quot;Open&quot;)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/vAuto__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting will hold anything specific to vAuto BU.</description>
    <fields>
        <fullName>Conquest_Franchise_Setup_Task_Assignee__c</fullName>
        <defaultValue>&quot;jdougherty@vauto.com&quot;</defaultValue>
        <description>User with email be assignee for all &quot;Conquest Franchise Setup&quot; tasks created for conquest project.</description>
        <inlineHelpText>User with email be assignee for all &quot;Conquest Franchise Setup&quot; tasks created for conquest project.</inlineHelpText>
        <label>Conquest Franchise Setup Task Assignee</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Conquest_Monthly_Billing_EL_Assignee__c</fullName>
        <defaultValue>&quot;elliott.lerner@vauto.com&quot;</defaultValue>
        <description>User with this email will be the Assignee of Conquest Monthly Billing Task (EL) on conquest project.</description>
        <inlineHelpText>User with this email will be the Assignee of Conquest Monthly Billing Task (EL) on conquest project.</inlineHelpText>
        <label>Conquest Monthly Billing (EL) Assignee</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Conquest_Monthly_Billing_JT_Assingee__c</fullName>
        <defaultValue>&quot;jill.tyson@vauto.com&quot;</defaultValue>
        <description>User with this email will be the Asignee for Conquest Monthly Billing Task (JT) task on conquest project.</description>
        <inlineHelpText>User with this email will be the Asignee for Conquest Monthly Billing Task (JT) task on conquest project.</inlineHelpText>
        <label>Conquest Monthly Billing (JT) Assingee</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Conquest_Monthly_Billing_MM_Assignee__c</fullName>
        <defaultValue>&quot;mmorrissey@vauto.com.fulltest&quot;</defaultValue>
        <description>User with this email will be the Assignee of Conquest Monthly Billing Task (MM) on conquest project.</description>
        <inlineHelpText>User with this email will be the Assignee of Conquest Monthly Billing Task (MM) on conquest project.</inlineHelpText>
        <label>Conquest Monthly Billing (MM) Assignee</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Conquest_Verification_C_Task_Assignee__c</fullName>
        <defaultValue>&quot;mwheet@vauto.com&quot;</defaultValue>
        <description>User with email be assignee for all &quot;Conquest Verification C&quot; tasks created for conquest project.</description>
        <inlineHelpText>User with email be assignee for all &quot;Conquest Verification C&quot; tasks created for conquest project.</inlineHelpText>
        <label>Conquest Verification C - Task Assignee</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Training_1_Conquest_Task_Assignee__c</fullName>
        <defaultValue>&quot;jdougherty@vauto.com&quot;</defaultValue>
        <description>The user with this email will be the Assignee for all &quot;Training 1 Conquest &quot; Tasks on conquest project.</description>
        <inlineHelpText>The user with this email will be the Assignee for all &quot;Training 1 Conquest &quot; Tasks on conquest project.</inlineHelpText>
        <label>Training 1 Conquest Task Assignee</label>
        <type>Email</type>
    </fields>
    <label>vAuto</label>
</CustomObject>

classes/TaskHandler.cls
public  class TaskHandler {
  // context-specific methods to implement  
  public void beforeInsert(Task t){}
  public  void beforeUpdate(Task newT, Task oldT){}
  public  void beforeDelete(Task t){}
  public  void afterInsert(Task t){}
  public  void afterUpdate(Task newT, Task oldT){
  	System.debug('New Task Subject:'+newT.Subject);
  	System.debug('New Task Status:'+newT.Status);
  	System.debug('Old Task Subject:'+oldT.Subject);
  	System.debug('Old Task Status:'+oldT.Status);
	if (newT.Subject != null)
	{
		//only if it is a project task
		
	
		
		if(newT.WhatId != null && Schema.SFDC_520_Quote__c.SObjectType == newT.WhatId.getSobjectType()){	
		if(newT.subject.StartsWith('* Integration C -')&&( newT.Status=='Completed' && oldT.Status !='Completed'))
		{			
			
			String subject = newT.subject.replace('* Integration C -','* Conquest Franchise Setup -');
		
			//get assignee user from custom setttings			
			String assigneeEmail = vAuto__c.getOrgDefaults().Conquest_Franchise_Setup_Task_Assignee__c;
			List<User> users = [Select Id from User where email =:assigneeEmail];	
			Id assigneeUserId = newT.OwnerId;
			if(users!= null && users.size() > 0){
				assigneeUserId = users[0].Id;
			}	
			
			//get the assigned user from the task '* Advance Setup Call  – ' 
			String serSubject = newT.subject.replace('* Integration C -','* Advance Setup Call  –');
			
			List<Task> advSetupTasks = [Select Id,ownerId from Task where subject =:serSubject and whatId =: newT.whatId];
			if(advSetupTasks == null || advSetupTasks.size() == 0){
				//If there is no Advance Setup Call created use what ever the setting is 
				//use what was got from settings
				system.debug('No Advance Call task found with subject:'+serSubject);
			}
			else{
				//use from Advance Setup Call ownerId
				assigneeUserId = advSetupTasks[0].ownerId;
			}
			
			
			
			CreateTask(subject, 0,assigneeUserId,newT.whatId,newT.WhoId,'Not Started');
		}
		else if(newT.subject.StartsWith('* Conquest Franchise Setup -')&&( newT.Status=='Completed' && oldT.Status !='Completed'))
		{	
			
			String subject = newT.subject.replace('* Conquest Franchise Setup -','* Verification C -');
			//get assignee user from custom setttings			
			String assigneeEmail = vAuto__c.getOrgDefaults().Conquest_Verification_C_Task_Assignee__c;
			List<User> users = [Select Id from User where email =:assigneeEmail];	
			Id assigneeUserId = newT.OwnerId;
			if(users!= null && users.size() > 0){
				assigneeUserId = users[0].Id;
			}			
			CreateTask(subject, 0,assigneeUserId,newT.whatId,newT.WhoId,'Not Started');
			
			
			subject = newT.subject.replace('* Conquest Franchise Setup -','* Training 1 Conquest –');
			assigneeUserId = newT.OwnerId;
			//get assignee user from custom setttings			
			/*assigneeEmail = vAuto__c.getOrgDefaults().Training_1_Conquest_Task_Assignee__c;
			users = [Select Id from User where email =:assigneeEmail];	
			
			if(users!= null && users.size() > 0){
				assigneeUserId = users[0].Id;
			}*/			
			CreateTask(subject, 0,assigneeUserId,newT.whatId,newT.WhoId,'Not Started');
		}
		
			//CR-00012029; Looks like migrated seems to have non-printable characters that is not matching 
			//so matching on '* Training 1 Conquest' instaed of : '* Training 1 Conquest –'
		else if (newT.subject.StartsWith('* Training 1 Conquest') && ( newT.Status=='Completed' && oldT.Status !='Completed'))
		{	

		   System.debug('Task subject starts with:* Training 1 Conquest; and it is Completed'); 
			
		   //Get the project
		   SFDC_520_Quote__c proj = [Select Id, Status__c,Project_Type__c,Approval_Stage__c
		   ,Related_POA__r.OwnerId, Related_POA__c
		   from SFDC_520_Quote__c where id =: newT.WhatId]; 

		   //create Training2 Task if proj.Project_Type__c == 'Conquest Stand-Alone'
		   if(proj.Project_Type__c == 'Conquest Stand-Alone'){
		   	  String trainingTask2Subject = newT.subject.replace('* Training 1 Conquest','* Training 2 Conquest');
		   		CreateTask(trainingTask2Subject, 0,newT.OwnerId,newT.whatId,newT.WhoId,'Not Started');
		   }

			String subject = newT.subject.replace('* Training 1 Conquest','* Conquest Monthly Billing Task (MM)');
			//get assignee user from custom setttings			
			String assigneeEmail = vAuto__c.getOrgDefaults().Conquest_Monthly_Billing_MM_Assignee__c;
			List<User> users = [Select Id from User where email =:assigneeEmail and IsActive = true];	
			Id assigneeUserId = newT.OwnerId;
			if(users!= null && users.size() > 0){
				assigneeUserId = users[0].Id;
			}			
			CreateTask(subject, 0,assigneeUserId,newT.whatId,newT.WhoId,'Not Started');
			
			
			subject = newT.subject.replace('* Training 1 Conquest','* Conquest Monthly Billing Task (JT)');
			//get assignee user from custom setttings			
			assigneeEmail = vAuto__c.getOrgDefaults().Conquest_Monthly_Billing_JT_Assingee__c;
			users = [Select Id from User where email =:assigneeEmail];	
			assigneeUserId = newT.OwnerId;
			if(users!= null && users.size() > 0){
				assigneeUserId = users[0].Id;
			}			
			CreateTask(subject, 0,assigneeUserId,newT.whatId,newT.WhoId,'Not Started');
			
			
			subject = newT.subject.replace('* Training 1 Conquest','* Conquest Monthly Billing Task (EL)');
			//get assignee user from custom setttings			
			assigneeEmail = vAuto__c.getOrgDefaults().Conquest_Monthly_Billing_EL_Assignee__c;
			users = [Select Id from User where email =:assigneeEmail];	
			assigneeUserId = newT.OwnerId;
			if(users!= null && users.size() > 0){
				assigneeUserId = users[0].Id;
			}			
			CreateTask(subject, 0,assigneeUserId,newT.whatId,newT.WhoId,'Not Started');
			
			
			subject = newT.subject.replace('* Training 1 Conquest –','* 1st Conquest PM Review Call -');
			//get assignee user from project POA
			SFDC_520_Quote__c project = [Select Id, Related_POA__c,Related_POA__r.OwnerId from SFDC_520_Quote__c where Id =:newT.WhatId];			
			CreateTask(subject, 0,project.Related_POA__r.OwnerId,project.Related_POA__c,newT.WhoId,'Not Started');
			
		}
		else{
			system.debug('Project Task did not match any criteria to handle');			
		}
		}
		
		//POA Task
		if(newT.WhatId != null &&  Schema.POA__c.SObjectType == newT.WhatId.getSobjectType()){	
		if(newT.subject.StartsWith('* 1st Conquest PM Review Call -')&&( newT.Status=='Completed' && oldT.Status !='Completed'))
		{	
			String subject = newT.subject.replace('* 1st Conquest PM Review Call -','* 2nd Conquest PM Review Call -');
			CreateTask(subject, 0,newT.OwnerId,newT.WhatId,newT.WhoId,'Not Started');
		}		
		else if(newT.subject.StartsWith('* 2nd Conquest PM Review Call -')&&( newT.Status=='Completed' && oldT.Status !='Completed'))
		{	
			String subject = newT.subject.replace('* 2nd Conquest PM Review Call -','* 3rd Conquest PM Review Call -');
			CreateTask(subject, 0,newT.OwnerId,newT.WhatId,newT.WhoId,'Not Started');
		}
		else if(newT.subject.StartsWith('* 3rd Conquest PM Review Call -')&&( newT.Status=='Completed' && oldT.Status !='Completed'))
		{	
			String subject = newT.subject.replace('* 3rd Conquest PM Review Call -','* 4th Conquest PM Review Call -');
			CreateTask(subject, 0,newT.OwnerId,newT.WhatId,newT.WhoId,'Not Started');
		}
		}		
	}				
  }
  public  void afterDelete(Task t){}
  public  void afterUndelete(Task t){}
  
  
     public Static void CreateTask(String subject, Integer dueInDays, Id ownerId, Id whatId, Id whoId, String status){
   	system.debug('Creating Task: subject: '+subject + ' ownerId: '+ownerId +'whatId: '+whatId +' whoId: '+whoId + 'status: '+status);
   	      //check if the task created
      List<Task> tasks = [Select Id from Task where 
      ownerId=:ownerId
      and whatId=:whatId
      and Subject =: subject
      and Status =: status
      and WhoId =: whoId];
      
      if(tasks == null || tasks.size() == 0){
		Task task = new Task();
		task.Subject =  subject;
		task.ActivityDate = System.today().addDays(dueInDays);
		task.OwnerId = ownerId;
		task.WhatId = whatId;
		task.WhoId = whoId;
		insert task;		
      }
     }
  
}