objects/Product_Process__c.object
<CustomObject>
    <label>Product Process</label>
    <nameField>
        <label>Product Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Product_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup the contact at the dealership related to this specific product and assign to piece</inlineHelpText>
        <label>Product Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Pieces (Contact)</relationshipLabel>
        <relationshipName>Product_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Piece_Issue__c</fullName>
        <inlineHelpText>Auto-populated from Products sold when Opportunity marked PAID</inlineHelpText>
        <label>Piece Issue</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <inlineHelpText>automatically populated from the Opportunity Products Sold</inlineHelpText>
        <label>Product Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>look up Product to assign the milestone and stages for the product process</inlineHelpText>
        <label>Product Process</label>
        <referenceTo>Product_Process__c</referenceTo>
        <relationshipLabel>Project Pieces</relationshipLabel>
        <relationshipName>Project_Pieces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Piece_Stage__c</fullName>
        <label>Project Asset Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Travel Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer&apos;s Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Website Approval-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Shipment Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing/Shipping/Uploading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial QA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Runner__c.object
<CustomObject>
    <description>used to move Project Pieces departmentally</description>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <inlineHelpText>Time to set even date/time for the Designer</inlineHelpText>
        <label>Event Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <label>Event End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Piece_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to owner</description>
        <label>Project Piece Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Runners1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Normal</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Project_Piece__r.Product_Name__c</formula>
        <inlineHelpText>formula field that reads the product name from the related project piece</inlineHelpText>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Piece_Stage__c</fullName>
        <formula>IF( ISPICKVAL(Project_Piece__r.Project_Piece_Stage__c, &quot;Completed&quot;),&quot;Completed&quot;, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>formula field - looks at the project piece stage and if Completed, shows Completed otherwise the field is blank</inlineHelpText>
        <label>Project Piece Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Piece__c</fullName>
        <label>Project Piece</label>
        <referenceTo>Project_Piece__c</referenceTo>
        <relationshipLabel>Project Runners</relationshipLabel>
        <relationshipName>Project_Runners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Run_To__c</fullName>
        <label>Run To</label>
        <picklist>
            <picklistValues>
                <fullName>Creative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Runner_Action__c</fullName>
        <label>Runner Action</label>
        <picklist>
            <picklistValues>
                <fullName>Go Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Pull</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pull Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Start</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Runner_Type__c</fullName>
        <label>Runner Type</label>
        <picklist>
            <picklistValues>
                <fullName>All Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PBX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Runner</label>
    <nameField>
        <displayFormat>PR-{0000000000}</displayFormat>
        <label>Project Runner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Runners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Business_Unit__c</field>
                <operation>equals</operation>
                <valueField>$User.Business_Unit_for_Contact_Filter__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (Contact)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DataIntegrationController.cls
public with sharing class DataIntegrationController { 
    
    private final ApexPages.Standardcontroller controller;
    Id id;
    public String notes {get; set;}
    public String requestType {get; set;}
    public SFDC_520_Quote__c thisProject = new SFDC_520_Quote__c();
    public Boolean pieceExists;
    public Project_Piece__c dataIntegrationPiece = new Project_Piece__c();
    public LIST<Selectoption> requestOptions = new LIST<SelectOption>();
    public Account thisAccount = new Account();
    public LIST<Project_Runner__c> pieceRunnerHistory = new LIST<Project_Runner__c>();

    public DataIntegrationController(ApexPages.Standardcontroller controller){
        this.controller = controller;
        id = Apexpages.currentPage().getParameters().get('id');
        thisProject = [select id, OwnerId, Account__c, Contact__c, Name from SFDC_520_Quote__c where id =: id];
        thisAccount = [select id, OwnerId, Name from Account where id =: thisProject.Account__c limit 1];
    }
    
    public Id getId(){
        id = Apexpages.currentPage().getParameters().get('id');
        return id;
    }
    
    public Account getThisAccount(){
        return thisAccount;
    }
    
    public SFDC_520_Quote__c getThisProject(){
        return thisProject;
    }
    
    
    public String getNotes(){
    //------- Getter/Setter for notes
    
        return notes;
    }
    
    public String getRequestType(){
    //------- Getter/Setter for requestType
    
        return requestType; 
    }
    
    public LIST<Selectoption> getRequestOptions(){
       //update code here!
      sObject pr = new Project_Runner__c();
       
       return getPickValues(pr, 'Runner_Type__c', '');
       
    
    
    }
    
    public LIST<Project_Runner__c> getPieceRunnerHistory(){
        pieceRunnerHistory = [select id, CreatedDate, Run_To__c, Runner_Action__c, Runner_Type__c from Project_Runner__c where project_Piece__c =: dataIntegrationPiece.Id order by CreatedDate DESC];
        return pieceRunnerHistory;

    }
    
    

    public void setNotes (String theseNotes){
        notes = theseNotes; 
    }
    
    public void setRequestType (String thisRequest){
        requestType = thisRequest;
    }
    
    public boolean getPieceExists(){
        boolean hasDataIntegration = false;
        LIST <Project_Piece__c> thesePieces = [select id, OwnerId, Project__c, Name, Piece_Issue__c from Project_Piece__c where Project__c =: id];

        for (Project_Piece__c thisPiece: thesePieces){
            string thisPieceName = thisPiece.Name.toLowerCase();
            string thisPieceIssue = thisPiece.Piece_Issue__c.toLowerCase();
            if (thisPieceName.contains('data integration') || thisPieceIssue.contains('data integration')) {
                dataIntegrationPiece = thisPiece;
                hasDataIntegration = true;
            }       
            system.debug(thisPiece.Name);   
        }
        if (hasDataIntegration) return true;
        else return false;          
    }
    
    
    public Pagereference generateProjectPiece(){       
        PageReference projectPage = new ApexPages.StandardController(thisProject).view();
                
        Product2 thisProduct = [select id, Name from Product2 where Name =: 'Data Integration' limit 1];
        Product_Process__c thisProductProcess = [select id, OwnerId, Name from Product_Process__c where Name =: 'Data Integration' limit 1];             
        
                
        Datetime dateTimeTemp = System.now();
		Date dateTemp = Date.newInstance(dateTimeTemp.year(), dateTimeTemp.month(), dateTimeTemp.day());
		String x = dateTemp.format();
        
        Project_Piece__c newProjectPiece = new Project_Piece__c();
        newProjectPiece.Project__c = thisProject.Id;
        newProjectPiece.Piece_Issue__c = 'PP-Data Integration -' + thisAccount.Name + ' - ' + system.now();
        newProjectPiece.Name = 'PP-Data Integration -' + thisAccount.Name + ' - ' + x;
        newProjectPiece.Product_Name__c = thisProduct.Name;
        newProjectPiece.Product_Process__c = thisProductProcess.Id; 
        newProjectPiece.Account__c = thisAccount.Id;
        newProjectPiece.Contact__c = thisProject.Contact__c;
        newProjectPiece.Project_Piece_Stage__c = 'Introduction';
    
        insert newProjectPiece;
             
        Project_Runner__c newRunner = new Project_Runner__c();
        newRunner.Project_Piece__c = newProjectPiece.Id;
        newRunner.Run_To__c = 'Integration';
        newRunner.Runner_Action__c = 'Request';
        newRunner.Runner_Type__c = requestType;
        newRunner.Comments__c = notes;
        newRunner.Piece_Owner__c = dataIntegrationPiece.OwnerId;
        newRunner.Priority__c = '3 - Normal';
 		
 		if (requestType == 'Comp'){
	        newRunner.Event_Date_Time__c = system.now();
	        newRunner.Event_End_Date_Time__c = system.now() + 120;
        }
        
        insert newRunner; 

        
                
        return projectPage;
    }
    
    
        
    public Pagereference updateProjectPiece(){
        PageReference projectPage = new ApexPages.StandardController(thisProject).view();
        
        Project_Runner__c newRunner = new Project_Runner__c();
        newRunner.Project_Piece__c = dataIntegrationPiece.Id;
        newRunner.Run_To__c = 'Integration';
        newRunner.Runner_Action__c = 'Request';
        newRunner.Runner_Type__c = requestType;
        newRunner.Comments__c = notes;
        newRunner.Piece_Owner__c = dataIntegrationPiece.OwnerId;
        newRunner.Priority__c = '3 - Normal';
        
        if (requestType == 'Comp'){
	        newRunner.Event_Date_Time__c = system.now();
	        newRunner.Event_End_Date_Time__c = system.now() + 120;
        }
        insert newRunner; 
        
        return projectPage;
    } 
    

    
    public Pagereference returnToProject(){
        PageReference projectPage = new ApexPages.StandardController(thisProject).view();
        return projectPage;
    }
    
    public Pagereference goToPiece(){
        pageReference dataPiecePage = new ApexPages.StandardController(dataIntegrationPiece).view();
        return dataPiecePage;
    }
    
    public List<selectOption> getPickValues(Sobject object_name, String field_name, String first_val) {
      List<selectOption> options = new List<selectOption>(); //new list for holding all of the picklist options
      if (first_val != null) { //if there is a first value being provided
         options.add(new selectOption(first_val, first_val)); //add the first option
      }
      Schema.sObjectType sobject_type = object_name.getSObjectType(); //grab the sobject that was passed
      Schema.DescribeSObjectResult sobject_describe = sobject_type.getDescribe(); //describe the sobject
      Map<String, Schema.SObjectField> field_map = sobject_describe.fields.getMap(); //get a map of fields for the passed sobject
      List<Schema.PicklistEntry> pick_list_values = field_map.get(field_name).getDescribe().getPickListValues(); //grab the list of picklist values for the passed field on the sobject
      for (Schema.PicklistEntry a : pick_list_values) { //for all values in the picklist list
         options.add(new selectOption(a.getLabel(), a.getValue())); //add the value and label to our final list
      }
      return options; //return the List
   }

}