objects/Product_Process__c.object
<CustomObject>
    <label>Product Process</label>
    <nameField>
        <label>Product Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UnitTestUtilities__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to help make code coverage easier.</description>
    <fields>
        <fullName>UnitTestAccountId__c</fullName>
        <label>UnitTestAccountId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestContactId__c</fullName>
        <label>UnitTestContactId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestOppRecordTypeId__c</fullName>
        <label>UnitTestOppRecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestPBEid__c</fullName>
        <label>UnitTestPBEid</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestPriceBookId__c</fullName>
        <label>UnitTestPriceBookId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestProduct2Id__c</fullName>
        <label>UnitTestProduct2Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitTestProjectRecordTypeImp__c</fullName>
        <label>UnitTestProjectRecordTypeImp</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>UnitTestUtilities</label>
</CustomObject>

classes/DataIntegrationController_TEST.cls
@isTest(SeeAllData=true)
private class DataIntegrationController_TEST {

    static testMethod void DataIntegrationController_TestMethod() {

        UnitTestUtilities__c testId = UnitTestUtilities__c.getValues('UnitTestIds');
        String acctId = testId.UnitTestAccountId__c;
		String rtId = testId.UnitTestOppRecordTypeId__c;
		String conId = testId.UnitTestContactId__c;
		String pbeId = testId.UnitTestPBEid__c;
		String pbId = testId.UnitTestPriceBookId__c;
		String prod2 = testId.UnitTestProduct2Id__c;
		String projRtIdImp = testId.UnitTestProjectRecordTypeImp__c;
        
        Opportunity O = new Opportunity();
        O.AccountId = acctId;
        O.Name = 'Test';
        O.CloseDate = system.today();
        O.StageName = 'Prospect';
        insert O;
    
        SFDC_520_Quote__c Proj = new SFDC_520_Quote__c();
        Proj.Account__c = acctId;
        Proj.Opportunity__c = O.Id;
        insert Proj;
        
        Product2 p = new Product2();
        p.name = 'Data Integration';
        insert p;
        
        Product_Process__c pp = new Product_Process__c();
        pp.name = 'Data Integration';
        insert pp;
        
        PageReference testStart = Page.Data_Integration;
        Test.setCurrentPage(testStart);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(Proj);
        ApexPages.currentPage().getParameters().put('id', Proj.Id);
        
       DataIntegrationController DI = new DataIntegrationController(controller);
       
       Id Id = DI.getId();
       SFDC_520_Quote__c testProj = DI.getThisProject();
       Account testAccount = DI.getThisAccount();
       boolean pieceExists = DI.getPieceExists();
       DI.generateProjectPiece();
       pieceExists = DI.getPieceExists();
       
       DI.setRequestType('Inventory');
       DI.updateProjectPiece();
       sObject sObj = o;
        
       List<selectOption> options = DI.getPickValues(sObj, 'StageName', 'Something');
       string notes = DI.getNotes();
       DI.setNotes(notes);
       DI.getRequestType();
       DI.getRequestOptions();
       DI.getPieceRunnerHistory();
       DI.getThisProject();
       DI.goToPiece();
       DI.returnToProject();
       
        
    }
}