objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Assigned_Designer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Designer assigned from the Project Runner</inlineHelpText>
        <label>Assigned Designer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Pieces5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Comp_Requested__c</fullName>
        <description>Date a Comp was requested</description>
        <label>Date Comp Requested</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_1_Completed__c</fullName>
        <label>Milestone 1 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_1__c</fullName>
        <formula>Product_Process__r.Milestone_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milestone 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_2_Completed__c</fullName>
        <label>Milestone 2 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_2__c</fullName>
        <formula>Product_Process__r.Milestone_2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milestone 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_3_Completed__c</fullName>
        <label>Milestone 3 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_3__c</fullName>
        <formula>Product_Process__r.Milestone_3__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milestone 3</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_4_Completed__c</fullName>
        <label>Milestone 4 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_4__c</fullName>
        <formula>Product_Process__r.Milestone_4__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milestone 4</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_5_Completed__c</fullName>
        <label>Milestone 5 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_5__c</fullName>
        <formula>Product_Process__r.Milestone_5__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milestone 5</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_6_Completed__c</fullName>
        <label>Milestone 6 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_6__c</fullName>
        <formula>Product_Process__r.MIlestone_6__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milestone 6</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Piece_Stage__c</fullName>
        <label>Project Asset Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Travel Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer&apos;s Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Website Approval-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Shipment Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing/Shipping/Uploading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial QA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage_Type__c</fullName>
        <label>Stage Type</label>
        <picklist>
            <controllingField>Project_Piece_Stage__c</controllingField>
            <picklistValues>
                <fullName>Add&apos;l Information Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add&apos;l Information Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build in Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Reviewed Internally</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Reviewed w/Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Revisions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Revisions Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content QA Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content QA Corrections Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content QA Corrections in Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design QA Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design QA Corrections Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design QA Corrections in Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final QA Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final QA Corrections Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final QA Corrections Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final QA Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Content QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Design QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Dealer Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Design Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revisions Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revisions in Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Runner__c.object
<CustomObject>
    <description>used to move Project Pieces departmentally</description>
    <fields>
        <fullName>Designer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assign To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>Website, Design, Creative, Integration, Marketing, SEO, SEM, SMM</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Runners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <inlineHelpText>Time to set even date/time for the Designer</inlineHelpText>
        <label>Event Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_End_Date_Time__c</fullName>
        <label>Event End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project_Piece_Stage__c</fullName>
        <formula>IF( ISPICKVAL(Project_Piece__r.Project_Piece_Stage__c, &quot;Completed&quot;),&quot;Completed&quot;, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>formula field - looks at the project piece stage and if Completed, shows Completed otherwise the field is blank</inlineHelpText>
        <label>Project Piece Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Piece__c</fullName>
        <label>Project Piece</label>
        <referenceTo>Project_Piece__c</referenceTo>
        <relationshipLabel>Project Runners</relationshipLabel>
        <relationshipName>Project_Runners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Runner_Action__c</fullName>
        <label>Runner Action</label>
        <picklist>
            <picklistValues>
                <fullName>Go Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Pull</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pull Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Start</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Runner_Type__c</fullName>
        <label>Runner Type</label>
        <picklist>
            <picklistValues>
                <fullName>All Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PBX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Runner</label>
    <nameField>
        <displayFormat>PR-{0000000000}</displayFormat>
        <label>Project Runner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Runners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdatePieceStage.cls
public with sharing class UpdatePieceStage {
	
	public static void updatePieceStage(Project_Runner__c r)
	{
		Project_Piece__c p = [select Id, Stage_Type__c from Project_Piece__c where Id = : r.Project_Piece__c limit 1];
		
		List <Event> ev = [Select  WhoId, WhatId, StartDateTime, OwnerId, Id, CreatedById, EndDateTime, Created_Date_Time__c From Event Where WhatId =: p.Id ORDER BY Created_Date_Time__c DESC];
		
		integer eventDifference = 120;
		
		
		if (r.Runner_Action__c=='Request' && r.Runner_Type__c == 'Comp')
		{
			p.Stage_Type__c = 'Comp Requested';
			p.Project_Piece_Stage__c = 'Design';
			p.Date_Comp_Requested__c = system.today();
			
		if (ev.size() > 0) {
				
			if ((ev[0].StartDateTime != r.Event_Date_Time__c) || (ev[0].OwnerId != r.Designer__c)){
			Event e = new Event();
			
			if (r.Designer__c != null) e.OwnerId = r.Designer__c;
			else e.OwnerId = '00570000001doz3';
			
			if (r.Designer__c != null) p.Assigned_Designer__c = r.Designer__c;
			
			e.Subject = '*Comp Design ';
			e.WhatId = p.Id;
			e.StartDateTime = r.Event_Date_Time__c;
			e.EndDateTime = r.Event_End_Date_Time__c;
			//if (r.Event_End_Date_Time__c != null) e.EndDateTime = r.Event_End_Date_Time__c;
			//else e.DurationInMinutes = 120;
			
			insert e;
			}
			
		} else {
			
			Event e = new Event();
			
			if (r.Designer__c != null) e.OwnerId = r.Designer__c;
			else e.OwnerId = '00570000001doz3';
			
			if (r.Designer__c != null) p.Assigned_Designer__c = r.Designer__c;
			
			e.Subject = '*Comp Design ';
			e.WhatId = p.Id;
			e.StartDateTime = r.Event_Date_Time__c;
			//e.EndDateTime = r.Event_End_Date_Time__c;
			if (r.Event_End_Date_Time__c != null) e.EndDateTime = r.Event_End_Date_Time__c;
			else e.DurationInMinutes = 120;
			
			insert e;
			
			
		}
		
		
		
			
			if (p.Milestone_1__c == 'Requirements Gathered') p.Milestone_1_Completed__c = system.today();
			if (p.Milestone_2__c == 'Requirements Gathered') p.Milestone_2_Completed__c = system.today();
			if (p.Milestone_3__c == 'Requirements Gathered') p.Milestone_3_Completed__c = system.today();
			if (p.Milestone_4__c == 'Requirements Gathered') p.Milestone_4_Completed__c = system.today();
			if (p.Milestone_5__c == 'Requirements Gathered') p.Milestone_5_Completed__c = system.today();
			if (p.Milestone_6__c == 'Requirements Gathered') p.Milestone_6_Completed__c = system.today();
			if (p.Milestone_7__c == 'Requirements Gathered') p.Milestone_7_Completed__c = system.today();
			if (p.Milestone_8__c == 'Requirements Gathered') p.Milestone_8_Completed__c = system.today();
			if (p.Milestone_9__c == 'Requirements Gathered') p.Milestone_9_Completed__c = system.today();
			if (p.Milestone_10__c == 'Requirements Gathered') p.Milestone_10_Completed__c = system.today();
					
		}
		
		if (r.Runner_Action__c == 'Start' && r.Runner_Type__c == 'Comp')
		{
			p.Stage_Type__c = 'Comp in Progress';
			p.Date_Comp_Started__c = system.today();
		}		
		
		if (r.Runner_Action__c == 'Submit' && r.Runner_Type__c == 'Comp')
		{
			p.Stage_Type__c = 'Comp Completed';
			p.Date_Comp_Completed__c = system.today();
		}
		
		if (r.Runner_Action__c == 'Approve' && r.Runner_Type__c == 'Comp')
		{
			p.Stage_Type__c = 'Comp Approved';
			p.Date_Comp_Approved__c = system.today();
		}
		
		if (r.Runner_Action__c == 'Request' && r.Runner_Type__c == 'Revision')
		{
			p.Stage_Type__c = 'Revision Requested';
			p.Latest_Revisions_Requested__c = system.today();	
			p.Latest_Revisions_Completed__c = null;
			
				
			if (ev.size() > 0) {	
			
			if((ev[0].StartDateTime != r.Event_Date_Time__c) || (ev[0].OwnerId != r.Designer__c))	
			{
				
			Event e = new Event();
			if (r.Designer__c != null) e.OwnerId = r.Designer__c;
			else e.OwnerId = '00570000001doz3';
			
			if (r.Designer__c != null) p.Assigned_Designer__c = r.Designer__c;			
			
			e.Subject = '*Revision Request';
			e.WhatId = p.Id;
			e.StartDateTime = r.Event_Date_Time__c;
			e.EndDateTime = r.Event_End_Date_Time__c;
			insert e;		
			}
			
			} else { 
			
			
				
			
			Event e = new Event();
			if (r.Designer__c != null) e.OwnerId = r.Designer__c;
			else e.OwnerId = '00570000001doz3';
			
			if (r.Designer__c != null) p.Assigned_Designer__c = r.Designer__c;			
			
			e.Subject = '*Revision Request';
			e.WhatId = p.Id;
			e.StartDateTime = r.Event_Date_Time__c;
			e.EndDateTime = r.Event_End_Date_Time__c;
			insert e;
			}
		
		}
		
		if (r.Runner_Action__c == 'Start' && r.Runner_Type__c == 'Revision')
		{
			p.Stage_Type__c = 'Revision in Progress';
			p.Date_Revisions_Started__c = system.today();
		}
		
		if (r.Runner_Action__c == 'Submit' && r.Runner_Type__c == 'Revision')
		{
			p.Stage_Type__c = 'Revision Completed';
			p.Latest_Revisions_Completed__c = system.today();	
		}		
		
		if (r.Runner_Action__c == 'Request' && r.Runner_Type__c == 'Site' )
		{
			p.Stage_Type__c = 'Build Requested';
			p.Date_Build_Requested__c = system.today();
		
		if(ev.size() > 0)
		{
		if((ev[0].StartDateTime != r.Event_Date_Time__c) || (ev[0].OwnerId != r.Designer__c))	
		
		{
			Event e = new Event();

			if (r.Designer__c != null) e.OwnerId = r.Designer__c;
			else e.OwnerId = '00570000001eh38';
			
			if (r.Designer__c != null) p.Assigned_Designer__c = r.Designer__c;
			
			e.Subject = '*Build Requested ';
			e.WhatId = p.Id;			
			e.StartDateTime = r.Event_Date_Time__c;
			e.EndDateTime = r.Event_End_Date_Time__c;
			insert e;	
		}
		} else {
			Event e = new Event();

			if (r.Designer__c != null) e.OwnerId = r.Designer__c;
			else e.OwnerId = '00570000001eh38';
			
			if (r.Designer__c != null) p.Assigned_Designer__c = r.Designer__c;
			
			e.Subject = '*Build Requested ';
			e.WhatId = p.Id;			
			e.StartDateTime = r.Event_Date_Time__c;
			e.EndDateTime = r.Event_End_Date_Time__c;
			insert e;	

		
		}
		
			if (p.Milestone_1__c == 'Proof Approved') p.Milestone_1_Completed__c = system.today();
			if (p.Milestone_2__c == 'Proof Approved') p.Milestone_2_Completed__c = system.today();
			if (p.Milestone_3__c == 'Proof Approved') p.Milestone_3_Completed__c = system.today();
			if (p.Milestone_4__c == 'Proof Approved') p.Milestone_4_Completed__c = system.today();
			if (p.Milestone_5__c == 'Proof Approved') p.Milestone_5_Completed__c = system.today();
			if (p.Milestone_6__c == 'Proof Approved') p.Milestone_6_Completed__c = system.today();
			if (p.Milestone_7__c == 'Proof Approved') p.Milestone_7_Completed__c = system.today();
			if (p.Milestone_8__c == 'Proof Approved') p.Milestone_8_Completed__c = system.today();
			if (p.Milestone_9__c == 'Proof Approved') p.Milestone_9_Completed__c = system.today();
			if (p.Milestone_10__c == 'Proof Approved') p.Milestone_10_Completed__c = system.today();		
		}
		
		if (r.Runner_Action__c == 'Submit' && r.Runner_Type__c == 'Site')
		{
			p.Stage_Type__c = 'Build Completed';
			p.Date_Build_Completed__c = system.today();	
		}
		
		if (r.Runner_Action__c == 'Approve' && r.Runner_Type__c == 'Site')
		{
			p.Stage_Type__c = 'Build Approved';
			p.Date_Build_Approved__c = system.today();	
		}
		
		if (r.Runner_Action__c == 'Start' && r.Runner_Type__c == 'Site')
		{
			p.Stage_Type__c = 'Build in Progress';
			p.Date_Build_Started__c = system.today();
		}
		
		//end build
		
		if (r.Runner_Action__c == 'Request' && r.Runner_Type__c == 'Correction')
		{
			p.Stage_Type__c = 'Correction Requested';
			p.Latest_Revisions_Requested__c = system.today();	
			p.Latest_Revisions_Completed__c = null;
			
				
			if (ev.size() > 0) {	
			
			if((ev[0].StartDateTime != r.Event_Date_Time__c) || (ev[0].OwnerId != r.Designer__c))	
			{
				
			Event e = new Event();
			if (r.Designer__c != null) e.OwnerId = r.Designer__c;
			else e.OwnerId = '00570000001doz3';
			
			if (r.Designer__c != null) p.Assigned_Designer__c = r.Designer__c;			
			
			e.Subject = '*Correction Request';
			e.WhatId = p.Id;
			e.StartDateTime = r.Event_Date_Time__c;
			e.EndDateTime = r.Event_End_Date_Time__c;
			insert e;		
			}
			
			} else { 
			
			
				
			
			Event e = new Event();
			if (r.Designer__c != null) e.OwnerId = r.Designer__c;
			else e.OwnerId = '00570000001doz3';
			
			if (r.Designer__c != null) p.Assigned_Designer__c = r.Designer__c;			
			
			e.Subject = '*Correction Request';
			e.WhatId = p.Id;
			e.StartDateTime = r.Event_Date_Time__c;
			e.EndDateTime = r.Event_End_Date_Time__c;
			insert e;
			}
		
		}
		
		if (r.Runner_Action__c == 'Start' && r.Runner_Type__c == 'Correction')
		{
			p.Stage_Type__c = 'Correction in Progress';
			p.Date_Revisions_Started__c = system.today();
		}
		
		if (r.Runner_Action__c == 'Submit' && r.Runner_Type__c == 'Correction')
		{
			p.Stage_Type__c = 'CorrectionCompleted';
			p.Latest_Revisions_Completed__c = system.today();	
		}		
		
		
				
		update p;	
	}
	
	
	
	
}