objects/Project_Comment__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_Piece__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Piece</label>
        <referenceTo>Project_Piece__c</referenceTo>
        <relationshipLabel>Project Comments</relationshipLabel>
        <relationshipName>Project_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Comment</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Project Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProjComments_test.cls
@isTest
private class ProjComments_test {

    static testMethod void myUnitTest() {
        
	        Account testAcct = TestData.setupAccount();
	        Contact testContact = TestData.setupContact();
	        insert testAcct;
	        insert testContact;
	        Opportunity testOppty = TestData.setupOpportunity(testAcct, testContact);
	        insert testOppty;
	        SFDC_520_Quote__c testProject = TestData.setupProject(testOppty);
	        insert testProject;
	        Project_Piece__c testPP = TestData.setupProjectPiece(testProject);
	        insert testPP;
	        Project_Comment__c testComment = TestData.setupProComment(testProject, testPP);
	        insert testComment;
			
			Project_Comment__c[] pjcArray = new Project_Comment__c[]{testComment};
        	
        	//Set your controller
        	ProjComments controller = new ProjComments();
        	
        	test.startTest();
        	
        	ProjComments.UpdateLastComment(pjcArray);

        	test.stopTest();
    }
    
    
    static testMethod void myUnitTest2() {
        
        	Account testAcct = TestData.setupAccount();
	        Contact testContact = TestData.setupContact();
	        insert testAcct;
	        insert testContact;
	        Opportunity testOppty = TestData.setupOpportunity(testAcct, testContact);
	        insert testOppty;
	        SFDC_520_Quote__c testProject = TestData.setupProject(testOppty);
	        insert testProject;
	        Project_Piece__c testPP = TestData.setupProjectPiece(testProject);
	        insert testPP;
	        Project_Comment__c testComment = TestData.setupProComment(testProject, testPP);
	        testComment.Comments__c = 'testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest';
	        insert testComment;
			
			Project_Comment__c[] pjcArray = new Project_Comment__c[]{testComment};
        	
        	//Set your controller
        	ProjComments controller = new ProjComments();
        	
        	test.startTest();
        	
        	ProjComments.UpdateLastComment(pjcArray);

        	test.stopTest();
    }
}