objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Project_Owner_Email__c</fullName>
        <inlineHelpText>used to trigger workflow</inlineHelpText>
        <label>Project Owner Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>MS10_PP_Inventory__c</fullName>
        <label>Vector File Uploaded PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS1_PP_FormMapping__c</fullName>
        <label>Forms Review PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS1_PP_ILM__c</fullName>
        <label>Process/Templates Copied PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS1_PP_Inventory__c</fullName>
        <label>Users Entered PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS1_PP_Survey__c</fullName>
        <label>Survey Enabled PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS2_PP_ILM__c</fullName>
        <label>Call Provider Set Up PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS2_PP_Launch__c</fullName>
        <label>Intro to User List Call PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS2_PP_eBayListings__c</fullName>
        <label>Set up Ebay and Post PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS3_PP_AIS_Desking__c</fullName>
        <label>AIS Desking Verified PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS3_PP_AIS_Site__c</fullName>
        <label>AIS Websites Verified PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS3_PP_Inventory__c</fullName>
        <label>Autocheck SID Set Up PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS3_PP_Launch__c</fullName>
        <label>User List/Lead Settings Call PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS4_PP_Inventory__c</fullName>
        <label>Inventory Polled PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS4_PP_Launch__c</fullName>
        <label>Processes Templates Call PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS4_PP_TextMsgs__c</fullName>
        <label>Text Messaging Enabled PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS5_PP_DataAppend__c</fullName>
        <label>Data Append Enabled PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS5_PP_Desking__c</fullName>
        <label>DealerTrack RouteOne Set Up PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS5_PP_Inventory__c</fullName>
        <label>Photos Loaded PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS5_PP_Launch__c</fullName>
        <label>Desking Review Call PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS6_PP_CRMImp__c</fullName>
        <label>Sold History Reports Loaded PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS6_PP_EmailBanner__c</fullName>
        <label>Email Banner Uploaded PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS6_PP_Launch__c</fullName>
        <label>Custom Forms/Desking Verified PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS6_PP_PBX__c</fullName>
        <label>PBX Set Up PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS6_PP_PhotoOverlay__c</fullName>
        <label>Photo Overlay Loaded PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS8_PP_CRMImp__c</fullName>
        <label>Service History Reports Loaded PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS8_PP_Desking__c</fullName>
        <label>Desking Enabled PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS8_PP_Launch__c</fullName>
        <label>DealerTrack LC Verified PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS9_PP_CRMImp__c</fullName>
        <label>Trade Appraisal Push PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS9_PP_Desking__c</fullName>
        <label>Credit Bureau Set Up PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS9_PP_ILM__c</fullName>
        <label>Lead Address Created PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS9_PP_Inventory__c</fullName>
        <label>Exports Set Up PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS9_PP_Launch__c</fullName>
        <label>Route One LC Verified PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Owner_Email__c</fullName>
        <label>Project Owner Email</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>CRM</fullName>
        <active>false</active>
        <label>CRM</label>
    </recordTypes>
    <recordTypes>
        <fullName>Implementation</fullName>
        <active>true</active>
        <label>Basic Implementation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/handler_ProjectTrigger.cls
public with sharing class handler_ProjectTrigger {
	
	public static void updateProjectOwnerEmail(List<SFDC_520_Quote__c> projects, List<SFDC_520_Quote__c> oldProjects) {
		
		List<SFDC_520_Quote__c> ownerChangedProjects = new List<SFDC_520_Quote__c>();
		Set<Id> ownerChangedProjectIds = new Set<Id>();
		
		for(SFDC_520_Quote__c proj : projects) {
			
			for(SFDC_520_Quote__c oldProj : oldProjects) {
				
				if(proj.Id == oldProj.Id && proj.OwnerId != oldProj.OwnerId) {
					
					ownerChangedProjects.add(proj);
					ownerChangedProjectIds.add(proj.Id);
				}
			}
		}
		
		if(ownerChangedProjectIds.size() > 0) {
		
			List<Project_Piece__c> relatedProjectPieces = [SELECT Id, Project_Owner_Email__c, Project__c
														   FROM Project_Piece__c
														   WHERE Project__c IN :ownerChangedProjectIds];
														   
		   	for(SFDC_520_Quote__c proj : ownerChangedProjects) {
		   		
		   		for(Project_Piece__c pp : relatedProjectPieces) {
		   			
		   			if(proj.Id == pp.Project__c) {
		   				
		   				pp.Project_Owner_Email__c = proj.Owner.Email;
		   			}
		   		}
		   	}
		   	
			update relatedProjectPieces;
		}
	}
	
	public static void updateProjectMilestoneNA(List<SFDC_520_Quote__c> projects) {
		
		Set<Id> projIds = new Set<Id>();
		
		for(SFDC_520_Quote__c proj : projects) {
			
			projIds.add(proj.Id);
		}
		
		Map<Id, List<Project_Piece__c>> projPPMap = new Map<Id, List<Project_Piece__c>>();
		
		
		
		//List<Project_Piece__c> ppsT = [SELECT Id, Project__c, Name FROM Project_Piece__c WHERE Project__c IN :projIds];
		
		for(Project_Piece__c pp : [SELECT Id, Project__c, Name
							       FROM Project_Piece__c
							       WHERE Project__c IN :projIds]) {
			
			system.debug('Bazinga... projectPiece query loop');
			
			if(projPPMap.containsKey(pp.Project__c)) {
				
				/*
				List<Project_Piece__c> pps = projPPMap.get(pp.Project__c);
				
				pps.add(pp);
				
				projPPMap.put(pp.Project__c, pps);
				*/
				
				projPPMap.get(pp.Project__c).add(pp);
			}			
			else {
				
				/*
				List<Project_Piece__c> pps = new List<Project_Piece__c>();
				
				pps.add(pp);
				
				projPPMap.put(pp.Project__c, pps);
				*/
				
				projPPMap.put(pp.Project__c, new List<Project_Piece__c>{pp});
			}		       	
		}
		
		List<SFDC_520_Quote__c> updateProjects = new List<SFDC_520_Quote__c>();
		
		for(SFDC_520_Quote__c proj : projects) {
			
			boolean ppInventoryModule = false;
			boolean ppEbay = false;
			boolean ppPhotoOverlay = false;
			boolean ppILMImplementation = false;
			boolean ppEmailBanners = false;
			boolean ppLaunchCoordinator = false;
			boolean ppCRMImplementation = false;
			boolean ppDesking = false;
			boolean ppTextMessages = false;
			boolean ppAISRebatesSiteIntegration = false;
			boolean ppAISRebatesDeskingIntegration = false;
			boolean ppPBXIntegration = false;
			boolean ppDateAppendAuthenticom = false;
			boolean ppSurveyTool = false;
			boolean ppFormMapping = false;
			
			List<Project_Piece__c> pps = projPPMap.get(proj.Id);
			
			for(Project_Piece__c pp : pps) {
				
				if(pp.Name.contains('PP-Inventory Module-')) {
					
					ppInventoryModule = true;
				}
				else if(pp.Name.contains('PP-eBay listings - 10 free')) {
					
					ppEbay = true;
				}
				else if(pp.Name.contains('PP-Photo overlay-')) {
					
					ppPhotoOverlay = true;
				}
				else if(pp.Name.contains('PP-ILM Implementation-')) {
					
					ppILMImplementation = true;
				}
				else if(pp.Name.contains('PP-Email Banners-')) {
					
					ppEmailBanners = true;
				}
				else if(pp.Name.contains('PP-Launch Coordinator-')) {
					
					ppLaunchCoordinator = true;
				}
				else if(pp.Name.contains('PP-CRM Implementation-')) {
					
					ppCRMImplementation = true;
				}
				else if(pp.Name.contains('PP-Desking-')) {
					
					ppDesking = true;
				}
				else if(pp.Name.contains('PP-Text messages-')) {
					
					ppTextMessages = true;
				}
				else if(pp.Name.contains('PP-AIS Rebates (Site Integration)-')) {
					
					ppAISRebatesSiteIntegration = true;
				}
				else if(pp.Name.contains('PP-AIS Rebates (Desking integration) - Inventory-')) {
					
					ppAISRebatesDeskingIntegration = true;
				}
				else if(pp.Name.contains('PP-PBX Integration-')) {
					
					ppPBXIntegration = true;
				}
				else if(pp.Name.contains('PP-Data Append Authenticom-')) {
					
					ppDateAppendAuthenticom = true;
				}
				else if(pp.Name.contains('PP-Survey Tool-')) {
					
					ppSurveyTool = true;
				}
				else if(pp.Name.contains('PP-Form Mapping-')) {
				
					ppFormMapping = true;
				}
			}
			
			if(ppInventoryModule == false) {
				
				proj.MS1_PP_Inventory__c = 'N/A';
				proj.MS3_PP_Inventory__c = 'N/A';
				proj.MS4_PP_Inventory__c = 'N/A';
				proj.MS5_PP_Inventory__c = 'N/A';
				proj.MS9_PP_Inventory__c = 'N/A'; 
				proj.MS10_PP_Inventory__c = 'N/A';    
			}
			
			if(ppEbay == false) {
				
				proj.MS2_PP_eBayListings__c = 'N/A';
			}
			
			if(ppPhotoOverlay == false) {
				
				proj.MS6_PP_PhotoOverlay__c = 'N/A';
			}
			
			if(ppILMImplementation == false) {
				
				proj.MS1_PP_ILM__c = 'N/A';
				proj.MS2_PP_ILM__c = 'N/A';
				proj.MS9_PP_ILM__c = 'N/A';
			}
			
			if(ppEmailBanners == false) {
				
				proj.MS6_PP_EmailBanner__c = 'N/A';
			}
			
			if(ppLaunchCoordinator == false) {
				
				proj.MS2_PP_Launch__c = 'N/A';
				proj.MS3_PP_Launch__c = 'N/A';
				proj.MS4_PP_Launch__c = 'N/A';
				proj.MS5_PP_Launch__c = 'N/A';
				proj.MS6_PP_Launch__c = 'N/A';
				proj.MS8_PP_Launch__c = 'N/A';
				proj.MS9_PP_Launch__c = 'N/A';
			}
			
			if(ppCRMImplementation == false) {
				
				proj.MS6_PP_CRMImp__c = 'N/A';
				proj.MS8_PP_CRMImp__c = 'N/A';
				proj.MS9_PP_CRMImp__c = 'N/A';
			}
			
			if(ppDesking == false) {
				
				proj.MS5_PP_Desking__c = 'N/A';
				proj.MS8_PP_Desking__c = 'N/A';
				proj.MS9_PP_Desking__c = 'N/A';
			}
			
			if(ppTextMessages == false) {
				
				proj.MS4_PP_TextMsgs__c = 'N/A';
			}
			
			if(ppAISRebatesSiteIntegration == false) {
				
				proj.MS3_PP_AIS_Site__c = 'N/A';
			}
			
			if(ppAISRebatesDeskingIntegration == false) {
				
				proj.MS3_PP_AIS_Desking__c = 'N/A';
			}
			
			if(ppPBXIntegration == false) {
				
				proj.MS6_PP_PBX__c = 'N/A';
			}
			
			if(ppDateAppendAuthenticom == false) {
				
				proj.MS5_PP_DataAppend__c = 'N/A';
			}
			
			if(ppSurveyTool == false) {
				
				proj.MS1_PP_Survey__c = 'N/A';
			}
			
			if(ppFormMapping == false) {
				
				proj.MS1_PP_FormMapping__c = 'N/A';
			}
			
			updateProjects.add(proj);
		}
		
		update updateProjects;
	}
}