objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Product_Family__c</fullName>
        <formula>Product_Process__r.Product_Family__c</formula>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <inlineHelpText>automatically populated from the Opportunity Products Sold</inlineHelpText>
        <label>Product Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Piece_Stage__c</fullName>
        <label>Project Asset Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Travel Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer&apos;s Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Website Approval-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Shipment Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing/Shipping/Uploading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial QA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Has_Recurring_Products__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Valid from 1/10/13.</description>
        <inlineHelpText>Valid from 1/10/13.</inlineHelpText>
        <label>Has Recurring Products</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_Custom__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Project includes a website</inlineHelpText>
        <label>Website Included</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/HayAsyncHandler.cls
global class HayAsyncHandler {
@future
public static void handleProjectCreation(Id projectId){

	
	try{

List<SFDC_520_Quote__c> projectList = [Select Id from SFDC_520_Quote__c where Id =: projectId];
  if(projectList != null && projectList.size() > 0){
  	     SFDC_520_Quote__c project = projectList[0];
      
       List<Project_Piece__c> projectPieces = [Select Id,  Product_Family__c, Product_Name__c,Project_Piece_Stage__c ,RecordTypeId from Project_Piece__c where Project__c =: project.Id];
       Boolean hasRecurring = false;
       Boolean websiteIncluded = false;

      //TODO: Update 
      for(Project_Piece__c piece :projectPieces){
      // check Has Recurring Products if any of the generated Project Assets are for products where the Product Family is Monthly Reoccurring
      if(piece.Product_Family__c != null && piece.Product_Family__c.contains('Reoccuring')){
		hasRecurring = true;
	  }

	  // check Website Included if any of the the generated Proejct Assets are for products that have 'website' in the Product Name
	  if(piece.Product_Name__c != null && piece.Product_Name__c.contains('Website')){
		websiteIncluded = true;
	  }
	  }
	  project.Has_Recurring_Products__c = hasRecurring;
	  project.Website_Custom__c = websiteIncluded;
	  update project;

  }
  else{
      System.debug('No Project found with Id: '+projectId);
  }
  
	}
	catch(Exception ex){
		 try{
		  string errorDetails = UtilityClass.DebugException(ex);
          string message = 'There has been an error in vAutoAsynHandler.handleProjectCreation '+ errorDetails;
		  Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
          String[] toAddresses = new String[] {'ramana.mosali@autotradergroup.com'};
          mail.setToAddresses(toAddresses);
          mail.setSubject('vAutoAsynHandler.handleProjectCreation Error');
          mail.setPlainTextBody(message);
          Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
		  }catch(Exception e){
		  	//Ignore if anything else fail
		  }
	}
  

}
}