objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>Project_Piece_Stage__c</fullName>
        <label>Project Asset Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Travel Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer&apos;s Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Website Approval-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Shipment Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing/Shipping/Uploading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comp Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <formula>Project__r.Project_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Approval_Stage__c</fullName>
        <inlineHelpText>Updated by the system upon milestone completion</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>1-Initiating</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>2-Planning and Design</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>3-Executing</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>4-Review</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>5-Finalizing</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Launched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-CRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-ILM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration-Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GO LIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Introduction</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Intro Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending AM Strategy Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Dealer Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work Complete</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>This date is updated when the project is approved and the Stage is also updated to GO LIVE</inlineHelpText>
        <label>Go Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Complete_Date__c</fullName>
        <inlineHelpText>When the Stage is updated to Completed, Go Live, or Design, workflow updates the date through workflow rule</inlineHelpText>
        <label>Work Complete Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <inlineHelpText>Uses the Opportunity&apos;s Product Suite and is updated by the Trigger</inlineHelpText>
        <label>Opp Product Suite</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProjectPiecesWorkflow.cls
public class ProjectPiecesWorkflow {
		


//======================================================Mark All Tasks on Piece Completion==============================
	/*
	public static void runWorkflowRules(Project_Piece__c p, Project_Piece__c oldPiece, Task[] closeTasksList, SFDC_520_Quote__c Project) {		
		
		system.debug('runWorkflow p.Project_Piece_Stage__c = ' + p.Project_Piece_Stage__c);
		
		if(p.Project_Piece_Stage__c == 'Completed' || p.Project_Piece_Stage__c == 'Cancelled' || 
		   p.Project_Piece_Stage__c == 'Awaiting Website Approval-Customer' || p.RecordTypeId == '01270000000Q3Vc') {
		
			if(oldPiece.Project_Piece_Stage__c != 'Completed' || oldPiece.Project_Piece_Stage__c != 'Cancelled' || 
			   oldPiece.Project_Piece_Stage__c != 'Awaiting Website Approval-Customer' || oldPiece.RecordTypeId != '01270000000Q3Vc') {
			   	
				//Find and Close all Open tasks now that the piece is marked "Completed"
				LIST<Task> closeTasks = new LIST<Task>();					
			
				for(Task close: closeTasksList) {
					
					close.Status = 'Completed';
					close.Date_Time_Completed__c = System.now();
					closeTasks.add(close);
				}
				
				update closeTasks;
				
				//This piece has been marked completed. Find out if there are any more that are NOT marked Completed...if not, then mark project "Completed"
				//SFDC_520_Quote__c Project = [select id, name, Approval_Stage__c from SFDC_520_Quote__c where id = : p.Project__c limit 1];
				//update Project;
				if(Project.Approval_Stage__c != 'GO LIVE' || Project.Approval_Stage__c != 'Work Complete') {
					
					integer OpenPiece = [SELECT count() 
										 FROM Project_Piece__c 
										 WHERE Project__c = :Project.Id 
										 AND Project_Piece_Stage__c != 'Completed' 
										 AND Project_Piece_Stage__c != 'Cancelled' 
										 AND Project_Piece_Stage__c != 'Awaiting Website Approval-Customer' 
										 AND RecordTypeId != '01270000000Q3Vc' 
										 AND Id != :p.Id];
										 
					system.debug('runWorkflow OpenPiece = ' + OpenPiece);
					
					if(OpenPiece == 0) {
						
						if(Project.Approval_Stage__c != 'GO LIVE') {
						
	                        if(Project.Project_Type__c == 'Fulfillment') {
	                        	
						 		Project.Approval_Stage__c = 'GO LIVE';
						 		Project.End_Date__c = system.today();
	                    	}
	                   		else {
	                    		
	                    		if(Project.Approval_Stage__c != 'Work Complete') {
	                    		
	                        		Project.Approval_Stage__c = 'Work Complete';
	                        		Project.Project_Complete_Date__c = system.today();
	                    		}
	                        }
						}
					}
					
					update Project;						
				}
			} 
		}             
	}
	*/
	
	//public static void runWorkflowRules2(Project_Piece__c p, Project_Piece__c oldPiece, Task[] closeTasksList, SFDC_520_Quote__c Project) {		
	public static void runWorkflowRules(List<Project_Piece__c> projectPieces, Map<Id, Project_Piece__c> oldProjectPieces, List<Task> relatedTasks, List<SFDC_520_Quote__c> projects) {
		
		List<Task> updateCloseTasks = new List<Task>();
		List<SFDC_520_Quote__c> updateProjects = new List<SFDC_520_Quote__c>();
		
		for(Project_Piece__c pp : projectPieces) {
			
			if(pp.Project_Piece_Stage__c == 'Completed' || pp.Project_Piece_Stage__c == 'Cancelled' ||
			   pp.Project_Piece_Stage__c == 'Awaiting Website Approval-Customer' || pp.RecordTypeId == '01270000000Q3Vc') {
			
				Project_Piece__c oldPiece = oldProjectPieces.get(pp.Id);
				
				if(oldPiece.Project_Piece_Stage__c != 'Completed' || oldPiece.Project_Piece_Stage__c != 'Cancelled' ||
				   oldPiece.Project_Piece_Stage__c != 'Awaiting Website Approval-Customer' || oldPiece.RecordTypeId != '01270000000Q3Vc') {
				   	
			   		for(Task t : relatedTasks) {
					
						if(t.WhatId == pp.Id) {
							
							t.Status = 'Completed';
							t.Date_Time_Completed__c = system.now();
							
							updateCloseTasks.add(t);
						}	
			   		}
			   		
			   		SFDC_520_Quote__c project = new SFDC_520_Quote__c();
			   		
			   		for(SFDC_520_Quote__c p : projects) {
					
						if(p.Id == pp.Project__c) {
							
							project = p;
							break;
						}
			   		}
			   		
			   		//if(project.Approval_Stage__c != 'GO LIVE' || project.Approval_Stage__c != 'Work Complete') {
			   		if(project.Approval_Stage__c != 'GO LIVE' && project.Approval_Stage__c != 'Work Complete' && project.Approval_Stage__c != 'Cancelled' && project.Approval_Stage__c != 'Completed') {
			   			
			   			integer OpenPiece = [SELECT count()
			   								 FROM Project_Piece__c
			   								 WHERE Project__c = :project.Id 
											 AND Project_Piece_Stage__c != 'Completed' 
											 AND Project_Piece_Stage__c != 'Cancelled' 
											 AND Project_Piece_Stage__c != 'Awaiting Website Approval-Customer' 
											 AND RecordTypeId != '01270000000Q3Vc' 
											 AND Id != :pp.Id];
											 
				 		if(OpenPiece == 0) {
				 			
				 			//if(project.Approval_Stage__c != 'GO LIVE' && project.Approval_Stage__c != 'Cancelled') {
				 				
				 				if(project.Project_Type__c == 'Fulfillment') {
				 					
				 					project.Approval_Stage__c = 'GO LIVE';
				 					project.End_Date__c = system.today();
				 					
				 					updateProjects.add(project);
				 				}
				 				else {
				 					
				 					//if(project.Approval_Stage__c != 'Work Complete') {
				 						
				 						project.Approval_Stage__c = 'Work Complete';
				 						project.Project_Complete_Date__c = system.today();
				 						
				 						updateProjects.add(project);
				 					//}
				 				}
				 			//}
				 		}
			   		}
			   	}    	
	   		}
		}
		
		update updateCloseTasks;
		update updateProjects;
	}
		
	
	
	
}