objects/Project_Piece__c.object
<CustomObject>
    <description>sub object of Projects</description>
    <fields>
        <fullName>IsClosed__c</fullName>
        <formula>CASE(Project_Piece_Stage__c, &quot;Completed&quot;, &quot;True&quot;, &quot;Cancelled&quot;, &quot;True&quot;, &quot;Incomplete&quot;, &quot;True&quot;, &quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsClosed</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_10_Completed__c</fullName>
        <label>Milestone 10 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_1_Completed__c</fullName>
        <label>Milestone 1 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_2_Completed__c</fullName>
        <label>Milestone 2 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_3_Completed__c</fullName>
        <label>Milestone 3 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_4_Completed__c</fullName>
        <label>Milestone 4 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_5_Completed__c</fullName>
        <label>Milestone 5 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_6_Completed__c</fullName>
        <label>Milestone 6 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_8_Completed__c</fullName>
        <label>Milestone 8 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_9_Completed__c</fullName>
        <label>Milestone 9 Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_520_Quote__c</referenceTo>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Asset</label>
    <nameField>
        <label>Project Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>MS10_PP_Inventory__c</fullName>
        <label>Vector File Uploaded PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS1_PP_FormMapping__c</fullName>
        <label>Forms Review PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS1_PP_ILM__c</fullName>
        <label>Process/Templates Copied PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS1_PP_Inventory__c</fullName>
        <label>Users Entered PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS1_PP_Survey__c</fullName>
        <label>Survey Enabled PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS2_PP_ILM__c</fullName>
        <label>Call Provider Set Up PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS2_PP_Launch__c</fullName>
        <label>Intro to User List Call PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS2_PP_eBayListings__c</fullName>
        <label>Set up Ebay and Post PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS3_PP_AIS_Desking__c</fullName>
        <label>AIS Desking Verified PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS3_PP_AIS_Site__c</fullName>
        <label>AIS Websites Verified PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS3_PP_Inventory__c</fullName>
        <label>Autocheck SID Set Up PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS3_PP_Launch__c</fullName>
        <label>User List/Lead Settings Call PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS4_PP_Inventory__c</fullName>
        <label>Inventory Polled PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS4_PP_Launch__c</fullName>
        <label>Processes Templates Call PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS4_PP_TextMsgs__c</fullName>
        <label>Text Messaging Enabled PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS5_PP_DataAppend__c</fullName>
        <label>Data Append Enabled PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS5_PP_Desking__c</fullName>
        <label>DealerTrack RouteOne Set Up PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS5_PP_Inventory__c</fullName>
        <label>Photos Loaded PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS5_PP_Launch__c</fullName>
        <label>Desking Review Call PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS6_PP_CRMImp__c</fullName>
        <label>Sold History Reports Loaded PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS6_PP_EmailBanner__c</fullName>
        <label>Email Banner Uploaded PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS6_PP_Launch__c</fullName>
        <label>Custom Forms/Desking Verified PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS6_PP_PBX__c</fullName>
        <label>PBX Set Up PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS6_PP_PhotoOverlay__c</fullName>
        <label>Photo Overlay Loaded PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS8_PP_CRMImp__c</fullName>
        <label>Service History Reports Loaded PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS8_PP_Desking__c</fullName>
        <label>Desking Enabled PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS8_PP_Launch__c</fullName>
        <label>DealerTrack LC Verified PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS9_PP_CRMImp__c</fullName>
        <label>Trade Appraisal Push PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS9_PP_Desking__c</fullName>
        <label>Credit Bureau Set Up PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS9_PP_ILM__c</fullName>
        <label>Lead Address Created PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS9_PP_Inventory__c</fullName>
        <label>Exports Set Up PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS9_PP_Launch__c</fullName>
        <label>Route One LC Verified PPMS</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>CRM</fullName>
        <active>false</active>
        <label>CRM</label>
    </recordTypes>
    <recordTypes>
        <fullName>Implementation</fullName>
        <active>true</active>
        <label>Basic Implementation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/handler_ProjectPiece.cls
public without sharing class handler_ProjectPiece {
	
	public static void autofollow(List<Project_Piece__c> projectPieces) {
		
		//..
		//..
		List<EntitySubscription> insertEntitySubscriptions = new List<EntitySubscription>();
		Set<Id> closedProjectPieceIds = new Set<Id>();
		
		
		
		for(Project_Piece__c pp : projectPieces) {
			
			//if(pp.Owner.UserRoleId)
			//String roleName = 
			
			if(pp.Owner.userrole.DeveloperName != 'DirectorofImplementation' && pp.Owner.userrole.DeveloperName != 'Director_of_Websites' && pp.Owner.Name != 'Brian Schmid') {
			
				insertEntitySubscriptions.add(new EntitySubscription(ParentId = pp.Id, SubscriberId = pp.OwnerId));
				
				/* -------------------------------------------------
				------------------------------------------------- */
				if(pp.isClosed__c == 'True') {
					
					closedProjectPieceIds.add(pp.Id);
				}
			
			}
		}
		
		try {
			
			insert insertEntitySubscriptions;
		}
		catch(Exception e) {
			
			//do nothing
		}
		
		
		
		//User apiUser = [SELECT Id FROM User WHERE Name = 'API User'];
		
		
		//auto-UNfollow
		
		List<EntitySubscription> deleteEntitySubscriptions = new List<EntitySubscription>();
		
		if(closedProjectPieceIds.size() > 0) {
			
			deleteEntitySubscriptions = [SELECT Id, ParentId FROM EntitySubscription WHERE ParentId IN :closedProjectPieceIds LIMIT 500]; 
			
			//System.runas(apiUser) {
			
			delete deleteEntitySubscriptions;
			//}
		}
	}
	
	public static void updateProjectMilestoneComplete(List<Project_Piece__c> oldPPs, List<Project_Piece__c> newPPs) {
		
		Map<Id, Project_Piece__c> ppMap = new Map<Id, Project_Piece__c>();
		
		Set<Id> projectIds = new Set<Id>();
		
		for(Project_Piece__c pp : newPPs) {
			
			ppMap.put(pp.Id, pp);
			
			projectIds.add(pp.Project__c);	
		}
		
		List<SFDC_520_Quote__c> relatedProjects = new List<SFDC_520_Quote__c>();
		
		/**/
		relatedProjects = [SELECT Id, MS1_PP_Inventory__c, MS4_PP_Inventory__c, MS5_PP_Inventory__c, MS9_PP_Inventory__c,
								MS3_PP_Inventory__c, MS2_PP_ebayListings__c, MS6_PP_PhotoOverlay__c, MS2_PP_ILM__c,
								MS9_PP_ILM__c, MS6_PP_EmailBanner__c, MS1_PP_ILM__c, MS3_PP_Launch__c, MS6_PP_CRMImp__c,
								MS8_PP_CRMImp__c, MS8_PP_Desking__c, MS5_PP_Desking__c, MS4_PP_TextMsgs__c, MS3_PP_AIS_Site__c,
								MS3_PP_AIS_Desking__c, MS6_PP_PBX__c, MS5_PP_DataAppend__c, MS1_PP_Survey__c, MS2_PP_Launch__c,
								MS4_PP_Launch__c, MS1_PP_FormMapping__c, MS6_PP_Launch__c, MS5_PP_Launch__c
						   FROM SFDC_520_Quote__c
						   WHERE Id IN :projectIds];
		
		Map<Id, SFDC_520_Quote__c> projMap = new Map<Id, SFDC_520_Quote__c>();
		
		for(Project_Piece__c pp : newPPs) {
			
			for(SFDC_520_Quote__c proj : relatedProjects) {
				
				if(pp.Project__c == proj.Id) {
					
					projMap.put(pp.Id, proj);
				}
			}
		}
		
		//List<SFDC_520_Quote__c> updateProjects;// = new List<SFDC_520_Quote__c>();
		
		for(Project_Piece__c pp : oldPPs) {
			
			//updateProjects = new List<SFDC_520_Quote__c>();
			
			boolean projUpdate = false;
			
			Project_Piece__c newPP = ppMap.get(pp.Id);
			
			SFDC_520_Quote__c updateProj = projMap.get(newPP.Id);
			
			if(pp.Name.contains('PP-Inventory Module-')) {
				
				//
				if(pp.Milestone_1_Completed__c != newPP.Milestone_1_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_1_Completed__c != null) {
						
						updateProj.MS1_PP_Inventory__c = 'Complete ' + newPP.Milestone_1_Completed__c.format();
					}
					else {
						
						updateProj.MS1_PP_Inventory__c = '';
					}
				}
				
				//
				if(pp.Milestone_4_Completed__c != newPP.Milestone_4_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_4_Completed__c != null) {
						
						updateProj.MS4_PP_Inventory__c = 'Complete ' + newPP.Milestone_4_Completed__c.format();
					}
					else {
						
						updateProj.MS4_PP_Inventory__c = '';
					}
				}
				
				//
				if(pp.Milestone_5_Completed__c != newPP.Milestone_5_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_5_Completed__c != null) {
						
						updateProj.MS5_PP_Inventory__c = 'Complete ' + newPP.Milestone_5_Completed__c.format();
					}
					else {
						
						updateProj.MS5_PP_Inventory__c = '';
					}
				}
				
				//
				if(pp.Milestone_9_Completed__c != newPP.Milestone_9_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_9_Completed__c != null) {
						
						updateProj.MS9_PP_Inventory__c = 'Complete ' + newPP.Milestone_9_Completed__c.format();
					}
					else {
						
						updateProj.MS9_PP_Inventory__c = '';
					}
				}
				
				//
				if(pp.Milestone_3_Completed__c != newPP.Milestone_3_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_3_Completed__c != null) {
						
						updateProj.MS3_PP_Inventory__c = 'Complete ' + newPP.Milestone_3_Completed__c.format();
					}
					else {
						
						updateProj.MS3_PP_Inventory__c = '';
					}
				}
				
				//
				if(pp.Milestone_10_Completed__c != newPP.Milestone_10_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_10_Completed__c != null) {
						
						updateProj.MS10_PP_Inventory__c = 'Complete ' + newPP.Milestone_10_Completed__c.format();
					}
					else {
						
						updateProj.MS10_PP_Inventory__c = '';
					}
				}
			}
			else if(pp.Name.contains('PP-eBay listings - 10 free')) {
				
				//
				if(pp.Milestone_2_Completed__c != newPP.Milestone_2_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_2_Completed__c != null) {
						
						updateProj.MS2_PP_eBayListings__c = 'Complete ' + newPP.Milestone_2_Completed__c.format();
					}
					else {
						
						updateProj.MS2_PP_eBayListings__c = '';
					}
				}
			}
			else if(pp.Name.contains('PP-Photo overlay-')) {
				
				//
				if(pp.Milestone_6_Completed__c != newPP.Milestone_6_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_6_Completed__c != null) {
						
						updateProj.MS6_PP_PhotoOverlay__c = 'Complete ' + newPP.Milestone_6_Completed__c.format();
					}
					else {
						
						updateProj.MS6_PP_PhotoOverlay__c = '';
					}
				}
			}
			else if(pp.Name.contains('PP-ILM Implementation-')) {
				
				//
				if(pp.Milestone_2_Completed__c != newPP.Milestone_2_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_2_Completed__c != null) {
						
						updateProj.MS2_PP_ILM__c = 'Complete ' + newPP.Milestone_2_Completed__c.format();
					}
					else {
						
						updateProj.MS2_PP_ILM__c = '';
					}
				}
				
				//
				if(pp.Milestone_9_Completed__c != newPP.Milestone_9_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_9_Completed__c != null) {
						
						updateProj.MS9_PP_ILM__c = 'Complete ' + newPP.Milestone_9_Completed__c.format();
					}
					else {
						
						updateProj.MS9_PP_ILM__c = '';
					}
				}
				
				//
				if(pp.Milestone_1_Completed__c != newPP.Milestone_1_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_1_Completed__c != null) {
						
						updateProj.MS1_PP_ILM__c = 'Complete ' + newPP.Milestone_1_Completed__c.format();
					}
					else {
						
						updateProj.MS1_PP_ILM__c = '';
					}
				}
			}
			else if(pp.Name.contains('PP-Email Banners-')) {
				
				//
				if(pp.Milestone_6_Completed__c != newPP.Milestone_6_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_6_Completed__c != null) {
						
						updateProj.MS6_PP_EmailBanner__c = 'Complete ' + newPP.Milestone_6_Completed__c.format();
					}
					else {
						
						updateProj.MS6_PP_EmailBanner__c = '';
					}
				}
			}
			else if(pp.Name.contains('PP-Launch Coordinator-')) {
				
				//
				if(pp.Milestone_3_Completed__c != newPP.Milestone_3_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_3_Completed__c != null) {
						
						updateProj.MS3_PP_Launch__c = 'Complete ' + newPP.Milestone_3_Completed__c.format();
					}
					else {
						
						updateProj.MS3_PP_Launch__c = '';
					}
				}
				
				//
				if(pp.Milestone_2_Completed__c != newPP.Milestone_2_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_2_Completed__c != null) {
						
						updateProj.MS2_PP_Launch__c = 'Complete ' + newPP.Milestone_2_Completed__c.format();
					}
					else {
						
						updateProj.MS2_PP_Launch__c = '';
					}
				}
				
				//
				if(pp.Milestone_4_Completed__c != newPP.Milestone_4_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_4_Completed__c != null) {
						
						updateProj.MS4_PP_Launch__c = 'Complete ' + newPP.Milestone_4_Completed__c.format();
					}
					else {
						
						updateProj.MS4_PP_Launch__c = '';
					}
				}
				
				//
				if(pp.Milestone_6_Completed__c != newPP.Milestone_6_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_6_Completed__c != null) {
						
						updateProj.MS6_PP_Launch__c = 'Complete ' + newPP.Milestone_6_Completed__c.format();
					}
					else {
						
						updateProj.MS6_PP_Launch__c = '';
					}
				}
				
				//
				if(pp.Milestone_5_Completed__c != newPP.Milestone_5_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_5_Completed__c != null) {
						
						updateProj.MS5_PP_Launch__c = 'Complete ' + newPP.Milestone_5_Completed__c.format();
					}
					else {
						
						updateProj.MS5_PP_Launch__c = '';
					}
				}
				
				//
				if(pp.Milestone_8_Completed__c != newPP.Milestone_8_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_8_Completed__c != null) {
						
						updateProj.MS8_PP_Launch__c = 'Complete ' + newPP.Milestone_8_Completed__c.format();
					}
					else {
						
						updateProj.MS8_PP_Launch__c = '';
					}
				}
				
				//
				if(pp.Milestone_9_Completed__c != newPP.Milestone_9_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_9_Completed__c != null) {
						
						updateProj.MS9_PP_Launch__c = 'Complete ' + newPP.Milestone_9_Completed__c.format();
					}
					else {
						
						updateProj.MS9_PP_Launch__c = '';
					}
				}
			}
			else if(pp.Name.contains('PP-CRM Implementation-')) {
				
				//
				if(pp.Milestone_6_Completed__c != newPP.Milestone_6_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_6_Completed__c != null) {
						
						updateProj.MS6_PP_CRMImp__c = 'Complete ' + newPP.Milestone_6_Completed__c.format();
					}
					else {
						
						updateProj.MS6_PP_CRMImp__c = '';
					}
				}
				
				//
				if(pp.Milestone_8_Completed__c != newPP.Milestone_8_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_8_Completed__c != null) {
						
						updateProj.MS8_PP_CRMImp__c = 'Complete ' + newPP.Milestone_8_Completed__c.format();
					}
					else {
						
						updateProj.MS8_PP_CRMImp__c = '';
					}
				}
				
				//
				if(pp.Milestone_9_Completed__c != newPP.Milestone_9_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_9_Completed__c != null) {
						
						updateProj.MS9_PP_CRMImp__c = 'Complete ' + newPP.Milestone_9_Completed__c.format();
					}
					else {
						
						updateProj.MS9_PP_CRMImp__c = '';
					}
				}
			}
			else if(pp.Name.contains('PP-Desking-')) {
				
				//
				if(pp.Milestone_8_Completed__c != newPP.Milestone_8_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_8_Completed__c != null) {
						
						updateProj.MS8_PP_Desking__c = 'Complete ' + newPP.Milestone_8_Completed__c.format();
					}
					else {
						
						updateProj.MS8_PP_Desking__c = '';
					}
				}
				
				//
				if(pp.Milestone_5_Completed__c != newPP.Milestone_5_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_5_Completed__c != null) {
						
						updateProj.MS5_PP_Desking__c = 'Complete ' + newPP.Milestone_5_Completed__c.format();
					}
					else {
						
						updateProj.MS5_PP_Desking__c = '';
					}
				}
				
				//
				if(pp.Milestone_9_Completed__c != newPP.Milestone_9_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_9_Completed__c != null) {
						
						updateProj.MS9_PP_Desking__c = 'Complete ' + newPP.Milestone_9_Completed__c.format();
					}
					else {
						
						updateProj.MS9_PP_Desking__c = '';
					}
				}
			}
			else if(pp.Name.contains('PP-Text messages-')) {
				
				//
				if(pp.Milestone_4_Completed__c != newPP.Milestone_4_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_4_Completed__c != null) {
						
						updateProj.MS4_PP_TextMsgs__c = 'Complete ' + newPP.Milestone_4_Completed__c.format();
					}
					else {
						
						updateProj.MS4_PP_TextMsgs__c = '';
					}
				}
			}
			else if(pp.Name.contains('PP-AIS Rebates (Site Integration)-')) {
				
				//
				if(pp.Milestone_3_Completed__c != newPP.Milestone_3_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_3_Completed__c != null) {
						
						updateProj.MS3_PP_AIS_Site__c = 'Complete ' + newPP.Milestone_3_Completed__c.format();
					}
					else {
						
						updateProj.MS3_PP_AIS_Site__c = '';
					}
				}
			}
			else if(pp.Name.contains('PP-AIS Rebates (Desking integration) - Inventory-')) {
				
				//
				if(pp.Milestone_3_Completed__c != newPP.Milestone_3_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_3_Completed__c != null) {
						
						updateProj.MS3_PP_AIS_Desking__c = 'Complete ' + newPP.Milestone_3_Completed__c.format();
					}
					else {
						
						updateProj.MS3_PP_AIS_Desking__c = '';
					}
				}
			}
			else if(pp.Name.contains('PP-PBX Integration-')) {
				
				//
				if(pp.Milestone_6_Completed__c != newPP.Milestone_6_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_6_Completed__c != null) {
						
						updateProj.MS6_PP_PBX__c = 'Complete ' + newPP.Milestone_6_Completed__c.format();
					}
					else {
						
						updateProj.MS6_PP_PBX__c = '';
					}
				}
			}
			else if(pp.Name.contains('PP-Data Append Authenticom-')) {
				
				//
				if(pp.Milestone_5_Completed__c != newPP.Milestone_5_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_5_Completed__c != null) {
						
						updateProj.MS5_PP_DataAppend__c = 'Complete ' + newPP.Milestone_5_Completed__c.format();
					}
					else {
						
						updateProj.MS5_PP_DataAppend__c = '';
					}
				}
			}
			else if(pp.Name.contains('PP-Survey Tool-')) {
				
				//
				if(pp.Milestone_1_Completed__c != newPP.Milestone_1_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_1_Completed__c != null) {
						
						updateProj.MS1_PP_Survey__c = 'Complete ' + newPP.Milestone_1_Completed__c.format();
					}
					else {
						
						updateProj.MS1_PP_Survey__c = '';
					}
				}
			}
			else if(pp.Name.contains('PP-Form Mapping-')) {
				
				//
				if(pp.Milestone_1_Completed__c != newPP.Milestone_1_Completed__c) {
					
					projUpdate = true;
					
					if(newPP.Milestone_1_Completed__c != null) {
						
						updateProj.MS1_PP_FormMapping__c = 'Complete ' + newPP.Milestone_1_Completed__c.format();
					}
					else {
						
						updateProj.MS1_PP_FormMapping__c = '';
					}
				}
			}
			
			if(projUpdate == true) {
			
				update updateProj;
			}	
		}	
	}
}