objects/SFDC_Paid_Time_Off__c.object
<CustomObject>
    <description>Track your Paid Time Off requests and approvals here.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Approvers will review the leave application and change the status to approved (if approved, or rejected if not approved)</description>
        <inlineHelpText>this field is updated by the approval process, it is not editable by users</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approving_Manager__c</fullName>
        <formula>Employee_s_Name__r.Manager.FirstName&amp;&quot; &quot;&amp; Employee_s_Name__r.Manager.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approving Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Employee_Notes__c</fullName>
        <defaultValue>&quot;You must click on the Submit for Approval button after Save&quot;</defaultValue>
        <inlineHelpText>please enter any notes if this request is for bereavement, jury duty or medical reasons.</inlineHelpText>
        <label>Employee Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employee_Role__c</fullName>
        <formula>Employee_s_Name__r.UserRole.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Employee Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_s_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup Salesforce User</inlineHelpText>
        <label>Employee&apos;s Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Paid_Time_Off</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exclude_Weekends__c</fullName>
        <inlineHelpText>please check this box if your time off requests includes a Saturday and Sunday you do not wanted deducted from your PTO accrual bucket</inlineHelpText>
        <label>Exclude Weekends</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <description>Date that you will first be on leave.</description>
        <label>From Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Help_Information__c</fullName>
        <description>Let employees know they must Submit for Approval</description>
        <formula>IF(  ISPICKVAL(Approval_Status__c, &quot;Not Submitted&quot;), IMAGE(&quot;/servlet/servlet.ImageServer?id=01570000001U1qS&amp;oid=00D700000008zHZ&amp;lastMod=1309469134000&quot;,&quot;Help&quot;), NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Help Information</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hours_to_be_Used__c</fullName>
        <inlineHelpText>enter the # of PTO hours you will be using for this request</inlineHelpText>
        <label>Hours to be Used</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Manager_Email_Address__c</fullName>
        <defaultValue>$User.Manager_Email_Address__c</defaultValue>
        <label>Manager Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <defaultValue>&quot;if logging PTO for your employee change owner to the employee before submitting for approval&quot;</defaultValue>
        <inlineHelpText>if you are logging PTO for another user, change the owner to the employee requesting the PTO before submitting for approval</inlineHelpText>
        <label>Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>PTO</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time_Off_Balance__c</fullName>
        <label>Time Off Balance</label>
        <referenceTo>Time_Off_Balance__c</referenceTo>
        <relationshipName>Time_Off_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <description>Last Date that you will be on Leave.</description>
        <label>To Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_Days_Requested__c</fullName>
        <formula>Hours_to_be_Used__c /8</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>formula field calculated by the system by taking the hours to be used divided by 8</inlineHelpText>
        <label>Total Days Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>used by Managers to define the request</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Unpaid Time Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unplanned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOA 1: these hours DO come out of the PTO balance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOA 2: these hours DO NOT come out of the PTO balance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JURY: these hours do NOT come out of the PTO balance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BEREAVE: these hours do NOT come out of the PTO balance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VinGives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Time Off Request</label>
    <nameField>
        <displayFormat>PTOFF-{000000}</displayFormat>
        <label>Paid Time Off Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Off Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Off_Balance__c.object
<CustomObject>
    <description>used to hold the accruals for time off</description>
    <label>Time Off Balance</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Time Off Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Off Balances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Manager_Email_Address__c</fullName>
        <formula>Manager.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Manager Email Address</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PTO_Calendar_Controller.cls
public with sharing class PTO_Calendar_Controller {
        
        public LIST<SFDC_Paid_Time_Off__c> ptoRequests {get; set;}
        public String selectedDepartment{get; set;}
        public String departmentString {get; set;}
        public String managerString {get; set;}
        public LIST<SelectOption> requestOptions = new LIST<SelectOption>();
        public LIST<SelectOption> requestOptionsB = new LIST<SelectOption>();
        
        
        
        public PTO_Calendar_Controller()        
        {
                departmentString = 'All Departments';
                managerString = 'All Managers';
                setptoRequests();       
                        
        }
        
        public Pagereference returnHome()
        {
                
                return new PageReference('/home/home.jsp');
        }
        
        public Pagereference PTOobjrctPage()
        {
        
                return new PageReference('/a0Q/o');     
                
        }
        
        public void setptoRequests()
        {
                
                Date lDate = date.today();
                lDate = lDate.addDays(-15);
                Datetime dt = datetime.newInstance(lDate.year(), lDate.month(),lDate.day());
                String ptoRequestQuery = 'Select Type__c, Total_Days_Requested__c, To_Date__c, Time_Off_Balance__c, SystemModstamp, Request_Type__c, Notes__c, Name, Manager_Email_Address__c,'; 
                ptoRequestQuery += 'LastModifiedDate, LastModifiedById, LastActivityDate, IsDeleted, Id, Hours_to_be_Used__c,';
                ptoRequestQuery += 'Help_Information__c, From_Date__c, Exclude_Weekends__c, Employee_s_Name__c, Employee_Role__c,'; 
                ptoRequestQuery += 'Employee_Notes__c, Description__c, Approving_Manager__c, Approval_Status__c,'; 
                ptoRequestQuery += 'Employee_s_Name__r.Name, Employee_s_Name__r.Department '; 
                ptoRequestQuery += 'From SFDC_Paid_Time_Off__c where ';
                ptoRequestQuery += '(Approval_Status__c = \'Awaiting Manager Approval\' OR Approval_Status__c = \'Approved\')';
                ptoRequestQuery += 'AND To_Date__c > :dt';
                
                //add an if statement here to only go off the manager
                if (departmentString != 'All Departments')
                {
                        ptoRequestQuery += ' AND Employee_s_Name__r.Department = \'' + departmentString + '\'';
                }       else  {
                
                
                if (managerString != 'All Managers')
                {
                        
                        ptoRequestQuery += ' AND Approving_Manager__c = \'' + managerString + '\'';
                        
                }
                }
                //Added by ProCore 6/16/12 for debugging
               	//ptoRequestQuery += ' AND Approving_Manager__c != \'Kevin Broderick\'';
        		ptoRequestQuery += ' ORDER BY From_Date__c asc';
        		//ptoRequestQuery += 'AND Id != \'a0Q70000008Dzey\'';
        		
                
                ptoRequests = Database.query(ptoRequestQuery); 
                system.debug(ptoRequestQuery);
                
        }
        
        public LIST<SelectOption> getRequestOptions()
        {
                requestOptions = new LIST<SelectOption>();        
                //Commented by Procore 6/16/2012 for bulkified aggregateresult
                /*
                LIST<User> userList= [select Id, Department, IsActive, IsPortalEnabled from User where IsActive = true AND IsPortalEnabled = false];              
                LIST<String> uniqueDepartments = new LIST<String>();
                MAP<String, String> departmentMap = new MAP<String, String>();
                        
                for (User user: userList)
                {
                        if (user.Department != null)
                        {
                                departmentMap.put(user.Department, user.Department);    
                        }                                               
                }
                uniqueDepartments = departmentMap.values();
                
                requestOptions.add(new SelectOption('All Departments', 'All Departments'));
                
                for (String department: uniqueDepartments)
                {
                        requestOptions.add(new SelectOption(department, department));
                }                       
                */
                
                requestOptions.add(new SelectOption('All Departments', 'All Departments'));
                List<AggregateResult> arDepts = [SELECT department department 
                                                                                        FROM User
                                                                                        WHERE isActive = true
                                                                                        AND isPortalEnabled = false
                                                                                        AND department != null
                                                                                        GROUP BY department];
                
                for(AggregateResult ar : arDepts){
                        requestOptions.add(new SelectOption(string.valueOf(ar.get('department')), string.valueOf(ar.get('department'))));
                }
                return requestOptions;
        }
        
        public LIST<SelectOption> getRequestOptionsB()
        {
                requestOptionsB = new LIST<SelectOption>();
                //Commented by Procore 6/16/2012 for bulkified aggregateresult
                /*
                LIST<User> userList= [select Id, firstName, lastName, Department, IsActive, managerId, IsPortalEnabled from User where IsActive = true AND IsPortalEnabled = false AND managerId != null];
                MAP<String, String> managerMap = new MAP<String, String>();
                LIST<String> managerList = new LIST<String>();
                
                
                String mName = '';

                for (User userO: userList)
                {

                        for (User userI: userList)
                        {

                                if (userO.id == userI.managerId)
                                {
                                        mName = userO.firstName + ' ' + userO.lastName;
                                                                
                                        managerMap.put( mName, mName);

                                }
        
                        }
        
                
                }
                requestOptionsB.add(new SelectOption('All Managers', 'All Managers'));

                for (string manOut: managerMap.keySet())
                {

                        requestOptionsB.add(new SelectOption(manOut, manOut));
        
                }
                */
                requestOptionsB.add(new SelectOption('All Managers', 'All Managers'));
                List<AggregateResult> arManagers = [SELECT Manager.Name managerName
                                                                                        FROM User 
                                                                                        WHERE IsActive = true 
                                                                                        AND IsPortalEnabled = false 
                                                                                        AND managerId != null
                                                                                        GROUP BY Manager.Name];
                for(AggregateResult ar : arManagers){
                        requestOptionsB.add(new SelectOption(string.valueOf(ar.get('managerName')), string.valueOf(ar.get('managerName'))));
                }
                return requestOptionsB;
        }
        
        
        /*
        public LIST<SFDC_Paid_Time_Off__c> getptoRequests()
        {
                return ptoRequests;
        }
        */


}