objects/SFDC_Paid_Time_Off__c.object
<CustomObject>
    <description>Track your Paid Time Off requests and approvals here.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Approvers will review the leave application and change the status to approved (if approved, or rejected if not approved)</description>
        <inlineHelpText>this field is updated by the approval process, it is not editable by users</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approving_Manager__c</fullName>
        <formula>Employee_s_Name__r.Manager.FirstName&amp;&quot; &quot;&amp; Employee_s_Name__r.Manager.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approving Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_Role__c</fullName>
        <formula>Employee_s_Name__r.UserRole.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Employee Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_s_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>lookup Salesforce User</inlineHelpText>
        <label>Employee&apos;s Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Paid_Time_Off</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <description>Date that you will first be on leave.</description>
        <label>From Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hours_to_be_Used__c</fullName>
        <inlineHelpText>enter the # of PTO hours you will be using for this request</inlineHelpText>
        <label>Hours to be Used</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>PTO</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <description>Last Date that you will be on Leave.</description>
        <label>To Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_Days_Requested__c</fullName>
        <formula>Hours_to_be_Used__c /8</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>formula field calculated by the system by taking the hours to be used divided by 8</inlineHelpText>
        <label>Total Days Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>used by Managers to define the request</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Unpaid Time Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unplanned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOA 1: these hours DO come out of the PTO balance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOA 2: these hours DO NOT come out of the PTO balance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JURY: these hours do NOT come out of the PTO balance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BEREAVE: these hours do NOT come out of the PTO balance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VinGives</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Time Off Request</label>
    <nameField>
        <displayFormat>PTOFF-{000000}</displayFormat>
        <label>Paid Time Off Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Off Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Log__c.object
<CustomObject>
    <fields>
        <fullName>Employee_Role__c</fullName>
        <formula>VS_Employee__r.UserRole.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Employee Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Log_Date__c</fullName>
        <inlineHelpText>enter the date you are logging time for</inlineHelpText>
        <label>Time Log Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VS_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VS Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Log</label>
    <nameField>
        <displayFormat>TL-{YYYY}{MM}-{0}</displayFormat>
        <label>Time Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Auto_Time_Log_Ignore__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Time Log Ignore</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/scheduledTimeLogCreationInterface.cls
global class scheduledTimeLogCreationInterface implements Schedulable{
    global void execute(SchedulableContext ctx) 
    {
    //Date lDate = system.today();
    //Datetime dt = datetime.newInstance(lDate.year(), lDate.month(),lDate.day());
    LIST<Time_Log__c> newTimeLogs = new LIST<Time_Log__c>();
        
    MAP<Id, UserLicense> userLicenses = new MAP<Id, UserLicense>([
    select Id, Name from UserLicense where Name = 'Salesforce' OR Name = 'Force.com - Free' OR Name = 'Salesforce Platform']);
            
    MAP<Id, Profile> userProfiles = new MAP<Id, Profile>([select Id, UserLicenseId from Profile where UserLicenseId IN: userLicenses.keyset()]);
 
    MAP<Id,SFDC_Paid_Time_Off__c> onPTO = new MAP<ID,SFDC_Paid_Time_Off__c>([Select Type__c, Total_Days_Requested__c, To_Date__c,SystemModstamp, Request_Type__c, Name, 
    IsDeleted, Id, Hours_to_be_Used__c,From_Date__c,Employee_s_Name__c, Employee_Role__c, Approving_Manager__c, Approval_Status__c, Employee_s_Name__r.Name, Employee_s_Name__r.Department From SFDC_Paid_Time_Off__c where (From_Date__c <= TODAY and To_Date__c >= TODAY) and Approval_Status__c = 'Approved']);
        
    List<Id> excludeIds = new List<Id>();

    for(id pto : onPTO.keyset()) excludeIds.add(onPTO.get(pto).Employee_s_Name__c);

    LIST<User> UsersExPTO = [select Id, isActive, isPortalEnabled from User where isActive = true AND isPortalEnabled = false AND ProfileId IN: userProfiles.keyset() AND Auto_Time_Log_Ignore__c = false And Id NOT IN: excludeIds];

    system.debug('Users not on PTO: ' + UsersExPTO.size());

    for(user b : UsersExPTO) system.debug(b.id);
        // old user query
        // LIST<User> allUsers = [select Id, isActive, isPortalEnabled from User where isActive = true AND isPortalEnabled = false AND ProfileId IN: userProfiles.keyset() AND Auto_Time_Log_Ignore__c = false];
        
        for (User user: UsersExPTO)
        {
            
            Time_Log__c newTimeLog = new Time_Log__c();
            newTimeLog.VS_Employee__c = user.Id;
            newTimeLog.OwnerId = user.Id;
            newTimeLog.Time_Log_Date__c = system.today();           
            newTimeLogs.add(newTimeLog);

        }
        insert newTimeLogs;
    }   
    
    //******Test methods******
    
    
    static testmethod void test()
    {
        Test.startTest();
        String jobId = System.schedule('scheduledTimeLogCreationInterface',
            '0 0 0 3 9 ? 2022', 
            new scheduledTimeLogCreationInterface());
         
        CronTrigger ct = [SELECT id, CronExpression, TimesTriggered, 
            NextFireTime
            FROM CronTrigger WHERE id = :jobId];
        System.assertEquals('0 0 0 3 9 ? 2022',
            ct.CronExpression);         
        
         
        System.assertEquals('2022-09-03 00:00:00', 
            String.valueOf(ct.NextFireTime));
        
        Test.stopTest();
    }
}