objects/SFDC_520_Quote__c.object
<CustomObject>
    <description>recycled the quoting tool and made in projects-used the functionality to copy the opportunity line items into the Project so everyone could see what was sold.</description>
    <fields>
        <fullName>Project_Owner_Email__c</fullName>
        <label>Project Owner Email</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Owner_Name__c</fullName>
        <inlineHelpText>updated by a trigger to get the project owner into the project piece</inlineHelpText>
        <label>Project Owner Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Squad_Name__c</fullName>
        <inlineHelpText>updated by a trigger that looks at the Squad Name assigned in the owner&apos;s user profile and updates the team name to this field for reporting</inlineHelpText>
        <label>Squad Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <inlineHelpText>updated by a trigger that looks at the Team Name assigned in the owner&apos;s user profile and updates the team name to this field for reporting</inlineHelpText>
        <label>Team Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Squad_Name__c</fullName>
        <label>Squad Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <inlineHelpText>used for Sales and Implementation for reporting</inlineHelpText>
        <label>Team Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ProjectClass2.cls
public with sharing class ProjectClass2 
{
	public static void UpdateOwnerName(SFDC_520_Quote__c Proj)
	{
		for(User pOwner: [select id, LastName, FirstName, email, Team_Name__c, Squad_Name__c from User where Id =: Proj.OwnerId limit 1])
	
		{
			Proj.Project_Owner_Name__c = pOwner.FirstName+' '+pOwner.LastName;
			Proj.Project_Owner_Email__c = pOwner.Email;
			Proj.Team_Name__c = pOwner.Team_Name__c;
			Proj.Squad_Name__c = pOwner.Squad_Name__c;
			
		}
		
	}	
}