objects/SLX__Change_Control__c.object
<CustomObject>
    <description>Administrative Object to allow the tracking and approval of system changes</description>
    <fields>
        <fullName>IsClosed__c</fullName>
        <formula>CASE( SLX__Request_Status__c , 
&quot;Completed&quot;, &quot;True&quot;, 
&quot;Denied&quot;, &quot;True&quot;, 
&quot;Cancelled&quot;, &quot;True&quot;,
&quot;Duplicate&quot;,&quot;True&quot;,
&quot;Converted&quot;,&quot;True&quot;,
&quot;False&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsClosed</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLX__Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enter your name</inlineHelpText>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N40000001Hw99EAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change Control</label>
    <nameField>
        <label>Change Control Request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SLXChangeControl.cls
public with sharing class SLXChangeControl {
	
	public static void autofollow(List<SLX__Change_Control__c> changeControls) {
		
		//...
		//...
		
		//User mark = [SELECT Id FROM User WHERE Name = 'Mark Ross'];
		
		
		//List<EntitySubscription> insertEntitySubscriptions = new List<EntitySubscription>();
		
		EntitySubscription insertRequestor = new EntitySubscription();
		EntitySubscription insertOwner = new EntitySubscription();
		//EntitySubscription insertMark = new EntitySubscription();
		
		
		Set<Id> closedChangeControlIds = new Set<Id>();
		
		List<User> usersToFollow = [SELECT Id FROM User WHERE Name = 'Dean Lukowski' OR Name = 'Angel Bourret'];
		
		Map<Id, User> userIdsToFollow = new Map<Id, User>(usersToFollow);
		
		//Set<Id> userIdsToFollow = new Set<Id>();
			
		//for(User u : usersToFollow) {
				
			//userIdsToFollow.add(u.Id);
		//}
		
		for(SLX__Change_Control__c c : changeControls) {
			
			//set the record creator to autofollow
			
			
			//insertEntitySubscriptions.add(new EntitySubscription(ParentId = c.Id, SubscriberId = c.SLX__Requestor__c));
			insertRequestor.ParentId = c.Id;
			insertRequestor.SubscriberId = c.SLX__Requestor__c;
			
			//insertEntitySubscriptions.add(new EntitySubscription(ParentId = c.Id, SubscriberId = c.OwnerId));
			insertOwner.ParentId = c.Id;
			insertOwner.SubscriberId = c.OwnerId;
			
			
			//if(userIdsToFollow.keyset().contains(c.OwnerId)) {
				
				//insertMark.ParentId = c.Id;
				//insertMark.SubscriberId = mark.Id;
			//}
			
			//if(userIdsToFollow.contains(c.OwnerId)) {
				
				//if(c.isClosed__c == 'False') {
			
					//insertEntitySubscriptions.add(new EntitySubscription(ParentId = c.Id, SubscriberId = mark.Id));
				//}
				//else if(c.isClosed__c == 'True') {
					
					//closedChangeControlIds.add(c.Id);
				//}
			
			//}
			
			if(c.isClosed__c == 'True') {
				
				closedChangeControlIds.add(c.Id);
			}
			
		}
		
		try {
			
			//insert insertEntitySubscriptions;
			insert insertRequestor;
		}
		catch(Exception e) {
			
			//do nothing
		}
		
		try {
			
			insert insertOwner;
		}
		catch(Exception e) {
			
			//do nothing
		}
		
		//try {
			
			//insert insertMark;
		//}
		//catch(Exception e) {
			
			//do nothing
		//}
		
		
		//auto-UNfollow
		
		List<EntitySubscription> deleteEntitySubscriptions = new List<EntitySubscription>();
		
		if(closedChangeControlIds.size() > 0) {
			
			//try {
			
				deleteEntitySubscriptions = [SELECT Id, ParentId FROM EntitySubscription WHERE ParentId IN :closedChangeControlIds];
			//}
			//catch(Exception e) {
				
				//none exist
			//}
			
			//try {
				
				delete deleteEntitySubscriptions;
			//}
			//catch(Exception e) {
				
				//..
			//}
		}
		
	}
	
}