objects/Template__c.object
<CustomObject>
    <fields>
        <fullName>API_Name__c</fullName>
        <label>API Name</label>
        <picklist>
            <picklistValues>
                <fullName>POA__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFDC_520_Quote__c</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Text__c</fullName>
        <label>Standard Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Urgency__c</fullName>
        <label>Urgency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Template</label>
    <nameField>
        <displayFormat>Temp-{0000000000}</displayFormat>
        <label>Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Template_Merge_Field__c.object
<CustomObject>
    <fields>
        <fullName>API_Name__c</fullName>
        <label>API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Column_Header__c</fullName>
        <label>Column Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plural_Name__c</fullName>
        <label>Plural Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Template</label>
        <referenceTo>Template__c</referenceTo>
        <relationshipLabel>Template Merge Fields</relationshipLabel>
        <relationshipName>Template_Merge_Fiels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Template Merge Field</label>
    <nameField>
        <displayFormat>TMF-{0000000000}</displayFormat>
        <label>Template Merge Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Template Merge Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ctrl_EmailTables.cls
public with sharing class ctrl_EmailTables {

	public ID tempID {get;set;}
	public ID RID {get;set;}

	public List<dynamicEmailHandler.tableDisplay> getTables(){
		List<dynamicEmailHandler.tableDisplay> temp = new List<dynamicEmailHandler.tableDisplay>();
		try{
		if(tempID != null && RID != null){
		Template__c mainTemplate = [Select ID, Urgency__c, Name__c, Body__c, Standard_Text__c, API_Name__c, (SELECT ID, Column_Header__c, Name, Name__c, API_Name__c, Plural_Name__c FROM Template_Merge_Fiels__r) FROM Template__c WHERE ID = :tempID];
		if(mainTemplate != null ){
			map<string,List<string>> fieldSetMap = dynamicEmailHandler.findTableFields(mainTemplate);
			sObject sobj;
			if(fieldSetMap.size() > 0){
				for(String s : fieldSetmap.keySet()){
					sobj = dynamicEmailHandler.runQuery(mainTemplate.ID, RID);
					List<sObject> objects = sObj.getSobjects(s);
					dynamicEmailHandler.tableDisplay td = new dynamicEmailHandler.tableDisplay();
					td.objRecs = objects;
					td.colHeads = dynamicEmailHandler.findColumnHeaders(mainTemplate);
					td.headerValues = dynamicEmailHandler.findHeaderValues(mainTemplate);
					try{
					td.headerMap = dynamicEmailHandler.findHeaderMap(mainTemplate);
					}catch(exception e){
					}
					system.debug('FIND THIS' + td.headerValues);
					temp.add(td);
				}
			}
		}
		}
		}catch(exception e){
			
		}
		return temp;
	}

}