objects/User.object
<CustomObject>
    <fields>
        <fullName>Alternate_PTO_Approver__c</fullName>
        <description>The Alternate PTO Approver will have the same access as the PTO Approver.</description>
        <inlineHelpText>Alternate PTO Approver will have the same ability as the PTO Approver assigned to the User</inlineHelpText>
        <label>Alternate PTO Approver</label>
        <relationshipName>User</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Delegated_Approver_2__c</fullName>
        <label>Delegated Approver (2)</label>
        <relationshipName>DAUsers</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Employee_Number__c</fullName>
        <label>Employee Number (PTO)</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HR_Department__c</fullName>
        <description>Field to match PANs for HR.</description>
        <inlineHelpText>Field to match PANs for HR.</inlineHelpText>
        <label>HR Department</label>
        <picklist>
            <picklistValues>
                <fullName>HY17691000 HY Ad Ops - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17676000 HY Ad Ops - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17690000 HY Content - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17675000 HY Content - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17697000 HY Development - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17682000 HY Development - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17698000 HY Executive - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17683000 HY Executive - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17687000 HY Finance - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17672000 HY Finance - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17699000 HY Human Resources - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17684000 HY Human Resources - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17696000 HY Implementation - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17681000 HY Implementation - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17688000 HY IT - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17673000 HY IT - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17671000 HY Marketing - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17686000 HY Marketing - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17692000 HY Operations - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17677000 HY Operations - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17695000 HY Performance Mgmnt - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17680000 HY Perform. Mgmnt - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17670000 HY Product - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17685000 HY Product - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17689000 HY Sales – SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17674000 HY Sales - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17693000 HY Support - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17678000 HY Support - Websites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17694000 HY Training - SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HY17679000 HY Training - Websites</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HR_Job_Title__c</fullName>
        <description>Used to match New Job Title field from PAN for HR.</description>
        <inlineHelpText>Used to match New Job Title field from PAN for HR.</inlineHelpText>
        <label>HR Job Title</label>
        <picklist>
            <picklistValues>
                <fullName>A017 - Instructional Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1135 - Account Mgr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1171 - Accounting Associate I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1172 - Accounting Associate II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1002 - Accounts Receivable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1003 - Admin Assist Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1173 - Admin Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1214 - Application Support Mgr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1337 - Associate Data Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1264 – Associate Mgr, Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1254 - Assoc Mgr, Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1168 - Associate Program Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1260 - Assoc Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1169 - Associate Software Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1163 - Brand Coord</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1005 - Business Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1275 - Business Development Mgr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1335 - Certified Technician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1229 - Compliance Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1009 - Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1143 - Corporate Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1222 - Corporate Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1013 - Creative Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1014 - Creative Designer Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1106 - Creative Project Mgr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1177 - Cust. Service Rep II- Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1178 - Cust. Service Rep II- Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1176 - Customer Service Rep I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1162 - Data Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S1124 - Database Administrator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PTO_Approver__c</fullName>
        <label>PTO Approver</label>
        <relationshipName>Users</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Team_Lead__c</fullName>
        <label>Team Lead</label>
        <relationshipName>Team_Lead</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/handler_userTrigger.cls
public with sharing class handler_userTrigger {
	
	public static void lockDownUserFields(List<User> oldList, List<User> newList) {
		
		for(User oldUser : oldList) {
			for(User newUser : newList) {
				if(oldUser.Id == newUser.Id) {
					
					//check if not admin profiles
					//VinSystem Admin: 00e70000000wzXQAAY
					//VinSystem Dev Admin: 00e70000001FaWMAA0
					//David Tinsley: 00570000001Jg6xAAC
					//Angel Bourret: 00570000001eNX0AAM
					
					system.debug('Bazinga... profileId: ' + UserInfo.getProfileId());
					system.debug('Bazinga... userId: ' + UserInfo.getUserId());
					
					if((UserInfo.getProfileId() != '00e70000000wzXQAAY' && UserInfo.getProfileId() != '00e70000001FaWMAA0' && UserInfo.getUserId() != '00570000001eNX0AAM') || UserInfo.getUserId() == '00570000001Jg6xAAC') {
							
						//Role
						if(oldUser.UserRoleId != newUser.UserRoleId) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your Role. ***');
						}
						
						//Profile
						if(oldUser.ProfileId != newUser.ProfileId) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your Profile. ***');
						}
						
						//Title
						if(oldUser.Title != newUser.Title) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your Title. ***');
						}
						
						//Department
						if(oldUser.Department != newUser.Department) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your Department. ***');
						}
						
						//Employee Number
						if(oldUser.Employee_Number__c != newUser.Employee_Number__c) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your Employee Number. ***');
						}
						
						//Employee Number
						if(oldUser.EmployeeNumber != newUser.EmployeeNumber) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your Employee Number. ***');
						}
						
						//PTO Approver
						if(oldUser.PTO_Approver__c != newUser.PTO_Approver__c) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your PTO Approver. ***');
						}
						
						//Alternate PTO Approver
						if(oldUser.Alternate_PTO_Approver__c != newUser.Alternate_PTO_Approver__c) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your Alternate PTO Approver. ***');
						}
						
						//HR Department
						if(oldUser.HR_Department__c != newUser.HR_Department__c) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your HR Department. ***');
						}
						
						//HR Job Title
						if(oldUser.HR_Job_Title__c != newUser.HR_Job_Title__c) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your HR Job Title. ***');
						}
						
						//Delegated Approver
						if(oldUser.Delegated_Approver_2__c != newUser.Delegated_Approver_2__c) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your Delegated Approver. ***');
						}
						
						//Delegated Approver
						if(oldUser.DelegatedApproverId != newUser.DelegatedApproverId) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your Delegated Approver. ***');
						}
						
						//Manager
						if(oldUser.ManagerId != newUser.ManagerId) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your Manager. ***');
						}
						
						//First Name
						if(oldUser.FirstName != newUser.FirstName) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your First Name. ***');
						}
						
						//Last Name
						if(oldUser.LastName != newUser.LastName) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your Last Name. ***');
						}
						
						//Start Date
						if(oldUser.Start_Date__c != newUser.Start_Date__c) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your Start Date. ***');
						}
						
						//Team Lead
						if(oldUser.Team_Lead__c != newUser.Team_Lead__c) {
							
							newUser.addError('*** Error: Insufficient Privileges, you cannot change your Team Lead. ***');
						}
						
						//Receive Approval Request Emails
						//if(oldUser.)
					}
				}
			}
		}
	}
}